#!/usr/bin/env node
/* ===========================================================================
   docs/system-integrity/RULES.md, generated from the integrity engine's own
   rule table (lib/edgedesk_integrity.js I.RULES), so the document can never
   describe a rule the code does not enforce.

   Run:  node tools/integrity/rules_doc.js          # rewrite RULES.md
         node tools/integrity/rules_doc.js --check  # fail if it is stale
   =========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..', '..');
const I = require(path.join(ROOT, 'lib', 'edgedesk_integrity.js'));
const TARGET = path.join(ROOT, 'docs', 'system-integrity', 'RULES.md');

const SHORT = { RESEARCH_DASHBOARD: 'Dash', BETTING_DECISION: 'Decision', PUBLIC_BRIEF: 'Brief', AI_CONTEXT: 'AI', EDITORIAL_APPROVAL: 'Approval', READY_TO_SEND: 'Ready', PUBLISHER_EXPORT: 'Export' };
const MARK = { BLOCK: '**B**', WARN: 'W', OFF: '–' };

function build() {
  const B = I.BOUNDARIES;
  const L = [];
  L.push('# Integrity rules');
  L.push('');
  L.push('<!-- GENERATED by tools/integrity/rules_doc.js from lib/edgedesk_integrity.js — do not edit by hand. -->');
  L.push('');
  L.push('Engine `' + I.VERSION + '`, record schema `' + I.RECORD_SCHEMA + '`. Every rule is deterministic code. AI never decides whether arithmetic or a fact is correct.');
  L.push('');
  L.push('`EDIntegrity.evaluate(record, boundary, ctx)` runs every rule for one boundary. It returns **PASS**, **WARNING** or **BLOCKED** overall, plus one check per rule. Each check carries:');
  L.push('');
  L.push('- the rule id and its severity;');
  L.push('- the record it is about (record id, game id, matchup);');
  L.push('- the evidence;');
  L.push('- a plain-English explanation;');
  L.push('- the remediation.');
  L.push('');
  L.push('A check that cannot run reports the failure, never PASS: unknown is not PASS.');
  L.push('');
  L.push('## Boundaries');
  L.push('');
  L.push('| Boundary | Where it runs |');
  L.push('|---|---|');
  const WHERE = {
    RESEARCH_DASHBOARD: 'the CFB terminal board and game pages; the in-app board (`app.html`); BLOCKED rows are marked, never hidden',
    BETTING_DECISION: 'before a decision class is shown: a BLOCKED record caps any BET/LEAN/WATCH/WAIT (`DEC.INTEGRITY_FAULT`)',
    PUBLIC_BRIEF: 'the public brief and every content-engine game packet: a BLOCKED game is withheld from every article',
    AI_CONTEXT: 'the research packet sent to Claude',
    EDITORIAL_APPROVAL: 'the approve door: `content_engine_article_approve` refuses `integrity_blocked`',
    READY_TO_SEND: 'the articles guard: ready_to_send and sent need `integrity_ok(checks)` and unchanged research',
    PUBLISHER_EXPORT: 'every Markdown, HTML, Word and email export (`exportCheck`)'
  };
  B.forEach((b) => L.push('| `' + b + '` | ' + (WHERE[b] || '') + ' |'));
  L.push('');
  L.push('## Rules');
  L.push('');
  L.push('**B** = BLOCKED when the rule fails, W = WARNING, – = not evaluated. Groups: schedule, projection, market, calculation, decision.');
  L.push('');
  L.push('| Rule | Group | What it requires | ' + B.map((b) => SHORT[b] || b).join(' | ') + ' |');
  L.push('|---|---|---|' + B.map(() => ':-:').join('|') + '|');
  I.RULES.forEach((r) => {
    const mode = (b) => MARK[Object.prototype.hasOwnProperty.call(r.at, b) ? r.at[b] : r.at._default] || '?';
    L.push('| `' + r.id + '` | ' + r.group + ' | ' + r.title + ' | ' + B.map(mode).join(' | ') + ' |');
  });
  L.push('| `DEC.INTEGRITY_FAULT` | decision | No integrity fault under an actionable decision | ' + B.map((b) => (b === 'BETTING_DECISION' ? '**B**' : '–')).join(' | ') + ' |');
  L.push('| `SCHED.DUPLICATE_GAME` | schedule | No accidental duplicate game (set level, `evaluateSet`) | ' + B.map(() => '**B**').join(' | ') + ' |');
  L.push('');
  L.push('## Editorial rules (content engine)');
  L.push('');
  L.push('`EDContentEngine.validate` runs these on every draft, human or AI. The verdict it stores (`checks.integrity_status`) is what the database enforces at approval and Ready to Send.');
  L.push('');
  L.push('| Check | Rule | Fails when |');
  L.push('|---|---|---|');
  [
    ['integrity_engine', 'EDIT.ENGINE', 'the integrity layer did not load (validation fails closed)'],
    ['games_publishable', 'EDIT.GAMES', 'a featured game is BLOCKED at the public-brief boundary'],
    ['numbers_per_game', 'EDIT.NUMBERS', 'a number sits in a sentence about a game whose research does not contain it'],
    ['qb_claims_sourced', 'EDIT.QB_UNCERTAINTY', 'prose asserts quarterback or injury uncertainty without a sourced report'],
    ['conference_claims', 'EDIT.CONFERENCE', 'a conference is named in a sentence about teams that do not play in it'],
    ['kickoff_claims', 'EDIT.KICKOFF', 'an unannounced (TBA) kickoff is given a clock time'],
    ['spread_claims', 'EDIT.CONTRADICTION', 'a spread is printed that is neither EdgeDesk’s number nor the quoted line'],
    ['snapshot_current', 'EDIT.SNAPSHOT', 'the research changed after the draft was written']
  ].forEach((r) => L.push('| `' + r[0] + '` | `' + r[1] + '` | ' + r[2] + ' |'));
  L.push('');
  L.push('## Export rules');
  L.push('');
  L.push('`EDContentEngine.exportCheck` runs before any file leaves the page. It reads the Markdown text, the HTML text and the Word file\'s runs back, and checks four things:');
  L.push('');
  L.push('| Rule | Fails when |');
  L.push('|---|---|');
  L.push('| `EXPORT.APPROVED` | the content is not the approved revision |');
  L.push('| `EXPORT.RESEARCH` | the research changed after approval |');
  L.push('| `EXPORT.NUMBERS` | any format\'s numbers differ, in value or order, from the approved article\'s |');
  L.push('| `EXPORT.DISCLOSURE` / `EXPORT.REFERRAL` | the disclaimer, or the campaign-tagged EdgeDesk link, is missing |');
  L.push('');
  return L.join('\n') + '\n';
}

const text = build();
if (process.argv.indexOf('--check') > 0) {
  const cur = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, 'utf8') : '';
  if (cur !== text) { console.log('FAIL | docs/system-integrity/RULES.md is stale: run node tools/integrity/rules_doc.js'); process.exit(1); }
  console.log('PASS | RULES.md matches the integrity engine (' + I.RULES.length + ' rules)');
} else {
  fs.writeFileSync(TARGET, text);
  console.log('wrote ' + path.relative(ROOT, TARGET) + ' (' + I.RULES.length + ' rules)');
}
