#!/usr/bin/env python3
"""Bundle a Supabase edge function into one paste-ready file.

The Supabase dashboard editor takes a single index.ts per function, but the
sources here are split so the shared pieces have one owner. This walks the
local `../_shared/*.ts` imports of a function entry point, inlines each shared
module once in dependency order, strips the import and export keywords that
only make sense across module boundaries, and writes a file that can be pasted
straight into the dashboard.

    python3 tools/collective/bundle_functions.py                 # all functions
    python3 tools/collective/bundle_functions.py collective_odds # just one
    python3 tools/collective/bundle_functions.py --check         # CI: is the
                                                                 # committed
                                                                 # bundle current?

Output lands in supabase/functions/_bundles/<name>.bundle.ts.

Only relative imports are inlined. A remote import (https://…, npm:…, jsr:…)
is left exactly as written, because Deno resolves those at deploy time.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FUNCTIONS = ROOT / "supabase" / "functions"
OUT_DIR = FUNCTIONS / "_bundles"

# A function that must not have JWT verification enforced by the gateway,
# because it serves the public site. Recorded here so the deployment note in
# the bundle header cannot drift from reality.
PUBLIC_FUNCTIONS = {"collective_public", "collective_odds"}

IMPORT_RE = re.compile(
    r"""^import\s+(?:type\s+)?(?:[\w*{}\n\r\t,\s]+?\s+from\s+)?["']([^"']+)["'];?\s*$""",
    re.MULTILINE,
)
# `export { a, b };` and `export { a } from "./x.ts";` carry no meaning once
# everything is in one scope.
EXPORT_LIST_RE = re.compile(r"""^export\s*\{[^}]*\}\s*(?:from\s*["'][^"']+["'])?;?\s*$""", re.MULTILINE)
EXPORT_KW_RE = re.compile(
    r"^export\s+(?=(?:default\s+)?(?:async\s+)?"
    r"(?:const|let|var|function|class|interface|type|enum|abstract)\b)",
    re.MULTILINE,
)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def local_imports(src: str) -> list[str]:
    """Relative specifiers imported by this source, in the order written."""
    out = []
    for spec in IMPORT_RE.findall(src):
        if spec.startswith("."):
            out.append(spec)
    return out


def strip_module_syntax(src: str) -> str:
    src = IMPORT_RE.sub("", src)
    src = EXPORT_LIST_RE.sub("", src)
    src = EXPORT_KW_RE.sub("", src)
    # Collapse the run of blank lines the stripped imports leave behind.
    return re.sub(r"\n{3,}", "\n\n", src).strip("\n")


def collect(entry: Path) -> list[Path]:
    """Shared modules the entry point needs, depth first so a module always
    appears after everything it depends on."""
    ordered: list[Path] = []
    seen: set[Path] = set()
    visiting: set[Path] = set()

    def walk(path: Path) -> None:
        path = path.resolve()
        if path in seen:
            return
        if path in visiting:
            raise SystemExit(f"import cycle involving {path.relative_to(ROOT)}")
        visiting.add(path)
        for spec in local_imports(read(path)):
            target = (path.parent / spec).resolve()
            if not target.exists():
                raise SystemExit(f"{path.relative_to(ROOT)} imports missing {spec}")
            walk(target)
        visiting.discard(path)
        seen.add(path)
        if path != entry.resolve():
            ordered.append(path)

    walk(entry)
    return ordered


def bundle(name: str) -> str:
    entry = FUNCTIONS / name / "index.ts"
    if not entry.exists():
        raise SystemExit(f"no such function: {name} (expected {entry})")

    jwt_note = (
        f'// IMPORTANT: turn OFF "Enforce JWT verification" for this function.'
        if name in PUBLIC_FUNCTIONS
        else f'// IMPORTANT: keep "Enforce JWT verification" ON for this function.'
    )
    parts = [
        f"// {name} - SELF-CONTAINED BUNDLE for the Supabase dashboard editor.",
        "// Generated from supabase/functions/ by tools/collective/bundle_functions.py.",
        "// Do not edit this file: edit the sources and regenerate.",
        f"// Paste this whole file as index.ts for a function named exactly: {name}",
        jwt_note,
        "",
    ]
    for dep in collect(entry):
        rel = dep.relative_to(FUNCTIONS)
        parts.append(f"// ---------- inlined {rel.as_posix()} ----------")
        parts.append(strip_module_syntax(read(dep)))
        parts.append("")
    parts.append(f"// ---------- {name}/index.ts ----------")
    parts.append(strip_module_syntax(read(entry)))
    parts.append("")
    return "\n".join(parts)


def function_names() -> list[str]:
    return sorted(
        d.name for d in FUNCTIONS.iterdir()
        if d.is_dir() and not d.name.startswith("_") and (d / "index.ts").exists()
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("names", nargs="*", help="function names (default: all)")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if a committed bundle is out of date")
    args = ap.parse_args()

    names = args.names or function_names()
    if not names:
        print("no functions found under supabase/functions/", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stale = []
    for name in names:
        text = bundle(name)
        out = OUT_DIR / f"{name}.bundle.ts"
        if args.check:
            current = read(out) if out.exists() else ""
            if current != text:
                stale.append(name)
                print(f"STALE {out.relative_to(ROOT)}")
            else:
                print(f"ok    {out.relative_to(ROOT)}")
            continue
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)}  ({len(text.splitlines())} lines)")

    if stale:
        print(
            f"\n{len(stale)} bundle(s) out of date. Run: "
            f"python3 tools/collective/bundle_functions.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
