#!/usr/bin/env node
/* ===========================================================================
   The alias rows of collective.fg2_name_alias, generated from
   lib/football_identity.js ALIAS_GROUPS — the one list of which spellings are
   the same team. The migration carries the output between its
   FG2_ALIAS_BEGIN / FG2_ALIAS_END markers, and football_grading_sql.test.js
   fails if the block in the migration is not exactly what this prints.

     node tools/collective/football_identity_sql.js            # print the block
     node tools/collective/football_identity_sql.js --write    # rewrite it in place
   =========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const I = require(path.join(__dirname, '..', '..', 'lib', 'football_identity.js'));

const MIGRATION = path.join(__dirname, '..', '..', 'supabase', 'migrations', '20260928120000_football_grading_v2.sql');
const BEGIN = '-- FG2_ALIAS_BEGIN (generated by tools/collective/football_identity_sql.js; do not edit by hand)';
const END = '-- FG2_ALIAS_END';

function q(s) { return "'" + String(s).replace(/'/g, "''") + "'"; }

function aliasRows() {
  const rows = [];
  const seen = new Set();
  Object.keys(I.ALIAS_GROUPS).forEach(league => {
    I.ALIAS_GROUPS[league].forEach((grp, gi) => {
      grp.forEach(name => {
        [name, I.expandState(name)].forEach(n => {
          const k = I.teamKey(n);
          if (!k) return;
          const id = league + '|' + k;
          if (seen.has(id)) return;
          seen.add(id);
          rows.push(`  (${q(league)}, ${q(k)}, ${gi + 1}, ${q(name)})`);
        });
      });
    });
  });
  return rows;
}

function block() {
  return [BEGIN,
    'insert into collective.fg2_name_alias (league, alias_key, group_no, alias) values',
    aliasRows().join(',\n'),
    'on conflict (league, alias_key) do update set group_no = excluded.group_no, alias = excluded.alias;',
    END].join('\n');
}

function embedded(sql) {
  const a = sql.indexOf(BEGIN), b = sql.indexOf(END);
  if (a < 0 || b < 0) return null;
  return sql.slice(a, b + END.length);
}

module.exports = { block, embedded, MIGRATION, BEGIN, END };

if (require.main === module) {
  if (process.argv.includes('--write')) {
    const sql = fs.readFileSync(MIGRATION, 'utf8');
    const cur = embedded(sql);
    if (!cur) { console.error('markers not found in ' + MIGRATION); process.exit(1); }
    fs.writeFileSync(MIGRATION, sql.replace(cur, block()));
    console.log('rewrote the alias block in ' + path.relative(process.cwd(), MIGRATION));
  } else {
    console.log(block());
  }
}
