/* GENERATED by football/research/nfl_regime.py --holdout --write. Do not edit by hand.
   The NFL regime signal (new head coach, new starting quarterback, the regular starter out) and its
   walk-forward fitted adjustment. `promoted` says whether the adjustment prices; while it is false the
   board shows the signal and the adjustment it would make, and prices nothing. */
(function (root) {
  var R = {
   "version": "nfl_regime_v1",
   "generated_by": "football/research/nfl_regime.py",
   "generated_at": "2026-09-30T20:59:18.291163+00:00",
   "promoted": false,
   "promotion_rule": "priced only if the holdout regime subset beats the model with a 95% interval that excludes zero",
   "signals": {
    "hc_new": "the head coach\u2019s tenure with the team began this season (incl. a mid-season change)",
    "qb_new": "the game\u2019s starting quarterback is not last season\u2019s primary starter",
    "qb_out": "the team has started 2+ games this season and the game\u2019s starter is not its regular starter so far"
   },
   "early_weeks": 6,
   "coefficients": {
    "hc_new_early": -1.4883,
    "hc_new_late": -0.9011,
    "qb_new_early": 0.1276,
    "qb_new_late": -0.7276,
    "qb_out": -2.3287
   },
   "coefficient_meaning": "points added to the team\u2019s side of the fair margin when the signal is active (home minus away enters the margin)",
   "record": {
    "validation": {
     "regime_subset": {
      "games": 1062,
      "mae_model": 10.224,
      "mae_adjusted": 10.085,
      "delta": -0.139,
      "delta_ci95": [
       -0.275,
       -0.012
      ],
      "bias_model": 1.299,
      "bias_adjusted": 0.087
     },
     "overall": {
      "games": 2191,
      "mae_model": 10.216,
      "mae_adjusted": 10.153
     },
     "significant": true
    },
    "holdout": {
     "regime_subset": {
      "games": 303,
      "mae_model": 10.509,
      "mae_adjusted": 10.34,
      "delta": -0.169,
      "delta_ci95": [
       -0.394,
       0.056
      ],
      "bias_model": 1.294,
      "bias_adjusted": 0.166
     },
     "overall": {
      "games": 570,
      "mae_model": 10.139,
      "mae_adjusted": 10.041
     },
     "significant": false,
     "by_season": {
      "2024": {
       "regime_subset": {
        "games": 146,
        "mae_model": 10.681,
        "mae_adjusted": 10.299,
        "delta": -0.382,
        "delta_ci95": [
         -0.708,
         -0.048
        ],
        "bias_model": 1.439,
        "bias_adjusted": 0.293
       },
       "overall": {
        "games": 285,
        "mae_model": 10.112,
        "mae_adjusted": 9.912
       },
       "significant": true
      },
      "2025": {
       "regime_subset": {
        "games": 157,
        "mae_model": 10.35,
        "mae_adjusted": 10.378,
        "delta": 0.028,
        "delta_ci95": [
         -0.28,
         0.332
        ],
        "bias_model": 1.157,
        "bias_adjusted": 0.045
       },
       "overall": {
        "games": 285,
        "mae_model": 10.166,
        "mae_adjusted": 10.171
       },
       "significant": false
      }
     }
    }
   },
   "report": "football/research/report/nfl_regime.json"
  };
  root.EDNflRegime = R;
  if (typeof module !== 'undefined' && module.exports) module.exports = R;
})(typeof window !== 'undefined' ? window : globalThis);
