/* ============================================================================
   EdgeDesk Football Engine (NFL + NCAA FBS) — deterministic client engine.

   ONE shared architecture, TWO sport-specific feature layers:
     shared   — odds math (de-vig, EV, CLV), margin/total distributions with
                learned key-number mass, calibration, market comparison,
                confidence, data-quality gate, versioning/fingerprint
     nfl      — opponent-adjusted EPA rating recursion + QB layer + the
                koerner/sharp/stuckey/fezzik submodels (learned coefficients)
     cfb      — capped-margin iterative rating recursion + scoring EWMAs,
                with CFB's OWN learned constants (never NFL's)

   Every constant in here is LEARNED by football/research/*.py from public
   data whose provenance ships inside params.js — nothing is asserted by
   hand. The recursions are byte-for-byte mirrors of the python reference
   (train_nfl.Ratings / train_cfb.CfbRatings); tests.js replays golden
   vectors generated by python and requires 1e-9 agreement.

   HONESTY CONTRACT (this is the part that must never regress):
     - The NFL model does NOT beat the closing line out of sample (see
       params.validation_summary). classifyEdge() therefore never returns a
       tier above RESEARCH_LEAN, and every output carries validated:false
       until the model's own graded CLV says otherwise.
     - No CFB market backtest exists (no public historical CFB lines), so
       CFB market gaps are labeled exactly that way.
     - Missing input -> {status:'INSUFFICIENT_DATA', missing:[...]}. The
       engine never guesses, never substitutes, never fakes a projection.

   Runs in browser (window.EDFootball) and node (module.exports). ES5-only
   on purpose: it matches the app it ships inside.
   ============================================================================ */
(function () {
  'use strict';
  var root = (typeof window !== 'undefined') ? window
    : (typeof globalThis !== 'undefined') ? globalThis : this;

  function params() {
    var p = root.EDFootballParams;
    if (!p && typeof require === 'function') {
      try { p = require('./params.js'); } catch (e) { /* browser path */ }
    }
    return p || null;
  }

  function isNum(x) { return typeof x === 'number' && isFinite(x); }

  /* ---------------- shared: odds math ---------------- */
  var odds = {
    amToDec: function (a) { return a > 0 ? a / 100 + 1 : 100 / (-a) + 1; },
    decToAm: function (d) { return d >= 2 ? Math.round((d - 1) * 100) : Math.round(-100 / (d - 1)); },
    implied: function (dec) { return dec > 1 ? 1 / dec : null; },
    /* two-way de-vig. 'multiplicative' scales; 'power' solves sum q^k = 1 */
    devigTwoWay: function (decA, decB, method) {
      if (!(decA > 1) || !(decB > 1)) return null;
      var qa = 1 / decA, qb = 1 / decB, S = qa + qb;
      if (method === 'power') {
        var lo = 0.5, hi = 6, k, i;
        for (i = 0; i < 80; i++) {
          k = (lo + hi) / 2;
          if (Math.pow(qa, k) + Math.pow(qb, k) > 1) lo = k; else hi = k;
        }
        k = (lo + hi) / 2;
        return [Math.pow(qa, k), Math.pow(qb, k)];
      }
      return [qa / S, qb / S];
    },
    evPct: function (prob, dec) { return isNum(prob) && dec > 1 ? prob * dec - 1 : null; },
    /* EdgeDesk CLV doctrine: closing fair probability x frozen entry price - 1 */
    clv: function (entryDec, closingFairProb) {
      return (entryDec > 1 && isNum(closingFairProb)) ? closingFairProb * entryDec - 1 : null;
    },
    noVigClv: function (entryFairProb, closingFairProb) {
      return (isNum(entryFairProb) && isNum(closingFairProb) && entryFairProb > 0)
        ? closingFairProb / entryFairProb - 1 : null;
    }
  };

  /* ---------------- shared: distributions ---------------- */
  function erf(x) {
    /* Abramowitz & Stegun 7.1.26, |err| <= 1.5e-7 */
    var s = x < 0 ? -1 : 1; x = Math.abs(x);
    var t = 1 / (1 + 0.3275911 * x);
    var y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t
      - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x);
    return s * y;
  }
  function normCdf(x) { return 0.5 * (1 + erf(x / Math.SQRT2)); }

  function sportParams(sport) {
    var P = params(); if (!P) return null;
    return sport === 'nfl' ? P.nfl : sport === 'cfb' ? P.cfb : null;
  }
  function pmfEntries(pmf) {
    var out = [], k;
    for (k in pmf) if (pmf.hasOwnProperty(k)) out.push([parseInt(k, 10), pmf[k]]);
    out.sort(function (a, b) { return a[0] - b[0]; });
    return out;
  }
  var dist = {
    winProb: function (sport, fairSpread) {
      var sp = sportParams(sport);
      if (!sp || !isNum(fairSpread)) return null;
      return normCdf(fairSpread / sp.sigma_margin);
    },
    /* P(home side of `line` wins / pushes / loses) given the model's fair
       spread. Primary path: the learned margin PMF CONDITIONED on the spread
       (kernel over closing spreads; keeps real key-number mass — margin 3 at
       spread 3 is ~9%, which a pooled residual table smears away). Fallback
       when the fair spread is outside the table range: the pooled residual
       PMF, which is unconditioned and says so via `basis`. */
    coverProbSpread: function (sport, fairSpread, line) {
      var sp = sportParams(sport);
      if (!sp || !isNum(fairSpread) || !isNum(line)) return null;
      var tab = sp.margin_pmf_by_spread, rng = sp.pmf_spread_range;
      var win = 0, push = 0, tot = 0, i, es;
      if (tab && rng && fairSpread >= rng[0] && fairSpread <= rng[1]) {
        var key = (Math.round(fairSpread * 2) / 2).toFixed(1);
        if (key === '-0.0') key = '0.0';
        var pmf = tab[key] || tab[Math.round(fairSpread).toFixed(1)];
        if (pmf) {
          es = pmfEntries(pmf);
          for (i = 0; i < es.length; i++) {
            tot += es[i][1];
            if (Math.abs(es[i][0] - line) < 1e-9) push += es[i][1];
            else if (es[i][0] > line) win += es[i][1];
          }
          if (tot > 0.5) return { win: win / tot, push: push / tot,
            lose: 1 - (win + push) / tot, basis: 'margin_pmf_by_spread' };
        }
      }
      var need = line - fairSpread;               // resid must exceed this
      es = pmfEntries(sp.margin_resid_pmf);
      win = 0; push = 0; tot = 0;
      for (i = 0; i < es.length; i++) {
        tot += es[i][1];
        if (Math.abs(es[i][0] - need) < 1e-9) push += es[i][1];
        else if (es[i][0] > need) win += es[i][1];
      }
      if (!(tot > 0.5)) return null;              // degenerate table
      return { win: win / tot, push: push / tot,
        lose: 1 - (win + push) / tot, basis: 'pooled_residual' };
    },
    coverProbTotal: function (sport, fairTotal, line, side) {
      var sp = sportParams(sport);
      if (!sp || !isNum(fairTotal) || !isNum(line)) return null;
      var need = line - fairTotal;
      var es = pmfEntries(sp.total_resid_pmf);
      var over = 0, push = 0, tot = 0, i;
      for (i = 0; i < es.length; i++) {
        tot += es[i][1];
        if (Math.abs(es[i][0] - need) < 1e-9) push += es[i][1];
        else if (es[i][0] > need) over += es[i][1];
      }
      if (!(tot > 0.5)) return null;
      var p = { win: over / tot, push: push / tot, lose: 1 - (over + push) / tot };
      if (side === 'under') p = { win: p.lose, push: p.push, lose: p.win };
      return p;
    },
    keyMass: function (sport) {
      var sp = sportParams(sport);
      return sp ? (sp.abs_margin_key_mass || null) : null;
    },
    /* worth of moving a spread from one number to another, in cover prob */
    halfPointValue: function (sport, fairSpread, fromLine, toLine) {
      var a = dist.coverProbSpread(sport, fairSpread, fromLine);
      var b = dist.coverProbSpread(sport, fairSpread, toLine);
      if (!a || !b) return null;
      return (b.win + 0.5 * b.push) - (a.win + 0.5 * a.push);
    },
    fairSpreadFromWinProb: function (sport, p) {
      var sp = sportParams(sport);
      if (!sp || !(p > 0 && p < 1)) return null;
      /* inverse Phi by bisection on the same erf (no new approximations) */
      var lo = -60, hi = 60, m, i;
      for (i = 0; i < 60; i++) {
        m = (lo + hi) / 2;
        if (normCdf(m / sp.sigma_margin) < p) lo = m; else hi = m;
      }
      return (lo + hi) / 2;
    }
  };

  /* ---------------- NFL layer ---------------- */
  var NFL_RATE_FEATS = ['off_epa_play', 'pass_epa_db', 'rush_epa_att',
    'expl_pass', 'expl_rush', 'sack_rate_all', 'pass_rate', 'plays',
    'def_epa_play', 'def_pass_epa_db', 'def_rush_epa_att', 'def_expl_pass',
    'def_expl_rush', 'sack_rate_made', 'pts_for', 'pts_against'];
  var NFL_COUNTER = {
    off_epa_play: 'def_epa_play', pass_epa_db: 'def_pass_epa_db',
    rush_epa_att: 'def_rush_epa_att', expl_pass: 'def_expl_pass',
    expl_rush: 'def_expl_rush', sack_rate_all: 'sack_rate_made',
    def_epa_play: 'off_epa_play', def_pass_epa_db: 'pass_epa_db',
    def_rush_epa_att: 'rush_epa_att', def_expl_pass: 'expl_pass',
    def_expl_rush: 'expl_rush', sack_rate_made: 'sack_rate_all',
    pts_for: 'pts_against', pts_against: 'pts_for'
  };
  var NFL_SPREAD_FEATS = ['net_pts', 'net_epa', 'net_pass', 'net_rush',
    'qb_adj_diff', 'rest_diff', 'div_game'];
  var NFL_TOTAL_FEATS = ['off_epa_sum', 'def_epa_sum', 'pass_matchup',
    'rush_matchup', 'expl_sum', 'sack_env', 'pace_sum', 'pts_env',
    'is_dome', 'temp_c', 'wind_o', 'div_game', 'week_frac'];
  var NFL_CTX_FEATS = ['rest_diff', 'home_short', 'away_short',
    'home_off_bye', 'away_off_bye', 'div_game', 'week_frac', 'is_dome', 'grass'];

  function clone(o) { return JSON.parse(JSON.stringify(o)); }

  var nfl = {
    RATE_FEATS: NFL_RATE_FEATS,
    /* fresh mutable rating state from the shipped end-of-training seeds */
    newState: function () {
      var sp = sportParams('nfl'); if (!sp) return null;
      var st = { hp: clone(sp.hyperparams), team: clone(sp.seed_ratings),
        lmean: clone(sp.league_means), teamQb: clone(sp.seed_team_qb || {}),
        qb: clone(sp.seed_qb_values || {}), ngames: {},
        seededThrough: sp.trained_through_season };
      var t;
      for (t in st.team) if (st.team.hasOwnProperty(t)) st.ngames[t] = 99;
      return st;
    },
    _team: function (st, t) {
      if (!st.team[t]) {
        var o = {}, i;
        for (i = 0; i < NFL_RATE_FEATS.length; i++) o[NFL_RATE_FEATS[i]] = 0;
        st.team[t] = o; st.ngames[t] = 0; st.teamQb[t] = 0;
      }
      return st.team[t];
    },
    seasonBreak: function (st) {
      var c = st.hp.carry, t, i;
      for (t in st.team) if (st.team.hasOwnProperty(t)) {
        for (i = 0; i < NFL_RATE_FEATS.length; i++) st.team[t][NFL_RATE_FEATS[i]] *= c;
        st.teamQb[t] = (st.teamQb[t] || 0) * c;
      }
    },
    qbEff: function (st, qbId) {
      var q = st.qb[qbId];
      if (!q) return st.hp.qb_prior;
      var k = st.hp.qb_shrink;
      return q.v * (q.n / (q.n + k)) + st.hp.qb_prior * (k / (q.n + k));
    },
    qbAdjust: function (st, team, qbId) {
      if (typeof qbId !== 'string' || !qbId) return 0;
      return nfl.qbEff(st, qbId) - (st.teamQb[team] || 0);
    },
    /* exact per-team-game feature computation from a raw stats_team_week row
       (mirrors research/build_features.py) */
    teamGameFromStw: function (r) {
      function n(x) { var v = +x; return isFinite(v) ? v : NaN; }
      var att = n(r.attempts), car = n(r.carries), sk = n(r.sacks_suffered);
      var db = att + sk, plays = att + car + sk;
      return {
        off_epa_play: (n(r.passing_epa) + n(r.rushing_epa)) / plays,
        pass_epa_db: db > 0 ? n(r.passing_epa) / db : NaN,
        rush_epa_att: car > 0 ? n(r.rushing_epa) / car : NaN,
        expl_pass: att > 0 ? n(r.passing_20) / att : NaN,
        expl_rush: car > 0 ? n(r.rushing_10) / car : NaN,
        sack_rate_all: db > 0 ? sk / db : NaN,
        pass_rate: plays > 0 ? att / plays : NaN,
        plays: plays
      };
    },
    /* ordered absorb: pairs = [[homeTeam, homeRaw],[awayTeam, awayRaw]];
       qbStarts = [[team, qbId, passDevOrNull], ...] in the same order.
       Order is part of the algorithm (league means update sequentially). */
    absorbGame: function (st, pairs, qbStarts) {
      var pre = {}, i, j, t, raw, opp, f, v, lm, cf, perf, a;
      for (i = 0; i < pairs.length; i++) pre[pairs[i][0]] = clone(nfl._team(st, pairs[i][0]));
      for (i = 0; i < pairs.length; i++) {
        t = pairs[i][0]; raw = pairs[i][1];
        opp = pairs[1 - i][0];
        for (j = 0; j < NFL_RATE_FEATS.length; j++) {
          f = NFL_RATE_FEATS[j]; v = raw[f];
          if (!isNum(v)) continue;
          lm = st.lmean[f];
          if (lm === undefined || lm === null) { st.lmean[f] = v; continue; }
          cf = NFL_COUNTER[f];
          perf = v - lm - (cf && isNum(pre[opp][cf]) ? pre[opp][cf] : 0);
          a = (f === 'pts_for' || f === 'pts_against') ? st.hp.alpha_pts : st.hp.alpha;
          st.team[t][f] = (1 - a) * st.team[t][f] + a * perf;
          st.lmean[f] = (1 - st.hp.alpha_league) * lm + st.hp.alpha_league * v;
        }
        st.ngames[t] = (st.ngames[t] || 0) + 1;
      }
      for (i = 0; i < (qbStarts || []).length; i++) {
        t = qbStarts[i][0];
        var qbId = qbStarts[i][1], dev = qbStarts[i][2];
        if (typeof qbId === 'string' && qbId && isNum(dev)) {
          var q = st.qb[qbId] || (st.qb[qbId] = { v: 0, n: 0 });
          var aq = st.hp.alpha_qb;
          q.v = (1 - aq) * q.v + aq * dev;
          q.n += 1;
          var e = nfl.qbEff(st, qbId);
          var at = st.hp.alpha;
          st.teamQb[t] = (1 - at) * (st.teamQb[t] || 0) + at * e;
        }
      }
    },
    /* game = {home, away, home_qb_id?, away_qb_id?, home_rest?, away_rest?,
               roof?, temp?, wind?, div_game?, week?, surface?} */
    gameFeatures: function (st, game) {
      var rh = nfl._team(st, game.home), ra = nfl._team(st, game.away);
      var qh = nfl.qbAdjust(st, game.home, game.home_qb_id);
      var qa = nfl.qbAdjust(st, game.away, game.away_qb_id);
      var restH = isNum(game.home_rest) ? game.home_rest : 7;
      var restA = isNum(game.away_rest) ? game.away_rest : 7;
      var dome = (String(game.roof) === 'dome' || String(game.roof) === 'closed') ? 1 : 0;
      var temp = (isNum(game.temp) && !dome) ? game.temp : 68;
      var wind = (isNum(game.wind) && !dome) ? game.wind : 0;
      var weekFrac = Math.min(1, (isNum(game.week) ? game.week : 9) / 18);
      var div = game.div_game ? 1 : 0;
      var sf = {
        net_pts: (rh.pts_for + rh.pts_against) - (ra.pts_for + ra.pts_against),
        net_epa: (rh.off_epa_play - rh.def_epa_play) - (ra.off_epa_play - ra.def_epa_play),
        net_pass: (rh.pass_epa_db - rh.def_pass_epa_db) - (ra.pass_epa_db - ra.def_pass_epa_db),
        net_rush: (rh.rush_epa_att - rh.def_rush_epa_att) - (ra.rush_epa_att - ra.def_rush_epa_att),
        qb_adj_diff: qh - qa,
        rest_diff: (restH - restA) / 7,
        div_game: div
      };
      var tf = {
        off_epa_sum: rh.off_epa_play + ra.off_epa_play,
        def_epa_sum: rh.def_epa_play + ra.def_epa_play,
        pass_matchup: rh.pass_epa_db + ra.def_pass_epa_db + ra.pass_epa_db + rh.def_pass_epa_db,
        rush_matchup: rh.rush_epa_att + ra.def_rush_epa_att + ra.rush_epa_att + rh.def_rush_epa_att,
        expl_sum: rh.expl_pass + ra.expl_pass + rh.def_expl_pass + ra.def_expl_pass,
        sack_env: rh.sack_rate_all + ra.sack_rate_all - rh.sack_rate_made - ra.sack_rate_made,
        pace_sum: rh.plays + ra.plays,
        pts_env: rh.pts_for + ra.pts_for + rh.pts_against + ra.pts_against,
        is_dome: dome,
        temp_c: (temp - 68) / 25,
        wind_o: Math.max(0, wind - 8) / 10,
        div_game: div,
        week_frac: weekFrac
      };
      var cf = {
        rest_diff: (restH - restA) / 7,
        home_short: restH <= 5 ? 1 : 0,
        away_short: restA <= 5 ? 1 : 0,
        home_off_bye: restH >= 12 ? 1 : 0,
        away_off_bye: restA >= 12 ? 1 : 0,
        div_game: div,
        week_frac: weekFrac,
        is_dome: dome,
        grass: String(game.surface || '').toLowerCase().indexOf('grass') === 0 ? 1 : 0
      };
      var known = Math.min(st.ngames[game.home] || 0, st.ngames[game.away] || 0);
      return { spread: sf, total: tf, ctx: cf, known: known,
        qb_known: { home: !!game.home_qb_id, away: !!game.away_qb_id } };
    },
    predict: function (st, game) {
      var sp = sportParams('nfl'); if (!sp) return null;
      var F = nfl.gameFeatures(st, game);
      function lin(feats, names, w) {
        var s = w[w.length - 1], i;
        for (i = 0; i < names.length; i++) s += feats[names[i]] * w[i];
        return s;
      }
      var koerner = lin(F.spread, NFL_SPREAD_FEATS, sp.w_spread);
      var ctxAdj = lin(F.ctx, NFL_CTX_FEATS, sp.w_ctx);
      var total = lin(F.total, NFL_TOTAL_FEATS, sp.w_total);
      return { koerner_spread: koerner, ctx_adj: ctxAdj,
        model_spread: koerner + ctxAdj, sharp_total: total,
        features: F, known: F.known };
    }
  };

  /* ---------------- CFB layer ---------------- */
  var cfb = {
    newState: function () {
      var sp = sportParams('cfb'); if (!sp) return null;
      return { hp: clone(sp.hyperparams), r: clone(sp.seed_ratings),
        n: clone(sp.seed_ngames || {}), off: clone(sp.seed_totals || {}),
        lmeanPts: sp.league_mean_pts,
        seededThrough: sp.trained_through_season };
    },
    get: function (st, team, fbs) {
      if (!fbs) return st.hp.fcs_rating;
      return st.r.hasOwnProperty(team) ? st.r[team] : st.hp.init_rating;
    },
    games: function (st, team) { return st.n[team] || 0; },
    seasonBreak: function (st) {
      var c = st.hp.carry, t;
      for (t in st.r) if (st.r.hasOwnProperty(t)) st.r[t] *= c;
      for (t in st.off) if (st.off.hasOwnProperty(t)) {
        st.off[t].pf *= c; st.off[t].pa *= c;
      }
    },
    predictMargin: function (st, home, away, hFbs, aFbs, neutral) {
      var hfa = neutral ? 0 : st.hp.hfa;
      return cfb.get(st, home, hFbs) - cfb.get(st, away, aFbs) + hfa;
    },
    predictTotal: function (st, home, away) {
      if (!isNum(st.lmeanPts)) return null;
      var oh = st.off[home], oa = st.off[away];
      if (!oh || !oa) return null;
      return 2 * st.lmeanPts + st.hp.k_total * (oh.pf + oh.pa + oa.pf + oa.pa);
    },
    absorb: function (st, home, away, hFbs, aFbs, neutral, margin, hPts, aPts) {
      var hp = st.hp;
      var m = Math.max(-hp.cap, Math.min(hp.cap, margin));
      var err = m - cfb.predictMargin(st, home, away, hFbs, aFbs, neutral);
      if (hFbs) { st.r[home] = cfb.get(st, home, true) + hp.k * err; st.n[home] = cfb.games(st, home) + 1; }
      if (aFbs) { st.r[away] = cfb.get(st, away, true) - hp.k * err; st.n[away] = cfb.games(st, away) + 1; }
      if (!isNum(st.lmeanPts)) st.lmeanPts = (hPts + aPts) / 2;
      var rows = [[home, hPts, aPts, hFbs], [away, aPts, hPts, aFbs]], i;
      for (i = 0; i < 2; i++) {
        if (!rows[i][3]) continue;
        var t = rows[i][0];
        var o = st.off[t] || (st.off[t] = { pf: 0, pa: 0 });
        var at = hp.alpha_total;
        o.pf = (1 - at) * o.pf + at * (rows[i][1] - st.lmeanPts);
        o.pa = (1 - at) * o.pa + at * (rows[i][2] - st.lmeanPts);
      }
      var al = hp.alpha_league;
      st.lmeanPts = (1 - al) * st.lmeanPts + al * ((hPts + aPts) / 2);
    }
  };

  /* ---------------- shared: market layer ---------------- */
  var market = {
    /* median of per-book de-vigged fair probabilities for a two-way market.
       books = [[decA, decB], ...]; returns [fairA, fairB] or null. */
    consensusFair: function (books) {
      var fa = [], i, p;
      for (i = 0; i < (books || []).length; i++) {
        p = odds.devigTwoWay(books[i][0], books[i][1]);
        if (p) fa.push(p[0]);
      }
      if (!fa.length) return null;
      fa.sort(function (a, b) { return a - b; });
      var mid = fa.length >> 1;
      var m = (fa.length % 2) ? fa[mid] : (fa[mid - 1] + fa[mid]) / 2;
      return [m, 1 - m];
    },
    /* learned blend of football number and market number (walk-forward
       ridge; note how heavily the market is weighted — that is the finding,
       not a choice). */
    blendSpread: function (modelSpread, marketSpread) {
      var sp = sportParams('nfl');
      if (!sp || !isNum(modelSpread) || !isNum(marketSpread)) return null;
      var w = sp.w_blend_spread;
      return w[0] * modelSpread + w[1] * marketSpread + w[2];
    },
    blendTotal: function (modelTotal, marketTotal) {
      var sp = sportParams('nfl');
      if (!sp || !isNum(modelTotal) || !isNum(marketTotal)) return null;
      var w = sp.w_blend_total;
      return w[0] * modelTotal + w[1] * marketTotal + w[2];
    },
    topDownBottomUpGap: function (modelNumber, marketNumber) {
      return (isNum(modelNumber) && isNum(marketNumber)) ? modelNumber - marketNumber : null;
    },
    /* HONEST recommendation. The 2016-2025 backtest cleared NO edge class
       against the closing line (see params.validation_summary), so the
       ceiling here is RESEARCH_LEAN and validated is ALWAYS false. If a
       future retrain validates a threshold, regenerate params — do not
       edit this function into optimism. */
    classifyEdge: function (sport, marketKind, gapPts) {
      var P = params();
      var out = { recommendation: 'PASS', validated: false, gap: gapPts,
        historical: null,
        basis: sport === 'nfl'
          ? 'NFL 2016-2025 walk-forward vs closing consensus: no gap size cleared p<0.05.'
          : 'No historical CFB market backtest exists (no public line archive); nothing is validated.' };
      if (!isNum(gapPts)) { out.recommendation = 'NO_MARKET'; return out; }
      if (P && sport === 'nfl' && P.validation_summary) {
        var tab = marketKind === 'total'
          ? P.validation_summary.nfl.ou_vs_close
          : P.validation_summary.nfl.ats_vs_close;
        var best = null, k, t;
        for (k in tab) if (tab.hasOwnProperty(k)) {
          t = parseFloat(k);
          if (Math.abs(gapPts) >= t && (best === null || t > best)) best = t;
        }
        if (best !== null) out.historical = tab[String(best)];
      }
      if (Math.abs(gapPts) >= 2) out.recommendation = 'RESEARCH_LEAN';
      return out;
    }
  };

  /* ---------------- shared: data quality gate ---------------- */
  function dataQuality(sport, input) {
    var missing = [], sp = sportParams(sport);
    if (!sp) return { status: 'BLOCKED', missing: ['params'], reason: 'EDFootballParams not loaded' };
    if (!input || !input.state) missing.push('rating_state');
    if (!input || !input.game) missing.push('game');
    else {
      if (!input.game.home) missing.push('home_team');
      if (!input.game.away) missing.push('away_team');
      if (input.game.home === input.game.away) missing.push('distinct_teams');
    }
    if (input && input.season && isNum(input.season)
        && input.season > sp.trained_through_season + 1) {
      return { status: 'BLOCKED', missing: ['fresh_params'],
        reason: 'Parameters trained through ' + sp.trained_through_season
          + '; season ' + input.season + ' is beyond the supported window. '
          + 'Regenerate params (football/research) before predicting.' };
    }
    if (missing.length) return { status: 'INSUFFICIENT_DATA', missing: missing, reason: 'required inputs absent' };
    var warn = [];
    if (sport === 'nfl') {
      if (!input.game.home_qb_id) warn.push('home QB starter unknown');
      if (!input.game.away_qb_id) warn.push('away QB starter unknown');
    }
    return { status: 'OK', missing: [], warnings: warn };
  }

  /* ---------------- fingerprint (cache key) ---------------- */
  function fingerprint(obj) {
    var s = JSON.stringify(obj), h = 5381, i;
    for (i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
    return 'fp_' + (h >>> 0).toString(36);
  }

  /* ---------------- full production prediction ---------------- */
  /* req = { sport:'nfl'|'cfb', state, game, season?,
             market?: {spread_line?, total_line?, quotes_h2h?: [[decH,decA],...]},
             timestamps?: {odds?, injuries?, weather?} } */
  function predictGame(req) {
    var P = params();
    var sport = req && req.sport;
    var q = dataQuality(sport, req || {});
    var nowIso = new Date().toISOString();
    if (q.status !== 'OK') {
      return { status: q.status === 'BLOCKED' ? 'BLOCKED' : 'INSUFFICIENT_DATA',
        reason: q.reason, missing: q.missing,
        model_version: P ? P.model_version : null,
        prediction_timestamp: nowIso };
    }
    var sp = sportParams(sport);
    var comp = {}, fairSpread = null, fairTotal = null;
    if (sport === 'nfl') {
      var pr = nfl.predict(req.state, req.game);
      comp.koerner_spread = pr.koerner_spread;
      comp.stuckey_ctx_adj = pr.ctx_adj;
      comp.sharp_total = pr.sharp_total;
      fairSpread = pr.model_spread;
      fairTotal = pr.sharp_total;
    } else {
      var g = req.game;
      fairSpread = cfb.predictMargin(req.state, g.home, g.away,
        g.home_fbs !== false, g.away_fbs !== false, !!g.neutral_site);
      fairTotal = cfb.predictTotal(req.state, g.home, g.away);
      comp.rating_spread = fairSpread;
      comp.rating_total = fairTotal;
    }
    var mkt = req.market || {};
    comp.fezzik_market_spread = isNum(mkt.spread_line) ? mkt.spread_line : null;
    comp.fezzik_market_total = isNum(mkt.total_line) ? mkt.total_line : null;
    var blendS = (sport === 'nfl') ? market.blendSpread(fairSpread, mkt.spread_line) : null;
    var blendT = (sport === 'nfl') ? market.blendTotal(fairTotal, mkt.total_line) : null;
    var pHome = dist.winProb(sport, fairSpread);
    var gapS = market.topDownBottomUpGap(fairSpread, mkt.spread_line);
    var gapT = market.topDownBottomUpGap(fairTotal, mkt.total_line);
    var consensus = mkt.quotes_h2h ? market.consensusFair(mkt.quotes_h2h) : null;
    var out = {
      status: 'PREDICTED',
      sport: sport,
      game: { home: req.game.home, away: req.game.away },
      model: {
        fair_spread: fairSpread,
        fair_total: fairTotal,
        home_win_prob: pHome,
        fair_home_ml: pHome ? odds.decToAm(1 / pHome) : null,
        fair_away_ml: pHome ? odds.decToAm(1 / (1 - pHome)) : null,
        blend_spread: blendS,
        blend_total: blendT
      },
      components: comp,
      market: {
        spread_line: isNum(mkt.spread_line) ? mkt.spread_line : null,
        total_line: isNum(mkt.total_line) ? mkt.total_line : null,
        consensus_fair_home: consensus ? consensus[0] : null,
        spread_gap: gapS, total_gap: gapT
      },
      edge: {
        spread: market.classifyEdge(sport, 'spread', gapS),
        total: market.classifyEdge(sport, 'total', gapT)
      },
      cover: isNum(mkt.spread_line)
        ? dist.coverProbSpread(sport, fairSpread, mkt.spread_line) : null,
      over: isNum(mkt.total_line) && isNum(fairTotal)
        ? dist.coverProbTotal(sport, fairTotal, mkt.total_line, 'over') : null,
      data_quality: q,
      unproven: true,
      model_version: P.model_version,
      feature_version: sp.feature_version,
      trained_through_season: sp.trained_through_season,
      prediction_timestamp: nowIso,
      odds_timestamp: (req.timestamps && req.timestamps.odds) || null,
      injury_timestamp: (req.timestamps && req.timestamps.injuries) || null,
      weather_timestamp: (req.timestamps && req.timestamps.weather) || null,
      fingerprint: fingerprint({ g: req.game, s: sport,
        v: P.model_version, f: sp.feature_version,
        o: (req.timestamps && req.timestamps.odds) || null,
        m: [mkt.spread_line, mkt.total_line] })
    };
    /* sanity checks (spec: fail loudly, never publish nonsense) */
    if (!isNum(fairSpread) || Math.abs(fairSpread) > 60
      || (pHome !== null && !(pHome > 0 && pHome < 1))
      || (isNum(fairTotal) && (fairTotal < 10 || fairTotal > 120))) {
      return { status: 'BLOCKED', reason: 'sanity check failed',
        missing: [], debug: { fair_spread: fairSpread, fair_total: fairTotal, p_home: pHome },
        model_version: P.model_version, prediction_timestamp: nowIso };
    }
    return out;
  }

  var API = {
    version: function () { var P = params(); return P ? P.model_version : null; },
    meta: function () {
      var P = params(); if (!P) return null;
      return { model_version: P.model_version, built_at: P.built_at,
        nfl: { feature_version: P.nfl.feature_version, trained_through: P.nfl.trained_through_season,
          provenance: P.nfl.data_provenance },
        cfb: { feature_version: P.cfb.feature_version, trained_through: P.cfb.trained_through_season,
          provenance: P.cfb.data_provenance },
        validation: P.validation_summary };
    },
    odds: odds, dist: dist, nfl: nfl, cfb: cfb, market: market,
    dataQuality: dataQuality, predictGame: predictGame,
    fingerprint: fingerprint, _normCdf: normCdf
  };

  root.EDFootball = API;
  if (typeof module !== 'undefined' && module.exports) module.exports = API;
})();
