/* GENERATED by football/cfb_p4/research/regime_magnitude_backtest.js --write. Do not edit by hand.
   The v2 regime prior: a continuous turnover MAGNITUDE (coach change, returning production, QB
   change, production-weighted portal inflow; football/coaching/regime_signal.js), fitted walk-forward
   on 2021+ seasons and scored on a 2024-2025 holdout it never saw. It prices ONLY when promoted is
   true; otherwise football/coaching/build_regime.js publishes it as research and the v1 curve
   (regime_curve.js) keeps pricing. */
(function (root) {
  var R = {
   "version": "cfb_regime_magnitude_v2",
   "generated_by": "football/cfb_p4/research/regime_magnitude_backtest.js",
   "generated_at": "2026-09-30T20:25:51.925Z",
   "engine_model_version": "edgedesk_cfb_p4_v1.0.0",
   "status": "CANDIDATE",
   "promoted": false,
   "family": "w_raw",
   "form": "w = w_std·exp(−a·f), cut weight onto the raw this-season track",
   "features": "football/coaching/regime_signal.js magnitudeFeatures: coach 0/1; prod = max(0, 1 − 2·returning production pct); qb 0/1; port = max(0, 2·incoming production pct − 1)",
   "params": {
    "coach": 0.25,
    "prod": 0.05,
    "qb": 0,
    "port": 0
   },
   "fitted_on": "2021-2025",
   "evaluation_params": {
    "coach": 0.15,
    "prod": 0.1,
    "qb": 0,
    "port": 0.05
   },
   "evaluation_fitted_on": "2021-2023",
   "verdict": {
    "chosen": "w_raw",
    "promote": false,
    "rule": "promote only if, on the 2024-2025 holdout, the chosen family is no worse than the standard curve AND no worse than the shipped v1 curve on all games and on the regime subset (point estimates); significance is reported, not required, because v1 itself is the incumbent",
    "all_vs_standard": {
     "delta_mae": -0.015,
     "ci95": [
      -0.055,
      0.023
     ],
     "significant": false
    },
    "all_vs_v1": {
     "delta_mae": 0.02,
     "ci95": [
      -0.013,
      0.053
     ],
     "significant": false
    },
    "regime_vs_v1": {
     "delta_mae": 0.025,
     "ci95": [
      -0.048,
      0.099
     ],
     "significant": false
    }
   },
   "record": {
    "holdout": "2024-2025",
    "chosen": "w_raw",
    "all_games": {
     "games": 1604,
     "mae_standard": 12.594,
     "mae_v1": 12.559,
     "mae_v2": 12.579,
     "v2_vs_standard": {
      "delta_mae": -0.015,
      "ci95": [
       -0.055,
       0.023
      ],
      "significant": false
     },
     "v2_vs_v1": {
      "delta_mae": 0.02,
      "ci95": [
       -0.013,
       0.053
      ],
      "significant": false
     }
    },
    "regime_subset": {
     "games": 537,
     "mae_standard": 13.027,
     "mae_v1": 12.921,
     "mae_v2": 12.946,
     "bias_standard": 1.679,
     "bias_v1": 0.939,
     "bias_v2": 0.791,
     "v1_vs_standard": {
      "delta_mae": -0.106,
      "ci95": [
       -0.226,
       0.017
      ],
      "significant": false
     },
     "v2_vs_standard": {
      "delta_mae": -0.08,
      "ci95": [
       -0.181,
       0.022
      ],
      "significant": false
     },
     "v2_vs_v1": {
      "delta_mae": 0.025,
      "ci95": [
       -0.048,
       0.099
      ],
      "significant": false
     }
    }
   },
   "report": "football/cfb_p4/research/report/regime_magnitude_backtest.json"
  };
  root.EDCfbP4RegimeMagnitude = R;
  if (typeof module !== 'undefined' && module.exports) module.exports = R;
})(typeof window !== 'undefined' ? window : globalThis);
