#!/usr/bin/env python3
"""Render report_nfl.json + report_cfb.json into report/BACKTEST.md.
Usage: python3 gen_report.py <out_dir>
"""
import sys, os, json

OUT = sys.argv[1] if len(sys.argv) > 1 else 'out'
HERE = os.path.dirname(os.path.abspath(__file__))
os.makedirs(os.path.join(HERE, 'report'), exist_ok=True)

n = json.load(open(os.path.join(OUT, 'report_nfl.json')))
c = json.load(open(os.path.join(OUT, 'report_cfb.json')))

def tbl(rows, headers):
    out = ['| ' + ' | '.join(headers) + ' |',
           '|' + '|'.join(['---'] * len(headers)) + '|']
    for r in rows:
        out.append('| ' + ' | '.join(str(x) for x in r) + ' |')
    return '\n'.join(out)

L = []
L.append('# EdgeDesk Football Engine — walk-forward backtest report\n')
L.append('Generated by `gen_report.py` from `report_nfl.json` / `report_cfb.json` '
         '(themselves produced by `train_nfl.py` / `train_cfb.py`). '
         'Chronological walk-forward only; hyperparameters frozen on seasons '
         '≤2015; 2016–2025 untouched. **No random splits anywhere.**\n')
L.append('## The headline, stated plainly\n')
L.append('**The NFL model does NOT beat the closing line out of sample.** '
         'Against the closing consensus spread it goes '
         f"{n['ats_spread_vs_close_test']['2']['wins']}-"
         f"{n['ats_spread_vs_close_test']['2']['n'] - n['ats_spread_vs_close_test']['2']['wins']} "
         f"({n['ats_spread_vs_close_test']['2']['win_pct']}%) at 2+ points of disagreement "
         f"(p={n['ats_spread_vs_close_test']['2']['binom_p_one_sided']}); totals reach "
         f"{n['ou_total_vs_close_test']['3']['win_pct']}% at 3+ points "
         f"(p={n['ou_total_vs_close_test']['3']['binom_p_one_sided']}) — suggestive, not significant. "
         'Only historical CLOSING lines are publicly archived (no openers), so no CLV backtest is '
         'possible; beating the close is a strictly harder test than beating an opener, and the '
         'engine ships labeled UNPROVEN until its own graded CLV against real quotes says otherwise. '
         'No CFB line archive exists at all, so CFB claims exactly nothing about the market.\n')

L.append('## NFL (1999–2025 data; scored 2003–2025; 6,232 games)\n')
L.append('### Spread accuracy (mean absolute error of the projected margin)\n')
rows = []
for era in ('tune_2003_2015', 'test_2016_2025'):
    e = n['spread_model'][era]
    rows.append([era, e['n'], e['mae_model'], e['mae_market'], e['corr_with_market']])
L.append(tbl(rows, ['window', 'games', 'model MAE', 'closing market MAE', 'corr(model, market)']))
L.append('\n### Total accuracy\n')
rows = []
for era in ('tune_2003_2015', 'test_2016_2025'):
    e = n['total_model'][era]
    rows.append([era, e['n'], e['mae_model'], e['mae_market'], e['corr_with_market']])
L.append(tbl(rows, ['window', 'games', 'model MAE', 'closing market MAE', 'corr']))
L.append('\n### ATS vs the CLOSE, 2016–2025 (the strict test)\n')
rows = [[t, d['n'], d['wins'], f"{d['win_pct']}%", d['binom_p_one_sided']]
        for t, d in n['ats_spread_vs_close_test'].items()]
L.append(tbl(rows, ['min gap (pts)', 'bets', 'wins', 'win %', 'p (one-sided)']))
L.append('\n### Totals O/U vs the CLOSE, 2016–2025\n')
rows = [[t, d['n'], d['wins'], f"{d['win_pct']}%", d['binom_p_one_sided']]
        for t, d in n['ou_total_vs_close_test'].items()]
L.append(tbl(rows, ['min gap (pts)', 'bets', 'wins', 'win %', 'p (one-sided)']))
L.append('\n### Incremental information over the market (walk-forward blend)\n')
L.append(f"Spread: blend MAE {n['spread_blend']['test_mae_blend']} vs market alone "
         f"{n['spread_blend']['test_mae_market']}; the ridge assigns the market ~1.0 weight and the "
         'football model ~0.04–0.16 — the market already contains nearly everything the model knows.\n')
L.append(f"Total: blend MAE {n['total_blend']['test_mae_blend']} vs market alone "
         f"{n['total_blend']['test_mae_market']}; model weight ~0.22–0.42, decaying over time as the "
         'market improves.\n')
L.append('\n### Win probability (2016–2025, vs de-vigged closing moneylines)\n')
rows = [['model (spread → Φ, σ=' + str(n['sigma_margin_mle']) + ')',
         n['winprob_model']['n'], n['winprob_model']['brier'], n['winprob_model']['log_loss']],
        ['market no-vig', n['winprob_market_novig']['n'],
         n['winprob_market_novig']['brier'], n['winprob_market_novig']['log_loss']]]
L.append(tbl(rows, ['source', 'n', 'Brier', 'log loss']))
L.append('\nCalibration (model): ' + ', '.join(
    f"{b['bin']}: pred {b['p_pred']} obs {b['p_obs']} (n={b['n']})" for b in n['calibration_2016_2025']))
L.append('\n### Ablations (test-era spread MAE — every layer must earn its place)\n')
a = n['ablation_spread_mae_test']
rows = [['full model', a['full_model']], ['without QB layer', a['no_qb']],
        ['without season carryover', a['no_carryover']],
        ['points-only rating (no EPA)', a['points_only']]]
L.append(tbl(rows, ['variant', 'spread MAE 2016-2025']))
L.append('\n### Key numbers (learned, not asserted)\n')
L.append('Unconditional |margin| mass: ' + ', '.join(
    f"{k}: {v*100:.1f}%" for k, v in n['abs_margin_key_mass'].items()))
L.append(f"\nConditioned on the spread (kernel, bw={n['pmf_spread_bw']} chosen by held-out "
         f"log-likelihood): P(margin=3 | spread=3) = {n['key_mass_at_minus3']['p_margin_3_given_spread_3']*100:.1f}%, "
         f"P(margin=7 | spread=7) = {n['key_mass_at_minus3']['p_margin_7_given_spread_7']*100:.1f}%.\n")

L.append('## CFB (2002–2025; FBS-involved games; 16,542 scored)\n')
L.append('No public historical CFB betting-line archive is freely available, so the benchmarks are '
         'the dataset\'s own third-party pregame Elo (mapped to margin by walk-forward fit) and '
         'home-field-only. **No market claim is made or implied for CFB.**\n')
rows = []
for era in ('2006_2013', '2014_2020', '2021_2025_portal', 'test_2016_2025'):
    e = c[era]
    rows.append([era, e['n'], e['mae_margin_model'], e['mae_margin_elo_benchmark'],
                 e['mae_margin_hfa_only'], e['mae_total_model'], e['mae_total_league_mean']])
L.append(tbl(rows, ['window', 'games', 'model margin MAE', 'Elo benchmark', 'HFA-only',
                    'model total MAE', 'league-mean total']))
L.append(f"\nWin probability (2016–2025): Brier {c['winprob_model_test']['brier']}, "
         f"log loss {c['winprob_model_test']['log_loss']}, σ = {c['sigma_margin_mle']} "
         '(wider than NFL, as it should be).')
L.append('\nCFB key-number mass (its own, flatter distribution): ' + ', '.join(
    f"{k}: {v*100:.1f}%" for k, v in c['abs_margin_key_mass'].items()))
L.append('\nEra note: the portal/NIL era (2021+) is scored separately above; frozen hyperparameters '
         'still hold up (12.98 MAE vs Elo 13.04), and the faster learned update rate (k=0.14, '
         'carry=0.75) reflects the modern roster-churn environment.\n')
L.append('\n## Reproduction\n')
L.append('```\n./fetch_data.sh data\npython3 build_features.py data out\n'
         'python3 train_nfl.py out\npython3 train_cfb.py out\n'
         'python3 make_params.py out\npython3 gen_goldens.py out\n'
         'python3 gen_report.py out\nnode ../tests.js\n```\n')

open(os.path.join(HERE, 'report', 'BACKTEST.md'), 'w').write('\n'.join(L) + '\n')
print('report/BACKTEST.md written')
