"""Render report/backtest.json (+ ablation, gates, coverage) into docs/cfb-v2/BACKTEST.md."""
import json
import os

import pandas as pd

from . import config as C
from . import common
from . import contract as K
from . import gates as GT

DOCS = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', '..', 'docs', 'cfb-v2'))
NAMES = {'ens_pred': 'V2 ensemble (pure)', 'pred_A_adj_eff': 'V2 · A adjusted-efficiency', 'pred_B_elo': 'V2 · B dynamic Elo (simple Elo baseline)',
         'pred_C_ridge': 'V2 · C ridge matchup', 'pred_D_gbm': 'V2 · D gradient boosted', 'pred_E_drive': 'V2 · E drive model',
         'ens_equal': 'V2 equal-weight average', 'base_v1': 'EdgeDesk V1 (cfb_p4, cold replay)', 'base_hfa': 'naive home-field',
         'base_cfbd_elo': 'CFBD pregame Elo (external)', 'line': 'opening market', 'close_margin': 'closing market'}


def f(x, k=3):
    if x is None:
        return '—'
    try:
        return ('%.' + str(k) + 'f') % float(x)
    except (TypeError, ValueError):
        return str(x)


def ci(c, k=3):
    if not c or c[0] is None:
        return ''
    return ' [%s, %s]' % (f(c[0], k), f(c[1], k))


def acc_table(A):
    L = ['| predictor | n | MAE [95% CI] | RMSE | median AE | bias | MAE(V2) − MAE(this) [95% CI] |', '|---|---|---|---|---|---|---|']
    for k in ('ens_pred', 'base_v1', 'base_hfa', 'pred_B_elo', 'base_cfbd_elo', 'line', 'close_margin',
              'pred_A_adj_eff', 'pred_C_ridge', 'pred_D_gbm', 'pred_E_drive', 'ens_equal'):
        a = A['accuracy'].get(k)
        if not a or not a.get('n'):
            continue
        p = A['paired_vs_v2'].get(k, {})
        L.append('| %s | %d | %s%s | %s | %s | %s | %s |' % (
            NAMES.get(k, k), a['n'], f(a['mae']), ci(a.get('mae_ci')), f(a['rmse']), f(a['median_ae']),
            f(a['bias']), ('—' if k == 'ens_pred' else f(p.get('diff')) + ci(p.get('ci')))))
    return '\n'.join(L)


def bet_line(name, b):
    if not b or not b.get('n'):
        return '| %s | 0 | — | — | — | — | — |' % name
    return '| %s | %d | %s%s | %s%s | %s%s | %s | %s |' % (
        name, b['n'], f(b.get('ats_win_rate'), 3), ci(b.get('ats_win_rate_ci')), f(b.get('roi_per_bet'), 3),
        ci(b.get('roi_ci')), f(b.get('clv_mean'), 2), ci(b.get('clv_ci'), 2), f(b.get('clv_positive_share'), 3),
        f(b.get('max_drawdown_units'), 1))


BET_HEAD = '| slice | n | ATS win rate [CI] | ROI/bet at −110 [CI] | mean CLV pts [CI] | share +CLV | max drawdown (u) |\n|---|---|---|---|---|---|---|'


def render():
    R = json.load(open(common.out_path('report', 'backtest.json')))
    G = GT.evaluate(R, 'p_home_' + R['win_calibration_choice']['method'])
    common.write_json(common.out_path('report', 'promotion.json'), G)
    run1 = common.out_path('report', 'backtest_run1_bug.json')
    R1 = json.load(open(run1)) if os.path.exists(run1) else None
    AB = json.load(open(common.out_path('report', 'ablation.json')))
    W = R['windows']
    L = []
    L.append('# EdgeDesk CFB V2 — walk-forward backtest, market comparison and promotion decision\n')
    L.append('Generated by `football/cfb_v2/research` (`v2.pipeline` → `v2.report`). Model `%s`, features `%s`. '
             'Every number is out-of-sample: each season is predicted by models fit only on earlier seasons, '
             'from features frozen at each week\'s Tuesday 12:00 UTC freeze. Scope: FBS-vs-FBS unless stated; '
             'every predictor in a table is scored on the SAME games.\n' % (R['model_version'], R['feature_version']))
    L.append('Windows: **development 2016–2023** (all tuning, ablation and threshold choices), **holdout 2024–2025** '
             '(scored once with the frozen configuration), **live 2026** (weeks already played; a replay with '
             'models trained through 2025 — see the model card for what that does and does not prove).\n')
    if R1:
        h1 = R1['windows']['holdout_2024_2025']['accuracy']['accuracy']
        L.append('## Disclosure: the holdout was scored twice\n')
        L.append('Run 1 exposed two defects, both fixed before run 2; no tuning value, feature family, window or '
                 'gate changed between the runs:\n')
        L.append('1. **Submodels A, B and E were fitted without an intercept on standardized inputs**, so they could '
                 'not represent the average home margin and came out biased by about −4 points (dev bias A −4.06, '
                 'B −3.88, E −4.10). Fixed by giving them an intercept.')
        L.append('2. **The multi-book line archive carries corrupt rows** — openers of −185 and +334 and openers whose '
                 'sign is flipped against the close. They inflated CLV (REVIEW rows showed +26.8 pts mean CLV on dev) '
                 'and fed the BET-rule search. Fixed by market QA at ingestion: implausible numbers and sign-flipped '
                 'or >14-pt opener jumps are DROPPED (never repaired). 31 values dropped.\n')
        L.append('Run 1 holdout MAE: V2 %s, V1 %s, opener %s, close %s. Run 1 dev-selected rule: `%s` — it was '
                 'enabled then, and it would have gone into production had the defects not been found. Run 2 '
                 '(this report) is the one of record.\n' % (
                     f(h1['ens_pred']['mae']), f(h1['base_v1']['mae']), f(h1['line']['mae']),
                     f(h1['close_margin']['mae']),
                     json.dumps({k: R1['rule'][k] for k in ('bet_gap', 'bet_ev', 'bet_min_rel', 'exclude_early',
                                                             'bet_enabled')})))
    L.append('## Promotion decision\n')
    L.append('**%s** — champion remains **%s**. Automatic replacement: %s.\n' % (G['decision'], G['champion'], G['automatic_replacement']))
    L.append('| gate | rule | result | evidence |\n|---|---|---|---|')
    for k, v in G['detail'].items():
        ev_ = json.loads(json.dumps(v['evidence'], default=str),
                         parse_float=lambda x: round(float(x), 4))
        L.append('| %s | %s | %s | `%s` |' % (k, v['rule'], 'PASS' if v['pass'] else '**FAIL**',
                                            json.dumps(ev_)[:240]))
    L.append('\nBET status: **%s**. %s\n' % ('enabled' if G['bet_allowed'] else 'DISABLED', G['bet_gate']))
    for wn, title in (('holdout_2024_2025', 'Holdout 2024–2025'), ('dev_2016_2023', 'Development 2016–2023'),
                      ('live_2026', 'Live 2026 (replay, weeks played so far)')):
        A = W[wn]['accuracy']
        L.append('## %s — margin accuracy\n' % title)
        L.append('Games in window: %d; common set scored below: %d.\n' % (A['n_games_all'], A['n_common']))
        L.append(acc_table(A))
        L.append('')
        wp = A['win_prob']
        L.append('**Win probability** (all games in window with a V2 probability):\n')
        L.append('| method | n | Brier [CI] | log loss | ECE |\n|---|---|---|---|---|')
        for k, v in wp.items():
            if v.get('n'):
                L.append('| %s | %d | %s%s | %s | %s |' % (k, v['n'], f(v['brier'], 4), ci(v.get('brier_ci'), 4), f(v['log_loss'], 4), f(v['ece'], 4)))
        cv = A['intervals']
        L.append('\n**Prediction-interval coverage** (nominal → observed): 50%% → %s, 80%% → %s, 95%% → %s '
                 '(mean widths %s / %s / %s pts)\n' % (
                     f(cv['50']['coverage'], 3), f(cv['80']['coverage'], 3), f(cv['95']['coverage'], 3),
                     f(cv['50']['mean_width'], 1), f(cv['80']['mean_width'], 1), f(cv['95']['mean_width'], 1)))
        B = W[wn]['betting']
        vm = B['vs_market']
        L.append('**Against the market** (games with an opener): V2 MAE %s vs opener %s (paired diff %s%s); '
                 'on games with a close: V2 %s vs close %s (paired diff %s%s). Market-adjusted challenger (V2 + '
                 'opener, weights learned walk-forward): MAE %s (vs opener diff %s%s; vs close diff %s%s). '
                 'Close moved toward V2 on %s of games where it moved. Mean learned model weight in the challenger: %s.\n' % (
                     f(vm['mae_v2']), f(vm['mae_open']), f(vm['paired_v2_minus_open']['diff']), ci(vm['paired_v2_minus_open']['ci']),
                     f(vm['mae_v2_on_close_games']), f(vm['mae_close_on_same_games']), f(vm['paired_v2_minus_close']['diff']),
                     ci(vm['paired_v2_minus_close']['ci']), f(vm['mae_market_adjusted_challenger']),
                     f(vm['paired_ma_minus_open']['diff']), ci(vm['paired_ma_minus_open']['ci']),
                     f(vm['paired_ma_minus_close']['diff']), ci(vm['paired_ma_minus_close']['ci']),
                     f(vm['close_moved_toward_v2_share'], 3), f(vm['market_adjusted_model_weight_mean'], 3)))
        L.append('**Betting simulation** — side of V2 vs the OPENER at −110, graded on the final score; CLV = move from '
                 'the opener to the close on the side taken:\n')
        L.append(BET_HEAD)
        L.append(bet_line('every game (always bet V2 side)', B['all_games_side_of_model']))
        L.append(bet_line('rows the dev rule selects (BET %s)' % ('enabled' if R['rule']['bet_enabled'] else 'DISABLED'),
                          B.get('rule_qualified')))
        for s in ('BET', 'LEAN', 'REVIEW', 'PASS'):
            L.append(bet_line('status ' + s, B['by_status'].get(s)))
        L.append('\n**Pessimistic check — the same sides graded at the CLOSING number** (if a side only wins at '
                 'the opener, the result is timing, not football):\n')
        L.append(BET_HEAD)
        L.append(bet_line('every game at close', B.get('all_games_side_of_model_at_close')))
        for s in ('BET', 'LEAN', 'REVIEW', 'PASS'):
            L.append(bet_line('status ' + s + ' at close', B.get('by_status_at_close', {}).get(s)))
        for k, v in B.get('by_edge_bucket_at_close', {}).items():
            L.append(bet_line('gap ' + k + ' at close', v))
        L.append('\nBy model–market gap (|V2 − opener|):\n')
        L.append(BET_HEAD)
        for k, v in B.get('by_edge_bucket', {}).items():
            L.append(bet_line(k + ' pts', v))
        L.append('\nBy reliability (football_prediction_confidence):\n')
        L.append(BET_HEAD)
        for k, v in B.get('by_reliability_bucket', {}).items():
            L.append(bet_line(k, v))
        cc = B.get('cover_prob_calibration_cal', {})
        cr = B.get('cover_prob_calibration_raw', {})
        L.append('\nCover-probability calibration (home cover at the opener, pushes removed): raw Brier %s / ECE %s → '
                 'calibrated Brier %s / ECE %s (n %s).\n' % (f(cr.get('brier'), 4), f(cr.get('ece'), 4),
                                                            f(cc.get('brier'), 4), f(cc.get('ece'), 4), cc.get('n')))
        if wn != 'live_2026':
            L.append('<details><summary>Betting by week, spread size, favourite/underdog, home/away, P4/G5, QB certainty, total, season</summary>\n')
            for key in ('by_week_bucket', 'by_spread_size', 'by_fav_dog_bet', 'by_home_away_bet', 'by_p4_g5',
                        'by_qb_certainty', 'by_total_size', 'by_season'):
                if key in B:
                    L.append('\n' + key.replace('by_', '').replace('_', ' ') + ':\n')
                    L.append(BET_HEAD)
                    for k, v in B[key].items():
                        L.append(bet_line(k, v))
            L.append('\n</details>\n')
            L.append('<details><summary>Accuracy by subgroup (V2 vs V1 vs opener vs close on the same games)</summary>\n')
            for key, tab in W[wn]['subgroups'].items():
                L.append('\n%s:\n' % key)
                L.append('| group | n | V2 MAE | V2 bias | V1 MAE (V2 same) | opener MAE (V2 same) | close MAE (V2 same) | 80% coverage |')
                L.append('|---|---|---|---|---|---|---|---|')
                for g, v in tab.items():
                    L.append('| %s | %d | %s | %s | %s (%s) | %s (%s) | %s (%s) | %s |' % (
                        g, v['n'], f(v['mae_v2']), f(v['bias_v2']), f(v.get('mae_base_v1')), f(v.get('mae_v2_same_base_v1')),
                        f(v.get('mae_line')), f(v.get('mae_v2_same_line')), f(v.get('mae_close_margin')),
                        f(v.get('mae_v2_same_close_margin')), f(v.get('cov80'), 3)))
            L.append('\n</details>\n')
    L.append('## Calibration curve, holdout (V2 shipped method vs V1)\n')
    H = W['holdout_2024_2025']['accuracy']['win_prob']
    m = 'p_home_' + R['win_calibration_choice']['method']
    L.append('Shipped method: **%s** (chosen on dev log loss: %s).\n' % (R['win_calibration_choice']['method'],
                                                                        json.dumps({k: round(v, 4) for k, v in R['win_calibration_choice']['dev_log_loss'].items()})))
    L.append('| bin | n | mean predicted | observed |\n|---|---|---|---|')
    for r in H.get(m, {}).get('reliability_table', []):
        L.append('| %s | %d | %s | %s |' % (r['bin'], r['n'], f(r['mean_pred'], 3), f(r['observed'], 3)))
    L.append('\n## Ensemble weights (non-negative, sum to one, fit on earlier seasons\' out-of-fold predictions)\n')
    L.append('| season | ' + ' | '.join(['A adj-eff', 'B Elo', 'C ridge', 'D GBM', 'E drive']) + ' |\n|---|---|---|---|---|---|')
    for s, w in sorted(R['stack_weights_by_season'].items()):
        L.append('| %s | %s |' % (s, ' | '.join(f(w.get(k), 3) for k in ('A_adj_eff', 'B_elo', 'C_ridge', 'D_gbm', 'E_drive'))))
    L.append('\n## Feature-family ablation (development seasons only)\n')
    for mname, lab in (('C', 'Model C (ridge)'), ('D', 'Model D (GBM)')):
        a = AB[mname]
        L.append('**%s** — forward keep rule: dev MAE falls AND it falls in ≥ half the dev seasons; then backward '
                 'elimination removes any family whose removal lowers dev MAE. Final: `%s`, dev MAE %s.\n' % (
                     lab, ', '.join(a['selected']), f(a['final_mae_dev'], 4)))
        L.append('| step | family | dev MAE | Δ vs previous kept [paired 95% CI] | dev seasons improved | kept |\n|---|---|---|---|---|---|')
        for i, s in enumerate(a['steps']):
            L.append('| %d | %s | %s | %s%s | %s | %s |' % (i + 1, s['family'], f(s['mae_dev'], 4), f(s['delta_vs_prev'], 4),
                                                             ci(s['paired_ci'], 4), f(s['seasons_improved_share'], 3),
                                                             'yes' if s['kept'] else 'no'))
        L.append('\nDrop-one from the final set (Δ MAE if the family is removed; > 0 means the family earns its place):\n')
        L.append('| family | Δ if removed | dev seasons better without |\n|---|---|---|')
        for k, v in a['drop_one'].items():
            L.append('| %s | %s | %s |' % (k, f(v['delta_if_removed'], 4), f(v.get('seasons_better_without'), 3)))
        L.append('')
    L.append('## The dev-selected decision rule\n')
    rule = R['rule']
    L.append('Selection: %s. Grid size %d. Best on dev: `%s`. BET enabled by the rule: **%s** (and by the gates: **%s**).\n' % (
        rule['selection'], rule['grid_size'], json.dumps(rule['dev_best'], default=str), rule['bet_enabled'], G['bet_allowed']))
    os.makedirs(DOCS, exist_ok=True)
    with open(os.path.join(DOCS, 'BACKTEST.md'), 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    # feature coverage + data dictionary
    X = pd.read_parquet(common.out_path('stage5', 'cfb_model_training_snapshots.parquet'))
    rdir = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'report'))
    cnt = K.write_reports(rdir, list(X.columns))
    rows = K.coverage_rows()
    CL = ['# Feature coverage — the data-pack dictionary mapped to EdgeDesk sources\n',
          'Every one of the %d candidate fields in `edgedesk_feature_dictionary.csv` has a decision. Counts: %s.\n' % (
              len(rows), ', '.join('%s %d' % kv for kv in sorted(cnt.items()))),
          'Status meanings: **AVAILABLE** read directly from a reachable feed; **DERIVABLE** computed by V2 from '
          'available data; **NEW SOURCE REQUIRED** no reachable feed carries it point-in-time; **REJECTED** '
          'derivable but refused (drift, redundancy, instability or leakage). "Used" = enters a V2 model or overlay.\n',
          '| feature | layer | priority | status | V2 column | source | used | note |', '|---|---|---|---|---|---|---|---|']
    for r in rows:
        CL.append('| %s | %s | %s | %s | %s | %s | %s | %s |' % (r['feature_name'], r['dictionary_layer'], r['priority'],
                                                                r['status'], r['v2_column'] or '—', r['v2_source'] or '—',
                                                                'yes' if r['used_in_v2_0'] else 'no', r['note']))
    with open(os.path.join(DOCS, 'FEATURE_COVERAGE.md'), 'w') as fh:
        fh.write('\n'.join(CL) + '\n')
    print('[report] wrote', DOCS)


if __name__ == '__main__':
    render()
