"""Render the red-team final report, docs/cfb-v2/REDTEAM.md, from report/redteam/*.json.

    python3 -m v2.rt_report

Every number below is read from a result file written by the analysis code
(redteam.py, harden.py, champion_report.py, tests_poison, the leakage audit);
nothing is typed in by hand except the narrative, which only interprets them.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RD = os.path.join(HERE, '..', 'report', 'redteam')
DOCS = os.path.normpath(os.path.join(HERE, '..', '..', '..', '..', 'docs', 'cfb-v2'))


def J(name, hardened=False):
    p = os.path.join(RD, 'hardened' if hardened else '', name + '.json')
    return json.load(open(p)) if os.path.exists(p) else {}


def f(x, k=3):
    if x is None:
        return '—'
    try:
        return ('%.' + str(k) + 'f') % float(x)
    except (TypeError, ValueError):
        return str(x)


def ci(c, k=3):
    return '[%s, %s]' % (f(c[0], k), f(c[1], k)) if c and c[0] is not None else ''


def wk_key(k):
    """Order week buckets ('0-1', '10+', ...) and conditions ('gap>=10') numerically."""
    m = re.findall(r'\d+(?:\.\d+)?', k)
    return (re.sub(r'[-\d.+]+', '', k), float(m[0]) if m else 0.0)


def pct(x, k=1):
    return '—' if x is None else ('%.' + str(k) + 'f%%') % (100 * float(x))


def section_components(L):
    p5 = J('phase05_components')
    names = {'pred_A_adj_eff': 'A adjusted efficiency', 'pred_B_elo': 'B dynamic Elo', 'pred_C_ridge': 'C ridge matchup',
             'pred_D_gbm': 'D boosted matchup', 'pred_E_drive': 'E drive model', 'pred': 'V2 ensemble (candidate 001)',
             'base_v1': 'EdgeDesk V1', 'open_margin': 'opening market', 'close_margin': 'closing market'}
    for w in ('dev', 'holdout'):
        W = p5[w]
        L += ['**%s** (%d games, every predictor on the same games)' % ({'dev': 'Development 2016-2023', 'holdout': 'Holdout 2024-2025'}[w], W['n_common']), '',
              '| predictor | MAE | RMSE | median AE | bias | Brier | log loss | ECE | corr(final) | corr(open) | corr(close) | resid. var | MAE vs ensemble [CI] |',
              '|---|---|---|---|---|---|---|---|---|---|---|---|---|']
        for k in ('pred', 'pred_C_ridge', 'pred_D_gbm', 'pred_A_adj_eff', 'pred_E_drive', 'pred_B_elo', 'base_v1', 'open_margin', 'close_margin'):
            m = W['metrics'].get(k)
            if not m:
                continue
            ve = m.get('vs_ensemble') or {}
            L.append('| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
                names[k], f(m['mae']), f(m['rmse'], 2), f(m['median_ae'], 2), f(m['bias'], 2), f(m['brier'], 4), f(m['log_loss'], 4),
                f(m['ece'], 4), f(m['corr_margin']), f(m.get('corr_open_margin')), f(m.get('corr_close_margin')), f(m['resid_var'], 1),
                ('%s %s' % (f(-ve['diff']), ci([-ve['ci'][1], -ve['ci'][0]]))) if ve.get('diff') is not None else '—'))
        L.append('')
    R = p5['dev']['residual_corr']
    ks = ['pred_A_adj_eff', 'pred_B_elo', 'pred_C_ridge', 'pred_D_gbm', 'pred_E_drive']
    L += ['**Residual correlation between components, development.** High values mean the models make the same mistakes.', '',
          '| | ' + ' | '.join(k.split('_')[1] for k in ks) + ' |', '|---|' + '---|' * len(ks)]
    for a in ks:
        L.append('| %s | %s |' % (a.split('_')[1], ' | '.join(f(R[a][b], 2) for b in ks)))
    L.append('')


def n_inputs(hd):
    """Distinct model inputs of candidate 001 (all five components) and of the hardened model."""
    import sys
    sys.path.insert(0, os.path.join(HERE, '..'))
    from v2 import models as MD
    from v2 import rt_walkforward as RT
    fam = json.load(open(os.path.join(HERE, '..', 'report', 'selected_families.json')))
    allf = []
    for fams in (fam['C'], fam['D']):
        for g in fams:
            allf += MD.FAMILIES[g]
    c001 = set(allf) | set(RT.A_COLS + RT.B_COLS + RT.E_COLS)
    hard = set(allf) - set(hd['R4_joint_check']['final_removed_columns'])
    return len(hard), len(c001)


def build():
    L = []
    hd = J('hardening_decisions')
    cc = J('champion_challenger')
    p4 = J('phase04_reproduction')
    H = cc['windows']['holdout']
    Dv = cc['windows']['dev']
    Lv = cc['windows']['live']
    L += ['# CFB V2 red team: final report', '',
          'This report is generated by `python3 -m v2.rt_report` from `football/cfb_v2/research/report/redteam/*.json`.', '',
          '**Premise:** V2 was assumed wrong until the evidence said otherwise.', '',
          '**How it was attacked:** in six ways.',
          '- **Frozen and rebuilt:** candidate 001 was frozen and rebuilt from a fresh download.',
          '- **Re-implemented:** it was re-implemented independently.',
          '- **Poisoned:** its inputs were poisoned with future data, to see what moves.',
          '- **Injected:** its models were offered hindsight columns under realistic names.',
          '- **Every model and feature challenged:** every component, stacker and feature group was challenged.',
          '- **Market-tested:** its probabilities and market claims were tested against the opener, the close and a coin-flip reality check.', '',
          '**What changed:** only three kinds of change were made.',
          '- fixes for things that were wrong;',
          '- removals that pre-registered, development-only rules demanded;',
          '- a data-measured recalibration of the QB overlay.', '',
          '**Adding nothing new:** no feature was added, as the brief required.', '',
          '## Summary of the evidence', '',
          '| | V1 | V2 candidate 001 | V2 hardened | opener | close |', '|---|---|---|---|---|---|']
    op = H['V2 hardened']['mae_minus_opener']
    cl = H['V2 hardened']['mae_minus_close']
    L.append('| holdout MAE (same %d games) | %s | %s | %s | %s | %s |' % (
        H['n'], f(H['V1']['mae']), f(H['V2 candidate 001']['mae']), f(H['V2 hardened']['mae']),
        f(H['V2 hardened']['mae'] - op['diff']), f(H['V2 hardened']['mae'] - cl['diff'])))
    L.append('| development MAE (same %d games) | %s | %s | %s | | |' % (Dv['n'], f(Dv['V1']['mae']), f(Dv['V2 candidate 001']['mae']), f(Dv['V2 hardened']['mae'])))
    L.append('| 2026 to date MAE (%d games) | — | %s | %s | %s | %s |' % (
        Lv['n'], f(Lv['V2 candidate 001']['mae']), f(Lv['V2 hardened']['mae']),
        f(Lv['V2 hardened']['mae'] - Lv['V2 hardened']['mae_minus_opener']['diff']),
        f(Lv['V2 hardened']['mae'] - Lv['V2 hardened']['mae_minus_close']['diff'])))
    L.append('| holdout Brier | %s | %s | %s | | |' % (f(H['V1']['brier'], 4), f(H['V2 candidate 001']['brier'], 4), f(H['V2 hardened']['brier'], 4)))
    L.append('| holdout 80%% interval coverage | — | %s | %s | | |' % (f(H['V2 candidate 001']['coverage80']), f(H['V2 hardened']['coverage80'])))
    L.append('')
    ht = J('phase14_thresholds', True)
    stab = {}
    for w in ('dev', 'holdout'):
        tot = won = 0
        for t in cc['stability'][w].values():
            for v in t.values():
                if 'V1' in v and 'V2 hardened' in v:
                    tot += 1
                    won += v['V2 hardened'] < v['V1']
        stab[w] = (won, tot)
    L += ['**The bottom line.**', '',
          '- **V2 is genuinely more accurate than V1.** The hardened version beats V1 by %s points of MAE on the holdout %s. It also wins on Brier and calibration, and in %d of %d development and %d of %d holdout stability slices (season, week, conference, favourite size).'
          % (f(-cc['windows']['holdout']['hardened_minus_v1']['diff']), ci([-cc['windows']['holdout']['hardened_minus_v1']['ci'][1], -cc['windows']['holdout']['hardened_minus_v1']['ci'][0]]),
             stab['dev'][0], stab['dev'][1], stab['holdout'][0], stab['holdout'][1]),
          '- **Hardening changed accuracy by almost nothing.** Hardened minus candidate 001 is %s on the holdout %s: the simplification cost nothing, and the fixes were about honesty, not skill.'
          % (f(cc['windows']['holdout']['hardened_minus_c001']['diff']), ci(cc['windows']['holdout']['hardened_minus_c001']['ci'])),
          '- **V2 is less accurate than the betting market.** It trails the opener by %s %s and the close by %s %s.'
          % (f(op['diff']), ci(op['ci']), f(cl['diff']), ci(cl['ci'])),
          '- **Its disagreement carries some information the market later adopts.** It is small, and it is **not a demonstrated betting edge**:',
          '  - Cover probabilities have no skill: the holdout log loss is %s, against 0.6931 for a coin flip.' % f(J('phase09_calibration', True)['cover']['holdout']['platt']['log_loss'], 4),
          '  - The best development betting rule fails the coin-flip reality check (p = %s).' % f(ht['reality_check']['p_value'], 3),
          '  - On the holdout, graded at the closing number, that rule loses %s per bet.' % pct(-ht['holdout']['at_close_same_side_-110']['roi']),
          '', '**Recommendation, in one line:** keep V1 as the champion and run the hardened V2 in shadow. BET stays disabled, and EdgeDesk remains a research and pricing tool. The details are in section 24.', '']

    # ------------------------------------------------------------ 1 leakage
    po = J('poison_hardened')
    sg = J('signs')
    with open(os.path.join(RD, 'leakage_audit.csv')) as fh:
        n_audit = sum(1 for _ in fh) - 1
    L += ['## 1. Leakage audit', '',
          'The full per-feature audit is [`LEAKAGE_AUDIT.md`](LEAKAGE_AUDIT.md). It answers the brief\'s ten questions for every one of the %d inputs.' % n_audit, '',
          '**The future-poisoning test** (`tests_poison`) rebuilds season %s twice. The second build randomises everything after the week-%s freeze, plus every later season: plays, EPA, scores, QB starters, later rosters, talent and coaching.' % (po['season'], po['cut_week']), '',
          '**Result on candidate 001\'s code** (recorded when the test was introduced, commit 15eec6e):',
          '- One feature moved on 129 pre-cutoff rows: `vol_sum`, a whole-season median fill.',
          '- The error model and the cover calibrator filled missing values with a median over the batch being predicted.', '',
          '**Result on the v2.1.0 code** (`report/redteam/poison_hardened.json`): **%s**.' % po['result'],
          ('- All %d feature columns are bit-identical on the %d pre-cutoff rows.' % (po['n_feature_columns'], po['n_pre_cutoff_rows']) if not po['moved_pre_cutoff']
           else '- %d of %d feature columns changed on pre-cutoff rows: %s.' % (len(po['moved_pre_cutoff']), po['n_feature_columns'], ', '.join(sorted(po['moved_pre_cutoff'])))),
          '- %s post-cutoff values changed, which proves the poison reached the pipeline.' % format(po['moved_post_cutoff_values'], ','),
          '- Row independence (the error model and cover design read only their own row): %s.' % ('passes' if not po['row_independence_failures'] else 'FAILS: ' + '; '.join(po['row_independence_failures'])), '',
          '**Three more problems found by audit:**',
          '- **Market QA looked at the close.** It dropped openers that were sign-flipped or more than 14 points from the close, i.e. it used the close to decide which openers existed. Fixed: those flags are now evaluation-only, and the engine\'s point-in-time orientation guard decides instead.',
          '- **The layer contract checked name prefixes.** A column named `edge_closing_line` or `qb_status_final` would have been accepted as a pure feature. Fixed: an exact allowlist.',
          '- **The live engine accepted late overlays.** It would apply a status report stamped after kickoff. Fixed: such reports are refused.', '',
          '**Injection tests:** final score, closing spread, future opponent rating, future season average, future injury status, postgame EPA and postseason ranking. Each was offered under realistic names and each was refused by both model fits.', '',
          '**Residual hindsight that cannot be removed:**',
          '- EPA comes from the provider\'s expected-points model, which was fitted on historical seasons. It is a value function of down, distance and field position, not of any game\'s outcome.',
          '- The publication timestamps of third-party preseason releases (talent, returning production) are not in the feed. Their contribution is measured by ablation below instead.', '']

    # ------------------------------------------------------------ 2 signs
    L += ['## 2. Sign-convention audit', '',
          '**Canonical convention:** home margin > 0 means the home team is expected to win by that many points. A book line of Texas Tech −7 at home becomes internal +7; the same line with Texas Tech on the road becomes −7. The conversion happens once, at ingestion.', '',
          '**What `tests_signs.py` (%d of %d checks pass) and the engine `tests.js` sign block cover:**' % (sg['passed'], sg['total']),
          '- %d hand-graded scenarios, run through every consumer: %s;' % (len(sg['scenarios']), '; '.join(sg['scenarios'])),
          '- both converters: the archive, which is already margin convention and must not be negated again, and the CFBD feed, which is book convention;',
          '- cover grading, EV, CLV and the break-even price;',
          '- alternate spreads (now excluded from the consensus);',
          '- the market-moved-toward-model label;',
          '- mirror symmetry.', '',
          '**On the real archive** (the checks assert each of these):',
          '- Home and road favourites win in every source and every site type (%s).' % sg['tests']['data_home_and_road_favourites_win_by_source_and_site']['detail'],
          '- Pick\'em games split close to 50/50, and after a favourite flip the closing favourite wins more often (%s).' % sg['tests']['data_pickem_and_flips_behave']['detail'],
          '- Graded rows match a longhand implementation exactly (%s).' % sg['tests']['data_grading_matches_longhand_on_real_rows']['detail'], '',
          '**Result:** no sign bug was found.', '']

    # ------------------------------------------------------------ 3 walk-forward
    L += ['## 3. Walk-forward methodology', '',
          '**Seasons:**',
          '- **2009-2011:** burn-in (variance components, QB shrinkage).',
          '- **2012 onward:** the first frozen feature rows.',
          '- **2014 onward:** out-of-fold components.',
          '- **2016 onward:** stacking.',
          '- **2017 onward:** calibration.',
          '- **Development:** 2016-2023, where every choice is made.',
          '- **Holdout:** 2024-2025.',
          '- **Live:** 2026.', '',
          '**The rules:**',
          '- For season S, every fit uses seasons < S only: expanding window, never a random split.',
          '- Features are frozen at each week\'s Tuesday 12:00 UTC freeze, from games that kicked off before it.',
          '- There is one prediction per game and freeze, written once.', '',
          '**Independent reproduction.** `rt_walkforward.py` re-implements the loop without the original code: scikit-learn ridge, LightGBM called directly, and its own stackers, error model and calibrators. Against candidate 001\'s frozen record (%d games, stored to 4 decimals, so 5e-5 is the resolution) the largest absolute differences are:' % p4['n_games'],
          '- components: %s;' % ', '.join('%s %.1e' % (c, p4['pred_' + c]['max_abs_diff']) for c in ('A_adj_eff', 'B_elo', 'C_ridge', 'D_gbm', 'E_drive')),
          '- the ensemble %.1e, sigma %.1e, reliability %.1e;' % (p4['pred']['max_abs_diff'], p4['sigma']['max_abs_diff'], p4['reliability']['max_abs_diff']),
          '- interval bounds %.1e; raw win probability %.1e.' % (max(p4[b % q]['max_abs_diff'] for q in (50, 80, 95) for b in ('lo_%d', 'hi_%d')), p4['p_win_raw']['max_abs_diff']), '',
          '**A contamination this check caught.** Hardening added a production drop list (`config.DROPPED_FEATURES`) inside `models.features_for`, which silently removed the five dropped features from the red team\'s "candidate 001" spec too. This check then showed ridge and GBM differences of up to 4 points. The drop list is now applied only on production paths; the red-team spec is explicit (`drop=()` for candidate 001), a test pins that, and every candidate-001 phase computed after the change was re-run.', '',
          '**Reproduction from scratch.** Before freezing, the whole pipeline was rebuilt from a fresh data download. Every development and holdout metric matched the committed backtest to within optimizer tolerance.', '',
          '**The holdout has been used.** The 2024-2025 holdout was scored for candidate 001 before this red team, and its diagnostics were visible during the audit. Every hardening choice therefore followed pre-registered, development-only rules ([`HARDENING_PREREG.md`](HARDENING_PREREG.md)). The only untouched evidence is 2026.', '']

    # ------------------------------------------------------------ 4 components
    L += ['## 4. Individual model performance (candidate 001)', '']
    section_components(L)
    p5 = J('phase05_components')
    rc = {w: p5[w]['residual_corr'] for w in ('dev', 'holdout')}
    mae5 = {w: {k: v.get('mae') for k, v in p5[w]['metrics'].items()} for w in ('dev', 'holdout')}
    weak = ('pred_A_adj_eff', 'pred_B_elo', 'pred_E_drive')
    gaps = [mae5[w][k] - min(mae5[w]['pred_C_ridge'], mae5[w]['pred_D_gbm']) for w in mae5 for k in weak]
    cors = [rc[w][k][c] for w in rc for k in weak for c in ('pred_C_ridge', 'pred_D_gbm')]
    b_cor = [rc[w]['pred_B_elo'][c] for w in rc for c in ('pred_C_ridge', 'pred_D_gbm')]
    L += ['**Reading:**',
          '- C (ridge) and D (boosted trees) carry the ensemble. Their errors correlate at %s (development) and %s (holdout), so they are nearly the same model.' % (
              f(rc['dev']['pred_C_ridge']['pred_D_gbm'], 3), f(rc['holdout']['pred_C_ridge']['pred_D_gbm'], 3)),
          '- A, B and E are %s-%s points worse than the better of C and D, and their errors correlate %s-%s with C and D.' % (
              f(min(gaps), 2), f(max(gaps), 2), f(min(cors), 2), f(max(cors), 2)),
          '- B (results-only Elo) is the most *different* model (error correlation %s-%s with C and D), but it is also among the worst.' % (f(min(b_cor), 2), f(max(b_cor), 2)), '']

    # ------------------------------------------------------------ 5 ensembles
    p6 = J('phase06_ensembles')
    L += ['## 5. Ensemble performance', '',
          'Every stacker was fitted on out-of-fold component predictions of earlier seasons only.', '',
          '| method | dev MAE | holdout MAE | 2026 MAE | vs current stack, dev | vs simple mean, dev | weight SD across seasons |', '|---|---|---|---|---|---|---|']
    for m, v in p6['methods'].items():
        sd = v.get('weight_sd_across_seasons') or {}
        L.append('| %s | %s | %s | %s | %s | %s | %s |' % (m, f(v['windows']['dev']['mae']), f(v['windows']['holdout']['mae']), f(v['windows']['live']['mae']),
                                                           f(v['windows']['dev']['vs_current']['diff']), f(v['windows']['dev']['vs_mean']['diff']),
                                                           ', '.join('%s %s' % (k.split('_')[0], f(x, 3)) for k, x in sd.items()) if sd else '—'))
    L += ['', '**Drop one component from the stack** (MAE without it minus MAE with it; positive means it helped):', '',
          '| component | dev [CI] | holdout [CI] |', '|---|---|---|']
    for k, v in p6['drop_one_component'].items():
        L.append('| %s | %s %s | %s %s |' % (k, f(v['dev']['diff'], 4), ci(v['dev']['ci'], 4), f(v['holdout']['diff'], 4), ci(v['holdout']['ci'], 4)))
    L += ['', '| subset | dev MAE | holdout MAE | 2026 MAE |', '|---|---|---|---|']
    for k, v in p6['subsets'].items():
        L.append('| %s | %s | %s | %s |' % (k.replace(' | ', ' · '), f(v['dev']['mae']), f(v['holdout']['mae']), f(v['live']['mae'])))
    wr = p6['methods']['sum_to_one_nonneg']['weight_range']
    sub = p6['subsets']
    L += ['', '**Reading:**',
          '- **The weights are stable, not wild.** C stays at %s-%s and D at %s-%s across seasons.' % (
              f(wr['C_ridge'][0], 2), f(wr['C_ridge'][1], 2), f(wr['D_gbm'][0], 2), f(wr['D_gbm'][1], 2)),
          '- **The stack beats a simple 5-model mean only because the mean includes three weak models** (development MAE %s vs %s). A plain average of C and D scores %s on development and %s on the holdout, against the fitted stack\'s %s and %s.' % (
              f(p6['methods']['sum_to_one_nonneg']['windows']['dev']['mae']), f(p6['methods']['mean']['windows']['dev']['mae']),
              f(sub['C+D | mean']['dev']['mae']), f(sub['C+D | mean']['holdout']['mae']),
              f(p6['methods']['sum_to_one_nonneg']['windows']['dev']['mae']), f(p6['methods']['sum_to_one_nonneg']['windows']['holdout']['mae'])),
          '- **Hardened choice (rules R2/R3):** C and D, equal weights.', '']

    # ------------------------------------------------------------ 6 ablation
    p7 = J('phase07_ablation')
    L += ['## 6. Feature ablation', '',
          '**Method:** remove one group from every component that uses it, refit walk-forward, and compare on the same games.', '',
          '**Sign:** deltas are *ablated − baseline*, so a positive ΔMAE means removing the group hurts.', '',
          '**Decisions** apply the pre-registered rule on development seasons only. The development seasons with probabilities are 2017-2023, hence "of 7".', '',
          '| group | ΔMAE dev [95% CI] | ΔRMSE | ΔBrier | ΔATS | ΔCLV | seasons it hurts to remove | decision | ΔMAE holdout [CI] |', '|---|---|---|---|---|---|---|---|---|']
    for sec in ('groups', 'prior_rebuilds'):
        for g, v in p7[sec].items():
            if 'dev' not in v:
                L.append('| %s | — | | | | | | %s | |' % (g, v.get('status')))
                continue
            d, h = v['dev'], v['holdout']
            L.append('| %s%s | %s %s | %s | %s | %s | %s | %d of %d | **%s** | %s %s |' % (
                g, ' (prior rebuilt)' if sec == 'prior_rebuilds' else '', f(d['d_mae'], 4), ci(d['d_mae_ci'], 4), f(d['d_rmse'], 4),
                f(d['d_brier'], 4), f(d['d_ats'], 4), f(d['d_clv'], 3), d['seasons_removal_hurts'], d['seasons'], v['decision'],
                f(h['d_mae'], 4), ci(h['d_mae_ci'], 4)))
    for k, why in p7.get('not_testable', {}).items():
        L.append('| %s | not testable | | | | | | — | %s |' % (k, why))
    pr_ = p7['prior_rebuilds']
    gr_ = p7['groups']

    def dm(g, w):
        return f((pr_.get(g) or gr_.get(g))[w]['d_mae'], 2).replace('-0.00', '0.00')
    L += ['', '**Reading:** preseason information is by far the most valuable input.',
          '- All of it together is worth %s points on development and %s on the holdout.' % (dm('all preseason information', 'dev'), dm('all preseason information', 'holdout')),
          '- Talent alone is worth %s on development and %s on the holdout.' % (dm('recruiting / talent', 'dev'), dm('recruiting / talent', 'holdout')),
          '- Last-season ratings are worth %s on development and %s on the holdout; returning production %s on development and %s on the holdout.' % (
              dm('last season ratings (program baseline)', 'dev'), dm('last season ratings (program baseline)', 'holdout'),
              dm('returning production', 'dev'), dm('returning production', 'holdout')),
          '- In season, recent form carries signal on both windows (%s / %s); results-based Elo helps on development (%s) but not on the holdout (%s).' % (
              dm('recent form', 'dev'), dm('recent form', 'holdout'), dm('results-based Elo', 'dev'), dm('results-based Elo', 'holdout')),
          '- Havoc adds nothing (development %s): it was removed. Drive efficiency is also REMOVE, and only fed the dropped E model.' % f(gr_['havoc']['dev']['d_mae'], 4),
          '- Many groups are RETEST: tiny, unresolved effects the development window cannot separate from zero. They were kept, conservatively.', '']
    p8 = J('phase08_overfit')
    if p8:
        tv = p8['train_vs_oof']
        cur_g = p8['gbm_sweep']['current (7 leaves, 250 trees, lr .03)']
        cf = p8['by_home_conference_dev_holdout']
        early, late = ('2014', '2015', '2016'), ('2022', '2023', '2024', '2025')

        def gap(c, seasons):
            v = [tv[S][c]['oof_mae'] - tv[S][c]['train_mae'] for S in seasons if S in tv]
            return sum(v) / len(v)
        L += ['### Overfitting', '',
              '| season | ridge train MAE | ridge next-season MAE | GBM train MAE | GBM next-season MAE |', '|---|---|---|---|---|']
        for S, v in tv.items():
            L.append('| %s | %s | %s | %s | %s |' % (S, f(v['C_ridge']['train_mae']), f(v['C_ridge']['oof_mae']), f(v['D_gbm']['train_mae']), f(v['D_gbm']['oof_mae'])))
        L += ['', '**Complexity sweeps** (the component\'s own dev / holdout MAE):', '']
        L.append('- **Ridge alpha:** ' + '; '.join('%s → %s / %s' % (k, f(v['dev']), f(v['holdout'])) for k, v in sorted(p8['ridge_alpha_sweep'].items(), key=lambda kv: float(kv[0]))))
        L.append('- **GBM:** ' + '; '.join('%s → %s / %s' % (k, f(v['dev']), f(v['holdout'])) for k, v in p8['gbm_sweep'].items()))
        nz = p8['noise_features']
        L += ['', '**Noise test:** 10 pure-noise columns were added to both models.',
              '- Development MAE changed by %s %s.' % (f(nz['vs_base']['dev']['d_mae'], 4), ci(nz['vs_base']['dev']['d_mae_ci'], 4)),
              '- The GBM ranked noise columns as high as #%d of %d, with %s of the total gain.'
              % (min(min(v['noise_ranks']) for v in nz['ranks'].values()), list(nz['ranks'].values())[0]['n_features'],
                 pct(max(v['noise_gain_share'] for v in nz['ranks'].values()))),
              '- The ridge ranked noise as high as #%d.' % min(min(v['ridge_noise_ranks']) for v in nz['ranks'].values()),
              '- **Conclusion:** many features carry signal no bigger than noise. That is an argument for the simplification.', '',
              '**Leave-one-training-season-out:** dropping any single season changes the 2024 and 2025 fits by less than %s points, so there is no single-season dependence.'
              % f(max(abs(x) for S in p8['leave_one_training_season_out'].values() for d in S.values() for x in d.values() if x is not None), 3),
              '', '**Other checks:**',
              '- Train and next-season errors converge as training data grows: the next-season minus training gap averages %s (ridge) and %s (GBM) for 2014-2016 and %s and %s for 2022-2025.' % (
                  f(gap('C_ridge', early), 2), f(gap('D_gbm', early), 2), f(gap('C_ridge', late), 2), f(gap('D_gbm', late), 2)),
              '- The chosen settings are within %s (ridge) and %s (GBM) points of the best development value in their sweeps. GBM settings better than the chosen one on development: %s.'
              % (f(p8['ridge_alpha_sweep']['30']['dev'] - min(v['dev'] for v in p8['ridge_alpha_sweep'].values()), 3),
                 f(cur_g['dev'] - min(v['dev'] for v in p8['gbm_sweep'].values()), 3),
                 ', '.join('%s (%s)' % (k, f(v['dev'] - cur_g['dev'], 3)) for k, v in p8['gbm_sweep'].items() if v['dev'] < cur_g['dev']) or 'none'),
              '- By season, candidate 001 beats V1 in %d of %d seasons with a V1 replay. By home conference (development + holdout), its gap to the opener on the same games ranges from %s to %s points and its bias from %s to %s.' % (
                  sum(1 for v in p8['by_season'].values() if v.get('mae_v1') is not None and v['mae_v2'] < v['mae_v1']),
                  sum(1 for v in p8['by_season'].values() if v.get('mae_v1') is not None),
                  f(min(v['mae_v2_same'] - v['mae_open_same'] for v in cf.values()), 2), f(max(v['mae_v2_same'] - v['mae_open_same'] for v in cf.values()), 2),
                  f(min(v['bias_v2'] for v in cf.values()), 2), f(max(v['bias_v2'] for v in cf.values()), 2)), '']

    # ------------------------------------------------------------ 7 calibration
    for tag, hard in (('candidate 001', False), ('hardened', True)):
        p9 = J('phase09_calibration', hard)
        if tag == 'candidate 001':
            L += ['## 7. Calibration report', '',
                  'All calibrators (raw, Platt, isotonic, beta) are fitted on earlier seasons only. The method is chosen on development log loss.', '']
        L += ['**%s**' % tag, '', '| target | window | method | Brier | log loss | ECE | slope | intercept |', '|---|---|---|---|---|---|---|---|']
        for kind in ('win', 'cover'):
            for w in ('dev', 'holdout', 'live'):
                for m, v in p9[kind][w].items():
                    if isinstance(v, dict) and v.get('n'):
                        L.append('| %s | %s | %s | %s | %s | %s | %s | %s |' % (kind, w, m, f(v['brier'], 4), f(v['log_loss'], 4), f(v['ece'], 4),
                                                                             f(v['cal_slope'], 2), f(v['cal_intercept'], 3)))
        L.append('')
    p9 = J('phase09_calibration', True)
    L += ['**Win probability (hardened, raw), folded to the favourite:**', '', '| bucket | dev n | dev predicted | dev observed | holdout n | holdout predicted | holdout observed [CI] |', '|---|---|---|---|---|---|---|']
    hb = {b['bucket']: b for b in p9['win']['holdout']['raw']['favorite_buckets']}
    for b in p9['win']['dev']['raw']['favorite_buckets']:
        h = hb.get(b['bucket'], {})
        L.append('| %s | %d | %s | %s | %s | %s | %s %s |' % (b['bucket'], b['n'], pct(b['pred']), pct(b['obs']), h.get('n', '—'), pct(h.get('pred')), pct(h.get('obs')),
                                                            ('[%s, %s]' % (pct(h['obs_ci'][0]), pct(h['obs_ci'][1]))) if h.get('obs_ci') and h['obs_ci'][0] is not None else ''))
    L += ['', '**Cover probability against the opener (raw, before calibration), folded to the side the model takes:**', '',
          '| bucket | dev n | dev predicted | dev observed | holdout n | holdout observed |', '|---|---|---|---|---|---|']
    hb = {b['bucket']: b for b in p9['cover']['holdout']['raw']['side_buckets']}
    for b in p9['cover']['dev']['raw']['side_buckets']:
        h = hb.get(b['bucket'], {})
        L.append('| %s | %d | %s | %s | %s | %s |' % (b['bucket'], b['n'], pct(b['pred']), pct(b['obs']), h.get('n', '—'), pct(h.get('obs'))))
    rb = {w: {b['bucket']: b for b in p9['cover'][w]['raw']['side_buckets']} for w in ('dev', 'holdout')}
    pb = p9['cover']['holdout']['platt']['side_buckets']
    in5055 = sum(b['n'] for b in pb if b['bucket'] == '50-55%') / max(1, sum(b['n'] for b in pb))
    L += ['', '**Reading:**',
          ('- **Win probabilities are well calibrated.** The raw distribution is already the best on development log loss, so no calibration layer is needed.'
           if p9['win_choice_dev_logloss'] == 'raw' else '- **Win probabilities:** development log loss selects %s.' % p9['win_choice_dev_logloss']),
          '- **Raw cover probabilities are badly overconfident.** "65-70%% to cover" covered %s on development and %s on the holdout.' % (
              pct(rb['dev']['65-70%']['obs']), pct(rb['holdout']['65-70%']['obs'])),
          '- **Calibrated cover probabilities collapse toward a coin flip.** %s of holdout Platt probabilities fall in 50-55%%, and their holdout log loss is %s against a coin flip\'s 0.6931.' % (
              pct(in5055), f(p9['cover']['holdout']['platt']['log_loss'], 4)),
          '- **V2\'s disagreement with the opener does not predict covers.** It is shown, and never sold as a probability edge.', '']

    # ------------------------------------------------------------ 8 uncertainty
    p10 = J('phase10_uncertainty', True)
    L += ['## 8. Uncertainty coverage (hardened)', '', '| segment | dev n | 50% | 80% | 95% | holdout n | 50% | 80% | 95% |', '|---|---|---|---|---|---|---|---|---|']
    for k, v in p10['dev'].items():
        if not isinstance(v, dict):
            L.append('| %s | %s | | | | | | | |' % (k, v))
            continue
        h = p10['holdout'].get(k, {}) if isinstance(p10['holdout'].get(k), dict) else {}
        L.append('| %s | %d | %s | %s | %s | %s | %s | %s | %s |' % (k, v['n'], f(v['cov50']), f(v['cov80']), f(v['cov95']), h.get('n', '—'),
                                                                  f(h.get('cov50')), f(h.get('cov80')), f(h.get('cov95'))))
    off = []
    for w in ('dev', 'holdout'):
        for k, v in p10[w].items():
            if isinstance(v, dict) and v.get('n', 0) >= 150 and v.get('cov80') is not None and abs(v['cov80'] - 0.8) > 0.03 \
                    and not k.startswith('FBS-vs-FCS'):
                off.append('%s %s (80%% covers %s, n=%d)' % (w, k, f(v['cov80']), v['n']))
    a = p10['holdout']['all FBS-vs-FBS']
    fc = {w: p10[w]['FBS-vs-FCS'] for w in ('dev', 'holdout', 'live')}
    L += ['', '**Reading:**',
          '- **FBS vs FBS as a whole is honest:** on the holdout, the 50/80/95%% intervals cover %s / %s / %s.' % (f(a['cov50']), f(a['cov80']), f(a['cov95'])),
          '- **Segments off target by more than 3 points at 80%% (n ≥ 150):** %s. These are small, mixed-direction deviations and are not corrected.' % ('; '.join(off) if off else 'none'),
          '- **FBS vs FCS:** the 80%% intervals cover %s on development and %s on the holdout, but only because they are about %s points wide; on the %d FBS-vs-FCS games of 2026 so far they cover %s. The mean is biased against the FBS side by %s %s on development and %s %s on the holdout. That bias is why those games are not priced.' % (
              f(fc['dev']['cov80']), f(fc['holdout']['cov80']), f(fc['holdout']['mean_width80'], 0), fc['live']['n'], f(fc['live']['cov80']),
              f(fc['dev'].get('fbs_side_bias'), 2), ci(fc['dev'].get('fbs_side_bias_ci'), 2), f(fc['holdout'].get('fbs_side_bias'), 2), ci(fc['holdout'].get('fbs_side_bias_ci'), 2)), '']

    # ------------------------------------------------------------ 9 misses
    p11 = J('phase11_misses')
    L += ['## 9. Largest-miss analysis (candidate 001, dev + holdout)', '',
          'The worst %d misses were classified from post-game evidence: turnovers, special teams, explosive plays, success margin, garbage-time share, QB starter vs expected, observed weather (used only as a diagnostic), pace and data completeness.' % p11['n_worst'], '',
          '| class | count |', '|---|---|']
    for k, v in sorted(p11['class_frequency'].items(), key=lambda kv: -kv[1]):
        L.append('| %s | %d |' % (k, v))
    L += ['', '**Decomposition of the error** (development fit, per unit of each):',
          '- %s points per turnover of margin;' % f(p11['decomposition_coef_dev']['to_margin'], 2),
          '- %s per point of net special-teams EPA;' % f(p11['decomposition_coef_dev']['st_net'], 2),
          '- %s per explosive-play differential;' % f(p11['decomposition_coef_dev']['expl_diff'], 2),
          '- %s per play of success margin.' % f(p11['decomposition_coef_dev']['sr_margin'], 2), '',
          '**How much it explains:**',
          '- These post-game factors explain %s of V2\'s error variance.' % pct(p11['decomposition_r2_dev'], 0),
          '- Turnovers, special teams and explosive plays alone explain %s.' % pct(p11['share_of_error_variance_explained_by_postgame_luck_factors']['turnovers+special teams+explosives (no success margin)'], 0),
          '- The opening line also missed %s of these games by more than 21 points.' % pct(p11['market_also_missed_share'], 0), '',
          '**Reading:**',
          '- %s of the worst misses are blowouts (garbage time) or FCS games; the market missed nearly all of them too.' % (
              pct((p11['class_frequency'].get('garbage time', 0) + p11['class_frequency'].get('FCS data weakness', 0)) / p11['n_worst'], 0)),
          '- Unexpected quarterback changes (%s) are the largest class a pregame source could have flagged, ahead of bad preseason priors (%s); the QB overlay now addresses the first.' % (
              pct(p11['class_frequency'].get('QB injury/change', 0) / p11['n_worst'], 0), pct(p11['class_frequency'].get('bad preseason prior', 0) / p11['n_worst'], 0)),
          '- No single failure mode justifies a new feature.', '']

    # ------------------------------------------------------------ 10 residuals
    p12 = J('phase12_residuals', True)
    L += ['## 10. Residual bias (hardened)', '',
          'Each slice is oriented to a team of interest: a positive bias means V2 **overrates** that team.', '',
          '**Rule:** a bias counts as systematic only if the development CI excludes 0 **and** the holdout CI excludes 0 with the same sign.', '',
          '| slice | dev bias [CI] (n) | holdout bias [CI] (n) | verdict |', '|---|---|---|---|']
    for k, verdict in p12['verdict'].items():
        d, h = p12['dev'][k], p12['holdout'].get(k, {})
        L.append('| %s | %s %s (%d) | %s %s (%s) | %s |' % (k, f(d['bias'], 2), ci(d['ci'], 2), d['n'], f(h.get('bias'), 2), ci(h.get('ci'), 2), h.get('n', '—'), verdict))
    L += ['', '**Margin calibration slope** (actual on predicted): development %s, holdout %s.'
          % (f(p12['dev']['margin calibration slope (actual on predicted)']['slope'], 3), f(p12['holdout']['margin calibration slope (actual on predicted)']['slope'], 3)), '',
          '**Systematic, on both windows:**',
          '- V2 underrates the P4 side of P4-vs-G5 games.',
          '- V2 underrates market favourites, especially favourites of more than 21 points.', '',
          '**Not found:** overreaction to blowouts, turnover luck or explosiveness, and home-field bias, on both windows.', '',
          '**Not fixed yet:** the fix is a new feature, and the brief says not to add features. It is sized in section 23.', '']

    # ------------------------------------------------------------ 11-13 market
    for tag, hard in (('candidate 001', False), ('hardened', True)):
        m = J('phase13_market', hard)
        if tag == 'candidate 001':
            L += ['## 11. Opener / close comparison', '',
                  '**Scope:** every priced game with an opener and a close. Model direction is the sign of V2 minus the opener.', '',
                  '| model | window | games | V2 − opener MAE [CI] | V2 − close MAE [CI] |', '|---|---|---|---|---|']
        for w in ('dev', 'holdout', 'live'):
            o = m[w]
            L.append('| %s | %s | %d | %s %s | %s %s |' % (tag, w, o['n_movement'], f(o['v2_minus_open']['diff']), ci(o['v2_minus_open']['ci']),
                                                         f(o['v2_minus_close']['diff']), ci(o['v2_minus_close']['ci'])))
    L += ['', '**Reading:** V2 is less accurate than the opener and the close in every window, including the 2026 games to date.', '',
          '## 12. CLV analysis', '',
          '| model | window | close moved toward V2 (of moves) | mean CLV, all games [CI] | excluding rows production sends to REVIEW [CI] | move per point of opener gap [CI] | V1\'s move per point |',
          '|---|---|---|---|---|---|---|']
    for tag, hard in (('candidate 001', False), ('hardened', True)):
        m = J('phase13_market', hard)
        for w in ('dev', 'holdout', 'live'):
            o = m[w]
            L.append('| %s | %s | %s | %s %s | %s %s | %s %s | %s |' % (
                tag, w, f(o['close_moved_toward_v2_share_of_moves']), f(o['mean_clv_all_games']), ci(o['mean_clv_ci']),
                f(o['mean_clv_excluding_review_rows']), ci(o['mean_clv_excluding_review_ci']),
                f(o['move_on_gap_slope']['slope']), ci(o['move_on_gap_slope']['ci']), f(o.get('v1_move_on_gap_slope'))))
    MK = {(tag, w): J('phase13_market', hard)[w] for tag, hard in (('001', False), ('hardened', True)) for w in ('dev', 'holdout', 'live')}
    sl = [o['move_on_gap_slope'] for o in MK.values()]
    clv = [o[k] for o in MK.values() for k in ('mean_clv_all_games', 'mean_clv_excluding_review_rows')]
    jr = {k: o['joint_move_regression_v2_v1'] for k, o in MK.items() if 'joint_move_regression_v2_v1' in o}
    hd_dev, hd_ho = MK[('hardened', 'dev')], MK[('hardened', 'holdout')]
    L += ['', '**Reading:** the close moves toward V2 by %s-%s points per point of disagreement with the opener.' % (f(min(x['slope'] for x in sl), 2), f(max(x['slope'] for x in sl), 2)),
          '- The slope\'s CI is above zero on %d of %d model-window pairs.' % (sum(x['ci'][0] > 0 for x in sl), len(sl)),
          '- In a joint regression of the move on both gaps, V2\'s coefficient is %s to %s and V1\'s is %s to %s: V2 carries V1\'s information about the move.' % (
              f(min(v[0] for v in jr.values()), 3), f(max(v[0] for v in jr.values()), 3), f(min(v[1] for v in jr.values()), 3), f(max(v[1] for v in jr.values()), 3)),
          '- Mean CLV is positive: %s to %s points depending on window and definition.' % (f(min(clv), 2), f(max(clv), 2)), '',
          'Two cautions:',
          '1. **Opener QA matters.** The hardened pipeline restores openers the old close-based QA dropped; the ones production must route to REVIEW (mostly corrupt, sign-flipped rows: %d on development, %d on the holdout) carry "CLV" that no bet could collect. Excluding them moves development CLV from %s to %s and holdout from %s to %s.' % (
              hd_dev['review_rows'], hd_ho['review_rows'], f(hd_dev['mean_clv_all_games'], 2), f(hd_dev['mean_clv_excluding_review_rows'], 2),
              f(hd_ho['mean_clv_all_games'], 2), f(hd_ho['mean_clv_excluding_review_rows'], 2)),
          '2. **CLV of this size does not clear a −110 vig.** See sections 13-15.', '',
          '## 13. Edge-bucket analysis (hardened)', '',
          'Every game at the opener, on the side the model prefers, at −110. Buckets are the absolute gap between V2 and the opener. Tiny buckets are flagged.', '',
          '| window | gap | games | mean move toward V2 [CI] | +CLV share | ATS at open [CI] | ROI at open [CI] | ATS at close | ROI at close |',
          '|---|---|---|---|---|---|---|---|---|']
    m = J('phase13_market', True)
    for w in ('dev', 'holdout'):
        for k, b in m[w]['gap_buckets'].items():
            L.append('| %s | %s%s | %d | %s %s | %s | %s %s | %s %s | %s | %s |' % (
                w, k, ' (small)' if b['tiny'] else '', b['n'], f(b['avg_move_toward_model'], 2), ci(b['move_ci'], 2), f(b['pos_clv_share']),
                f(b['ats_open']), ci(b['ats_open_ci']), f(b['roi_open']), ci(b['roi_open_ci']), f(b['ats_close']), f(b['roi_close'])))
    sig = [(w, k, b) for w in ('dev', 'holdout') for k, b in m[w]['gap_buckets'].items()
           if b.get('ats_open_ci') and b['ats_open_ci'][0] is not None and b['ats_open_ci'][0] > 0.5]
    L += ['', '**Reading:** larger disagreement brings a larger move toward V2. But no bucket\'s against-the-spread win rate is distinguishable from 50% on **both** windows.']
    for w, k, b in sig:
        other = 'holdout' if w == 'dev' else 'dev'
        o = m[other]['gap_buckets'].get(k, {})
        L += ['', '**One exception on one window: the %s bucket.**' % k,
              '- **%s:** %s against the spread %s over %d games.' % (w, pct(b['ats_open']), '[%s, %s]' % (pct(b['ats_open_ci'][0]), pct(b['ats_open_ci'][1])), b['n']),
              '- **%s:** %s %s over %d games. It did not replicate.' % (other, pct(o.get('ats_open')), '[%s, %s]' % (pct(o['ats_open_ci'][0]), pct(o['ats_open_ci'][1])) if o.get('ats_open_ci') else '', o.get('n', 0)),
              '- **Why it is not an edge:** one bucket of seven clearing on one window is what multiple comparisons produce. The threshold search, which includes such rules, still fails the reality check. Many of these rows are ones production routes to REVIEW.',
              '- **What to do with it:** it is recorded as a hypothesis to evaluate on frozen 2026+ shadow games, not an edge.']
    L.append('')

    # ------------------------------------------------------------ 14 thresholds
    L += ['## 14. Betting-threshold analysis', '',
          '**How the rule was chosen:**',
          '- **Grid:** minimum gap × maximum gap × minimum calibrated cover probability × minimum reliability × maximum C/D disagreement.',
          '- **Selection:** the lower 90% bound of ROI on development, requiring at least 150 plays.',
          '- **Reality check:** the same search was repeated on 500 coin-flip worlds.',
          '- **Holdout:** scored once.', '',
          '| model | rule chosen on dev | dev ROI (open) | reality check p | holdout at open: n / ATS / ROI [CI] | holdout at close: ATS / ROI [CI] | 2026: n / ROI at close |',
          '|---|---|---|---|---|---|---|']
    for tag, hard in (('candidate 001', False), ('hardened', True)):
        t = J('phase14_thresholds', hard)
        ho, hc, lv = t['holdout']['at_open_-110'], t['holdout']['at_close_same_side_-110'], t['live']['at_close_same_side_-110']
        L.append('| %s | %s | %s | %s | %d / %s / %s %s | %s / %s %s | %s / %s |' % (
            tag, ', '.join('%s %s' % (k, v) for k, v in t['best_rule'].items()), pct(t['dev_best_roi']), f(t['reality_check']['p_value'], 3),
            ho['n'], pct(ho['win_rate']), pct(ho['roi']), '[%s, %s]' % (pct(ho['roi_ci'][0]), pct(ho['roi_ci'][1])),
            pct(hc['win_rate']), pct(hc['roi']), '[%s, %s]' % (pct(hc['roi_ci'][0]), pct(hc['roi_ci'][1])), lv.get('n'), pct(lv.get('roi'))))
    t = J('phase14_thresholds', True)
    L += ['', '**One condition at a time (hardened):**', '',
          '| condition | dev n | dev ATS | dev ROI | dev CLV | holdout n | holdout ATS | holdout ROI |', '|---|---|---|---|---|---|---|---|']
    for k, v in sorted(t['one_condition_curves'].items(), key=lambda kv: wk_key(kv[0])):
        d, h = v['dev'], v['holdout']
        L.append('| %s | %s | %s | %s | %s | %s | %s | %s |' % (k, d.get('n'), pct(d.get('win_rate')), pct(d.get('roi')), f(d.get('clv_mean'), 2),
                                                               h.get('n'), pct(h.get('win_rate')), pct(h.get('roi'))))
    big = t['one_condition_curves'].get('gap>=10', {})
    g7 = t['one_condition_curves']['gap>=7']
    L += ['', '**Reading:**',
          '- The selected rules win on development at the opener, as selected rules always do.',
          '- They fail the reality check, and they lose on the holdout at the close.',
          '- The grid includes C/D disagreement and calibrated cover probability; no combination of them passes the reality check.',
          '- The largest gaps (10+) look good on both windows, but on %s development and %s holdout games; that is too few to separate from noise, and the 7+ bucket that carried the development result (%s ROI) falls to %s on %s holdout games.' % (
              big.get('dev', {}).get('n'), big.get('holdout', {}).get('n'), pct(g7['dev']['roi']), pct(g7['holdout']['roi']), g7['holdout']['n']),
          '- **BET stays disabled** under pre-registered rule R7.', '']

    # ------------------------------------------------------------ 15 bankroll
    b = J('phase15_bankroll', True)
    L += ['## 15. Bankroll simulation (hardened, the development rule)', '',
          '**Assumptions:** %s. Kelly stakes are capped at %s.' % (b['assumptions']['price'], b['assumptions']['kelly_stake_cap']), '',
          '**Fills:** %s.' % b['assumptions']['fills'].rstrip('.').replace('(see phase 16)', '(see *Edge decay by time* below)'), '',
          '| window | fill | strategy | bets | units / ending bankroll (start 100) | ROI | max drawdown | worst losing streak |', '|---|---|---|---|---|---|---|---|']
    for w in ('dev', 'holdout', 'live'):
        for fill in ('open_-110', 'close_-110'):
            o = b[w][fill]
            for s in ('flat_0.5u', 'flat_1u'):
                x = o[s]
                L.append('| %s | %s | %s | %s | %s u | %s | %s u | %s |' % (w, fill, s, x.get('n_bets'), f(x.get('units_won'), 1), pct(x.get('roi')), f(x.get('max_drawdown_units'), 1), o['streaks']['worst_losing']))
            for s in ('kelly_0.10', 'kelly_0.25'):
                x = o[s]
                L.append('| %s | %s | %s | %s | %s | — | %s%% | %s |' % (w, fill, s, x.get('n_bets'), f(x.get('ending_bankroll'), 1), f(x.get('max_drawdown_pct'), 1), o['streaks']['worst_losing']))
        if 'close_actual_juice_flat_1u' in b[w]:
            x = b[w]['close_actual_juice_flat_1u']
            L.append('| %s | close at the real closing price, where the 2014-2019 archive has one | flat_1u | %s | %s u | %s | %s u | — |' % (w, x.get('n_bets'), f(x.get('units_won'), 1), pct(x.get('roi')), f(x.get('max_drawdown_units'), 1)))
    L += ['', '**Reading:** full Kelly is never recommended. Even fractional Kelly on a rule without a demonstrated edge only makes the losses proportional.', '']

    # ------------------------------------------------------------ edge decay
    d16 = J('phase16_edge_decay', True)
    L += ['### Edge decay by time', '',
          '**What the data allows:** the historical archive has only the **opener and the close**. There is no 24-hour, midweek, day-before or game-day history, so only those two points can be compared.', '',
          '| window | mean abs gap vs opener | mean abs gap vs close | share of the gap the market closed | ATS at opener | ATS at close, same side | ATS re-decided at the close |', '|---|---|---|---|---|---|---|']
    for w in ('dev', 'holdout', 'live'):
        o = d16[w]
        L.append('| %s | %s | %s | %s | %s | %s | %s |' % (w, f(o['mean_abs_gap_at_open'], 2), f(o['mean_abs_gap_at_close'], 2), pct(o['share_of_open_gap_closed_by_market']),
                                                         pct(o['ats_at_open']), pct(o['ats_at_close_same_side']), pct(o['ats_model_vs_close_redecided'])))
    sf = d16['sunday_freeze_feasibility']
    L += ['', '**Reading:** what little advantage exists is against the **opener**: ATS at the opener is %s-%s percentage points higher than the same side at the close. It is gone by the close.' % (
              f(min(100 * (d16[w]['ats_at_open'] - d16[w]['ats_at_close_same_side']) for w in ('dev', 'holdout', 'live')), 1),
              f(max(100 * (d16[w]['ats_at_open'] - d16[w]['ats_at_close_same_side']) for w in ('dev', 'holdout', 'live')), 1)), '',
          '**Timing:** only %s of games kick off between Sunday 12:00 UTC and the Tuesday freeze, so freezing on Sunday instead would change the inputs of about that share of games. The archive has no opener timestamps, so whether a Sunday freeze would actually precede the openers has to be measured from the 2026 line ledger.' % pct(sf['share_of_games_kicking_off_sun_12utc_to_tue_12utc']), '',
          '**Implication:** if the product is ever built around early-week prices, the freeze should move to Sunday. Even then, the measured edge does not clear −110.', '',
          '**From now on:** timestamped line capture now runs daily in shadow mode (`football/cfb_v2/shadow/<season>/lines.jsonl`), so the 24-hour, midweek and game-day comparison becomes measurable from 2026 on.', '']

    # ------------------------------------------------------------ 16 early season
    p18 = J('phase18_early_season', True)
    L += ['## 16. Early-season analysis (hardened)', '',
          '| weeks in | dev n | V2 | opener (same games) | V1 | no preseason information | value of priors | holdout V2 | holdout opener | holdout value of priors |', '|---|---|---|---|---|---|---|---|---|---|']
    for k, v in sorted(p18['mae_by_week_dev'].items(), key=lambda kv: wk_key(kv[0])):
        h = p18['mae_by_week_holdout'].get(k, {})
        L.append('| %s | %d | %s | %s | %s | %s | %s | %s | %s | %s |' % (k, v['n'], f(v['mae_v2'], 2), f(v['mae_open_same'], 2), f(v['mae_v1'], 2),
                                                                     f(v.get('mae_no_preseason_info'), 2), f(v.get('value_of_priors'), 2),
                                                                     f(h.get('mae_v2'), 2), f(h.get('mae_open_same'), 2), f(h.get('value_of_priors'), 2)))
    slopes = p18['prior_component_residual_slopes_dev_and_holdout']
    wks = sorted(next(iter(slopes.values())).keys(), key=wk_key)
    L += ['', '**Does each prior component still predict what the model missed, by week?**', '',
          'Each cell is the slope of the residual on the component (points per SD) with its CI. Positive means under-used at that week; negative means over-used.', '',
          '| component | ' + ' | '.join(wks) + ' |', '|---|' + '---|' * len(wks)]
    for c, t in slopes.items():
        L.append('| %s | %s |' % (c, ' | '.join('%s %s' % (f(t[w]['pts_per_sd_in_residual'], 2), ci(t[w]['ci'], 2)) for w in wks)))
    vp = [v.get('value_of_priors') for w in ('mae_by_week_dev', 'mae_by_week_holdout') for k, v in p18[w].items() if k in ('0-1', '1-2')]
    vl = [v.get('value_of_priors') for w in ('mae_by_week_dev', 'mae_by_week_holdout') for k, v in p18[w].items() if k == '10+']
    under = {c: [w for w in wks if slopes[c][w]['ci'][0] > 0] for c in slopes}
    over = {c: [w for w in wks if slopes[c][w]['ci'][1] < 0] for c in slopes}
    rp = slopes.get('retprod_diff', {})
    L += ['', '**Reading:** priors are worth %s-%s points in the first two weeks and %s-%s from week 10 on%s.' % (
              f(min(vp), 2), f(max(vp), 2), f(min(vl), 2), f(max(vl), 2),
              ''.join(' (%s: %s in weeks %s)' % (w.split('_')[-1], f(v['value_of_priors'], 2), k) for w in ('mae_by_week_dev', 'mae_by_week_holdout')
                      for k, v in p18[w].items() if (v.get('value_of_priors') or 0) < 0)),
          '- **The fade shape is wrong.** Slopes whose CI excludes zero: under-used in %s; over-used in %s.' % (
              '; '.join('%s weeks %s' % (c, ', '.join(w)) for c, w in under.items() if w and c != 'retprod_diff') or 'none',
              '; '.join('%s weeks %s' % (c, ', '.join(w)) for c, w in over.items() if w) or 'none'),
          '- **Returning production** has a positive slope in %d of %d week buckets (CI above zero in weeks %s): under-used, most clearly after week 5.' % (
              sum(rp[w]['pts_per_sd_in_residual'] > 0 for w in wks), len(wks), ', '.join(under.get('retprod_diff', [])) or 'none'),
          '- **Faster updates don\'t fix it.** Making ratings update faster globally (prior strength ×2 or ×4, a 4-week half-life) did not help (rule R5).',
          '- **The cause:** priors enter with one constant weight. A prior-by-week interaction fixes it on development (section 23), but it is a new feature, so it was not adopted.', '']

    p17 = J('phase17_learning')
    L += ['### Week-to-week learning (candidate 001)', '',
          'Each team is rated at every freeze by the ensemble\'s neutral-site margin against a league-average reference team, built with the production snapshot code.', '',
          '| game class | team-games | rating change | scoreboard-Elo change | next-game residual [CI] |', '|---|---|---|---|---|']
    for k, v in p17['classes'].items():
        L.append('| %s | %d | %s | %s | %s %s |' % (k, v['n'], f(v['ensemble_rating_change'], 2), f(v['scoreboard_elo_rating_change'], 2),
                                                   f(v.get('next_game_residual'), 2), ci(v.get('next_game_residual_ci'), 2)))
    a = p17['A_vs_B_luck_effect_at_equal_surprise']
    cl = p17['classes']
    ka = next(k for k in cl if k.startswith('A ')); kb = next(k for k in cl if k.startswith('B ')); kd = next(k for k in cl if k.startswith('D '))
    L += ['', '**At equal surprise:** a turnover- or special-teams-driven result moves the rating %s points less than a sustainable one %s. The scoreboard Elo does the opposite even before adjusting for surprise: it moves %s for the luck class and %s for the sustainable one.' % (
              f(-a['coef_luck'], 2), ci([-a['ci'][1], -a['ci'][0]], 2), f(cl[kb]['scoreboard_elo_rating_change'], 2), f(cl[ka]['scoreboard_elo_rating_change'], 2)), '',
          '**Automated tests:**'] + ['- %s: **%s**' % (k, 'PASS' if v else 'FAIL') for k, v in p17['tests'].items()]
    L += ['', '**Reading:** the model learns the right *direction*.',
          '- It rewards sustainable efficiency more than luck.',
          '- It barely downgrades a loss that won the success battle; the next game says that small downgrade was fine.',
          '- **It under-reacts to sustained efficiency.** Teams that won big on efficiency beat V2 by %s points the following week, and teams that lost and lost the success battle fall %s short of it.' % (
              f(cl[ka]['next_game_residual'], 2), f(-cl[kd]['next_game_residual'], 2)),
          '- This is the same constant-prior-weight problem found in the early-season analysis.', '']

    # ------------------------------------------------------------ 17 QB
    p19 = J('phase19_qb')
    L += ['## 17. QB validation', '',
          '| transition (the snapshot expected last game\'s starter) | games | mean team residual [CI] | 80% coverage | the old overlay would predict |', '|---|---|---|---|---|']
    for k, v in p19['types'].items():
        L.append('| %s | %d | %s %s | %s | %s |' % (k, v['n'], f(v['mean_team_residual'], 2), ci(v['ci'], 2), f(v['coverage80']), f(v.get('overlay_would_predict_pts'), 2)))
    sc = p19.get('surprise_change_slope', {})
    dc = p19['double_counting_check_residual_on_qb_features']
    r8 = hd['R8_qb_overlay']
    L += ['', '**Findings:**',
          '- **The rating-gap coefficient is not supported.** Candidate 001 used %s points per EPA/dropback. The surprise-change regression gives %s %s (n = %s).' % (f(p19['coefficient_shipped_pts_per_epa_db'], 2), f(sc.get('pts_per_epa_db'), 2), ci(sc.get('ci'), 2), sc.get('n')),
          '- **What predicts the damage is the change itself, not the measured rating gap.** On development, an unexpected change costs %s points relative to same-starter games (difference %s). First-time starters average %s %s; that CI %s, so no separate first-time-starter effect is applied.'
          % (f(-r8['delta_change_minus_same'], 2), '%s %s' % (f(r8['delta_change_minus_same'], 2), ci(r8['delta_ci'], 2)), f(r8['first-time starter']['mean_resid'], 2), ci(r8['first-time starter']['ci'], 2),
             'includes 0' if r8['first-time starter']['ci'][1] >= 0 else 'excludes 0 but n = %d is below the pre-registered minimum' % r8['first-time starter']['n']),
          '- **The hardened overlay applies the measured level effect.** It is relative to the %s baseline same-starter rate, plus the measured extra variance of backup-QB games (%s points²).'
          % (pct(r8['baseline_same_starter_rate_dev']), f(r8['any unexpected change']['excess_var_pts2'], 1)),
          '- **Double counting.** Candidate 001 shifted the mean for the baseline change risk even with no status report, but the training data already contains those changes. The hardened overlay removes that shift.',
          '- **Other double-counting checks:** week-1 QB features are missing by construction, so returning production and the QB model never describe the same quarterback in week 1. The ensemble\'s residual slope on qb_delta is %s (t = %s): not significant, and if anything the QB signal is *under*-used rather than double counted.'
          % (f(dc['qb_delta_edge']['residual_slope'], 2), f(dc['qb_delta_edge']['t'], 2)), '']

    # ------------------------------------------------------------ 18 injuries
    L += ['## 18. Injury validation', '',
          '**Validated historically?** No. No point-in-time pregame injury report, depth chart or snap history exists in any feed this project can reach.', '',
          '**So nothing about injuries was trained or validated.** This follows the brief: lower the confidence, don\'t fabricate evidence.',
          '- The availability overlay **never moves the mean**. It widens the interval and caps reliability.',
          '- It now has **diminishing marginal effects** within a position group: saturating, never above the unit cap.',
          '- It accepts **replacement depth** when supplied.',
          '- It **refuses** any report stamped at or after kickoff (engine tests).', '',
          '**Where the evidence will come from:** every frozen shadow row now also stores the pregame availability, QB-availability and named-starter evidence the V1 board held at the freeze (source, state, timestamps, and the digest of the availability sync it came from). V2 does not read it. The monitor warns when an upcoming game\'s availability source is more than 72 hours old. The first honest validation becomes possible once a season of these frozen pregame reports exists.', '']

    # ------------------------------------------------------------ 19 simplifications
    L += ['## 19. Simplifications made (pre-registered rules, development only)', '',
          '- **Components (R2):** kept %s, dropped %s. Removing each dropped component changes development MAE by at most 0.005 points (%s); removing a kept one costs %s.'
          % (', '.join(hd['R2_components']['keep']), ', '.join(hd['R2_components']['drop']),
             ', '.join('%s %s' % (k, f(v, 4)) for k, v in hd['R2_components']['dev_drop_one_delta_mae'].items() if k in hd['R2_components']['drop']),
             ', '.join('%s %s' % (k, f(v, 4)) for k, v in hd['R2_components']['dev_drop_one_delta_mae'].items() if k in hd['R2_components']['keep'])),
          '- **Combination (R3):** %s. Development MAE %s.' % (hd['R3_combination']['chosen'], ', '.join('%s %s' % (k, f(v, 4)) for k, v in hd['R3_combination']['dev_dev_mae' if 'dev_dev_mae' in hd['R3_combination'] else 'dev_mae'].items())),
          '- **Features (R4):** removed %s. The joint development MAE is %s, against candidate 001\'s %s.'
          % (', '.join('`%s`' % c for c in hd['R4_joint_check']['final_removed_columns']), f(hd['R4_joint_check']['simplified_dev_mae'], 4), f(hd['R4_joint_check']['candidate_001_dev_mae'], 4)),
          '- **Update speed (R5):** no variant qualified. The development ΔMAE values were %s, against a required −0.02 with a CI below 0.'
          % ', '.join('%s %s' % (k, f(v.get('diff'), 4)) for k, v in hd['R5_update_speed']['variants'].items()),
          '- **Probabilities (R6):** win uses %s and cover uses %s.' % (hd['R6_calibration']['win'], hd['R6_calibration']['cover']),
          '- **Result:** 2 models instead of 5, and %d inputs instead of %d, at equal accuracy.' % n_inputs(hd), '']

    # ------------------------------------------------------------ 20 champion/challenger
    L += ['## 20. V1 vs candidate 001 vs hardened V2', '',
          'The full tables are in [`CHAMPION_CHALLENGER.md`](CHAMPION_CHALLENGER.md): margin, probability, uncertainty, market, betting and stability by year, week, conference and favourite size.', '',
          '| window | games | | MAE [CI] | RMSE | Brier | ECE | 80% cov. | V2 − opener | V2 − close | every game at the opener: ATS / ROI / CLV |', '|---|---|---|---|---|---|---|---|---|---|---|']
    for w in ('dev', 'holdout', 'live'):
        W = cc['windows'][w]
        for name in ('V1', 'V2 candidate 001', 'V2 hardened'):
            if name not in W:
                continue
            r = W[name]
            e = r['every_game_at_opener']
            L.append('| %s | %d | %s | %s %s | %s | %s | %s | %s | %s | %s | %s / %s / %s |' % (
                w, W['n'], name, f(r['mae']), ci(r['mae_ci']), f(r['rmse'], 2), f(r['brier'], 4), f(r['ece'], 4), f(r.get('coverage80')),
                f(r['mae_minus_opener']['diff']), f(r['mae_minus_close']['diff']), pct(e['ats']), pct(e['roi']), f(e['clv'], 2)))
    L += ['', '**Promotion rule R10:** hardened minus candidate 001 on the holdout is %s, within the 0.05 tolerance: %s. Gates G1-G7 against V1 all pass (`report/v2.1.0/promotion.json`).'
          % (f(cc['R10']['hardened_minus_c001_holdout_mae'], 4), 'yes' if cc['R10']['passes_tolerance'] else 'no'), '']

    # ------------------------------------------------------------ 21 shadow
    L += ['## 21. Shadow-mode implementation', '',
          'V2 runs **beside** V1 and changes nothing V1 does. Every weekly freeze (Tuesday 12:00 UTC) writes a write-once, hashed row per upcoming game. Each row carries:',
          '- the hardened V2 projection, its distribution and components;',
          '- candidate 001\'s projection, from its own hash-locked artifacts;',
          '- V1\'s projection, as published on the FBS board;',
          '- the market as observed by the run that froze it;',
          '- the pregame availability, QB-availability and named-starter evidence the V1 board held at the freeze (recorded only; V2 does not read it).', '',
          '**Afterwards, separately:**',
          '- An **append-only line ledger** timestamps every observed line change.',
          '- A **derived outcomes file** records the closing number, the final result, every model\'s error, CLV and grading.',
          '- The **production engine** computes the research status (BET/LEAN/REVIEW/PASS).', '',
          '**Monitoring** (`monitoring.json`, rendered by `football/cfb_v2/monitor.html`) covers, per week:',
          '- MAE, RMSE, Brier and calibration;',
          '- V1 vs V2 vs candidate 001 on the same games;',
          '- model vs the line at the freeze, and vs the close;',
          '- CLV and ATS;',
          '- statuses and pass rate;',
          '- largest misses;',
          '- model disagreement.', '',
          '**Health warnings:**',
          '- MAE spike and calibration;',
          '- missing play-by-play;',
          '- stale odds and a stale availability source;',
          '- BET while disabled;',
          '- ensemble weights;',
          '- C/D disagreement;',
          '- stale pipeline;',
          '- week-matched output drift, tested against a sampling-noise null.', '',
          'A warning informs a person; it never retrains anything. The frozen predictions are never modified.', '']

    # ------------------------------------------------------------ 22 weaknesses
    nx = J('phase99_next_iteration')
    p10h = J('phase10_uncertainty', True)
    L += ['## 22. Remaining weaknesses', '',
          '1. **Less accurate than the market** in every window: V2 hardened trails the opener by %s points on development, %s on the holdout and %s on the %d games of 2026 to date.' % (
              f(cc['windows']['dev']['V2 hardened']['mae_minus_opener']['diff'], 2), f(cc['windows']['holdout']['V2 hardened']['mae_minus_opener']['diff'], 2),
              f(cc['windows']['live']['V2 hardened']['mae_minus_opener']['diff'], 2), cc['windows']['live']['n']),
          '2. **The prior fade has the wrong shape.** Priors are under-used early and over-used mid-season, and the model under-reacts to sustained efficiency.',
          '3. **The P4 side of P4-vs-G5 games is underrated:** %s points on development and %s on the holdout. So are market favourites of more than 21 points (%s and %s).'
          % (f(p12['dev']['P4 team in P4-vs-G5']['bias'], 1), f(p12['holdout']['P4 team in P4-vs-G5']['bias'], 1),
             f(p12['dev']['market favourites > 21']['bias'], 1), f(p12['holdout']['market favourites > 21']['bias'], 1)),
          '4. **No cover skill.** Calibrated cover probabilities are indistinguishable from a coin flip.',
          '5. **No pregame QB-status, injury or weather history before 2026.** The live overlays are measured (QB) or declared (injury, weather), never validated on pregame reports. The frozen shadow rows now keep the pregame availability and QB evidence, so validation can start after 2026.',
          '6. **FBS-vs-FCS games are not priced.** The mean is biased against the FBS side (%s points on the holdout), and the intervals are honest only because they are about %s points wide.' % (
              f(p10h['holdout']['FBS-vs-FCS'].get('fbs_side_bias'), 1), f(p10h['holdout']['FBS-vs-FCS']['mean_width80'], 0)),
          '7. **The holdout is no longer pristine.** 2024-2025 has been scored for two versions; only 2026 onward is untouched.',
          '8. **No historical spread prices after 2019.** ROI for 2020-2025 assumes −110. The 2014-2019 closing prices are real.',
          '9. **The provider\'s EPA model** is fitted on historical seasons: fixed, unremovable value-function hindsight.', '']

    # ------------------------------------------------------------ 23 data
    L += ['## 23. What would give the biggest next improvement', '',
          '**Structural changes** (no new data needed), sized on development only and **not adopted** (the brief: no new features yet):', '']
    for k, v in nx.get('candidates', {}).items():
        L.append('- `%s`: development ΔMAE %s %s. Weeks 0-2: %s. P4-vs-G5 games: %s.' % (k, f(v['dev_d_mae'], 4), ci(v['ci'], 4), f(v['dev_d_mae_weeks_0_2'], 3), f(v['dev_d_mae_p4_vs_g5'], 3)))
    mi = J('phase11_misses')
    L += ['', '**New data sources**, ordered by expected value from this evidence:',
          '1. **Timestamped pregame QB status and depth charts.** QB changes are %d of the %d worst misses, the largest class a pregame source could have warned about (garbage time, %d, and FCS data, %d, are not). An unexpected change costs %s points on average, and the QB overlay could then be validated on reports instead of measured from surprises. The frozen shadow rows start this record for 2026.' % (
              mi['class_frequency'].get('QB injury/change', 0), mi['n_worst'], mi['class_frequency'].get('garbage time', 0), mi['class_frequency'].get('FCS data weakness', 0), f(-r8['delta_change_minus_same'], 2)),
          '2. **Intraday odds history with prices** (24 h / midweek / game day, per book, with juice). This would answer edge decay properly and replace the −110 assumption. The shadow ledger starts this for 2026.',
          '3. **Point-in-time injury and availability reports.** These would validate, or reject, the availability overlay.',
          '4. **Archived pregame weather forecasts.** Weather is currently only a post-hoc diagnostic.',
          '5. **An FCS model or data** (FCS play-by-play depth), if FBS-vs-FCS games are ever to be priced.', '']

    # ------------------------------------------------------------ 24 recommendation
    hv1 = cc['windows']['holdout']['hardened_minus_v1']
    L += ['## 24. Production recommendation (evidence only)', '',
          '1. **Keep V1 as the champion. Do not promote V2 automatically.**',
          '   - V2 hardened is materially more accurate than V1: %s points of MAE on the holdout %s, with every gate passed.' % (f(hv1['diff'], 3), ci(hv1['ci'], 3)),
          '   - Promotion is a person\'s decision after frozen 2026 shadow weeks confirm it live. The monitor page shows that comparison week by week.',
          '2. **Run `edgedesk_cfb_v2.1.0` (hardened) in shadow from the next Tuesday freeze.** Candidate 001 stays frozen, and its projection is recorded beside every row for comparison.',
          '3. **Keep BET disabled.** No rule survives the reality check or the holdout at an achievable price. Cover probabilities have no skill, and positive CLV of %s to %s points does not clear −110.' % (f(min(clv), 2), f(max(clv), 2)),
          '4. **Preserve EdgeDesk as a research and pricing tool.**',
          '   - Show the pure projection, its distribution and drivers, the disagreement with the market, and the market\'s own number.',
          '   - Present a disagreement as a research signal, with no probability-of-cover claim.',
          '5. **Keep collecting.** The frozen shadow rows, the timestamped line ledger and the monitor are the untouched evidence the next decision needs. None of them retrains anything by itself.',
          '6. **Next iteration, pre-registered and evaluated on 2026 onward:** the prior-by-week fade and the P4 tier term, then QB-status and odds-history data.', '']
    return L


def main():
    L = build()
    with open(os.path.join(DOCS, 'REDTEAM.md'), 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    print('[rt_report] %d lines -> docs/cfb-v2/REDTEAM.md' % len(L))


if __name__ == '__main__':
    main()
