// collective_odds_ingest - SELF-CONTAINED BUNDLE for the Supabase dashboard editor.
// Generated from supabase/functions/ by tools/collective/bundle_functions.py.
// Do not edit this file: edit the sources and regenerate.
// Paste this whole file as index.ts for a function named exactly: collective_odds_ingest
// IMPORTANT: keep "Enforce JWT verification" ON for this function.

// ---------- inlined _shared/env.ts ----------
// Shared environment access for Collective edge functions.
// SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, and SUPABASE_ANON_KEY are injected
// by the Supabase runtime. COLLECTIVE_BASE_URL is an optional secret that
// points at the public site root and defaults to production.

const SB_URL: string = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY: string = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const ANON_KEY: string = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
const BASE_URL: string = Deno.env.get("COLLECTIVE_BASE_URL") ?? "https://edgedesksports.com";

// ---------- inlined _shared/http.ts ----------
// Shared HTTP helpers: JSON responses, the contract error shape, CORS, and
// subpath routing. Every Collective edge function builds its responses here so
// the error taxonomy and CORS behavior stay identical across functions.

function corsHeaders(origin = "*"): Record<string, string> {
  const headers: Record<string, string> = {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers":
      "authorization, apikey, content-type, x-collective-key, x-client-info",
    "Access-Control-Max-Age": "86400",
  };
  if (origin !== "*") {
    headers["Vary"] = "Origin";
  }
  return headers;
}

function json(
  body: unknown,
  status = 200,
  headers: Record<string, string> = {},
): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      ...corsHeaders(),
      ...headers,
    },
  });
}

// Error response in the contract shape { error: { code, message, details } }.
// details is always present, null when there is nothing row-level to report.
function err(
  code: string,
  message: string,
  status: number,
  details?: unknown,
): Response {
  return json({ error: { code, message, details: details ?? null } }, status);
}

// Returns a 204 Response for OPTIONS requests, else null.
function preflight(req: Request, origin = "*"): Response | null {
  if (req.method !== "OPTIONS") return null;
  return new Response(null, { status: 204, headers: corsHeaders(origin) });
}

// Path after /functions/v1/<fnName>, normalized. Works both behind the
// production gateway (/functions/v1/<fnName>/...) and when served locally
// (/<fnName>/...). "" becomes "/", duplicate slashes collapse, and a
// trailing slash is stripped except on the root.
function subpath(req: Request, fnName: string): string {
  const pathname = new URL(req.url).pathname;
  const marker = `/${fnName}`;
  const idx = pathname.indexOf(marker);
  let rest = idx >= 0 ? pathname.slice(idx + marker.length) : pathname;
  if (!rest.startsWith("/")) rest = `/${rest}`;
  rest = rest.replace(/\/{2,}/g, "/");
  if (rest.length > 1 && rest.endsWith("/")) rest = rest.slice(0, -1);
  return rest;
}

// ---------- inlined _shared/db.ts ----------
// Shared database access. Edge functions never talk SQL: they call the
// SECURITY DEFINER RPCs in the collective schema through PostgREST with the
// service role key. RPCs return jsonb outcome objects like { ok: true, ... }
// or { ok: false, code: "token_expired", message: "..." }; callers translate
// ok:false codes to the HTTP error taxonomy. RpcError means an unexpected
// database failure and maps to 500 server_error (log it, never leak the body).

class RpcError extends Error {
  status: number;
  body: string;

  constructor(fn: string, status: number, body: string) {
    super(`rpc ${fn} failed with status ${status}`);
    this.name = "RpcError";
    this.status = status;
    this.body = body;
  }
}

async function rpc<T = unknown>(
  fn: string,
  args: Record<string, unknown>,
): Promise<T> {
  const res = await fetch(`${SB_URL}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: {
      "apikey": SERVICE_KEY,
      "Authorization": `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
      "Content-Profile": "collective",
    },
    body: JSON.stringify(args),
  });
  const text = await res.text();
  if (!res.ok) {
    throw new RpcError(fn, res.status, text);
  }
  if (text === "") {
    return null as T;
  }
  return JSON.parse(text) as T;
}

// ---------- inlined _shared/auth.ts ----------
// Shared JWT auth. Bearer tokens are validated against Supabase Auth by
// calling /auth/v1/user; the JWT is never decoded locally, so revoked or
// expired sessions fail closed. Admin checks compare the user id against the
// admin.user_ids config list via the get_config RPC.

async function getUser(
  req: Request,
): Promise<{ id: string; email: string | null } | null> {
  const authz = req.headers.get("authorization") ?? "";
  if (!/^Bearer\s+\S+/i.test(authz)) return null;
  let res: Response;
  try {
    res = await fetch(`${SB_URL}/auth/v1/user`, {
      headers: {
        "apikey": ANON_KEY,
        "Authorization": authz,
      },
    });
  } catch (e) {
    console.error("auth.getUser: auth service unreachable:", e);
    return null;
  }
  if (!res.ok) return null;
  const user = await res.json().catch(() => null) as
    | { id?: string; email?: string | null }
    | null;
  if (!user || typeof user.id !== "string" || user.id.length === 0) return null;
  return { id: user.id, email: typeof user.email === "string" ? user.email : null };
}

// getUser plus membership of admin.user_ids. Returns the user, or an err()
// Response (401 invalid_key or 403 forbidden) ready to return to the caller.
async function requireAdmin(
  req: Request,
): Promise<{ id: string; email: string | null } | Response> {
  const user = await getUser(req);
  if (!user) {
    return err("invalid_key", "A valid signed-in session is required.", 401);
  }
  const cfg = await rpc<unknown>("get_config", { p_key: "admin.user_ids" });
  const ids = Array.isArray(cfg) ? cfg.filter((v) => typeof v === "string") : [];
  if (!ids.includes(user.id)) {
    return err("forbidden", "This account is not an administrator.", 403);
  }
  return user;
}

// ---------- inlined _shared/odds_api.ts ----------
// Shared odds read helpers and the freshness envelope.
//
// Every odds payload the Collective serves carries the same three facts:
// where the number came from, when it was last updated, and whether that
// counts as current. A surface that cannot say when a price was captured is
// not allowed to display it as live, so this envelope is mandatory rather
// than decorative.

type Freshness = "live" | "stale" | "unavailable";

interface OddsEnvelope {
  source: { provider: string; league: string };
  last_updated: string | null;
  age_seconds: number | null;
  state: Freshness;
  stale_after_seconds: number;
  /** Present only when state is not "live": a sentence a UI can show as-is. */
  notice?: string;
}

const DEFAULT_STALE_AFTER = 900;

/**
 * Classifies a feed timestamp.
 *   live        a price captured inside the freshness window
 *   stale       we have a price, but it is older than the window. It is still
 *               returned, labelled, with its age. Never relabelled current.
 *   unavailable we have nothing to show. No number is invented to fill the gap.
 */
function envelope(
  lastUpdated: string | null | undefined,
  staleAfterSeconds: number | null | undefined,
  league = "nfl",
  provider = "oddsblaze",
): OddsEnvelope {
  const staleAfter = Number(staleAfterSeconds) > 0
    ? Number(staleAfterSeconds)
    : DEFAULT_STALE_AFTER;
  if (!lastUpdated) {
    return {
      source: { provider, league },
      last_updated: null,
      age_seconds: null,
      state: "unavailable",
      stale_after_seconds: staleAfter,
      notice: "Odds unavailable.",
    };
  }
  const ms = Date.parse(lastUpdated);
  if (!Number.isFinite(ms)) {
    return {
      source: { provider, league },
      last_updated: null,
      age_seconds: null,
      state: "unavailable",
      stale_after_seconds: staleAfter,
      notice: "Odds unavailable.",
    };
  }
  const age = Math.max(0, Math.round((Date.now() - ms) / 1000));
  if (age <= staleAfter) {
    return {
      source: { provider, league },
      last_updated: lastUpdated,
      age_seconds: age,
      state: "live",
      stale_after_seconds: staleAfter,
    };
  }
  return {
    source: { provider, league },
    last_updated: lastUpdated,
    age_seconds: age,
    state: "stale",
    stale_after_seconds: staleAfter,
    notice: `Odds may be out of date. Last updated ${relativeAge(age)}.`,
  };
}

function relativeAge(seconds: number): string {
  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 5400) return `${Math.round(seconds / 60)} minutes ago`;
  if (seconds < 172800) return `${Math.round(seconds / 3600)} hours ago`;
  return `${Math.round(seconds / 86400)} days ago`;
}

// ------------------------------------------------------------------ settings
// The odds* prefixes on the read helpers below are deliberate: the dashboard
// deploys these functions as one flattened script, where a top level
// `history` or `status` would sit alongside the DOM globals of the same name.
let settingsCache: { at: number; values: Record<string, unknown> } | null = null;
const SETTINGS_TTL_MS = 60_000;

/** Reads odds settings, cached briefly so a slate render does not make one
 *  round trip per tunable. */
async function settings(keys: string[]): Promise<Record<string, unknown>> {
  const now = Date.now();
  if (settingsCache && now - settingsCache.at < SETTINGS_TTL_MS) {
    const have = keys.every((k) => k in settingsCache!.values);
    if (have) return settingsCache.values;
  }
  const values: Record<string, unknown> = { ...(settingsCache?.values ?? {}) };
  await Promise.all(keys.map(async (k) => {
    try {
      values[k] = await rpc<unknown>("odds_get_setting", { p_key: k });
    } catch {
      values[k] = null;
    }
  }));
  settingsCache = { at: now, values };
  return values;
}

function num(v: unknown, fallback: number): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function strList(v: unknown, fallback: string[]): string[] {
  if (Array.isArray(v)) {
    const out = v.filter((x): x is string => typeof x === "string" && x.length > 0);
    if (out.length) return out;
  }
  return fallback;
}

/** Board payload straight from SQL. The math is not repeated here. */
async function oddsBoard(args: {
  league?: string;
  from?: string | null;
  to?: string | null;
  includeBooks?: boolean;
  limit?: number;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_board", {
    p_league: args.league ?? "nfl",
    p_from: args.from ?? null,
    p_to: args.to ?? null,
    p_include_books: args.includeBooks !== false,
    p_limit: args.limit ?? 40,
  });
}

async function oddsEventPayload(args: {
  eventId?: string | null;
  gameId?: string | null;
  includeBooks?: boolean;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_event", {
    p_event_id: args.eventId ?? null,
    p_game_id: args.gameId ?? null,
    p_include_books: args.includeBooks !== false,
  });
}

async function oddsHistory(args: {
  eventId: string;
  market?: string | null;
  book?: string | null;
  outcome?: string | null;
  limit?: number;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_history", {
    p_event_id: args.eventId,
    p_market: args.market ?? null,
    p_book: args.book ?? null,
    p_outcome: args.outcome ?? null,
    p_limit: args.limit ?? 500,
  });
}

async function oddsStatus(league = "nfl"): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_status", { p_league: league });
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function isUuid(s: string): boolean {
  return UUID_RE.test(s);
}

// ---------- inlined _shared/odds_provider.ts ----------
// The odds provider contract.
//
// Everything upstream of this file is vendor-specific; everything downstream
// speaks only these types. Adding a second provider means writing one more
// module that returns NormalizedSlate — no other file changes, because
// nothing else in the Collective ever sees a vendor payload.
//
// The credential never appears in any of these types. It is read from the
// environment inside a provider implementation and used only to build the
// outbound request.

/** Canonical markets. New families (props, futures) become new ids here and
 *  new rows in odds.markets; the pipeline itself does not change. */
type MarketId =
  | "moneyline"
  | "spread"
  | "total"
  | "team_total"
  | "alternate_spread"
  | "alternate_total"
  | string;

/** Which side of a market a price belongs to. */
type Outcome = "home" | "away" | "over" | "under" | "draw" | string;

/** One price, at one book, on one side of one market, at one moment. */
interface NormalizedOdd {
  book: string;
  market: MarketId;
  outcome: Outcome;
  outcome_label?: string | null;
  /** Points. Null for moneyline. Home convention for spreads: negative means
   *  the home team is favoured. */
  line?: number | null;
  /** American odds. -110, +135. Never a decimal or a probability. */
  price: number;
  is_live?: boolean;
  is_main?: boolean;
  /** The vendor row this was derived from, kept for audit. Bounded by the
   *  caller so a payload cannot balloon the snapshot table. */
  raw?: unknown;
}

/** One game, named in our terms, with the provider's id kept alongside as a
 *  mapping rather than as identity. */
interface NormalizedEvent {
  provider_event_id: string | null;
  home: string;
  away: string;
  home_name?: string | null;
  away_name?: string | null;
  commence_time: string;
  season?: number | null;
  week?: number | null;
  status?: string | null;
  is_live?: boolean;
  provider_updated_at?: string | null;
  odds: NormalizedOdd[];
}

/** What a provider hands back for one league, plus an honest account of what
 *  it could not map. Unmapped rows are reported, never silently dropped and
 *  never filled in with a guess. */
interface NormalizedSlate {
  provider: string;
  league: string;
  fetched_at: string;
  provider_updated_at: string | null;
  events: NormalizedEvent[];
  books_ok: string[];
  books_failed: { book: string; reason: string }[];
  /** Rows whose shape we did not recognise. Carries the row's KEY NAMES and
   *  a redacted sample, never a credential, so an API change is diagnosable
   *  from the run record alone. */
  unmapped: UnmappedRow[];
  counts: { events: number; odds: number; unmapped: number };
}

interface UnmappedRow {
  book: string;
  reason: string;
  keys: string[];
  sample?: unknown;
}

interface FetchOptions {
  league: string;
  books: string[];
  markets: MarketId[];
  /** true = live only, false = pregame only, undefined = both. */
  live?: boolean;
  /** true = main lines only. Alternates are off by default; turning them on
   *  is a settings change, not a code change. */
  mainOnly?: boolean;
  timeoutMs?: number;
  booksPerRequest?: number;
}

/** A provider is a named fetcher that returns canonical data. */
interface OddsProvider {
  readonly id: string;
  readonly name: string;
  /** True when the credential this provider needs is present. Checked before
   *  a run so a missing secret is a clear message, not a 401 from a vendor. */
  isConfigured(): boolean;
  fetchSlate(opts: FetchOptions): Promise<NormalizedSlate>;
  /** One request, reporting the observed response STRUCTURE rather than the
   *  data: endpoint reachability, status, and the key paths that came back.
   *  Used to confirm the integration against the live API without printing
   *  anything sensitive. */
  probe(opts: FetchOptions): Promise<ProbeResult>;
}

interface ProbeResult {
  provider: string;
  ok: boolean;
  /** The URL with every credential removed. Safe to log and to display. */
  url_redacted: string;
  http_status: number | null;
  /** Key paths seen in the response, e.g. "events[].odds[].selection.line". */
  observed_shape: string[];
  sample_event: unknown;
  sample_odd: unknown;
  counts: { events: number; odds: number };
  error: string | null;
  /** What the adapter made of the sample: proof the mapping works against
   *  the real feed, or a precise account of where it did not. */
  mapping: { mapped: number; unmapped: UnmappedRow[] };
}

const REGISTRY = new Map<string, OddsProvider>();

function registerProvider(p: OddsProvider): void {
  REGISTRY.set(p.id, p);
}

function getProvider(id: string): OddsProvider | null {
  return REGISTRY.get(id) ?? null;
}

function listProviders(): { id: string; name: string; configured: boolean }[] {
  return [...REGISTRY.values()].map((p) => ({
    id: p.id,
    name: p.name,
    configured: p.isConfigured(),
  }));
}

// ---------- inlined _shared/odds_normalize.ts ----------
// Vendor-agnostic normalization primitives.
//
// These are pure functions with no network and no environment access, which
// is what makes them testable outside Deno (see tests/collective/normalize_test.mjs).
// Each one has the same rule: recognise what it understands, and return null
// for anything else so the caller can report it. Nothing here ever guesses a
// number into existence.

/** lowercase, alphanumerics only. The comparison key for every fuzzy match. */
function normKey(s: unknown): string {
  return String(s ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

/**
 * American odds from whatever the wire carried: -110, "-110", "+135", "EVEN".
 * Returns null for anything that is not a usable American price, including
 * the impossible band between -99 and +99 — a "price" of 0 or 5 means the
 * field was not American odds, and inventing one would poison every downstream
 * probability.
 */
function parseAmericanPrice(v: unknown): number | null {
  if (v === null || v === undefined) return null;
  if (typeof v === "string") {
    const t = v.trim();
    if (/^(even|ev|evens|pk)$/i.test(t)) return 100;
    const cleaned = t.replace(/[\s,]/g, "");
    if (!/^[+-]?\d+(\.\d+)?$/.test(cleaned)) return null;
    v = Number(cleaned);
  }
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  const n = Math.round(v);
  if (n >= 100 || n <= -100) return n;
  return null;
}

/**
 * A points value: "-3.5", "+3.5", 3.5, "PK"/"Pick'em" (zero). Returns null
 * when there is no line, which is correct for a moneyline.
 */
function parseLine(v: unknown): number | null {
  if (v === null || v === undefined || v === "") return null;
  if (typeof v === "string") {
    const t = v.trim();
    if (/^(pk|pick|pickem|pick'?em|even)$/i.test(t)) return 0;
    const cleaned = t.replace(/[\s,]/g, "").replace(/^([+-])?(o|u|over|under)/i, "$1");
    if (!/^[+-]?\d+(\.\d+)?$/.test(cleaned)) return null;
    v = Number(cleaned);
  }
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  return v;
}

/** Decimal odds from American. Used for price comparison, where "bigger is
 *  better" holds and American odds do not sort. */
function americanToDecimal(price: number): number | null {
  if (!Number.isFinite(price)) return null;
  if (price >= 100) return 1 + price / 100;
  if (price <= -100) return 1 + 100 / Math.abs(price);
  return null;
}

function americanToProb(price: number): number | null {
  const d = americanToDecimal(price);
  return d === null ? null : 1 / d;
}

/** Two-way multiplicative de-vig. The only honest way to combine moneylines:
 *  raw American prices are never averaged. */
function devigTwoWay(pa: number, pb: number): number | null {
  if (!Number.isFinite(pa) || !Number.isFinite(pb) || pa + pb <= 0) return null;
  return pa / (pa + pb);
}

// -------------------------------------------------------------- markets
// Vendors label markets for humans ("Point Spread"), so match on the label.
// A name that matches nothing is reported as unmapped rather than forced into
// the nearest bucket.
const MARKET_ALIASES: Record<string, MarketId> = {
  moneyline: "moneyline",
  moneylines: "moneyline",
  money: "moneyline",
  ml: "moneyline",
  h2h: "moneyline",
  headtohead: "moneyline",
  matchupwinner: "moneyline",
  gamelines: "moneyline",

  pointspread: "spread",
  spread: "spread",
  spreads: "spread",
  handicap: "spread",
  pointhandicap: "spread",
  linespread: "spread",
  gamespread: "spread",

  totalpoints: "total",
  total: "total",
  totals: "total",
  overunder: "total",
  gametotal: "total",
  totalpointsoverunder: "total",

  teamtotal: "team_total",
  teamtotalpoints: "team_total",
  alternatepointspread: "alternate_spread",
  alternatespread: "alternate_spread",
  alternatetotal: "alternate_total",
  alternatetotalpoints: "alternate_total",
};

function canonicalMarket(raw: unknown): MarketId | null {
  const k = normKey(raw);
  if (!k) return null;
  return MARKET_ALIASES[k] ?? null;
}

/** Markets we store as game lines. Everything else is registered but not
 *  treated as a game line by the read API. */
const GAME_MARKETS: MarketId[] = ["moneyline", "spread", "total"];

// -------------------------------------------------------------- outcomes
const OVER_WORDS = new Set(["over", "o", "above", "more"]);
const UNDER_WORDS = new Set(["under", "u", "below", "less"]);

/**
 * Which side a price sits on.
 *
 * For totals this is over/under. For spreads and moneylines it is home/away,
 * decided by an explicit side field when the vendor gives one, and otherwise
 * by matching the selection text against the two team names we already know.
 * If neither works the answer is null: an unattributed price is useless and
 * a coin-flip guess would silently invert a whole market.
 */
function resolveOutcome(args: {
  market: MarketId;
  side?: unknown;
  selectionName?: unknown;
  homeNames: string[];
  awayNames: string[];
}): Outcome | null {
  const { market, side, selectionName, homeNames, awayNames } = args;
  const sideKey = normKey(side);
  const nameKey = normKey(selectionName);

  if (market === "total" || market === "team_total" || market === "alternate_total") {
    if (OVER_WORDS.has(sideKey)) return "over";
    if (UNDER_WORDS.has(sideKey)) return "under";
    if (OVER_WORDS.has(nameKey)) return "over";
    if (UNDER_WORDS.has(nameKey)) return "under";
    // "Over 47.5" / "Under 47.5"
    if (/^over/.test(nameKey)) return "over";
    if (/^under/.test(nameKey)) return "under";
    return null;
  }

  if (sideKey === "home") return "home";
  if (sideKey === "away") return "away";
  if (sideKey === "draw" || sideKey === "tie") return "draw";

  const home = new Set(homeNames.map(normKey).filter(Boolean));
  const away = new Set(awayNames.map(normKey).filter(Boolean));
  if (!nameKey) return null;
  if (home.has(nameKey)) return "home";
  if (away.has(nameKey)) return "away";
  // Vendors append the number: "Kansas City Chiefs -3.5".
  const stripped = nameKey.replace(/[+-]?\d+(\d|5)?$/, "");
  for (const h of home) if (h && (nameKey.startsWith(h) || stripped === h)) return "home";
  for (const a of away) if (a && (nameKey.startsWith(a) || stripped === a)) return "away";
  return null;
}

/** The trailing number in a selection label: "Chiefs -3.5" -> -3.5,
 *  "Over 47.5" -> 47.5. Last resort only, after every explicit field. */
function lineFromLabel(label: unknown): number | null {
  const s = String(label ?? "").trim();
  const m = s.match(/([+-]?\d+(?:\.\d+)?)\s*$/);
  return m ? parseLine(m[1]) : null;
}

/** First non-null among a list of candidate accessors. Lets an adapter list
 *  the documented field, then the documented alternatives, in priority order
 *  without a pile of nested ternaries. */
function firstOf<T>(...candidates: (T | null | undefined)[]): T | null {
  for (const c of candidates) {
    if (c !== null && c !== undefined) return c;
  }
  return null;
}

// -------------------------------------------------------------- diagnostics

/** Key paths present in a value, e.g. "events[].odds[].selection.line".
 *  Structure only: no values are included, so this is always safe to log. */
function shapePaths(value: unknown, maxDepth = 6, prefix = ""): string[] {
  const out = new Set<string>();
  walk(value, prefix, 0);
  function walk(v: unknown, path: string, depth: number): void {
    if (depth > maxDepth) return;
    if (Array.isArray(v)) {
      if (path) out.add(`${path}[]`);
      // One element is enough to describe the shape of a homogeneous array.
      if (v.length) walk(v[0], `${path}[]`, depth + 1);
      return;
    }
    if (v && typeof v === "object") {
      for (const k of Object.keys(v as Record<string, unknown>)) {
        const p = path ? `${path}.${k}` : k;
        const child = (v as Record<string, unknown>)[k];
        if (child && typeof child === "object") walk(child, p, depth + 1);
        else out.add(p);
      }
      return;
    }
    if (path) out.add(path);
  }
  return [...out].sort();
}

/** Removes anything credential-shaped from a URL before it is logged, stored,
 *  or returned. Query keys are matched by name; the value is replaced, never
 *  truncated to a prefix. */
const SECRET_PARAMS = ["key", "apikey", "api_key", "token", "access_token", "secret"];

function redactUrl(raw: string): string {
  try {
    const u = new URL(raw);
    for (const p of [...u.searchParams.keys()]) {
      if (SECRET_PARAMS.includes(p.toLowerCase())) u.searchParams.set(p, "REDACTED");
    }
    return u.toString();
  } catch {
    return "invalid-url";
  }
}

/** Strips a known secret out of arbitrary text (an error message, a vendor
 *  body) before it reaches a log line or an ingest_runs row. */
function redactSecret(text: string, secret: string | null | undefined): string {
  let out = String(text ?? "");
  if (secret && secret.length >= 6) {
    out = out.split(secret).join("REDACTED");
  }
  return out.replace(
    new RegExp(`([?&](?:${SECRET_PARAMS.join("|")})=)[^&\\s"']+`, "gi"),
    "$1REDACTED",
  );
}

function unmapped(book: string, reason: string, row: unknown): UnmappedRow {
  const keys = row && typeof row === "object" && !Array.isArray(row)
    ? Object.keys(row as Record<string, unknown>)
    : [];
  return { book, reason, keys, sample: sampleOf(row) };
}

/** A bounded, value-bearing sample for diagnosis. Capped so an unmapped-row
 *  report can never grow into a payload dump. */
function sampleOf(row: unknown, maxLen = 400): unknown {
  try {
    const s = JSON.stringify(row);
    if (s === undefined) return null;
    return s.length <= maxLen ? JSON.parse(s) : `${s.slice(0, maxLen)}…`;
  } catch {
    return null;
  }
}

// ---------- inlined _shared/oddsblaze.ts ----------
// OddsBlaze provider.
//
// The ONLY file in the Collective that knows what an OddsBlaze response looks
// like. Everything else consumes NormalizedSlate. Swapping or adding a vendor
// is a sibling of this file plus one registerProvider call.
//
// Wire contract, from the OddsBlaze API documentation (docs.oddsblaze.com):
//
//   GET <base>?key=<API key>&sportsbook=<book id>&league=<league id>
//              [&market=<id or name, comma separated>]
//              [&price=american|decimal|fractional|probability|…]
//              [&live=true|false]   include only live / only pre-match
//              [&main=true|false]   include only main / only alternate lines
//
//   -> { "updated": <timestamp>,
//        "league":     { "id": "nfl", "name": …, "sport": … },
//        "sportsbook": { "id": "draftkings", "name": "DraftKings" },
//        "events": [ { "id": …,
//                      "teams": { "home": { "id", "name", "abbreviation" },
//                                 "away": { … } },
//                      "date": …, "live": <bool>,
//                      "odds": [ { "id", "market", "name", "price", "main",
//                                  "selection": { "name", "side", "line" } } ] } ] }
//
// The credential is read here and here only, from the NFL_ODDS_API_KEY edge
// function secret. It is placed in the query string because that is the
// documented authentication method, and every URL that leaves this module —
// into a log, an error, an ingest_runs row, or a probe response — goes
// through redactUrl or redactSecret first.
//
// Where the documentation lists a field under more than one name, or where a
// vendor may add one, the reader below tries the documented field first and
// the documented alternatives after. A row that matches none of them is
// returned in `unmapped` with its key names, never with a substituted value.

const DEFAULT_BASE = "https://odds.oddsblaze.com/";
const DEFAULT_TIMEOUT_MS = 12000;
/** Concurrent provider requests. Low on purpose: a trial plan is a shared,
 *  rate limited resource and a burst is the fastest way to lose it. */
const CONCURRENCY = 3;

function apiKey(): string {
  return Deno.env.get("NFL_ODDS_API_KEY") ?? "";
}

function baseUrl(): string {
  return Deno.env.get("NFL_ODDS_BASE_URL") ?? DEFAULT_BASE;
}

/** Canonical market id -> the id OddsBlaze uses in its `market` parameter. */
const PROVIDER_MARKET: Record<string, string> = {
  moneyline: "moneyline",
  spread: "point-spread",
  total: "total-points",
  team_total: "team-total",
  alternate_spread: "alternate-point-spread",
  alternate_total: "alternate-total-points",
};

interface ObEvent {
  id?: unknown;
  teams?: { home?: ObTeam; away?: ObTeam };
  home?: unknown;
  away?: unknown;
  date?: unknown;
  start?: unknown;
  live?: unknown;
  status?: unknown;
  odds?: unknown;
}
interface ObTeam {
  id?: unknown;
  name?: unknown;
  abbreviation?: unknown;
  short_name?: unknown;
}

function teamNames(t: ObTeam | undefined): string[] {
  if (!t) return [];
  return [t.name, t.abbreviation, t.short_name]
    .filter((x): x is string => typeof x === "string" && x.length > 0);
}

/** The container the vendor puts the games in. `events` is what the docs
 *  show; `games` is accepted because the same feed is documented under that
 *  name elsewhere. The probe reports which one was actually seen. */
function eventArray(body: unknown): { rows: ObEvent[]; container: string | null } {
  if (!body || typeof body !== "object") return { rows: [], container: null };
  const o = body as Record<string, unknown>;
  for (const key of ["events", "games"]) {
    if (Array.isArray(o[key])) return { rows: o[key] as ObEvent[], container: key };
  }
  return { rows: [], container: null };
}

/**
 * One vendor odds row -> one NormalizedOdd, or an UnmappedRow explaining
 * exactly which part could not be read.
 */
function readOdd(
  row: unknown,
  ctx: { book: string; homeNames: string[]; awayNames: string[]; eventLive: boolean },
): { odd: NormalizedOdd } | { bad: UnmappedRow } {
  if (!row || typeof row !== "object") {
    return { bad: unmapped(ctx.book, "odds row is not an object", row) };
  }
  const r = row as Record<string, unknown>;
  const sel = (r.selection && typeof r.selection === "object" && !Array.isArray(r.selection))
    ? r.selection as Record<string, unknown>
    : null;

  // A player prop carries a player; it is a different family and is skipped
  // here rather than mangled into a game line.
  if (r.player || r.players) {
    return { bad: unmapped(ctx.book, "player market, not a game line", row) };
  }

  const market = canonicalMarket(firstOf(r.market, r.market_id, r.market_name));
  if (!market) {
    return { bad: unmapped(ctx.book, `unrecognised market ${JSON.stringify(r.market ?? null)}`, row) };
  }
  if (!GAME_MARKETS.includes(market)) {
    return { bad: unmapped(ctx.book, `market ${market} is not a stored game line`, row) };
  }

  const price = parseAmericanPrice(firstOf(r.price, r.odds, r.american));
  if (price === null) {
    return { bad: unmapped(ctx.book, "no usable American price", row) };
  }

  const selectionName = firstOf<unknown>(
    sel?.name,
    typeof r.selection === "string" ? r.selection : null,
    r.name,
  );
  const outcome = resolveOutcome({
    market,
    side: firstOf<unknown>(sel?.side, r.side, r.selection_side),
    selectionName,
    homeNames: ctx.homeNames,
    awayNames: ctx.awayNames,
  });
  if (!outcome) {
    return { bad: unmapped(ctx.book, "could not attribute the price to a side", row) };
  }

  // Documented field first, documented alternatives next, the label last.
  let line = parseLine(
    firstOf<unknown>(sel?.line, sel?.points, r.points, r.selection_points, r.line, r.handicap),
  );
  if (line === null && market !== "moneyline") {
    line = lineFromLabel(selectionName ?? r.name);
  }
  if (market !== "moneyline" && line === null) {
    return { bad: unmapped(ctx.book, `${market} row carries no line`, row) };
  }
  if (market === "moneyline") line = null;

  // Spreads are stored in home convention: the away number is the mirror of
  // the home number, so an away row keeps its own sign as sent.
  return {
    odd: {
      book: ctx.book,
      market,
      outcome,
      outcome_label: typeof selectionName === "string" ? selectionName : null,
      line,
      price,
      is_live: Boolean(firstOf(r.live, ctx.eventLive)),
      is_main: r.main === undefined ? true : Boolean(r.main),
      raw: sampleOf(row, 600),
    },
  };
}

/** One vendor event -> one NormalizedEvent. Team names are passed through
 *  verbatim; turning them into codes is the database's job, using the alias
 *  table, so there is one place where team identity is decided. */
function readEvent(
  ev: ObEvent,
  ctx: { book: string; providerUpdatedAt: string | null },
): { event: NormalizedEvent | null; bad: UnmappedRow[] } {
  const bad: UnmappedRow[] = [];
  const home = ev.teams?.home ?? (typeof ev.home === "object" ? ev.home as ObTeam : undefined);
  const away = ev.teams?.away ?? (typeof ev.away === "object" ? ev.away as ObTeam : undefined);
  const homeNames = teamNames(home).concat(typeof ev.home === "string" ? [ev.home] : []);
  const awayNames = teamNames(away).concat(typeof ev.away === "string" ? [ev.away] : []);

  const commence = firstOf<unknown>(ev.date, ev.start, (ev as Record<string, unknown>).commence_time);
  if (!homeNames.length || !awayNames.length || !commence) {
    bad.push(unmapped(ctx.book, "event missing teams or kickoff time", ev));
    return { event: null, bad };
  }

  const eventLive = Boolean(ev.live);
  const odds: NormalizedOdd[] = [];
  const rawOdds = Array.isArray(ev.odds) ? ev.odds : [];
  for (const row of rawOdds) {
    const res = readOdd(row, { book: ctx.book, homeNames, awayNames, eventLive });
    if ("odd" in res) odds.push(res.odd);
    else bad.push(res.bad);
  }

  return {
    event: {
      provider_event_id: ev.id === undefined || ev.id === null ? null : String(ev.id),
      home: homeNames[0],
      away: awayNames[0],
      home_name: homeNames[0],
      away_name: awayNames[0],
      commence_time: String(commence),
      status: eventLive ? "live" : (typeof ev.status === "string" ? ev.status : "scheduled"),
      is_live: eventLive,
      provider_updated_at: ctx.providerUpdatedAt,
      odds,
    },
    bad,
  };
}

function buildUrl(book: string, opts: FetchOptions): string {
  const u = new URL(baseUrl());
  u.searchParams.set("key", apiKey());
  u.searchParams.set("sportsbook", book);
  u.searchParams.set("league", opts.league);
  u.searchParams.set("price", "american");
  const markets = opts.markets
    .map((m: MarketId) => PROVIDER_MARKET[m] ?? m)
    .filter(Boolean);
  if (markets.length) u.searchParams.set("market", markets.join(","));
  if (opts.mainOnly) u.searchParams.set("main", "true");
  if (opts.live !== undefined) u.searchParams.set("live", String(opts.live));
  return u.toString();
}

/** Vendor HTTP status -> a stable reason code the ingest run can record and
 *  the dashboard can explain. Bodies are never surfaced. */
function reasonFor(status: number): string {
  if (status === 401 || status === 403) return "invalid_or_unauthorized_key";
  if (status === 402) return "plan_or_trial_expired";
  if (status === 404) return "endpoint_or_league_not_found";
  if (status === 429) return "rate_limited";
  if (status >= 500) return "provider_outage";
  return `provider_http_${status}`;
}

async function fetchBook(
  book: string,
  opts: FetchOptions,
): Promise<{ book: string; body: unknown } | { book: string; reason: string }> {
  const url = buildUrl(book, opts);
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), opts.timeoutMs ?? DEFAULT_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      signal: ctrl.signal,
      headers: { "accept": "application/json" },
    });
    if (!res.ok) {
      // The body may echo the query string, so it is read and discarded
      // rather than propagated.
      await res.text().catch(() => "");
      return { book, reason: reasonFor(res.status) };
    }
    const text = await res.text();
    try {
      return { book, body: JSON.parse(text) };
    } catch {
      return { book, reason: "malformed_json" };
    }
  } catch (e) {
    const msg = redactSecret(String((e as Error)?.message ?? e), apiKey());
    return { book, reason: /abort/i.test(msg) ? "timeout" : `request_failed: ${msg.slice(0, 120)}` };
  } finally {
    clearTimeout(timer);
  }
}

/** Runs tasks with a fixed ceiling on how many are in flight. */
async function pooled<T, R>(items: T[], limit: number, fn: (t: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  const workers = new Array(Math.min(limit, items.length)).fill(0).map(async () => {
    for (;;) {
      const i = next++;
      if (i >= items.length) return;
      out[i] = await fn(items[i]);
    }
  });
  await Promise.all(workers);
  return out;
}

/**
 * Merges per-book responses into one slate. Books are fetched separately (the
 * vendor takes one sportsbook per request) but a game is a game: the same
 * event across books collapses onto one entry keyed by teams and kickoff, so
 * the database receives one event carrying every book's prices.
 */
function mergeBooks(
  parts: { book: string; body: unknown }[],
): { events: NormalizedEvent[]; unmapped: UnmappedRow[]; providerUpdatedAt: string | null } {
  const byKey = new Map<string, NormalizedEvent>();
  const bad: UnmappedRow[] = [];
  let updated: string | null = null;

  for (const part of parts) {
    const body = part.body as Record<string, unknown> | null;
    const partUpdated = body && typeof body.updated === "string" ? body.updated : null;
    if (partUpdated && (!updated || partUpdated > updated)) updated = partUpdated;

    const { rows, container } = eventArray(body);
    if (!container) {
      bad.push(unmapped(part.book, "response carried no events array", body));
      continue;
    }
    for (const ev of rows) {
      const { event, bad: evBad } = readEvent(ev, {
        book: part.book,
        providerUpdatedAt: partUpdated,
      });
      bad.push(...evBad);
      if (!event) continue;
      const key = [event.home, event.away, event.commence_time.slice(0, 10)]
        .map((s) => s.toLowerCase().replace(/[^a-z0-9]/g, "")).join("|");
      const existing = byKey.get(key);
      if (existing) {
        existing.odds.push(...event.odds);
        existing.is_live = existing.is_live || event.is_live;
        // Keep the first provider id seen; the mapping table holds the rest.
        if (!existing.provider_event_id) existing.provider_event_id = event.provider_event_id;
      } else {
        byKey.set(key, event);
      }
    }
  }
  return { events: [...byKey.values()], unmapped: bad, providerUpdatedAt: updated };
}

const oddsBlazeProvider: OddsProvider = {
  id: "oddsblaze",
  name: "OddsBlaze",

  isConfigured(): boolean {
    return apiKey().length > 0;
  },

  async fetchSlate(opts: FetchOptions): Promise<NormalizedSlate> {
    const fetched_at = new Date().toISOString();
    if (!this.isConfigured()) {
      return {
        provider: "oddsblaze",
        league: opts.league,
        fetched_at,
        provider_updated_at: null,
        events: [],
        books_ok: [],
        books_failed: opts.books.map((b) => ({ book: b, reason: "missing_api_key" })),
        unmapped: [],
        counts: { events: 0, odds: 0, unmapped: 0 },
      };
    }

    const results = await pooled(opts.books, CONCURRENCY, (b) => fetchBook(b, opts));
    const ok = results.filter((r): r is { book: string; body: unknown } => "body" in r);
    const failed = results
      .filter((r): r is { book: string; reason: string } => "reason" in r)
      .map((r) => ({ book: r.book, reason: r.reason }));

    const merged = mergeBooks(ok);
    const oddsCount = merged.events.reduce((n, e) => n + e.odds.length, 0);
    return {
      provider: "oddsblaze",
      league: opts.league,
      fetched_at,
      provider_updated_at: merged.providerUpdatedAt,
      events: merged.events,
      books_ok: ok.map((r) => r.book),
      books_failed: failed,
      // Bounded: a systematic shape change produces one report per row, and
      // the run record is not the place to store thousands of them.
      unmapped: merged.unmapped.slice(0, 25),
      counts: { events: merged.events.length, odds: oddsCount, unmapped: merged.unmapped.length },
    };
  },

  async probe(opts: FetchOptions): Promise<ProbeResult> {
    const book = opts.books[0] ?? "draftkings";
    const url = buildUrl(book, opts);
    const base: ProbeResult = {
      provider: "oddsblaze",
      ok: false,
      url_redacted: redactUrl(url),
      http_status: null,
      observed_shape: [],
      sample_event: null,
      sample_odd: null,
      counts: { events: 0, odds: 0 },
      error: null,
      mapping: { mapped: 0, unmapped: [] },
    };
    if (!this.isConfigured()) {
      return { ...base, error: "NFL_ODDS_API_KEY is not set on this function" };
    }

    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), opts.timeoutMs ?? DEFAULT_TIMEOUT_MS);
    try {
      const res = await fetch(url, { signal: ctrl.signal, headers: { accept: "application/json" } });
      base.http_status = res.status;
      const text = await res.text();
      if (!res.ok) {
        return { ...base, error: reasonFor(res.status) };
      }
      let body: unknown;
      try {
        body = JSON.parse(text);
      } catch {
        return { ...base, error: "malformed_json" };
      }
      const { rows, container } = eventArray(body);
      const sample = rows[0];
      const sampleOdds = sample && Array.isArray(sample.odds) ? sample.odds : [];

      // Run the real adapter over the real sample: this is the difference
      // between "the endpoint answered" and "we can read what it said".
      let mapped = 0;
      const bad: UnmappedRow[] = [];
      for (const ev of rows.slice(0, 3)) {
        const r = readEvent(ev, { book, providerUpdatedAt: null });
        if (r.event) mapped += r.event.odds.length;
        bad.push(...r.bad);
      }

      return {
        ...base,
        ok: true,
        observed_shape: shapePaths(body).concat(container ? [`container=${container}`] : []),
        sample_event: sample
          ? { id: sample.id, teams: sample.teams, date: sample.date ?? sample.start, live: sample.live }
          : null,
        sample_odd: sampleOdds.length ? sampleOf(sampleOdds[0], 600) : null,
        counts: {
          events: rows.length,
          odds: rows.reduce((n, e) => n + (Array.isArray(e.odds) ? e.odds.length : 0), 0),
        },
        mapping: { mapped, unmapped: bad.slice(0, 10) },
      };
    } catch (e) {
      const msg = redactSecret(String((e as Error)?.message ?? e), apiKey());
      return { ...base, error: /abort/i.test(msg) ? "timeout" : msg.slice(0, 200) };
    } finally {
      clearTimeout(timer);
    }
  },
};

/** Exported for the read API's price comparison. Kept next to the provider so
 *  the American-odds convention has one owner. */

// ---------- collective_odds_ingest/index.ts ----------
// Model Collective — NFL odds ingestion.
//
// The single writer. Nothing else in the Collective calls an odds provider,
// and nothing else writes to the odds schema. One run: read the settings,
// decide whether it is time, fetch, normalize, hand the batch to SQL, close
// any market that has kicked off, and record what happened.
//
// DEPLOYMENT: keep "Enforce JWT verification" ON for this function. The
// gateway then rejects anonymous calls, and the checks below additionally
// require either the service role key (how pg_cron calls it) or an admin
// account. The OddsBlaze credential lives only in the NFL_ODDS_API_KEY
// secret and is read only inside the provider module.

registerProvider(oddsBlazeProvider);

const NO_STORE = { "cache-control": "no-store" };
/** Events per RPC call. Keeps a single request body small enough to stay well
 *  inside PostgREST limits on a full 16 game slate with every book. */
const BATCH_EVENTS = 12;

const SETTING_KEYS = [
  "nfl.enabled",
  "nfl.league_id",
  "nfl.books",
  "nfl.markets",
  "nfl.refresh_seconds.live",
  "nfl.refresh_seconds.pregame",
  "nfl.refresh_seconds.idle",
  "nfl.pregame_window_hours",
  "nfl.max_books_per_run",
  "provider.default",
];

/** pg_cron calls with the service role key; a founder calls with their own
 *  session. Anything else is refused before a provider request is made. */
async function authorize(req: Request): Promise<{ trigger: string } | Response> {
  const authz = req.headers.get("authorization") ?? "";
  const bearer = authz.replace(/^Bearer\s+/i, "").trim();
  if (SERVICE_KEY && bearer === SERVICE_KEY) return { trigger: "cron" };
  const admin = await requireAdmin(req);
  if (admin instanceof Response) return admin;
  return { trigger: "admin" };
}

interface Cadence {
  interval_seconds: number;
  reason: "live" | "pregame" | "idle";
  next_kickoff: string | null;
}

/**
 * How often to poll right now. Live games get the fastest cadence the plan
 * safely allows, a slate about to start gets a middle one, and an empty
 * calendar gets the slow one. Every value comes from odds.settings, so
 * changing the cadence is a settings update rather than a deploy.
 */
async function cadence(cfg: Record<string, unknown>, league: string): Promise<Cadence> {
  const st = await rpc<Record<string, unknown> | null>("odds_status", { p_league: league })
    .catch(() => null);
  const live = num(st?.events_live, 0);
  const windowHours = num(cfg["nfl.pregame_window_hours"], 36);

  if (live > 0) {
    return {
      interval_seconds: num(cfg["nfl.refresh_seconds.live"], 60),
      reason: "live",
      next_kickoff: null,
    };
  }
  const next = await nextKickoff(league);
  if (next) {
    const hours = (Date.parse(next) - Date.now()) / 3_600_000;
    if (hours <= windowHours) {
      return {
        interval_seconds: num(cfg["nfl.refresh_seconds.pregame"], 300),
        reason: "pregame",
        next_kickoff: next,
      };
    }
  }
  return {
    interval_seconds: num(cfg["nfl.refresh_seconds.idle"], 1800),
    reason: "idle",
    next_kickoff: next,
  };
}

async function nextKickoff(league: string): Promise<string | null> {
  const board = await rpc<Record<string, unknown> | null>("odds_board", {
    p_league: league,
    p_from: new Date().toISOString(),
    p_to: null,
    p_include_books: false,
    p_limit: 1,
  }).catch(() => null);
  const games = (board?.games ?? []) as { commence_time?: string }[];
  return games[0]?.commence_time ?? null;
}

/** Seconds since the last run that actually reached the provider. */
async function secondsSinceLastRun(): Promise<number | null> {
  const st = await rpc<Record<string, unknown> | null>("odds_status", { p_league: "nfl" })
    .catch(() => null);
  const last = st?.last_run as { started_at?: string; status?: string } | null | undefined;
  if (!last?.started_at) return null;
  const ms = Date.parse(last.started_at);
  return Number.isFinite(ms) ? Math.round((Date.now() - ms) / 1000) : null;
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

Deno.serve(async (req) => {
  const pre = preflight(req);
  if (pre) return pre;
  const path = subpath(req, "collective_odds_ingest");

  const auth = await authorize(req);
  if (auth instanceof Response) return auth;

  try {
    const url = new URL(req.url);
    const force = url.searchParams.get("force") === "1";
    const cfg = await settings(SETTING_KEYS);
    const league = typeof cfg["nfl.league_id"] === "string"
      ? cfg["nfl.league_id"] as string
      : "nfl";
    const providerId = typeof cfg["provider.default"] === "string"
      ? cfg["provider.default"] as string
      : "oddsblaze";
    const provider = getProvider(providerId);

    if (!provider) {
      return err("server_error", `No provider registered under "${providerId}".`, 500);
    }

    // ------------------------------------------------------------- probe
    // One real request, reporting the observed response STRUCTURE. This is
    // how the integration is confirmed against the live API without printing
    // a credential or trusting a guess about the payload shape.
    if (path === "/v1/probe" && (req.method === "POST" || req.method === "GET")) {
      const books = strList(cfg["nfl.books"], ["draftkings"]);
      const only = url.searchParams.get("book");
      const result = await provider.probe({
        league,
        books: only ? [only] : books.slice(0, 1),
        markets: strList(cfg["nfl.markets"], ["moneyline", "spread", "total"]),
        mainOnly: true,
        timeoutMs: 15000,
      });
      return json(result, result.ok ? 200 : 502, NO_STORE);
    }

    // ------------------------------------------------------------ status
    if (path === "/v1/status" && req.method === "GET") {
      const st = await rpc<Record<string, unknown> | null>("odds_status", { p_league: league });
      const cad = await cadence(cfg, league);
      return json({
        ...st,
        provider: { id: provider.id, name: provider.name, configured: provider.isConfigured() },
        cadence: cad,
        seconds_since_last_run: await secondsSinceLastRun(),
      }, 200, NO_STORE);
    }

    // ------------------------------------------------------ close markets
    if (path === "/v1/close" && req.method === "POST") {
      const closed = await rpc<number>("odds_finalize_closing", { p_event_id: null });
      const linked = await rpc<number>("odds_link_games", { p_league: league });
      return json({ ok: true, closing_rows: closed ?? 0, games_linked: linked ?? 0 }, 200, NO_STORE);
    }

    // -------------------------------------------------- link to the slate
    if (path === "/v1/link" && req.method === "POST") {
      const linked = await rpc<number>("odds_link_games", { p_league: league });
      return json({ ok: true, games_linked: linked ?? 0 }, 200, NO_STORE);
    }

    // ------------------------------------------------------------ ingest
    if (path === "/v1/ingest" && req.method === "POST") {
      if (cfg["nfl.enabled"] === false) {
        return json({ ok: true, skipped: "disabled", reason: "nfl.enabled is false" }, 200, NO_STORE);
      }
      if (!provider.isConfigured()) {
        return err(
          "not_configured",
          "The odds provider credential is not set on this function. Add NFL_ODDS_API_KEY to the edge function secrets.",
          503,
        );
      }

      // Do not hammer the API: a run that arrives early for the current
      // cadence returns without making a provider request at all.
      const cad = await cadence(cfg, league);
      const since = await secondsSinceLastRun();
      if (!force && since !== null && since < cad.interval_seconds) {
        return json({
          ok: true,
          skipped: "too_soon",
          cadence: cad,
          seconds_since_last_run: since,
        }, 200, NO_STORE);
      }

      const books = strList(cfg["nfl.books"], ["draftkings", "fanduel", "betmgm"])
        .slice(0, Math.max(1, num(cfg["nfl.max_books_per_run"], 12)));
      const markets = strList(cfg["nfl.markets"], ["moneyline", "spread", "total"]);
      const opts: FetchOptions = { league, books, markets, mainOnly: true, timeoutMs: 12000 };

      const runId = await rpc<number>("odds_begin_run", {
        p_provider: provider.id,
        p_league: league,
        p_trigger: auth.trigger,
      });

      try {
        const slate = await provider.fetchSlate(opts);

        // Every book failing is a provider problem, not a slate with no
        // games. Recording it as "0 events" would make an outage look like
        // an empty week, so it is reported as an error and no data is touched.
        if (slate.books_ok.length === 0) {
          const reason = slate.books_failed[0]?.reason ?? "no_books_returned";
          await rpc("odds_finish_run", {
            p_run_id: runId,
            p_stats: {
              status: "error",
              books_requested: books.length,
              books_ok: 0,
              books_failed: slate.books_failed.length,
              error_code: reason,
              error_message: `every requested sportsbook failed: ${
                slate.books_failed.map((b) => `${b.book}=${b.reason}`).join(", ").slice(0, 300)
              }`,
            },
          });
          return err("provider_unavailable", "The odds provider did not return any data.", 502, {
            books_failed: slate.books_failed,
          });
        }

        let written = 0, unchanged = 0, created = 0, seen = 0, rejected = 0;
        const unmatched: unknown[] = [];
        for (const part of chunk<NormalizedEvent>(slate.events, BATCH_EVENTS)) {
          const res = await rpc<Record<string, unknown>>("odds_ingest", {
            p_run_id: runId,
            p_provider: provider.id,
            p_league: league,
            p_payload: { events: part },
          });
          if (res && res.ok === false) {
            throw new Error(`ingest rejected: ${String(res.code ?? "unknown")}`);
          }
          written += num(res?.snapshots_written, 0);
          unchanged += num(res?.snapshots_unchanged, 0);
          created += num(res?.events_created, 0);
          seen += num(res?.events_seen, 0);
          rejected += num(res?.rows_rejected, 0);
          if (Array.isArray(res?.unmatched)) unmatched.push(...res.unmatched as unknown[]);
        }

        // A game that has kicked off closes now, while its last pre-kickoff
        // price is still the most recent thing we stored.
        const closingRows = await rpc<number>("odds_finalize_closing", { p_event_id: null })
          .catch(() => 0);
        const linked = await rpc<number>("odds_link_games", { p_league: league }).catch(() => 0);

        const partial = slate.books_failed.length > 0 || unmatched.length > 0 ||
          slate.counts.unmapped > 0;
        await rpc("odds_finish_run", {
          p_run_id: runId,
          p_stats: {
            status: partial ? "partial" : "ok",
            books_requested: books.length,
            books_ok: slate.books_ok.length,
            books_failed: slate.books_failed.length,
            events_seen: seen,
            events_created: created,
            events_matched: seen - created,
            snapshots_written: written,
            snapshots_unchanged: unchanged,
            rows_rejected: rejected,
            unmatched: {
              events: unmatched.slice(0, 20),
              provider_rows: slate.unmapped,
              books_failed: slate.books_failed,
            },
          },
        });

        return json({
          ok: true,
          run_id: runId,
          provider: provider.id,
          league,
          cadence: cad,
          books_ok: slate.books_ok,
          books_failed: slate.books_failed,
          events_seen: seen,
          events_created: created,
          snapshots_written: written,
          snapshots_unchanged: unchanged,
          rows_rejected: rejected,
          provider_rows_unmapped: slate.counts.unmapped,
          unmapped_sample: slate.unmapped.slice(0, 5),
          unmatched_events: unmatched.slice(0, 5),
          closing_rows: closingRows ?? 0,
          games_linked: linked ?? 0,
        }, 200, NO_STORE);
      } catch (e) {
        const msg = redactSecret(
          String((e as Error)?.message ?? e),
          Deno.env.get("NFL_ODDS_API_KEY"),
        );
        console.error("collective_odds_ingest run failed:", msg);
        await rpc("odds_finish_run", {
          p_run_id: runId,
          p_stats: { status: "error", error_code: "ingest_failed", error_message: msg },
        }).catch(() => {});
        return err("server_error", "The odds run did not complete.", 500);
      }
    }

    if (["/v1/ingest", "/v1/probe", "/v1/close", "/v1/link", "/v1/status"].includes(path)) {
      return err("method_not_allowed", "Wrong method for this route.", 405);
    }
    return err("not_found", `No such route: ${req.method} ${path}`, 404);
  } catch (e) {
    const msg = redactSecret(String((e as Error)?.message ?? e), Deno.env.get("NFL_ODDS_API_KEY"));
    if (e instanceof RpcError) console.error("collective_odds_ingest rpc failure:", e.message);
    else console.error("collective_odds_ingest failure:", msg);
    return err("server_error", "Something went wrong on our side.", 500);
  }
});
