// collective_odds - SELF-CONTAINED BUNDLE for the Supabase dashboard editor.
// Generated from supabase/functions/ by tools/collective/bundle_functions.py.
// Do not edit this file: edit the sources and regenerate.
// Paste this whole file as index.ts for a function named exactly: collective_odds
// IMPORTANT: turn OFF "Enforce JWT verification" for this function.

// ---------- inlined _shared/http.ts ----------
// Shared HTTP helpers: JSON responses, the contract error shape, CORS, and
// subpath routing. Every Collective edge function builds its responses here so
// the error taxonomy and CORS behavior stay identical across functions.

function corsHeaders(origin = "*"): Record<string, string> {
  const headers: Record<string, string> = {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers":
      "authorization, apikey, content-type, x-collective-key, x-client-info",
    "Access-Control-Max-Age": "86400",
  };
  if (origin !== "*") {
    headers["Vary"] = "Origin";
  }
  return headers;
}

function json(
  body: unknown,
  status = 200,
  headers: Record<string, string> = {},
): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      ...corsHeaders(),
      ...headers,
    },
  });
}

// Error response in the contract shape { error: { code, message, details } }.
// details is always present, null when there is nothing row-level to report.
function err(
  code: string,
  message: string,
  status: number,
  details?: unknown,
): Response {
  return json({ error: { code, message, details: details ?? null } }, status);
}

// Returns a 204 Response for OPTIONS requests, else null.
function preflight(req: Request, origin = "*"): Response | null {
  if (req.method !== "OPTIONS") return null;
  return new Response(null, { status: 204, headers: corsHeaders(origin) });
}

// Path after /functions/v1/<fnName>, normalized. Works both behind the
// production gateway (/functions/v1/<fnName>/...) and when served locally
// (/<fnName>/...). "" becomes "/", duplicate slashes collapse, and a
// trailing slash is stripped except on the root.
function subpath(req: Request, fnName: string): string {
  const pathname = new URL(req.url).pathname;
  const marker = `/${fnName}`;
  const idx = pathname.indexOf(marker);
  let rest = idx >= 0 ? pathname.slice(idx + marker.length) : pathname;
  if (!rest.startsWith("/")) rest = `/${rest}`;
  rest = rest.replace(/\/{2,}/g, "/");
  if (rest.length > 1 && rest.endsWith("/")) rest = rest.slice(0, -1);
  return rest;
}

// ---------- inlined _shared/env.ts ----------
// Shared environment access for Collective edge functions.
// SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, and SUPABASE_ANON_KEY are injected
// by the Supabase runtime. COLLECTIVE_BASE_URL is an optional secret that
// points at the public site root and defaults to production.

const SB_URL: string = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY: string = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const ANON_KEY: string = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
const BASE_URL: string = Deno.env.get("COLLECTIVE_BASE_URL") ?? "https://edgedesksports.com";

// ---------- inlined _shared/db.ts ----------
// Shared database access. Edge functions never talk SQL: they call the
// SECURITY DEFINER RPCs in the collective schema through PostgREST with the
// service role key. RPCs return jsonb outcome objects like { ok: true, ... }
// or { ok: false, code: "token_expired", message: "..." }; callers translate
// ok:false codes to the HTTP error taxonomy. RpcError means an unexpected
// database failure and maps to 500 server_error (log it, never leak the body).

class RpcError extends Error {
  status: number;
  body: string;

  constructor(fn: string, status: number, body: string) {
    super(`rpc ${fn} failed with status ${status}`);
    this.name = "RpcError";
    this.status = status;
    this.body = body;
  }
}

async function rpc<T = unknown>(
  fn: string,
  args: Record<string, unknown>,
): Promise<T> {
  const res = await fetch(`${SB_URL}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: {
      "apikey": SERVICE_KEY,
      "Authorization": `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
      "Content-Profile": "collective",
    },
    body: JSON.stringify(args),
  });
  const text = await res.text();
  if (!res.ok) {
    throw new RpcError(fn, res.status, text);
  }
  if (text === "") {
    return null as T;
  }
  return JSON.parse(text) as T;
}

// ---------- inlined _shared/odds_api.ts ----------
// Shared odds read helpers and the freshness envelope.
//
// Every odds payload the Collective serves carries the same three facts:
// where the number came from, when it was last updated, and whether that
// counts as current. A surface that cannot say when a price was captured is
// not allowed to display it as live, so this envelope is mandatory rather
// than decorative.

type Freshness = "live" | "stale" | "unavailable";

interface OddsEnvelope {
  source: { provider: string; league: string };
  /** When the feed was last confirmed current: the last successful poll. */
  last_updated: string | null;
  /** When a price last actually moved. Not the same question, and not what
   *  freshness is judged on — unchanged polls write nothing by design, so a
   *  quiet market would otherwise read as a broken feed. */
  last_change_at: string | null;
  age_seconds: number | null;
  state: Freshness;
  stale_after_seconds: number;
  /** Present only when state is not "live": a sentence a UI can show as-is. */
  notice?: string;
}

const DEFAULT_STALE_AFTER = 900;

/**
 * Classifies the feed.
 *   live        polled successfully inside the freshness window
 *   stale       the last successful poll is older than the window. Prices are
 *               still returned, labelled, with their age. Never relabelled
 *               current.
 *   unavailable nothing to show. No number is invented to fill the gap.
 *
 * lastPolled, not the newest price. A market that has not moved since Tuesday
 * is a quiet market, not a dead feed, and calling it stale would train people
 * to ignore the one label that is supposed to mean something.
 */
function envelope(
  lastPolled: string | null | undefined,
  staleAfterSeconds: number | null | undefined,
  league = "nfl",
  // Not a vendor name. A caller that forgets to pass the provider should
  // produce a visibly unknown source, not a confident and wrong one — the
  // field is read as fact, including by the assistant route.
  provider = "unknown",
  lastChangeAt: string | null | undefined = null,
): OddsEnvelope {
  const lastUpdated = lastPolled ?? null;
  const changed = lastChangeAt ?? null;
  const staleAfter = Number(staleAfterSeconds) > 0
    ? Number(staleAfterSeconds)
    : DEFAULT_STALE_AFTER;
  if (!lastUpdated) {
    return {
      source: { provider, league },
      last_updated: null,
      last_change_at: changed,
      age_seconds: null,
      state: "unavailable",
      stale_after_seconds: staleAfter,
      notice: "Odds unavailable.",
    };
  }
  const ms = Date.parse(lastUpdated);
  if (!Number.isFinite(ms)) {
    return {
      source: { provider, league },
      last_updated: null,
      last_change_at: changed,
      age_seconds: null,
      state: "unavailable",
      stale_after_seconds: staleAfter,
      notice: "Odds unavailable.",
    };
  }
  const age = Math.max(0, Math.round((Date.now() - ms) / 1000));
  if (age <= staleAfter) {
    return {
      source: { provider, league },
      last_updated: lastUpdated,
      last_change_at: changed,
      age_seconds: age,
      state: "live",
      stale_after_seconds: staleAfter,
    };
  }
  return {
    source: { provider, league },
    last_updated: lastUpdated,
    last_change_at: changed,
    age_seconds: age,
    state: "stale",
    stale_after_seconds: staleAfter,
    notice: `Odds may be out of date. Last polled ${relativeAge(age)}.`,
  };
}

function relativeAge(seconds: number): string {
  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 5400) return `${Math.round(seconds / 60)} minutes ago`;
  if (seconds < 172800) return `${Math.round(seconds / 3600)} hours ago`;
  return `${Math.round(seconds / 86400)} days ago`;
}

// ------------------------------------------------------------------ settings
// The odds* prefixes on the read helpers below are deliberate: the dashboard
// deploys these functions as one flattened script, where a top level
// `history` or `status` would sit alongside the DOM globals of the same name.
let settingsCache: { at: number; values: Record<string, unknown> } | null = null;
const SETTINGS_TTL_MS = 60_000;

/** Reads odds settings, cached briefly so a slate render does not make one
 *  round trip per tunable. */
async function settings(keys: string[]): Promise<Record<string, unknown>> {
  const now = Date.now();
  if (settingsCache && now - settingsCache.at < SETTINGS_TTL_MS) {
    const have = keys.every((k) => k in settingsCache!.values);
    if (have) return settingsCache.values;
  }
  const values: Record<string, unknown> = { ...(settingsCache?.values ?? {}) };
  await Promise.all(keys.map(async (k) => {
    try {
      values[k] = await rpc<unknown>("odds_get_setting", { p_key: k });
    } catch {
      values[k] = null;
    }
  }));
  settingsCache = { at: now, values };
  return values;
}

/**
 * A number, or the fallback.
 *
 * The null check is the whole point: Number(null) is 0, and 0 is finite, so a
 * bare Number.isFinite guard silently turns every absent value into zero.
 * URLSearchParams.get returns null for a missing parameter, so ?limit,
 * ?days and ?week all became 0 — a one-game board, a one-day window, and a
 * cadence of zero seconds when a setting was missing.
 */
function num(v: unknown, fallback: number): number {
  if (v === null || v === undefined || v === "") return fallback;
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function strList(v: unknown, fallback: string[]): string[] {
  if (Array.isArray(v)) {
    const out = v.filter((x): x is string => typeof x === "string" && x.length > 0);
    if (out.length) return out;
  }
  return fallback;
}

/** Board payload straight from SQL. The math is not repeated here. */
async function oddsBoard(args: {
  league?: string;
  from?: string | null;
  to?: string | null;
  includeBooks?: boolean;
  limit?: number;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_board", {
    p_league: args.league ?? "nfl",
    p_from: args.from ?? null,
    p_to: args.to ?? null,
    p_include_books: args.includeBooks !== false,
    p_limit: args.limit ?? 40,
  });
}

async function oddsEventPayload(args: {
  eventId?: string | null;
  gameId?: string | null;
  includeBooks?: boolean;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_event", {
    p_event_id: args.eventId ?? null,
    p_game_id: args.gameId ?? null,
    p_include_books: args.includeBooks !== false,
  });
}

async function oddsHistory(args: {
  eventId: string;
  market?: string | null;
  book?: string | null;
  outcome?: string | null;
  limit?: number;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_history", {
    p_event_id: args.eventId,
    p_market: args.market ?? null,
    p_book: args.book ?? null,
    p_outcome: args.outcome ?? null,
    p_limit: args.limit ?? 500,
  });
}

async function oddsStatus(league = "nfl"): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_status", { p_league: league });
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function isUuid(s: string): boolean {
  return UUID_RE.test(s);
}

// ---------- collective_odds/index.ts ----------
// Model Collective — internal NFL odds API.
//
// The only odds surface the browser is allowed to see. It reads what the
// ingestion function stored; it never calls a provider, and it holds no
// provider credential. Every response carries a freshness envelope, so a
// caller always knows whether a number is current, how old it is, or that
// there is nothing to show. Nothing here fabricates a price.
//
// DEPLOYMENT: turn OFF "Enforce JWT verification" for this function. Market
// odds are public information and the Collective's paid gate is on model
// projections, not on the market. Access to the odds tables themselves stays
// server side: the anon key has no grant on them.

/** Short cache: long enough to absorb a burst of page loads, short enough
 *  that a line move reaches the site inside a poll cycle. */
const CACHE = { "cache-control": "public, max-age=20" };
const NO_STORE = { "cache-control": "no-store" };
const LEAGUE = "nfl";

const SETTING_KEYS = ["nfl.stale_after_seconds", "nfl.league_id", "provider.default"];

function staleAfter(cfg: Record<string, unknown>): number {
  return num(cfg["nfl.stale_after_seconds"], 900);
}

/**
 * Who produced the stored numbers.
 *
 * First choice is the provider of the most recent successful run, which is
 * the run last_updated refers to. Falling back to provider.default answers a
 * different question — who will poll NEXT — and the two differ for exactly as
 * long as it takes the first run on a newly switched provider to finish, so
 * it is a fallback and not the primary. "unknown" rather than a plausible
 * vendor name when neither is available: a wrong attribution is worse than an
 * absent one, because it reads as a fact.
 */
function providerOf(fromRun: unknown, cfg: Record<string, unknown>): string {
  if (typeof fromRun === "string" && fromRun.length > 0) return fromRun;
  const configured = cfg["provider.default"];
  if (typeof configured === "string" && configured.length > 0) return configured;
  return "unknown";
}

/** Window helpers. "week" here is the Collective's own slate week, which the
 *  odds feed carries only when the provider supplies it, so the default
 *  window is time based: yesterday through a week out. */
function windowFrom(u: URL): {
  from: string | null;
  to: string | null;
  explicit: boolean;
} {
  const from = u.searchParams.get("from");
  const to = u.searchParams.get("to");
  if (from || to) {
    return { from: safeDate(from), to: safeDate(to), explicit: true };
  }
  const days = Math.min(28, Math.max(1, num(u.searchParams.get("days"), 8)));
  return {
    from: new Date(Date.now() - 24 * 3600e3).toISOString(),
    to: new Date(Date.now() + days * 24 * 3600e3).toISOString(),
    explicit: false,
  };
}

/**
 * The board for a window, widening a DEFAULT window that finds nothing.
 *
 * A days-based window is right during a season and wrong between them. Week 1
 * sits three weeks past a ten day window, so in August every caller gets an
 * empty board from a feed that is working perfectly — the same blank page a
 * dead feed produces, for an entirely different reason.
 *
 * So an empty default window retries with no upper bound and shows the next
 * games on the calendar. An EXPLICIT from/to is never widened: a caller that
 * named a range meant it, and quietly returning games outside it would be
 * worse than returning none. `widened` is reported either way, because a
 * surface that asked for ten days and is showing "the next games" needs to
 * know which it has.
 */
async function boardInWindow(
  u: URL,
  includeBooks: boolean,
  limit: number,
): Promise<{
  data: Record<string, unknown> | null;
  games: Record<string, unknown>[];
  from: string | null;
  to: string | null;
  widened: boolean;
}> {
  const win = windowFrom(u);
  const data = await oddsBoard({
    league: LEAGUE,
    from: win.from,
    to: win.to,
    includeBooks,
    limit,
  });
  const games = (data?.games ?? []) as Record<string, unknown>[];
  if (win.explicit || games.length > 0) {
    return { data, games, from: win.from, to: win.to, widened: false };
  }
  const next = await oddsBoard({
    league: LEAGUE,
    from: win.from,
    to: null,
    includeBooks,
    limit,
  });
  const upcoming = (next?.games ?? []) as Record<string, unknown>[];
  if (upcoming.length === 0) {
    return { data, games, from: win.from, to: win.to, widened: false };
  }
  return { data: next, games: upcoming, from: win.from, to: null, widened: true };
}

function safeDate(v: string | null): string | null {
  if (!v) return null;
  const ms = Date.parse(v);
  return Number.isFinite(ms) ? new Date(ms).toISOString() : null;
}

/** Trims a game to the fields a list view needs. The full book grid is a
 *  detail-view payload; sending it for every game on every page load is
 *  wasted bytes, not extra information. */
function summarize(game: Record<string, unknown>): Record<string, unknown> {
  const consensus = game.consensus as Record<string, unknown> | null;
  const best = game.best as Record<string, unknown> | null;
  return {
    event_id: game.event_id,
    collective_game_id: game.collective_game_id,
    season: game.season,
    week: game.week,
    home: game.home,
    away: game.away,
    home_name: game.home_name,
    away_name: game.away_name,
    commence_time: game.commence_time,
    status: game.status,
    is_live: game.is_live,
    market_closed: game.market_closed,
    last_odds_at: game.last_odds_at,
    book_count: game.book_count,
    /* Kept on the light payload: it is a small id -> name map, and without
       it a summary line can show a price but not name the book behind it. */
    book_names: game.book_names,
    consensus,
    best,
    opening: game.opening,
    closing: game.closing,
  };
}

Deno.serve(async (req) => {
  const pre = preflight(req);
  if (pre) return pre;
  const path = subpath(req, "collective_odds");
  const u = new URL(req.url);

  try {
    const cfg = await settings(SETTING_KEYS);
    const stale = staleAfter(cfg);
    /* Feed health is a property of the feed, not of one game, so the routes
       that return a single object still report the last successful poll.
       The provider comes from the SAME run as that poll, never from a
       constant: with more than one provider registered, a hardcoded name is a
       payload that misstates where its own numbers came from, and
       /v1/nfl/assistant hands this field to a research model as fact.
       Resolved once per request and reused. */
    let feed: { pollAt: string | null; provider: string } | undefined;
    const feedInfo = async (): Promise<{ pollAt: string | null; provider: string }> => {
      if (feed === undefined) {
        const st = await oddsStatus(LEAGUE).catch(() => null);
        feed = {
          pollAt: (st?.last_poll_at as string | null) ?? null,
          provider: providerOf(st?.provider, cfg),
        };
      }
      return feed;
    };
    const feedPolledAt = async (): Promise<string | null> => (await feedInfo()).pollAt;
    const feedProvider = async (): Promise<string> => (await feedInfo()).provider;

    // ------------------------------------------------------------ status
    // "Is the feed healthy?" as one object. The dashboards read this to
    // decide between showing numbers and showing why there are none.
    if (req.method === "GET" && (path === "/v1/nfl/status" || path === "/v1/status")) {
      const st = await oddsStatus(LEAGUE);
      const env = envelope(st?.last_poll_at as string | null, stale, LEAGUE,
        providerOf(st?.provider, cfg), st?.last_odds_at as string | null);
      return json({ ...env, ...st }, 200, NO_STORE);
    }

    // ------------------------------------------------------------- books
    if (req.method === "GET" && path === "/v1/nfl/books") {
      const rows = await rpc<unknown>("odds_get_setting", { p_key: "nfl.books" });
      return json({ books: Array.isArray(rows) ? rows : [] }, 200, CACHE);
    }

    // -------------------------------------------------- the slate + odds
    // /v1/nfl/games is the light list; /v1/nfl/odds is the same slate with
    // the full book grid. One code path, one source, two payload sizes.
    if (
      req.method === "GET" &&
      (path === "/v1/nfl/games" || path === "/v1/nfl/odds")
    ) {
      const wantBooks = path === "/v1/nfl/odds" && u.searchParams.get("books") !== "0";
      const limit = Math.min(200, Math.max(1, num(u.searchParams.get("limit"), 40)));
      const { data, games, from, to, widened } = await boardInWindow(u, wantBooks, limit);
      const env = envelope(
        data?.last_poll_at as string | null,
        num(data?.stale_after_seconds, stale),
        LEAGUE,
        providerOf(data?.provider, cfg),
        data?.last_odds_at as string | null,
      );
      const week = u.searchParams.get("week");
      const filtered = week
        ? games.filter((g) => String(g.week ?? "") === String(Number(week)))
        : games;
      return json({
        ...env,
        // widened is reported, not hidden: a caller asked for ten days and got
        // something else, and a surface that says "next games" instead of
        // "this week" needs to know which it is showing.
        window: { from, to, widened },
        count: filtered.length,
        games: wantBooks ? filtered : filtered.map(summarize),
      }, 200, env.state === "unavailable" ? NO_STORE : CACHE);
    }

    // ------------------------------------------------------- best prices
    // Deliberately per line. The payload never crowns one price across
    // different lines, because -4 -105 and -3.5 -110 are different bets.
    if (req.method === "GET" && path === "/v1/nfl/odds/best") {
      const eventId = u.searchParams.get("event");
      const market = u.searchParams.get("market");
      if (eventId) {
        if (!isUuid(eventId)) return err("invalid_payload", "event must be a uuid.", 422);
        const game = await oddsEventPayload({ eventId, includeBooks: true });
        if (!game) return err("not_found", "No odds for that game.", 404);
        const env = envelope(await feedPolledAt(), stale, LEAGUE, await feedProvider(),
          game.last_odds_at as string | null);
        const best = game.best as Record<string, unknown>;
        return json({
          ...env,
          event_id: game.event_id,
          home: game.home,
          away: game.away,
          best: market ? { [market]: best?.[market] ?? null } : best,
          note:
            "Prices are grouped by line. A better price at a different line is a different bet, not a better one.",
        }, 200, CACHE);
      }
      const { data, games } = await boardInWindow(u, false, 40);
      const env = envelope(data?.last_poll_at as string | null, stale, LEAGUE,
        providerOf(data?.provider, cfg), data?.last_odds_at as string | null);
      return json({
        ...env,
        count: games.length,
        games: games.map((g) => ({
          event_id: g.event_id,
          home: g.home,
          away: g.away,
          commence_time: g.commence_time,
          best: market
            ? { [market]: (g.best as Record<string, unknown>)?.[market] ?? null }
            : g.best,
        })),
        note:
          "Prices are grouped by line. A better price at a different line is a different bet, not a better one.",
      }, 200, CACHE);
    }

    // --------------------------------------------------------- consensus
    if (req.method === "GET" && path === "/v1/nfl/consensus") {
      const eventId = u.searchParams.get("event");
      if (eventId && !isUuid(eventId)) {
        return err("invalid_payload", "event must be a uuid.", 422);
      }
      if (eventId) {
        const game = await oddsEventPayload({ eventId, includeBooks: false });
        if (!game) return err("not_found", "No odds for that game.", 404);
        return json({
          ...envelope(await feedPolledAt(), stale, LEAGUE, await feedProvider(),
            game.last_odds_at as string | null),
          event_id: game.event_id,
          home: game.home,
          away: game.away,
          consensus: game.consensus,
        }, 200, CACHE);
      }
      const { data, games } = await boardInWindow(u, false, 40);
      return json({
        ...envelope(data?.last_poll_at as string | null, stale, LEAGUE,
          providerOf(data?.provider, cfg), data?.last_odds_at as string | null),
        games: games.map((g) => ({
          event_id: g.event_id,
          home: g.home,
          away: g.away,
          commence_time: g.commence_time,
          consensus: g.consensus,
        })),
      }, 200, CACHE);
    }

    // --------------------------------- closing line for a Collective game
    // What the Results screen prefills, and what a CLV calculation must use.
    // Returns available:false until the market has actually closed.
    let m = path.match(/^\/v1\/nfl\/closing\/([0-9a-f-]{36})$/i);
    if (req.method === "GET" && m) {
      const out = await rpc<Record<string, unknown> | null>("odds_closing_for_game", {
        p_game_id: m[1],
      });
      return json(out ?? { available: false, reason: "unknown" }, 200, NO_STORE);
    }

    // ------------------------------------------------- one game's history
    m = path.match(/^\/v1\/nfl\/odds\/([0-9a-f-]{36})\/history$/i);
    if (req.method === "GET" && m) {
      if (!isUuid(m[1])) return err("invalid_payload", "event must be a uuid.", 422);
      const data = await oddsHistory({
        eventId: m[1],
        market: u.searchParams.get("market"),
        book: u.searchParams.get("book"),
        outcome: u.searchParams.get("outcome"),
        limit: Math.min(2000, Math.max(1, num(u.searchParams.get("limit"), 500))),
      });
      const points = (data?.points ?? []) as { at?: string }[];
      const last = points.length ? points[points.length - 1].at ?? null : null;
      return json({
        ...envelope(await feedPolledAt(), stale, LEAGUE, await feedProvider(), last),
        ...data,
        note: "Every stored state, oldest first. Unchanged polls are not stored, so each point is a real move.",
      }, 200, CACHE);
    }

    // ------------------------------------------------------- one game
    // Accepts our event id or the Collective's own game id, so a model page
    // can look up the market without knowing the odds layer's identifiers.
    m = path.match(/^\/v1\/nfl\/odds\/([0-9a-f-]{36})$/i);
    if (req.method === "GET" && m) {
      const byEvent = await oddsEventPayload({ eventId: m[1], includeBooks: true });
      const game = byEvent ?? await oddsEventPayload({ gameId: m[1], includeBooks: true });
      if (!game) return err("not_found", "No odds for that game.", 404);
      return json({
        ...envelope(await feedPolledAt(), stale, LEAGUE, await feedProvider(),
          game.last_odds_at as string | null),
        game,
      }, 200, CACHE);
    }

    m = path.match(/^\/v1\/nfl\/game\/([0-9a-f-]{36})$/i);
    if (req.method === "GET" && m) {
      const game = await oddsEventPayload({ gameId: m[1], includeBooks: true });
      if (!game) {
        return json({
          ...envelope(await feedPolledAt(), stale, LEAGUE),
          game: null,
          reason: "no_linked_odds_event",
        }, 200, NO_STORE);
      }
      return json({
        ...envelope(await feedPolledAt(), stale, LEAGUE, await feedProvider(),
          game.last_odds_at as string | null),
        game,
      }, 200, CACHE);
    }

    // ------------------------------------------------- assistant snapshot
    // A compact, self-describing view of the current market for a research
    // assistant to read. It exists so an assistant answers from stored data
    // instead of from memory: every number is labelled with its book, its
    // capture time, and its freshness, and when there is nothing stored the
    // payload says so rather than returning an empty shell that could be
    // mistaken for "no line".
    if (req.method === "GET" && path === "/v1/nfl/assistant") {
      const { data, games } = await boardInWindow(u, true, 32);
      const env = envelope(
        data?.last_poll_at as string | null,
        num(data?.stale_after_seconds, stale),
        LEAGUE,
        providerOf(data?.provider, cfg),
        data?.last_odds_at as string | null,
      );
      return json({
        ...env,
        instructions: env.state === "unavailable"
          ? "No current NFL odds are stored. Say that the market is unavailable. Do not state a spread, total, or moneyline from memory."
          : `Answer only from the games below. Every price names its book and capture time. The feed was last updated ${
            relativeAge(env.age_seconds ?? 0)
          }. If a number is not present here, say it is not available rather than estimating it.`,
        definitions: {
          spread: "Home convention. A negative spread means the home team is favoured.",
          consensus_spread: "Median main line across retail books. Sharp books are reported separately.",
          consensus_moneyline: "Median of de-vigged two-way probabilities. American prices are never averaged.",
          best_price: "Best price within a line. Prices at different lines are different bets and are not ranked against each other.",
          opening: "Median of each book's first stored price.",
          closing: "Written only after kickoff. Absent means the market has not closed.",
        },
        count: games.length,
        games,
      }, 200, CACHE);
    }

    const known = [
      "/v1/nfl/status",
      "/v1/nfl/games",
      "/v1/nfl/odds",
      "/v1/nfl/odds/best",
      "/v1/nfl/consensus",
      "/v1/nfl/books",
      "/v1/nfl/assistant",
    ];
    if (known.includes(path)) {
      return err("method_not_allowed", "Wrong method for this route.", 405);
    }
    return err("not_found", `No such route: ${req.method} ${path}`, 404, { known });
  } catch (e) {
    if (e instanceof RpcError) console.error("collective_odds rpc failure:", e.message, e.body);
    else console.error("collective_odds failure:", e);
    // The site must stay usable when odds are not. Read failures degrade to
    // an explicit "unavailable" envelope rather than a broken page.
    return json({
      ...envelope(null, 900, LEAGUE),
      error: { code: "server_error", message: "Odds are temporarily unavailable.", details: null },
      games: [],
    }, 200, NO_STORE);
  }
});
