// collective_odds_ingest - SELF-CONTAINED BUNDLE for the Supabase dashboard editor.
// Generated from supabase/functions/ by tools/collective/bundle_functions.py.
// Do not edit this file: edit the sources and regenerate.
// Paste this whole file as index.ts for a function named exactly: collective_odds_ingest
// IMPORTANT: keep "Enforce JWT verification" ON for this function.

// ---------- inlined _shared/env.ts ----------
// Shared environment access for Collective edge functions.
// SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, and SUPABASE_ANON_KEY are injected
// by the Supabase runtime. COLLECTIVE_BASE_URL is an optional secret that
// points at the public site root and defaults to production.

const SB_URL: string = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY: string = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const ANON_KEY: string = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
const BASE_URL: string = Deno.env.get("COLLECTIVE_BASE_URL") ?? "https://edgedesksports.com";

// ---------- inlined _shared/http.ts ----------
// Shared HTTP helpers: JSON responses, the contract error shape, CORS, and
// subpath routing. Every Collective edge function builds its responses here so
// the error taxonomy and CORS behavior stay identical across functions.

function corsHeaders(origin = "*"): Record<string, string> {
  const headers: Record<string, string> = {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers":
      "authorization, apikey, content-type, x-collective-key, x-client-info",
    "Access-Control-Max-Age": "86400",
  };
  if (origin !== "*") {
    headers["Vary"] = "Origin";
  }
  return headers;
}

function json(
  body: unknown,
  status = 200,
  headers: Record<string, string> = {},
): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      ...corsHeaders(),
      ...headers,
    },
  });
}

// Error response in the contract shape { error: { code, message, details } }.
// details is always present, null when there is nothing row-level to report.
function err(
  code: string,
  message: string,
  status: number,
  details?: unknown,
): Response {
  return json({ error: { code, message, details: details ?? null } }, status);
}

// Returns a 204 Response for OPTIONS requests, else null.
function preflight(req: Request, origin = "*"): Response | null {
  if (req.method !== "OPTIONS") return null;
  return new Response(null, { status: 204, headers: corsHeaders(origin) });
}

// Path after /functions/v1/<fnName>, normalized. Works both behind the
// production gateway (/functions/v1/<fnName>/...) and when served locally
// (/<fnName>/...). "" becomes "/", duplicate slashes collapse, and a
// trailing slash is stripped except on the root.
function subpath(req: Request, fnName: string): string {
  const pathname = new URL(req.url).pathname;
  const marker = `/${fnName}`;
  const idx = pathname.indexOf(marker);
  let rest = idx >= 0 ? pathname.slice(idx + marker.length) : pathname;
  if (!rest.startsWith("/")) rest = `/${rest}`;
  rest = rest.replace(/\/{2,}/g, "/");
  if (rest.length > 1 && rest.endsWith("/")) rest = rest.slice(0, -1);
  return rest;
}

// ---------- inlined _shared/db.ts ----------
// Shared database access. Edge functions never talk SQL: they call the
// SECURITY DEFINER RPCs in the collective schema through PostgREST with the
// service role key. RPCs return jsonb outcome objects like { ok: true, ... }
// or { ok: false, code: "token_expired", message: "..." }; callers translate
// ok:false codes to the HTTP error taxonomy. RpcError means an unexpected
// database failure and maps to 500 server_error (log it, never leak the body).

class RpcError extends Error {
  status: number;
  body: string;

  constructor(fn: string, status: number, body: string) {
    super(`rpc ${fn} failed with status ${status}`);
    this.name = "RpcError";
    this.status = status;
    this.body = body;
  }
}

async function rpc<T = unknown>(
  fn: string,
  args: Record<string, unknown>,
): Promise<T> {
  const res = await fetch(`${SB_URL}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: {
      "apikey": SERVICE_KEY,
      "Authorization": `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
      "Content-Profile": "collective",
    },
    body: JSON.stringify(args),
  });
  const text = await res.text();
  if (!res.ok) {
    throw new RpcError(fn, res.status, text);
  }
  if (text === "") {
    return null as T;
  }
  return JSON.parse(text) as T;
}

// ---------- inlined _shared/auth.ts ----------
// Shared JWT auth. Bearer tokens are validated against Supabase Auth by
// calling /auth/v1/user; the JWT is never decoded locally, so revoked or
// expired sessions fail closed. Admin checks compare the user id against the
// admin.user_ids config list via the get_config RPC.

async function getUser(
  req: Request,
): Promise<{ id: string; email: string | null } | null> {
  const authz = req.headers.get("authorization") ?? "";
  if (!/^Bearer\s+\S+/i.test(authz)) return null;
  let res: Response;
  try {
    res = await fetch(`${SB_URL}/auth/v1/user`, {
      headers: {
        "apikey": ANON_KEY,
        "Authorization": authz,
      },
    });
  } catch (e) {
    console.error("auth.getUser: auth service unreachable:", e);
    return null;
  }
  if (!res.ok) return null;
  const user = await res.json().catch(() => null) as
    | { id?: string; email?: string | null }
    | null;
  if (!user || typeof user.id !== "string" || user.id.length === 0) return null;
  return { id: user.id, email: typeof user.email === "string" ? user.email : null };
}

// getUser plus membership of admin.user_ids. Returns the user, or an err()
// Response (401 invalid_key or 403 forbidden) ready to return to the caller.
async function requireAdmin(
  req: Request,
): Promise<{ id: string; email: string | null } | Response> {
  const user = await getUser(req);
  if (!user) {
    return err("invalid_key", "A valid signed-in session is required.", 401);
  }
  const cfg = await rpc<unknown>("get_config", { p_key: "admin.user_ids" });
  const ids = Array.isArray(cfg) ? cfg.filter((v) => typeof v === "string") : [];
  if (!ids.includes(user.id)) {
    return err("forbidden", "This account is not an administrator.", 403);
  }
  return user;
}

// ---------- inlined _shared/odds_api.ts ----------
// Shared odds read helpers and the freshness envelope.
//
// Every odds payload the Collective serves carries the same three facts:
// where the number came from, when it was last updated, and whether that
// counts as current. A surface that cannot say when a price was captured is
// not allowed to display it as live, so this envelope is mandatory rather
// than decorative.

type Freshness = "live" | "stale" | "unavailable";

interface OddsEnvelope {
  source: { provider: string; league: string };
  /** When the feed was last confirmed current: the last successful poll. */
  last_updated: string | null;
  /** When a price last actually moved. Not the same question, and not what
   *  freshness is judged on — unchanged polls write nothing by design, so a
   *  quiet market would otherwise read as a broken feed. */
  last_change_at: string | null;
  age_seconds: number | null;
  state: Freshness;
  stale_after_seconds: number;
  /** Present only when state is not "live": a sentence a UI can show as-is. */
  notice?: string;
}

const DEFAULT_STALE_AFTER = 900;

/**
 * Classifies the feed.
 *   live        polled successfully inside the freshness window
 *   stale       the last successful poll is older than the window. Prices are
 *               still returned, labelled, with their age. Never relabelled
 *               current.
 *   unavailable nothing to show. No number is invented to fill the gap.
 *
 * lastPolled, not the newest price. A market that has not moved since Tuesday
 * is a quiet market, not a dead feed, and calling it stale would train people
 * to ignore the one label that is supposed to mean something.
 */
function envelope(
  lastPolled: string | null | undefined,
  staleAfterSeconds: number | null | undefined,
  league = "nfl",
  provider = "oddsblaze",
  lastChangeAt: string | null | undefined = null,
): OddsEnvelope {
  const lastUpdated = lastPolled ?? null;
  const changed = lastChangeAt ?? null;
  const staleAfter = Number(staleAfterSeconds) > 0
    ? Number(staleAfterSeconds)
    : DEFAULT_STALE_AFTER;
  if (!lastUpdated) {
    return {
      source: { provider, league },
      last_updated: null,
      last_change_at: changed,
      age_seconds: null,
      state: "unavailable",
      stale_after_seconds: staleAfter,
      notice: "Odds unavailable.",
    };
  }
  const ms = Date.parse(lastUpdated);
  if (!Number.isFinite(ms)) {
    return {
      source: { provider, league },
      last_updated: null,
      last_change_at: changed,
      age_seconds: null,
      state: "unavailable",
      stale_after_seconds: staleAfter,
      notice: "Odds unavailable.",
    };
  }
  const age = Math.max(0, Math.round((Date.now() - ms) / 1000));
  if (age <= staleAfter) {
    return {
      source: { provider, league },
      last_updated: lastUpdated,
      last_change_at: changed,
      age_seconds: age,
      state: "live",
      stale_after_seconds: staleAfter,
    };
  }
  return {
    source: { provider, league },
    last_updated: lastUpdated,
    last_change_at: changed,
    age_seconds: age,
    state: "stale",
    stale_after_seconds: staleAfter,
    notice: `Odds may be out of date. Last polled ${relativeAge(age)}.`,
  };
}

function relativeAge(seconds: number): string {
  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 5400) return `${Math.round(seconds / 60)} minutes ago`;
  if (seconds < 172800) return `${Math.round(seconds / 3600)} hours ago`;
  return `${Math.round(seconds / 86400)} days ago`;
}

// ------------------------------------------------------------------ settings
// The odds* prefixes on the read helpers below are deliberate: the dashboard
// deploys these functions as one flattened script, where a top level
// `history` or `status` would sit alongside the DOM globals of the same name.
let settingsCache: { at: number; values: Record<string, unknown> } | null = null;
const SETTINGS_TTL_MS = 60_000;

/** Reads odds settings, cached briefly so a slate render does not make one
 *  round trip per tunable. */
async function settings(keys: string[]): Promise<Record<string, unknown>> {
  const now = Date.now();
  if (settingsCache && now - settingsCache.at < SETTINGS_TTL_MS) {
    const have = keys.every((k) => k in settingsCache!.values);
    if (have) return settingsCache.values;
  }
  const values: Record<string, unknown> = { ...(settingsCache?.values ?? {}) };
  await Promise.all(keys.map(async (k) => {
    try {
      values[k] = await rpc<unknown>("odds_get_setting", { p_key: k });
    } catch {
      values[k] = null;
    }
  }));
  settingsCache = { at: now, values };
  return values;
}

/**
 * A number, or the fallback.
 *
 * The null check is the whole point: Number(null) is 0, and 0 is finite, so a
 * bare Number.isFinite guard silently turns every absent value into zero.
 * URLSearchParams.get returns null for a missing parameter, so ?limit,
 * ?days and ?week all became 0 — a one-game board, a one-day window, and a
 * cadence of zero seconds when a setting was missing.
 */
function num(v: unknown, fallback: number): number {
  if (v === null || v === undefined || v === "") return fallback;
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function strList(v: unknown, fallback: string[]): string[] {
  if (Array.isArray(v)) {
    const out = v.filter((x): x is string => typeof x === "string" && x.length > 0);
    if (out.length) return out;
  }
  return fallback;
}

/** Board payload straight from SQL. The math is not repeated here. */
async function oddsBoard(args: {
  league?: string;
  from?: string | null;
  to?: string | null;
  includeBooks?: boolean;
  limit?: number;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_board", {
    p_league: args.league ?? "nfl",
    p_from: args.from ?? null,
    p_to: args.to ?? null,
    p_include_books: args.includeBooks !== false,
    p_limit: args.limit ?? 40,
  });
}

async function oddsEventPayload(args: {
  eventId?: string | null;
  gameId?: string | null;
  includeBooks?: boolean;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_event", {
    p_event_id: args.eventId ?? null,
    p_game_id: args.gameId ?? null,
    p_include_books: args.includeBooks !== false,
  });
}

async function oddsHistory(args: {
  eventId: string;
  market?: string | null;
  book?: string | null;
  outcome?: string | null;
  limit?: number;
}): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_history", {
    p_event_id: args.eventId,
    p_market: args.market ?? null,
    p_book: args.book ?? null,
    p_outcome: args.outcome ?? null,
    p_limit: args.limit ?? 500,
  });
}

async function oddsStatus(league = "nfl"): Promise<Record<string, unknown> | null> {
  return await rpc<Record<string, unknown> | null>("odds_status", { p_league: league });
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function isUuid(s: string): boolean {
  return UUID_RE.test(s);
}

// ---------- inlined _shared/odds_provider.ts ----------
// The odds provider contract.
//
// Everything upstream of this file is vendor-specific; everything downstream
// speaks only these types. Adding a second provider means writing one more
// module that returns NormalizedSlate — no other file changes, because
// nothing else in the Collective ever sees a vendor payload.
//
// The credential never appears in any of these types. It is read from the
// environment inside a provider implementation and used only to build the
// outbound request.

/** Canonical markets. New families (props, futures) become new ids here and
 *  new rows in odds.markets; the pipeline itself does not change. */
type MarketId =
  | "moneyline"
  | "spread"
  | "total"
  | "team_total"
  | "alternate_spread"
  | "alternate_total"
  | string;

/** Which side of a market a price belongs to. */
type Outcome = "home" | "away" | "over" | "under" | "draw" | string;

/** One price, at one book, on one side of one market, at one moment. */
interface NormalizedOdd {
  book: string;
  market: MarketId;
  outcome: Outcome;
  outcome_label?: string | null;
  /** Points. Null for moneyline. Home convention for spreads: negative means
   *  the home team is favoured. */
  line?: number | null;
  /** American odds. -110, +135. Never a decimal or a probability. */
  price: number;
  is_live?: boolean;
  is_main?: boolean;
  /** The vendor row this was derived from, kept for audit. Bounded by the
   *  caller so a payload cannot balloon the snapshot table. */
  raw?: unknown;
}

/** One game, named in our terms, with the provider's id kept alongside as a
 *  mapping rather than as identity. */
interface NormalizedEvent {
  provider_event_id: string | null;
  home: string;
  away: string;
  home_name?: string | null;
  away_name?: string | null;
  commence_time: string;
  season?: number | null;
  week?: number | null;
  status?: string | null;
  is_live?: boolean;
  provider_updated_at?: string | null;
  odds: NormalizedOdd[];
}

/** What a provider hands back for one league, plus an honest account of what
 *  it could not map. Unmapped rows are reported, never silently dropped and
 *  never filled in with a guess. */
interface NormalizedSlate {
  provider: string;
  league: string;
  fetched_at: string;
  provider_updated_at: string | null;
  events: NormalizedEvent[];
  books_ok: string[];
  books_failed: { book: string; reason: string }[];
  /** Rows whose shape we did not recognise. Carries the row's KEY NAMES and
   *  a redacted sample, never a credential, so an API change is diagnosable
   *  from the run record alone. */
  unmapped: UnmappedRow[];
  counts: { events: number; odds: number; unmapped: number };
  /** Present only for metered providers. */
  quota?: ProviderQuota;
}

/** Credit accounting a metered provider reports alongside its data. Numbers
 *  only, never a raw header value. A provider that does not meter leaves every
 *  field null, and the caller treats "unknown" as "no budget information",
 *  never as "unlimited". */
interface ProviderQuota {
  /** Credits left in the current billing period. */
  remaining: number | null;
  /** Credits spent so far in the current billing period. */
  used: number | null;
  /** What the request that produced this slate cost. Authoritative: it is the
   *  provider's own accounting, not our prediction of it. */
  last_cost: number | null;
}

interface UnmappedRow {
  book: string;
  reason: string;
  keys: string[];
  sample?: unknown;
}

interface FetchOptions {
  league: string;
  books: string[];
  markets: MarketId[];
  /** true = live only, false = pregame only, undefined = both. */
  live?: boolean;
  /** true = main lines only. Alternates are off by default; turning them on
   *  is a settings change, not a code change. */
  mainOnly?: boolean;
  timeoutMs?: number;
  booksPerRequest?: number;
}

/** A provider is a named fetcher that returns canonical data. */
interface OddsProvider {
  readonly id: string;
  readonly name: string;
  /** True when the credential this provider needs is present. Checked before
   *  a run so a missing secret is a clear message, not a 401 from a vendor. */
  isConfigured(): boolean;
  fetchSlate(opts: FetchOptions): Promise<NormalizedSlate>;
  /** One request, reporting the observed response STRUCTURE rather than the
   *  data: endpoint reachability, status, and the key paths that came back.
   *  Used to confirm the integration against the live API without printing
   *  anything sensitive. */
  probe(opts: FetchOptions): Promise<ProbeResult>;
}

interface ProbeResult {
  provider: string;
  ok: boolean;
  /** The URL with every credential removed. Safe to log and to display. */
  url_redacted: string;
  http_status: number | null;
  /** Key paths seen in the response, e.g. "events[].odds[].selection.line". */
  observed_shape: string[];
  sample_event: unknown;
  sample_odd: unknown;
  counts: { events: number; odds: number };
  error: string | null;
  /** What the adapter made of the sample: proof the mapping works against
   *  the real feed, or a precise account of where it did not. */
  mapping: { mapped: number; unmapped: UnmappedRow[] };
  /** Present only for metered providers. */
  quota?: ProviderQuota;
}

const REGISTRY = new Map<string, OddsProvider>();

function registerProvider(p: OddsProvider): void {
  REGISTRY.set(p.id, p);
}

function getProvider(id: string): OddsProvider | null {
  return REGISTRY.get(id) ?? null;
}

function listProviders(): { id: string; name: string; configured: boolean }[] {
  return [...REGISTRY.values()].map((p) => ({
    id: p.id,
    name: p.name,
    configured: p.isConfigured(),
  }));
}

// ---------- inlined _shared/odds_normalize.ts ----------
// Vendor-agnostic normalization primitives.
//
// These are pure functions with no network and no environment access, which
// is what makes them testable outside Deno (see tests/collective/normalize_test.mjs).
// Each one has the same rule: recognise what it understands, and return null
// for anything else so the caller can report it. Nothing here ever guesses a
// number into existence.

/** lowercase, alphanumerics only. The comparison key for every fuzzy match. */
function normKey(s: unknown): string {
  return String(s ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

/**
 * American odds from whatever the wire carried: -110, "-110", "+135", "EVEN".
 * Returns null for anything that is not a usable American price, including
 * the impossible band between -99 and +99 — a "price" of 0 or 5 means the
 * field was not American odds, and inventing one would poison every downstream
 * probability.
 */
function parseAmericanPrice(v: unknown): number | null {
  if (v === null || v === undefined) return null;
  if (typeof v === "string") {
    const t = v.trim();
    if (/^(even|ev|evens|pk)$/i.test(t)) return 100;
    const cleaned = t.replace(/[\s,]/g, "");
    if (!/^[+-]?\d+(\.\d+)?$/.test(cleaned)) return null;
    v = Number(cleaned);
  }
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  const n = Math.round(v);
  if (n >= 100 || n <= -100) return n;
  return null;
}

/**
 * A points value: "-3.5", "+3.5", 3.5, "PK"/"Pick'em" (zero). Returns null
 * when there is no line, which is correct for a moneyline.
 */
function parseLine(v: unknown): number | null {
  if (v === null || v === undefined || v === "") return null;
  if (typeof v === "string") {
    const t = v.trim();
    if (/^(pk|pick|pickem|pick'?em|even)$/i.test(t)) return 0;
    const cleaned = t.replace(/[\s,]/g, "").replace(/^([+-])?(o|u|over|under)/i, "$1");
    if (!/^[+-]?\d+(\.\d+)?$/.test(cleaned)) return null;
    v = Number(cleaned);
  }
  if (typeof v !== "number" || !Number.isFinite(v)) return null;
  return v;
}

/** Decimal odds from American. Used for price comparison, where "bigger is
 *  better" holds and American odds do not sort. */
function americanToDecimal(price: number): number | null {
  if (!Number.isFinite(price)) return null;
  if (price >= 100) return 1 + price / 100;
  if (price <= -100) return 1 + 100 / Math.abs(price);
  return null;
}

function americanToProb(price: number): number | null {
  const d = americanToDecimal(price);
  return d === null ? null : 1 / d;
}

/** Two-way multiplicative de-vig. The only honest way to combine moneylines:
 *  raw American prices are never averaged. */
function devigTwoWay(pa: number, pb: number): number | null {
  if (!Number.isFinite(pa) || !Number.isFinite(pb) || pa + pb <= 0) return null;
  return pa / (pa + pb);
}

// -------------------------------------------------------------- markets
// Vendors label markets for humans ("Point Spread"), so match on the label.
// A name that matches nothing is reported as unmapped rather than forced into
// the nearest bucket.
const MARKET_ALIASES: Record<string, MarketId> = {
  moneyline: "moneyline",
  moneylines: "moneyline",
  money: "moneyline",
  ml: "moneyline",
  h2h: "moneyline",
  headtohead: "moneyline",
  matchupwinner: "moneyline",
  gamelines: "moneyline",

  pointspread: "spread",
  spread: "spread",
  spreads: "spread",
  handicap: "spread",
  pointhandicap: "spread",
  linespread: "spread",
  gamespread: "spread",

  totalpoints: "total",
  total: "total",
  totals: "total",
  overunder: "total",
  gametotal: "total",
  totalpointsoverunder: "total",

  teamtotal: "team_total",
  teamtotalpoints: "team_total",
  alternatepointspread: "alternate_spread",
  alternatespread: "alternate_spread",
  alternatetotal: "alternate_total",
  alternatetotalpoints: "alternate_total",
};

function canonicalMarket(raw: unknown): MarketId | null {
  const k = normKey(raw);
  if (!k) return null;
  return MARKET_ALIASES[k] ?? null;
}

/** Markets we store as game lines. Everything else is registered but not
 *  treated as a game line by the read API. */
const GAME_MARKETS: MarketId[] = ["moneyline", "spread", "total"];

// -------------------------------------------------------------- outcomes
const OVER_WORDS = new Set(["over", "o", "above", "more"]);
const UNDER_WORDS = new Set(["under", "u", "below", "less"]);

/**
 * Which side a price sits on.
 *
 * For totals this is over/under. For spreads and moneylines it is home/away,
 * decided by an explicit side field when the vendor gives one, and otherwise
 * by matching the selection text against the two team names we already know.
 * If neither works the answer is null: an unattributed price is useless and
 * a coin-flip guess would silently invert a whole market.
 */
function resolveOutcome(args: {
  market: MarketId;
  side?: unknown;
  selectionName?: unknown;
  homeNames: string[];
  awayNames: string[];
}): Outcome | null {
  const { market, side, selectionName, homeNames, awayNames } = args;
  const sideKey = normKey(side);
  const nameKey = normKey(selectionName);

  if (market === "total" || market === "team_total" || market === "alternate_total") {
    if (OVER_WORDS.has(sideKey)) return "over";
    if (UNDER_WORDS.has(sideKey)) return "under";
    if (OVER_WORDS.has(nameKey)) return "over";
    if (UNDER_WORDS.has(nameKey)) return "under";
    // "Over 47.5" / "Under 47.5"
    if (/^over/.test(nameKey)) return "over";
    if (/^under/.test(nameKey)) return "under";
    return null;
  }

  if (sideKey === "home") return "home";
  if (sideKey === "away") return "away";
  if (sideKey === "draw" || sideKey === "tie") return "draw";

  const home = new Set(homeNames.map(normKey).filter(Boolean));
  const away = new Set(awayNames.map(normKey).filter(Boolean));
  if (!nameKey) return null;
  if (home.has(nameKey)) return "home";
  if (away.has(nameKey)) return "away";

  // Vendors append the number: "Kansas City Chiefs -3.5" normalizes to
  // "kansascitychiefs35", so the trailing digits come off before comparing.
  const stripped = nameKey.replace(/\d+$/, "");
  if (home.has(stripped)) return "home";
  if (away.has(stripped)) return "away";

  // Loose prefix matching, with two guards that a naive version does not have.
  //
  // MIN_PREFIX: a two-letter abbreviation prefix-matches half the league.
  // With New England at home and New Orleans away, a selection of
  // "New Orleans" normalizes to "neworleans", which starts with "ne" — and
  // the away price gets booked as the home price, silently inverting the
  // market. Short aliases only ever match exactly, above.
  //
  // Ambiguity: if a name matches both sides, no answer is better than a
  // coin flip, because the wrong one inverts a market and still looks
  // perfectly plausible on the page.
  // Either string may be the longer one: a vendor may send "Kansas City
  // Chiefs" against our "KC", or just "New Orleans" against our "New Orleans
  // Saints". So a prefix in either direction counts, but the SHORTER of the
  // two has to carry the minimum length — that is what stops "ne" matching
  // "neworleans".
  const MIN_PREFIX = 4;
  const prefixMatch = (a: string, k: string): boolean =>
    Math.min(a.length, k.length) >= MIN_PREFIX && (k.startsWith(a) || a.startsWith(k));
  const hit = (set: Set<string>): boolean => {
    for (const a of set) {
      if (prefixMatch(a, nameKey) || prefixMatch(a, stripped)) return true;
    }
    return false;
  };
  const isHome = hit(home);
  const isAway = hit(away);
  if (isHome && !isAway) return "home";
  if (isAway && !isHome) return "away";
  return null;
}

/** The trailing number in a selection label: "Chiefs -3.5" -> -3.5,
 *  "Over 47.5" -> 47.5. Last resort only, after every explicit field. */
function lineFromLabel(label: unknown): number | null {
  const s = String(label ?? "").trim();
  const m = s.match(/([+-]?\d+(?:\.\d+)?)\s*$/);
  return m ? parseLine(m[1]) : null;
}

/** First non-null among a list of candidate accessors. Lets an adapter list
 *  the documented field, then the documented alternatives, in priority order
 *  without a pile of nested ternaries. */
function firstOf<T>(...candidates: (T | null | undefined)[]): T | null {
  for (const c of candidates) {
    if (c !== null && c !== undefined) return c;
  }
  return null;
}

// -------------------------------------------------------------- diagnostics

/** Key paths present in a value, e.g. "events[].odds[].selection.line".
 *  Structure only: no values are included, so this is always safe to log. */
function shapePaths(value: unknown, maxDepth = 6, prefix = ""): string[] {
  const out = new Set<string>();
  walk(value, prefix, 0);
  function walk(v: unknown, path: string, depth: number): void {
    if (depth > maxDepth) return;
    if (Array.isArray(v)) {
      if (path) out.add(`${path}[]`);
      // One element is enough to describe the shape of a homogeneous array.
      if (v.length) walk(v[0], `${path}[]`, depth + 1);
      return;
    }
    if (v && typeof v === "object") {
      for (const k of Object.keys(v as Record<string, unknown>)) {
        const p = path ? `${path}.${k}` : k;
        const child = (v as Record<string, unknown>)[k];
        if (child && typeof child === "object") walk(child, p, depth + 1);
        else out.add(p);
      }
      return;
    }
    if (path) out.add(path);
  }
  return [...out].sort();
}

/** Removes anything credential-shaped from a URL before it is logged, stored,
 *  or returned. Query keys are matched by name; the value is replaced, never
 *  truncated to a prefix. */
const SECRET_PARAMS = ["key", "apikey", "api_key", "token", "access_token", "secret"];

function redactUrl(raw: string): string {
  try {
    const u = new URL(raw);
    for (const p of [...u.searchParams.keys()]) {
      if (SECRET_PARAMS.includes(p.toLowerCase())) u.searchParams.set(p, "REDACTED");
    }
    return u.toString();
  } catch {
    return "invalid-url";
  }
}

/** Strips a known secret out of arbitrary text (an error message, a vendor
 *  body) before it reaches a log line or an ingest_runs row. */
function redactSecret(text: string, secret: string | null | undefined): string {
  let out = String(text ?? "");
  if (secret && secret.length >= 6) {
    out = out.split(secret).join("REDACTED");
  }
  return out.replace(
    new RegExp(`([?&](?:${SECRET_PARAMS.join("|")})=)[^&\\s"']+`, "gi"),
    "$1REDACTED",
  );
}

function unmapped(book: string, reason: string, row: unknown): UnmappedRow {
  const keys = row && typeof row === "object" && !Array.isArray(row)
    ? Object.keys(row as Record<string, unknown>)
    : [];
  return { book, reason, keys, sample: sampleOf(row) };
}

/** A bounded, value-bearing sample for diagnosis. Capped so an unmapped-row
 *  report can never grow into a payload dump. */
function sampleOf(row: unknown, maxLen = 400): unknown {
  try {
    const s = JSON.stringify(row);
    if (s === undefined) return null;
    return s.length <= maxLen ? JSON.parse(s) : `${s.slice(0, maxLen)}…`;
  } catch {
    return null;
  }
}

// ---------- inlined _shared/oddsblaze.ts ----------
// OddsBlaze provider.
//
// The ONLY file in the Collective that knows what an OddsBlaze response looks
// like. Everything else consumes NormalizedSlate. Swapping or adding a vendor
// is a sibling of this file plus one registerProvider call.
//
// Wire contract, from the OddsBlaze API documentation (docs.oddsblaze.com):
//
//   GET <base>?key=<API key>&sportsbook=<book id>&league=<league id>
//              [&market=<id or name, comma separated>]
//              [&price=american|decimal|fractional|probability|…]
//              [&live=true|false]   include only live / only pre-match
//              [&main=true|false]   include only main / only alternate lines
//
//   -> { "updated": <timestamp>,
//        "league":     { "id": "nfl", "name": …, "sport": … },
//        "sportsbook": { "id": "draftkings", "name": "DraftKings" },
//        "events": [ { "id": …,
//                      "teams": { "home": { "id", "name", "abbreviation" },
//                                 "away": { … } },
//                      "date": …, "live": <bool>,
//                      "odds": [ { "id", "market", "name", "price", "main",
//                                  "selection": { "name", "side", "line" } } ] } ] }
//
// The credential is read here and here only, from the NFL_ODDS_API_KEY edge
// function secret. It is placed in the query string because that is the
// documented authentication method, and every URL that leaves this module —
// into a log, an error, an ingest_runs row, or a probe response — goes
// through redactUrl or redactSecret first.
//
// Where the documentation lists a field under more than one name, or where a
// vendor may add one, the reader below tries the documented field first and
// the documented alternatives after. A row that matches none of them is
// returned in `unmapped` with its key names, never with a substituted value.

const DEFAULT_BASE = "https://odds.oddsblaze.com/";
const DEFAULT_TIMEOUT_MS = 12000;
/** Concurrent provider requests. Low on purpose: a trial plan is a shared,
 *  rate limited resource and a burst is the fastest way to lose it. */
const CONCURRENCY = 3;

function apiKey(): string {
  return Deno.env.get("NFL_ODDS_API_KEY") ?? "";
}

function baseUrl(): string {
  return Deno.env.get("NFL_ODDS_BASE_URL") ?? DEFAULT_BASE;
}

/** Canonical market id -> the id OddsBlaze uses in its `market` parameter. */
const PROVIDER_MARKET: Record<string, string> = {
  moneyline: "moneyline",
  spread: "point-spread",
  total: "total-points",
  team_total: "team-total",
  alternate_spread: "alternate-point-spread",
  alternate_total: "alternate-total-points",
};

interface ObEvent {
  id?: unknown;
  teams?: { home?: ObTeam; away?: ObTeam };
  home?: unknown;
  away?: unknown;
  date?: unknown;
  start?: unknown;
  live?: unknown;
  status?: unknown;
  odds?: unknown;
}
interface ObTeam {
  id?: unknown;
  name?: unknown;
  abbreviation?: unknown;
  short_name?: unknown;
}

function hasPlayer(v: unknown): boolean {
  if (v === null || v === undefined || v === "") return false;
  if (Array.isArray(v)) return v.length > 0;
  if (typeof v === "object") return Object.keys(v as Record<string, unknown>).length > 0;
  return true;
}

/** The statuses odds.events accepts. A value outside this set violates the
 *  column's CHECK constraint, and because the whole slate is ingested in one
 *  transaction that would abort the batch and lose every price in it — so an
 *  unrecognised vendor status becomes "scheduled" rather than an outage. */
const EVENT_STATUS = new Set(["scheduled", "live", "final", "postponed", "canceled"]);
const STATUS_ALIASES: Record<string, string> = {
  cancelled: "canceled",
  delayed: "postponed",
  suspended: "postponed",
  complete: "final",
  completed: "final",
  finished: "final",
  ended: "final",
  closed: "final",
  inprogress: "live",
  started: "live",
  upcoming: "scheduled",
  pregame: "scheduled",
  notstarted: "scheduled",
};

function normalizeStatus(raw: unknown, live: boolean): string {
  if (live) return "live";
  const k = normKey(raw);
  if (!k) return "scheduled";
  if (EVENT_STATUS.has(k)) return k;
  return STATUS_ALIASES[k] ?? "scheduled";
}

function teamNames(t: ObTeam | undefined): string[] {
  if (!t) return [];
  return [t.name, t.abbreviation, t.short_name]
    .filter((x): x is string => typeof x === "string" && x.length > 0);
}

/** The container the vendor puts the games in. `events` is what the docs
 *  show; `games` is accepted because the same feed is documented under that
 *  name elsewhere. The probe reports which one was actually seen. */
function eventArray(body: unknown): { rows: ObEvent[]; container: string | null } {
  if (!body || typeof body !== "object") return { rows: [], container: null };
  const o = body as Record<string, unknown>;
  for (const key of ["events", "games"]) {
    if (Array.isArray(o[key])) return { rows: o[key] as ObEvent[], container: key };
  }
  return { rows: [], container: null };
}

/**
 * One vendor odds row -> one NormalizedOdd, or an UnmappedRow explaining
 * exactly which part could not be read.
 */
function readOdd(
  row: unknown,
  ctx: { book: string; homeNames: string[]; awayNames: string[]; eventLive: boolean },
): { odd: NormalizedOdd } | { bad: UnmappedRow } {
  if (!row || typeof row !== "object") {
    return { bad: unmapped(ctx.book, "odds row is not an object", row) };
  }
  const r = row as Record<string, unknown>;
  const sel = (r.selection && typeof r.selection === "object" && !Array.isArray(r.selection))
    ? r.selection as Record<string, unknown>
    : null;

  // A player prop carries a player; it is a different family and is skipped
  // here rather than mangled into a game line.
  //
  // Emptiness is checked, not truthiness: `players: []` is a truthy value, so
  // a feed that includes an empty players array on ordinary game lines would
  // have had every single row discarded as a prop.
  if (hasPlayer(r.player) || hasPlayer(r.players)) {
    return { bad: unmapped(ctx.book, "player market, not a game line", row) };
  }

  const market = canonicalMarket(firstOf(r.market, r.market_id, r.market_name));
  if (!market) {
    return { bad: unmapped(ctx.book, `unrecognised market ${JSON.stringify(r.market ?? null)}`, row) };
  }
  if (!GAME_MARKETS.includes(market)) {
    return { bad: unmapped(ctx.book, `market ${market} is not a stored game line`, row) };
  }

  const price = parseAmericanPrice(firstOf(r.price, r.odds, r.american));
  if (price === null) {
    return { bad: unmapped(ctx.book, "no usable American price", row) };
  }

  const selectionName = firstOf<unknown>(
    sel?.name,
    typeof r.selection === "string" ? r.selection : null,
    r.name,
  );
  const outcome = resolveOutcome({
    market,
    side: firstOf<unknown>(sel?.side, r.side, r.selection_side),
    selectionName,
    homeNames: ctx.homeNames,
    awayNames: ctx.awayNames,
  });
  if (!outcome) {
    return { bad: unmapped(ctx.book, "could not attribute the price to a side", row) };
  }

  // Documented field first, documented alternatives next, the label last.
  let line = parseLine(
    firstOf<unknown>(sel?.line, sel?.points, r.points, r.selection_points, r.line, r.handicap),
  );
  if (line === null && market !== "moneyline") {
    line = lineFromLabel(selectionName ?? r.name);
  }
  if (market !== "moneyline" && line === null) {
    return { bad: unmapped(ctx.book, `${market} row carries no line`, row) };
  }
  if (market === "moneyline") line = null;

  // Spreads are stored in home convention: the away number is the mirror of
  // the home number, so an away row keeps its own sign as sent.
  return {
    odd: {
      book: ctx.book,
      market,
      outcome,
      outcome_label: typeof selectionName === "string" ? selectionName : null,
      line,
      price,
      is_live: Boolean(firstOf(r.live, ctx.eventLive)),
      is_main: r.main === undefined ? true : Boolean(r.main),
      raw: sampleOf(row, 600),
    },
  };
}

/** One vendor event -> one NormalizedEvent. Team names are passed through
 *  verbatim; turning them into codes is the database's job, using the alias
 *  table, so there is one place where team identity is decided. */
function readEvent(
  ev: ObEvent,
  ctx: { book: string; providerUpdatedAt: string | null },
): { event: NormalizedEvent | null; bad: UnmappedRow[] } {
  const bad: UnmappedRow[] = [];
  const home = ev.teams?.home ?? (typeof ev.home === "object" ? ev.home as ObTeam : undefined);
  const away = ev.teams?.away ?? (typeof ev.away === "object" ? ev.away as ObTeam : undefined);
  const homeNames = teamNames(home).concat(typeof ev.home === "string" ? [ev.home] : []);
  const awayNames = teamNames(away).concat(typeof ev.away === "string" ? [ev.away] : []);

  const commence = firstOf<unknown>(ev.date, ev.start, (ev as Record<string, unknown>).commence_time);
  if (!homeNames.length || !awayNames.length || !commence) {
    bad.push(unmapped(ctx.book, "event missing teams or kickoff time", ev));
    return { event: null, bad };
  }

  const eventLive = Boolean(ev.live);
  const odds: NormalizedOdd[] = [];
  const rawOdds = Array.isArray(ev.odds) ? ev.odds : [];
  for (const row of rawOdds) {
    const res = readOdd(row, { book: ctx.book, homeNames, awayNames, eventLive });
    if ("odd" in res) odds.push(res.odd);
    else bad.push(res.bad);
  }

  return {
    event: {
      provider_event_id: ev.id === undefined || ev.id === null ? null : String(ev.id),
      home: homeNames[0],
      away: awayNames[0],
      home_name: homeNames[0],
      away_name: awayNames[0],
      commence_time: String(commence),
      status: normalizeStatus(ev.status, eventLive),
      is_live: eventLive,
      provider_updated_at: ctx.providerUpdatedAt,
      odds,
    },
    bad,
  };
}

function buildUrl(book: string, opts: FetchOptions): string {
  const u = new URL(baseUrl());
  u.searchParams.set("key", apiKey());
  u.searchParams.set("sportsbook", book);
  u.searchParams.set("league", opts.league);
  u.searchParams.set("price", "american");
  const markets = opts.markets
    .map((m: MarketId) => PROVIDER_MARKET[m] ?? m)
    .filter(Boolean);
  if (markets.length) u.searchParams.set("market", markets.join(","));
  if (opts.mainOnly) u.searchParams.set("main", "true");
  if (opts.live !== undefined) u.searchParams.set("live", String(opts.live));
  return u.toString();
}

/** Vendor HTTP status -> a stable reason code the ingest run can record and
 *  the dashboard can explain. Bodies are never surfaced. */
function reasonFor(status: number): string {
  if (status === 401 || status === 403) return "invalid_or_unauthorized_key";
  if (status === 402) return "plan_or_trial_expired";
  if (status === 404) return "endpoint_or_league_not_found";
  if (status === 429) return "rate_limited";
  if (status >= 500) return "provider_outage";
  return `provider_http_${status}`;
}

async function fetchBook(
  book: string,
  opts: FetchOptions,
): Promise<{ book: string; body: unknown } | { book: string; reason: string }> {
  const url = buildUrl(book, opts);
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), opts.timeoutMs ?? DEFAULT_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      signal: ctrl.signal,
      headers: { "accept": "application/json" },
    });
    if (!res.ok) {
      // The body may echo the query string, so it is read and discarded
      // rather than propagated.
      await res.text().catch(() => "");
      return { book, reason: reasonFor(res.status) };
    }
    const text = await res.text();
    try {
      return { book, body: JSON.parse(text) };
    } catch {
      return { book, reason: "malformed_json" };
    }
  } catch (e) {
    const msg = redactSecret(String((e as Error)?.message ?? e), apiKey());
    return { book, reason: /abort/i.test(msg) ? "timeout" : `request_failed: ${msg.slice(0, 120)}` };
  } finally {
    clearTimeout(timer);
  }
}

/** Runs tasks with a fixed ceiling on how many are in flight. */
async function pooled<T, R>(items: T[], limit: number, fn: (t: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  const workers = new Array(Math.min(limit, items.length)).fill(0).map(async () => {
    for (;;) {
      const i = next++;
      if (i >= items.length) return;
      out[i] = await fn(items[i]);
    }
  });
  await Promise.all(workers);
  return out;
}

/**
 * Merges per-book responses into one slate. Books are fetched separately (the
 * vendor takes one sportsbook per request) but a game is a game: the same
 * event across books collapses onto one entry keyed by teams and kickoff, so
 * the database receives one event carrying every book's prices.
 */
function mergeBooks(
  parts: { book: string; body: unknown }[],
): { events: NormalizedEvent[]; unmapped: UnmappedRow[]; providerUpdatedAt: string | null } {
  const byKey = new Map<string, NormalizedEvent>();
  const bad: UnmappedRow[] = [];
  let updated: string | null = null;

  for (const part of parts) {
    const body = part.body as Record<string, unknown> | null;
    const partUpdated = body && typeof body.updated === "string" ? body.updated : null;
    if (partUpdated && (!updated || partUpdated > updated)) updated = partUpdated;

    const { rows, container } = eventArray(body);
    if (!container) {
      bad.push(unmapped(part.book, "response carried no events array", body));
      continue;
    }
    for (const ev of rows) {
      const { event, bad: evBad } = readEvent(ev, {
        book: part.book,
        providerUpdatedAt: partUpdated,
      });
      bad.push(...evBad);
      if (!event) continue;
      const key = [event.home, event.away, event.commence_time.slice(0, 10)]
        .map((s) => s.toLowerCase().replace(/[^a-z0-9]/g, "")).join("|");
      const existing = byKey.get(key);
      if (existing) {
        existing.odds.push(...event.odds);
        existing.is_live = existing.is_live || event.is_live;
        // Keep the first provider id seen; the mapping table holds the rest.
        if (!existing.provider_event_id) existing.provider_event_id = event.provider_event_id;
      } else {
        byKey.set(key, event);
      }
    }
  }
  return { events: [...byKey.values()], unmapped: bad, providerUpdatedAt: updated };
}

const oddsBlazeProvider: OddsProvider = {
  id: "oddsblaze",
  name: "OddsBlaze",

  isConfigured(): boolean {
    return apiKey().length > 0;
  },

  async fetchSlate(opts: FetchOptions): Promise<NormalizedSlate> {
    const fetched_at = new Date().toISOString();
    if (!this.isConfigured()) {
      return {
        provider: "oddsblaze",
        league: opts.league,
        fetched_at,
        provider_updated_at: null,
        events: [],
        books_ok: [],
        books_failed: opts.books.map((b) => ({ book: b, reason: "missing_api_key" })),
        unmapped: [],
        counts: { events: 0, odds: 0, unmapped: 0 },
      };
    }

    const results = await pooled(opts.books, CONCURRENCY, (b) => fetchBook(b, opts));
    const ok = results.filter((r): r is { book: string; body: unknown } => "body" in r);
    const failed = results
      .filter((r): r is { book: string; reason: string } => "reason" in r)
      .map((r) => ({ book: r.book, reason: r.reason }));

    const merged = mergeBooks(ok);
    const oddsCount = merged.events.reduce((n, e) => n + e.odds.length, 0);
    return {
      provider: "oddsblaze",
      league: opts.league,
      fetched_at,
      provider_updated_at: merged.providerUpdatedAt,
      events: merged.events,
      books_ok: ok.map((r) => r.book),
      books_failed: failed,
      // Bounded: a systematic shape change produces one report per row, and
      // the run record is not the place to store thousands of them.
      unmapped: merged.unmapped.slice(0, 25),
      counts: { events: merged.events.length, odds: oddsCount, unmapped: merged.unmapped.length },
    };
  },

  async probe(opts: FetchOptions): Promise<ProbeResult> {
    const book = opts.books[0] ?? "draftkings";
    const url = buildUrl(book, opts);
    const base: ProbeResult = {
      provider: "oddsblaze",
      ok: false,
      url_redacted: redactUrl(url),
      http_status: null,
      observed_shape: [],
      sample_event: null,
      sample_odd: null,
      counts: { events: 0, odds: 0 },
      error: null,
      mapping: { mapped: 0, unmapped: [] },
    };
    if (!this.isConfigured()) {
      return { ...base, error: "NFL_ODDS_API_KEY is not set on this function" };
    }

    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), opts.timeoutMs ?? DEFAULT_TIMEOUT_MS);
    try {
      const res = await fetch(url, { signal: ctrl.signal, headers: { accept: "application/json" } });
      base.http_status = res.status;
      const text = await res.text();
      if (!res.ok) {
        return { ...base, error: reasonFor(res.status) };
      }
      let body: unknown;
      try {
        body = JSON.parse(text);
      } catch {
        return { ...base, error: "malformed_json" };
      }
      const { rows, container } = eventArray(body);
      const sample = rows[0];
      const sampleOdds = sample && Array.isArray(sample.odds) ? sample.odds : [];

      // Run the real adapter over the real sample: this is the difference
      // between "the endpoint answered" and "we can read what it said".
      let mapped = 0;
      const bad: UnmappedRow[] = [];
      for (const ev of rows.slice(0, 3)) {
        const r = readEvent(ev, { book, providerUpdatedAt: null });
        if (r.event) mapped += r.event.odds.length;
        bad.push(...r.bad);
      }

      return {
        ...base,
        ok: true,
        observed_shape: shapePaths(body).concat(container ? [`container=${container}`] : []),
        sample_event: sample
          ? { id: sample.id, teams: sample.teams, date: sample.date ?? sample.start, live: sample.live }
          : null,
        sample_odd: sampleOdds.length ? sampleOf(sampleOdds[0], 600) : null,
        counts: {
          events: rows.length,
          odds: rows.reduce((n, e) => n + (Array.isArray(e.odds) ? e.odds.length : 0), 0),
        },
        mapping: { mapped, unmapped: bad.slice(0, 10) },
      };
    } catch (e) {
      const msg = redactSecret(String((e as Error)?.message ?? e), apiKey());
      return { ...base, error: /abort/i.test(msg) ? "timeout" : msg.slice(0, 200) };
    } finally {
      clearTimeout(timer);
    }
  },
};

/** Exported for the read API's price comparison. Kept next to the provider so
 *  the American-odds convention has one owner. */

// ---------- inlined _shared/theoddsapi.ts ----------
// The Odds API provider (the-odds-api.com).
//
// The ONLY file in the Collective that knows what a The Odds API response
// looks like. Everything else consumes NormalizedSlate.
//
// Wire contract, from the v4 documentation:
//
//   GET https://api.the-odds-api.com/v4/sports/<sportKey>/odds
//         ?apiKey=<key>
//         &regions=us[,us2,uk,eu,au]
//         &markets=h2h,spreads,totals
//         &oddsFormat=american        <- REQUIRED, see below
//         &dateFormat=iso
//
//   -> [ { "id": …, "sport_key": "americanfootball_nfl",
//          "commence_time": "2026-09-13T17:00:00Z",
//          "home_team": "Cincinnati Bengals",
//          "away_team": "Tampa Bay Buccaneers",
//          "bookmakers": [ { "key": "draftkings", "title": "DraftKings",
//                            "last_update": …,
//                            "markets": [ { "key": "spreads", "last_update": …,
//                                           "outcomes": [ { "name": "Cincinnati Bengals",
//                                                           "price": -110,
//                                                           "point": -3.5 }, … ] } ] } ] } ]
//
// oddsFormat is not optional in practice. The API defaults to DECIMAL, and a
// decimal price is a small positive number that parses cleanly as a number —
// so omitting it does not fail, it silently stores 1.91 where -110 belongs and
// every consensus, de-vig and best-price number downstream becomes quiet
// nonsense. It is pinned below and asserted in the tests.
//
// COST MODEL. This differs from OddsBlaze in a way that matters:
//
//   OddsBlaze     one request PER BOOK; cost scales with how many books.
//   The Odds API  ONE request returns EVERY book in the region; cost is
//                 [number of markets] x [number of regions], independent of
//                 how many books come back.
//
// So this provider issues exactly one request per poll and keeps every book
// in the response. Filtering to a shorter book list would discard data already
// paid for without saving a single credit. `opts.books` is therefore a
// PRIORITY ORDER here, not a filter, and books that were asked for but did not
// appear are reported in books_failed so a vanished book is visible.
//
// The response carries the authoritative credit accounting in its headers:
//   x-requests-remaining  credits left in the period
//   x-requests-used       credits spent in the period
//   x-requests-last       what THIS request cost
// These are read and returned on the slate so the caller can enforce a budget
// against real numbers rather than a predicted cost.
//
// The credential is read here and here only, from THE_ODDS_API_KEY, falling
// back to NFL_ODDS_API_KEY so a single-provider deployment needs one secret.
// It goes in the query string because that is the documented authentication
// method, and every URL leaving this module — into a log, an error, an
// ingest_runs row, or a probe response — passes through redactUrl first.

const TA_DEFAULT_BASE = "https://api.the-odds-api.com/v4/";
const TA_DEFAULT_TIMEOUT_MS = 15000;
const TA_DEFAULT_REGIONS = "us";

/** Reported as the book on rows that are not attributable to one book, so an
 *  unmapped report never has an empty book column. */
const TA_NO_BOOK = "(response)";

function taApiKey(): string {
  return Deno.env.get("THE_ODDS_API_KEY") ?? Deno.env.get("NFL_ODDS_API_KEY") ?? "";
}

function taBaseUrl(): string {
  const raw = Deno.env.get("THE_ODDS_API_BASE_URL") ?? TA_DEFAULT_BASE;
  return raw.endsWith("/") ? raw : `${raw}/`;
}

/** Comma separated region list. More regions = proportionally more credits,
 *  so this is a setting rather than a constant: `eu` buys Pinnacle, and
 *  whether that is worth doubling the cost is a plan decision, not a code
 *  decision. */
function taRegions(): string {
  const raw = (Deno.env.get("THE_ODDS_API_REGIONS") ?? TA_DEFAULT_REGIONS).trim();
  return raw === "" ? TA_DEFAULT_REGIONS : raw;
}

/** Our league id -> the API's sport key. */
const TA_SPORT_KEY: Record<string, string> = {
  nfl: "americanfootball_nfl",
  ncaaf: "americanfootball_ncaaf",
  nba: "basketball_nba",
  ncaab: "basketball_ncaab",
  mlb: "baseball_mlb",
  nhl: "icehockey_nhl",
};

/** Canonical market id -> the API's `markets` value. Only the game-line
 *  family is available on the bulk odds endpoint; alternates and props live
 *  on the per-event endpoint, which bills per event and is deliberately not
 *  used here. */
const TA_MARKET_PARAM: Record<string, string> = {
  moneyline: "h2h",
  spread: "spreads",
  total: "totals",
};

/** The API's bookmaker keys are not all the ids the Collective already uses.
 *  Mapping them keeps one book from appearing twice under two names. Keys not
 *  listed here pass through unchanged and are auto-registered on ingest. */
const TA_BOOK_ALIASES: Record<string, string> = {
  williamhill_us: "caesars",
  betfair_ex_us: "betfair",
  betfair_ex_eu: "betfair",
  betfair_ex_uk: "betfair",
  hardrockbet: "hardrock",
  ballybet: "ballybet",
  lowvig: "lowvig",
  betonlineag: "betonline",
  mybookieag: "mybookie",
  betus: "betus",
  unibet_us: "unibet",
  superbook: "superbook",
  windcreek: "betfred",
};

function taCanonicalBook(raw: unknown): string {
  const k = normKey(raw).replace(/[^a-z0-9]/g, "");
  const lower = String(raw ?? "").trim().toLowerCase();
  return TA_BOOK_ALIASES[lower] ?? TA_BOOK_ALIASES[k] ?? (lower || k);
}

// --------------------------------------------------------------- wire types

interface TaOutcome {
  name?: unknown;
  price?: unknown;
  point?: unknown;
  description?: unknown;
}
interface TaMarket {
  key?: unknown;
  last_update?: unknown;
  outcomes?: unknown;
}
interface TaBookmaker {
  key?: unknown;
  title?: unknown;
  last_update?: unknown;
  markets?: unknown;
}
interface TaEvent {
  id?: unknown;
  sport_key?: unknown;
  commence_time?: unknown;
  home_team?: unknown;
  away_team?: unknown;
  bookmakers?: unknown;
}

function taAsArray(v: unknown): unknown[] {
  return Array.isArray(v) ? v : [];
}

// ------------------------------------------------------------ quota headers

/** The credit accounting the API reports on every response. Numbers only —
 *  no header is echoed verbatim, so a future header carrying anything
 *  identifying cannot leak through this path. */
function readTaQuota(headers: Headers): ProviderQuota {
  const n = (name: string): number | null => {
    const raw = headers.get(name);
    if (raw === null || raw.trim() === "") return null;
    const v = Number(raw);
    return Number.isFinite(v) ? v : null;
  };
  return {
    remaining: n("x-requests-remaining"),
    used: n("x-requests-used"),
    last_cost: n("x-requests-last"),
  };
}

/** What one poll will cost, by the documented formula. Used only to plan a
 *  budget before the fact; the authoritative number is x-requests-last on the
 *  response, which is what gets recorded. */
function taPredictedCost(markets: MarketId[], regionList: string): number {
  const m = markets.filter((x) => TA_MARKET_PARAM[x]).length || 1;
  const r = regionList.split(",").map((s) => s.trim()).filter(Boolean).length || 1;
  return m * r;
}

// ------------------------------------------------------------------ reading

/** One outcome -> one canonical price, or an unmapped row explaining why not.
 *
 *  `point` is per outcome and already in that team's own terms, which is
 *  exactly the home convention the Collective stores: the home outcome's point
 *  IS the home spread. No sign flipping happens here, and none should. */
function readTaOutcome(
  row: unknown,
  ctx: {
    book: string;
    market: MarketId;
    homeNames: string[];
    awayNames: string[];
    isLive: boolean;
  },
): { odd: NormalizedOdd | null; bad: UnmappedRow | null } {
  if (!row || typeof row !== "object" || Array.isArray(row)) {
    return { odd: null, bad: unmapped(ctx.book, "outcome is not an object", row) };
  }
  const o = row as TaOutcome;

  // A props payload carries `description` (the player). The bulk endpoint is
  // not asked for props, so one appearing means the request changed shape;
  // report it rather than filing a player line as a team line.
  if (o.description !== undefined && o.description !== null && o.description !== "") {
    return {
      odd: null,
      bad: unmapped(ctx.book, "outcome carries a player description; not a game line", row),
    };
  }

  const price = parseAmericanPrice(o.price);
  if (price === null) {
    return { odd: null, bad: unmapped(ctx.book, "no readable american price", row) };
  }

  const outcome = resolveOutcome({
    market: ctx.market,
    selectionName: o.name,
    homeNames: ctx.homeNames,
    awayNames: ctx.awayNames,
  });
  if (!outcome) {
    return {
      odd: null,
      bad: unmapped(ctx.book, "outcome name matched neither team nor over/under", row),
    };
  }

  // Moneyline has no line. Spreads and totals must have one: a spread with no
  // number is not a usable price, and storing it with a null line would let it
  // group with genuinely different numbers in best-price and consensus.
  let line: number | null = null;
  if (ctx.market !== "moneyline") {
    line = parseLine(o.point);
    if (line === null) {
      return { odd: null, bad: unmapped(ctx.book, `${ctx.market} outcome has no point`, row) };
    }
  }

  return {
    odd: {
      book: ctx.book,
      market: ctx.market,
      outcome,
      outcome_label: typeof o.name === "string" ? o.name : null,
      line,
      price,
      is_live: ctx.isLive,
      // The bulk endpoint returns main lines only; alternates are on the
      // per-event endpoint, which this provider does not call.
      is_main: true,
      raw: sampleOf(row, 200),
    },
    bad: null,
  };
}

/** One event -> canonical event plus every price under it. */
function readTaEvent(
  row: unknown,
  opts: { markets: MarketId[]; now: number },
): { event: NormalizedEvent | null; bad: UnmappedRow[] } {
  const bad: UnmappedRow[] = [];
  if (!row || typeof row !== "object" || Array.isArray(row)) {
    return { event: null, bad: [unmapped(TA_NO_BOOK, "event is not an object", row)] };
  }
  const e = row as TaEvent;

  const home = typeof e.home_team === "string" ? e.home_team : "";
  const away = typeof e.away_team === "string" ? e.away_team : "";
  const commence = typeof e.commence_time === "string" ? e.commence_time : "";
  if (!home || !away || !commence) {
    return {
      event: null,
      bad: [unmapped(TA_NO_BOOK, "event is missing home_team, away_team or commence_time", row)],
    };
  }
  const kickoff = Date.parse(commence);
  if (!Number.isFinite(kickoff)) {
    return { event: null, bad: [unmapped(TA_NO_BOOK, "commence_time is not a parseable time", row)] };
  }

  // There is no in-play flag on this endpoint, so live is inferred from the
  // clock. Stated plainly rather than guessed at: a game that has kicked off
  // is live until the ingest layer learns otherwise from the Collective's own
  // slate, which is the only place a final score is known.
  const isLive = kickoff <= opts.now;

  const wanted = new Set(opts.markets.length ? opts.markets : GAME_MARKETS);
  const odds: NormalizedOdd[] = [];
  const homeNames = [home];
  const awayNames = [away];
  let newestBook: number | null = null;

  for (const bRow of taAsArray(e.bookmakers)) {
    if (!bRow || typeof bRow !== "object" || Array.isArray(bRow)) {
      bad.push(unmapped(TA_NO_BOOK, "bookmaker is not an object", bRow));
      continue;
    }
    const b = bRow as TaBookmaker;
    const book = taCanonicalBook(firstOf(b.key, b.title));
    if (!book) {
      bad.push(unmapped(TA_NO_BOOK, "bookmaker has no key or title", bRow));
      continue;
    }
    const bUpdated = Date.parse(String(b.last_update ?? ""));
    if (Number.isFinite(bUpdated)) {
      newestBook = newestBook === null ? bUpdated : Math.max(newestBook, bUpdated);
    }

    for (const mRow of taAsArray(b.markets)) {
      if (!mRow || typeof mRow !== "object" || Array.isArray(mRow)) {
        bad.push(unmapped(book, "market is not an object", mRow));
        continue;
      }
      const m = mRow as TaMarket;
      const market = canonicalMarket(m.key);
      if (!market) {
        bad.push(unmapped(book, "market key is not one the Collective stores", mRow));
        continue;
      }
      if (!wanted.has(market)) continue;

      for (const oRow of taAsArray(m.outcomes)) {
        const { odd, bad: problem } = readTaOutcome(oRow, {
          book,
          market,
          homeNames,
          awayNames,
          isLive,
        });
        if (odd) odds.push(odd);
        if (problem) bad.push(problem);
      }
    }
  }

  return {
    event: {
      provider_event_id: typeof e.id === "string" ? e.id : null,
      // Team codes are resolved from these names by the database's alias
      // table, which is the one place that mapping lives.
      home,
      away,
      home_name: home,
      away_name: away,
      commence_time: new Date(kickoff).toISOString(),
      status: isLive ? "live" : "scheduled",
      is_live: isLive,
      provider_updated_at: newestBook === null ? null : new Date(newestBook).toISOString(),
      odds,
    },
    bad,
  };
}

// ------------------------------------------------------------------- request

function taBuildUrl(opts: FetchOptions): string {
  const league = normKey(opts.league) || "nfl";
  const sport = TA_SPORT_KEY[league] ?? league;
  const markets = (opts.markets.length ? opts.markets : GAME_MARKETS)
    .map((m) => TA_MARKET_PARAM[m])
    .filter(Boolean);
  const u = new URL(`sports/${sport}/odds`, taBaseUrl());
  u.searchParams.set("taApiKey", taApiKey());
  u.searchParams.set("taRegions", taRegions());
  u.searchParams.set("markets", (markets.length ? markets : ["h2h", "spreads", "totals"]).join(","));
  // Pinned, not defaulted. See the header note.
  u.searchParams.set("oddsFormat", "american");
  u.searchParams.set("dateFormat", "iso");
  return u.toString();
}

function taReasonFor(status: number): string {
  if (status === 401) return "the API rejected the key (401)";
  if (status === 429) return "credit limit reached or rate limited (429)";
  if (status === 422) return "the request parameters were rejected (422)";
  if (status === 404) return "no such sport key (404)";
  if (status >= 500) return `the provider returned ${status}`;
  return `unexpected status ${status}`;
}

interface TaRawFetch {
  ok: boolean;
  status: number | null;
  body: unknown;
  quota: ProviderQuota;
  reason: string | null;
}

async function taRequest(opts: FetchOptions): Promise<TaRawFetch> {
  const url = taBuildUrl(opts);
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), opts.timeoutMs ?? TA_DEFAULT_TIMEOUT_MS);
  const empty: ProviderQuota = { remaining: null, used: null, last_cost: null };
  try {
    const res = await fetch(url, { signal: controller.signal });
    const quota = readTaQuota(res.headers);
    if (!res.ok) {
      return { ok: false, status: res.status, body: null, quota, reason: taReasonFor(res.status) };
    }
    const text = await res.text();
    let body: unknown = null;
    try {
      body = JSON.parse(text);
    } catch {
      return {
        ok: false,
        status: res.status,
        body: null,
        quota,
        reason: "the response was not JSON",
      };
    }
    return { ok: true, status: res.status, body, quota, reason: null };
  } catch (e) {
    const msg = redactSecret(String((e as Error)?.message ?? e), taApiKey());
    return {
      ok: false,
      status: null,
      body: null,
      quota: empty,
      reason: msg.includes("abort") ? "the request timed out" : msg,
    };
  } finally {
    clearTimeout(timer);
  }
}

// ----------------------------------------------------------------- provider

const theOddsApiProvider: OddsProvider = {
  id: "theoddsapi",
  name: "The Odds API",

  isConfigured(): boolean {
    return taApiKey().length > 0;
  },

  async fetchSlate(opts: FetchOptions): Promise<NormalizedSlate> {
    const fetchedAt = new Date().toISOString();
    const now = Date.now();
    const base: NormalizedSlate = {
      provider: "theoddsapi",
      league: opts.league,
      fetched_at: fetchedAt,
      provider_updated_at: null,
      events: [],
      books_ok: [],
      books_failed: [],
      unmapped: [],
      counts: { events: 0, odds: 0, unmapped: 0 },
      quota: { remaining: null, used: null, last_cost: null },
    };

    if (!theOddsApiProvider.isConfigured()) {
      base.books_failed = [{ book: TA_NO_BOOK, reason: "no API key configured" }];
      return base;
    }

    const res = await taRequest(opts);
    base.quota = res.quota;
    if (!res.ok) {
      base.books_failed = [{ book: TA_NO_BOOK, reason: res.reason ?? "request failed" }];
      return base;
    }

    // One request returns every book, so a non-array body is the whole run
    // failing rather than one book failing.
    if (!Array.isArray(res.body)) {
      base.books_failed = [{ book: TA_NO_BOOK, reason: "response was not an array of events" }];
      base.unmapped = [unmapped(TA_NO_BOOK, "top level of response is not an array", res.body)];
      base.counts.unmapped = 1;
      return base;
    }

    const events: NormalizedEvent[] = [];
    const bad: UnmappedRow[] = [];
    const seenBooks = new Set<string>();
    let newest: number | null = null;
    let oddsCount = 0;

    for (const row of res.body) {
      const { event, bad: problems } = readTaEvent(row, { markets: opts.markets, now });
      bad.push(...problems);
      if (!event) continue;
      // Pregame/live filter, applied after mapping so the counts stay honest.
      if (opts.live === true && !event.is_live) continue;
      if (opts.live === false && event.is_live) continue;
      for (const o of event.odds) seenBooks.add(o.book);
      oddsCount += event.odds.length;
      if (event.provider_updated_at) {
        const t = Date.parse(event.provider_updated_at);
        if (Number.isFinite(t)) newest = newest === null ? t : Math.max(newest, t);
      }
      events.push(event);
    }

    // opts.books is a priority order, not a filter: every book in the response
    // is kept because it cost nothing extra. A book that was asked for and did
    // not arrive is reported so its absence is visible rather than silent.
    const asked = opts.books.map(taCanonicalBook).filter(Boolean);
    const missing = asked.filter((b) => !seenBooks.has(b));

    const ordered = [...seenBooks].sort((a, b) => {
      const ia = asked.indexOf(a);
      const ib = asked.indexOf(b);
      return (ia < 0 ? 999 : ia) - (ib < 0 ? 999 : ib) || a.localeCompare(b);
    });

    return {
      ...base,
      provider_updated_at: newest === null ? null : new Date(newest).toISOString(),
      events,
      books_ok: ordered,
      books_failed: missing.map((b) => ({
        book: b,
        reason: "requested but not present in the response for this region",
      })),
      unmapped: bad,
      counts: { events: events.length, odds: oddsCount, unmapped: bad.length },
    };
  },

  async probe(opts: FetchOptions): Promise<ProbeResult> {
    const urlRedacted = redactUrl(taBuildUrl(opts));
    const empty: ProbeResult = {
      provider: "theoddsapi",
      ok: false,
      url_redacted: urlRedacted,
      http_status: null,
      observed_shape: [],
      sample_event: null,
      sample_odd: null,
      counts: { events: 0, odds: 0 },
      error: null,
      mapping: { mapped: 0, unmapped: [] },
      quota: { remaining: null, used: null, last_cost: null },
    };

    if (!theOddsApiProvider.isConfigured()) {
      return { ...empty, error: "no API key configured" };
    }

    const res = await taRequest(opts);
    if (!res.ok) {
      return { ...empty, http_status: res.status, error: res.reason, quota: res.quota };
    }
    if (!Array.isArray(res.body)) {
      return {
        ...empty,
        http_status: res.status,
        quota: res.quota,
        observed_shape: shapePaths(res.body),
        error: "response was not an array of events",
      };
    }

    const first = res.body[0] ?? null;
    const { event, bad } = readTaEvent(first, { markets: opts.markets, now: Date.now() });
    const oddsTotal = res.body.reduce((n: number, row: unknown) => {
      const r = row as TaEvent;
      return n + taAsArray(r?.bookmakers).reduce((k: number, b: unknown) => {
        const bb = b as TaBookmaker;
        return k + taAsArray(bb?.markets).reduce(
          (j: number, m: unknown) => j + taAsArray((m as TaMarket)?.outcomes).length,
          0,
        );
      }, 0);
    }, 0);

    return {
      provider: "theoddsapi",
      ok: true,
      url_redacted: urlRedacted,
      http_status: res.status,
      observed_shape: shapePaths(first),
      sample_event: sampleOf(first, 600),
      sample_odd: event?.odds[0] ?? null,
      counts: { events: res.body.length, odds: oddsTotal },
      error: null,
      mapping: { mapped: event?.odds.length ?? 0, unmapped: bad },
      quota: res.quota,
    };
  },
};

// ---------- collective_odds_ingest/index.ts ----------
// Model Collective — NFL odds ingestion.
//
// The single writer. Nothing else in the Collective calls an odds provider,
// and nothing else writes to the odds schema. One run: read the settings,
// decide whether it is time, fetch, normalize, hand the batch to SQL, close
// any market that has kicked off, and record what happened.
//
// DEPLOYMENT: keep "Enforce JWT verification" ON for this function. The
// gateway then rejects anonymous calls, and the checks below additionally
// require either the service role key (how pg_cron calls it) or an admin
// account. A provider credential lives only in an edge function secret and is
// read only inside that provider's module.
//
// Two providers are registered. Which one runs is the `provider.default`
// setting, not a deploy: OddsBlaze bills per book, The Odds API bills per
// [markets x regions] and returns every book in one request. The Odds API
// reports its remaining credits on every response, so when the active provider
// meters itself this function enforces a budget against those real numbers
// before spending anything.

registerProvider(oddsBlazeProvider);
registerProvider(theOddsApiProvider);

const NO_STORE = { "cache-control": "no-store" };
/** Events per RPC call. Keeps a single request body small enough to stay well
 *  inside PostgREST limits on a full 16 game slate with every book. */
const BATCH_EVENTS = 12;

const SETTING_KEYS = [
  "nfl.enabled",
  "nfl.league_id",
  "nfl.books",
  "nfl.markets",
  "nfl.refresh_seconds.live",
  "nfl.refresh_seconds.pregame",
  "nfl.refresh_seconds.idle",
  "nfl.pregame_window_hours",
  "nfl.max_books_per_run",
  "provider.default",
  "provider.credit_reserve",
  "provider.quota",
];

/** Credit accounting carried forward between runs.
 *
 *  A metered provider only reports its remaining balance in a RESPONSE, which
 *  is after the credit has already been spent. So the balance from the last
 *  run is persisted in odds.settings and checked before the next one. That is
 *  what makes the budget a guard rather than a report: without it the first
 *  time we learn the plan is exhausted is a 429, mid-season, on the Sunday
 *  that matters.
 *
 *  An unknown balance is treated as "no information" and allowed through —
 *  never as "unlimited" — because the alternative is a deployment that can
 *  never make its first request. */
interface StoredQuota {
  remaining: number | null;
  used: number | null;
  last_cost: number | null;
  observed_at: string | null;
}

function readStoredQuota(v: unknown): StoredQuota {
  const o = (v && typeof v === "object" && !Array.isArray(v)) ? v as Record<string, unknown> : {};
  const n = (x: unknown): number | null => {
    if (x === null || x === undefined || x === "") return null;
    const k = Number(x);
    return Number.isFinite(k) ? k : null;
  };
  return {
    remaining: n(o.remaining),
    used: n(o.used),
    last_cost: n(o.last_cost),
    observed_at: typeof o.observed_at === "string" ? o.observed_at : null,
  };
}

/** pg_cron calls with the service role key; a founder calls with their own
 *  session. Anything else is refused before a provider request is made. */
async function authorize(req: Request): Promise<{ trigger: string } | Response> {
  const authz = req.headers.get("authorization") ?? "";
  const bearer = authz.replace(/^Bearer\s+/i, "").trim();
  if (SERVICE_KEY && bearer === SERVICE_KEY) return { trigger: "cron" };
  const admin = await requireAdmin(req);
  if (admin instanceof Response) return admin;
  return { trigger: "admin" };
}

interface Cadence {
  interval_seconds: number;
  reason: "live" | "pregame" | "idle";
  next_kickoff: string | null;
}

/**
 * How often to poll right now. Live games get the fastest cadence the plan
 * safely allows, a slate about to start gets a middle one, and an empty
 * calendar gets the slow one. Every value comes from odds.settings, so
 * changing the cadence is a settings update rather than a deploy.
 */
async function cadence(cfg: Record<string, unknown>, league: string): Promise<Cadence> {
  const st = await rpc<Record<string, unknown> | null>("odds_status", { p_league: league })
    .catch(() => null);
  const live = num(st?.events_live, 0);
  const windowHours = num(cfg["nfl.pregame_window_hours"], 36);

  if (live > 0) {
    return {
      interval_seconds: num(cfg["nfl.refresh_seconds.live"], 60),
      reason: "live",
      next_kickoff: null,
    };
  }
  const next = await nextKickoff(league);
  if (next) {
    const hours = (Date.parse(next) - Date.now()) / 3_600_000;
    if (hours <= windowHours) {
      return {
        interval_seconds: num(cfg["nfl.refresh_seconds.pregame"], 300),
        reason: "pregame",
        next_kickoff: next,
      };
    }
  }
  return {
    interval_seconds: num(cfg["nfl.refresh_seconds.idle"], 1800),
    reason: "idle",
    next_kickoff: next,
  };
}

async function nextKickoff(league: string): Promise<string | null> {
  const board = await rpc<Record<string, unknown> | null>("odds_board", {
    p_league: league,
    p_from: new Date().toISOString(),
    p_to: null,
    p_include_books: false,
    p_limit: 1,
  }).catch(() => null);
  const games = (board?.games ?? []) as { commence_time?: string }[];
  return games[0]?.commence_time ?? null;
}

/** Seconds since the last run that actually reached the provider. */
async function secondsSinceLastRun(): Promise<number | null> {
  const st = await rpc<Record<string, unknown> | null>("odds_status", { p_league: "nfl" })
    .catch(() => null);
  const last = st?.last_run as { started_at?: string; status?: string } | null | undefined;
  if (!last?.started_at) return null;
  const ms = Date.parse(last.started_at);
  return Number.isFinite(ms) ? Math.round((Date.now() - ms) / 1000) : null;
}

/** Why the site is showing "Odds unavailable", in the order the pipeline
 *  fails. The site itself deliberately says nothing beyond "unavailable" — it
 *  will not guess at a cause in front of a visitor — so this is where the
 *  cause is actually named, for an operator who is already authenticated. */
function diagnose(
  st: Record<string, unknown> | null,
  cfg: Record<string, unknown>,
  provider: { id: string; isConfigured(): boolean },
  quota: StoredQuota,
): { healthy: boolean; state: string; detail: string; fix: string | null } {
  if (cfg["nfl.enabled"] === false) {
    return {
      healthy: false,
      state: "disabled",
      detail: "nfl.enabled is false, so ingestion never runs.",
      fix: "Set nfl.enabled to true in odds.settings.",
    };
  }
  if (!provider.isConfigured()) {
    return {
      healthy: false,
      state: "no_credential",
      detail: `The "${provider.id}" provider has no API key in this function's environment.`,
      fix: provider.id === "theoddsapi"
        ? "Add THE_ODDS_API_KEY (or NFL_ODDS_API_KEY) to the edge function secrets."
        : "Add NFL_ODDS_API_KEY to the edge function secrets.",
    };
  }
  const last = st?.last_run as Record<string, unknown> | null | undefined;
  if (!st?.last_poll_at) {
    if (!last) {
      return {
        healthy: false,
        state: "never_run",
        detail:
          "No ingest run has ever been recorded, so nothing has called the provider. " +
          "This is what makes the site say odds are unavailable.",
        fix: "POST /v1/ingest?force=1 once by hand, then schedule it.",
      };
    }
    return {
      healthy: false,
      state: "never_succeeded",
      detail:
        `Runs exist but none finished ok or partial. The most recent ended "${
          String(last.status ?? "unknown")
        }"` + (last.error_message ? `: ${String(last.error_message).slice(0, 200)}` : "."),
      fix: "Run /v1/probe to see what the provider actually returned.",
    };
  }
  if (num(st?.books_current, 0) === 0) {
    return {
      healthy: false,
      state: "no_current_prices",
      detail: "A poll succeeded but no book has a current price stored.",
      fix: "Run /v1/probe; the mapping section shows which rows could not be read.",
    };
  }
  if (quota.remaining !== null && quota.remaining <= 0) {
    return {
      healthy: false,
      state: "out_of_credit",
      detail: "The provider reports no credits left in this billing period.",
      fix: "Wait for the period to reset, or raise the plan.",
    };
  }
  return {
    healthy: true,
    state: "ok",
    detail: `Last polled ${String(st?.last_poll_at)} with ${
      num(st?.books_current, 0)
    } book(s) currently priced.`,
    fix: null,
  };
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

Deno.serve(async (req) => {
  const pre = preflight(req);
  if (pre) return pre;
  const path = subpath(req, "collective_odds_ingest");

  const auth = await authorize(req);
  if (auth instanceof Response) return auth;

  try {
    const url = new URL(req.url);
    const force = url.searchParams.get("force") === "1";
    const cfg = await settings(SETTING_KEYS);
    const league = typeof cfg["nfl.league_id"] === "string"
      ? cfg["nfl.league_id"] as string
      : "nfl";
    const providerId = typeof cfg["provider.default"] === "string"
      ? cfg["provider.default"] as string
      : "oddsblaze";
    const provider = getProvider(providerId);

    if (!provider) {
      return err("server_error", `No provider registered under "${providerId}".`, 500);
    }

    // ------------------------------------------------------------- probe
    // One real request, reporting the observed response STRUCTURE. This is
    // how the integration is confirmed against the live API without printing
    // a credential or trusting a guess about the payload shape.
    if (path === "/v1/probe" && (req.method === "POST" || req.method === "GET")) {
      const books = strList(cfg["nfl.books"], ["draftkings"]);
      const only = url.searchParams.get("book");
      const result = await provider.probe({
        league,
        books: only ? [only] : books.slice(0, 1),
        markets: strList(cfg["nfl.markets"], ["moneyline", "spread", "total"]),
        mainOnly: true,
        timeoutMs: 15000,
      });
      return json(result, result.ok ? 200 : 502, NO_STORE);
    }

    // ------------------------------------------------------------ status
    if (path === "/v1/status" && req.method === "GET") {
      const st = await rpc<Record<string, unknown> | null>("odds_status", { p_league: league });
      const cad = await cadence(cfg, league);
      const quota = readStoredQuota(cfg["provider.quota"]);
      const markets = strList(cfg["nfl.markets"], ["moneyline", "spread", "total"]);
      const cost = taPredictedCost(markets, Deno.env.get("THE_ODDS_API_REGIONS") ?? "us");
      return json({
        ...st,
        provider: { id: provider.id, name: provider.name, configured: provider.isConfigured() },
        cadence: cad,
        seconds_since_last_run: await secondsSinceLastRun(),
        credits: {
          ...quota,
          estimated_cost_per_poll: cost,
          reserve: Math.max(0, num(cfg["provider.credit_reserve"], 0)),
          polls_affordable: quota.remaining === null
            ? null
            : Math.max(0, Math.floor(
              (quota.remaining - Math.max(0, num(cfg["provider.credit_reserve"], 0))) / cost,
            )),
        },
        diagnosis: diagnose(st, cfg, provider, quota),
      }, 200, NO_STORE);
    }

    // ------------------------------------------------------ close markets
    if (path === "/v1/close" && req.method === "POST") {
      const closed = await rpc<number>("odds_finalize_closing", { p_event_id: null });
      const linked = await rpc<number>("odds_link_games", { p_league: league });
      return json({ ok: true, closing_rows: closed ?? 0, games_linked: linked ?? 0 }, 200, NO_STORE);
    }

    // -------------------------------------------------- link to the slate
    if (path === "/v1/link" && req.method === "POST") {
      const linked = await rpc<number>("odds_link_games", { p_league: league });
      return json({ ok: true, games_linked: linked ?? 0 }, 200, NO_STORE);
    }

    // ------------------------------------------------------------ ingest
    if (path === "/v1/ingest" && req.method === "POST") {
      if (cfg["nfl.enabled"] === false) {
        return json({ ok: true, skipped: "disabled", reason: "nfl.enabled is false" }, 200, NO_STORE);
      }
      // Fail closed when the settings could not be read. settings() swallows
      // its errors and leaves null behind, and null is not false — so the
      // kill switch and the throttle would both have silently defaulted to
      // "on, as fast as you like". Against a metered trial plan an
      // unthrottled loop is the expensive failure, so an unreadable settings
      // table stops the run instead of guessing.
      if (cfg["nfl.enabled"] === null || cfg["nfl.enabled"] === undefined) {
        return err(
          "not_configured",
          "The odds settings could not be read, so the kill switch and poll interval are unknown. Refusing to call the provider.",
          503,
        );
      }
      if (!provider.isConfigured()) {
        return err(
          "not_configured",
          "The odds provider credential is not set on this function. Add NFL_ODDS_API_KEY to the edge function secrets.",
          503,
        );
      }

      // Do not hammer the API: a run that arrives early for the current
      // cadence returns without making a provider request at all.
      const cad = await cadence(cfg, league);
      const since = await secondsSinceLastRun();
      if (!force && since !== null && since < cad.interval_seconds) {
        return json({
          ok: true,
          skipped: "too_soon",
          cadence: cad,
          seconds_since_last_run: since,
        }, 200, NO_STORE);
      }

      const books = strList(cfg["nfl.books"], ["draftkings", "fanduel", "betmgm"])
        .slice(0, Math.max(1, num(cfg["nfl.max_books_per_run"], 12)));
      const markets = strList(cfg["nfl.markets"], ["moneyline", "spread", "total"]);
      const opts: FetchOptions = { league, books, markets, mainOnly: true, timeoutMs: 12000 };

      // ------------------------------------------------- credit budget
      // Spend nothing if the last known balance says this request would take
      // the plan below its reserve. The reserve exists so the closing-line
      // captures at the end of a period are still affordable after a month of
      // routine polling: running to exactly zero would mean the last games of
      // the month grade against no captured close at all.
      const reserve = Math.max(0, num(cfg["provider.credit_reserve"], 0));
      const stored = readStoredQuota(cfg["provider.quota"]);
      const cost = taPredictedCost(markets, Deno.env.get("THE_ODDS_API_REGIONS") ?? "us");
      if (stored.remaining !== null && stored.remaining - cost < reserve) {
        return json({
          ok: true,
          skipped: "credit_budget",
          reason:
            `The provider reports ${stored.remaining} credits left. This poll costs about ` +
            `${cost}, which would drop the balance below the reserve of ${reserve}.`,
          quota: stored,
          estimated_cost: cost,
          credit_reserve: reserve,
        }, 200, NO_STORE);
      }

      const runId = await rpc<number>("odds_begin_run", {
        p_provider: provider.id,
        p_league: league,
        p_trigger: auth.trigger,
      });

      try {
        const slate = await provider.fetchSlate(opts);

        // Every book failing is a provider problem, not a slate with no
        // games. Recording it as "0 events" would make an outage look like
        // an empty week, so it is reported as an error and no data is touched.
        if (slate.books_ok.length === 0) {
          const reason = slate.books_failed[0]?.reason ?? "no_books_returned";
          await rpc("odds_finish_run", {
            p_run_id: runId,
            p_stats: {
              status: "error",
              books_requested: books.length,
              books_ok: 0,
              books_failed: slate.books_failed.length,
              error_code: reason,
              error_message: `every requested sportsbook failed: ${
                slate.books_failed.map((b) => `${b.book}=${b.reason}`).join(", ").slice(0, 300)
              }`,
            },
          });
          return err("provider_unavailable", "The odds provider did not return any data.", 502, {
            books_failed: slate.books_failed,
          });
        }

        // Record the balance the provider just reported, before anything
        // below can throw. This is the only moment the real number is known,
        // and a run that fails later still spent the credit.
        if (slate.quota) {
          await rpc("odds_set_setting", {
            p_key: "provider.quota",
            p_value: { ...slate.quota, observed_at: new Date().toISOString() },
          }).catch((e) => console.error("could not persist provider quota:", e));
        }

        let written = 0, unchanged = 0, created = 0, seen = 0, rejected = 0;
        const unmatched: unknown[] = [];
        for (const part of chunk<NormalizedEvent>(slate.events, BATCH_EVENTS)) {
          const res = await rpc<Record<string, unknown>>("odds_ingest", {
            p_run_id: runId,
            p_provider: provider.id,
            p_league: league,
            p_payload: { events: part },
          });
          if (res && res.ok === false) {
            throw new Error(`ingest rejected: ${String(res.code ?? "unknown")}`);
          }
          written += num(res?.snapshots_written, 0);
          unchanged += num(res?.snapshots_unchanged, 0);
          created += num(res?.events_created, 0);
          seen += num(res?.events_seen, 0);
          rejected += num(res?.rows_rejected, 0);
          if (Array.isArray(res?.unmatched)) unmatched.push(...res.unmatched as unknown[]);
        }

        // A game that has kicked off closes now, while its last pre-kickoff
        // price is still the most recent thing we stored.
        const closingRows = await rpc<number>("odds_finalize_closing", { p_event_id: null })
          .catch(() => 0);
        const linked = await rpc<number>("odds_link_games", { p_league: league }).catch(() => 0);

        const partial = slate.books_failed.length > 0 || unmatched.length > 0 ||
          slate.counts.unmapped > 0;
        await rpc("odds_finish_run", {
          p_run_id: runId,
          p_stats: {
            status: partial ? "partial" : "ok",
            credits_spent: slate.quota?.last_cost ?? null,
            credits_remaining: slate.quota?.remaining ?? null,
            books_requested: books.length,
            books_ok: slate.books_ok.length,
            books_failed: slate.books_failed.length,
            events_seen: seen,
            events_created: created,
            events_matched: seen - created,
            snapshots_written: written,
            snapshots_unchanged: unchanged,
            rows_rejected: rejected,
            unmatched: {
              events: unmatched.slice(0, 20),
              provider_rows: slate.unmapped,
              books_failed: slate.books_failed,
            },
          },
        });

        return json({
          ok: true,
          run_id: runId,
          provider: provider.id,
          league,
          cadence: cad,
          books_ok: slate.books_ok,
          books_failed: slate.books_failed,
          events_seen: seen,
          events_created: created,
          snapshots_written: written,
          snapshots_unchanged: unchanged,
          rows_rejected: rejected,
          provider_rows_unmapped: slate.counts.unmapped,
          credits: slate.quota ?? null,
          unmapped_sample: slate.unmapped.slice(0, 5),
          unmatched_events: unmatched.slice(0, 5),
          closing_rows: closingRows ?? 0,
          games_linked: linked ?? 0,
        }, 200, NO_STORE);
      } catch (e) {
        const msg = redactSecret(
          String((e as Error)?.message ?? e),
          Deno.env.get("NFL_ODDS_API_KEY"),
        );
        console.error("collective_odds_ingest run failed:", msg);
        await rpc("odds_finish_run", {
          p_run_id: runId,
          p_stats: { status: "error", error_code: "ingest_failed", error_message: msg },
        }).catch(() => {});
        return err("server_error", "The odds run did not complete.", 500);
      }
    }

    if (["/v1/ingest", "/v1/probe", "/v1/close", "/v1/link", "/v1/status"].includes(path)) {
      return err("method_not_allowed", "Wrong method for this route.", 405);
    }
    return err("not_found", `No such route: ${req.method} ${path}`, 404);
  } catch (e) {
    const msg = redactSecret(String((e as Error)?.message ?? e), Deno.env.get("NFL_ODDS_API_KEY"));
    if (e instanceof RpcError) console.error("collective_odds_ingest rpc failure:", e.message);
    else console.error("collective_odds_ingest failure:", msg);
    return err("server_error", "Something went wrong on our side.", 500);
  }
});
