#!/usr/bin/env python3
"""Render report/BACKTEST.md from the trained artifacts.

The report is written to be readable by someone deciding whether to trust the
model, which means the negative results come FIRST and in the same typeface as
the positive ones.

Usage: python3 gen_report.py <out_dir>
"""
import json
import os
import sys

OUT = sys.argv[1] if len(sys.argv) > 1 else 'out'
HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, 'report', 'BACKTEST.md')


def j(path):
    p = os.path.join(OUT, path)
    return json.load(open(p)) if os.path.exists(p) else {}


def table(rows, headers):
    out = ['| ' + ' | '.join(headers) + ' |',
           '|' + '|'.join(['---'] * len(headers)) + '|']
    for r in rows:
        out.append('| ' + ' | '.join('' if x is None else str(x) for x in r) + ' |')
    return '\n'.join(out)


def main():
    rep = j('report_cfb_p4.json')
    repl = j('report_layers.json')
    P = j('params_cfb_p4.json')
    mh = rep.get('market_headline', {})
    ms = rep.get('market_secondary', {})
    L = []
    A = L.append

    A('# EdgeDesk CFB Power 4 Intelligence Model — backtest')
    A('')
    A('Generated by `research/gen_report.py`. Every number here is produced by the')
    A('pipeline in this directory from public data; nothing is quoted from memory.')
    A('')
    A('## The headline, which is a negative result')
    A('')
    A('| | model | closing market |')
    A('|---|---|---|')
    A('| spread MAE, %s | **%s** | **%s** |' % (mh.get('window'), mh.get('spread_mae_model'),
                                                mh.get('spread_mae_market')))
    A('| total MAE, %s | %s | %s |' % (mh.get('window'), mh.get('total_mae_model'),
                                       mh.get('total_mae_market')))
    A('')
    d_spread = float(mh.get('spread_mae_model', 0)) - float(mh.get('spread_mae_market', 0))
    d_total = float(mh.get('total_mae_model', 0)) - float(mh.get('total_mae_market', 0))
    A('The model is roughly **%.1f points per game worse than the closing line** on the'
      % d_spread)
    A('spread and %.1f worse on the total, over %s games in seasons that no layer of it'
      % (d_total, mh.get('n_games')))
    A('was tuned on. It does not beat the market.')
    A('')
    A('Against the close, by size of disagreement:')
    A('')
    ats = mh.get('ats_vs_close', {})
    A(table([[k, v['n'], v['wins'], '%.2f%%' % v['win_pct'], v['binom_p_one_sided']]
             for k, v in sorted(ats.items(), key=lambda x: float(x[0]))],
            ['gap >=', 'n', 'wins', 'win %', 'one-sided p']))
    A('')
    A('Not one threshold clears break-even, and the biggest disagreements are the')
    A('*worst* — the classic signature of a projection noisier than the market it is')
    A('arguing with. The engine therefore never emits anything above `RESEARCH_LEAN`,')
    A('and every projection ships with `unproven: true`.')
    A('')
    clv = mh.get('clv_open_to_close')
    if clv:
        A('Closing-line value, opening number to closing number:')
        A('')
        A('- games: %s' % clv['n'])
        A('- mean points gained by the side the model preferred at the open: **%+.3f**' % clv['mean_points_gained'])
        A('- share of games where the line moved toward that side: **%.1f%%**' % (100 * clv['beat_close_rate']))
        A('')
        A('A small positive mean with a sub-50% hit rate is not an edge. It is noise')
        A('with a slight tilt, and it is reported because it is what the data says.')
        A('')

    A('## What the line archive changed')
    A('')
    A('The v1 football engine in `football/` states that no public historical CFB')
    A('betting-line archive exists, and therefore makes no market claim for CFB at')
    A('all. That statement is now falsified: `sportsdataverse/cfbfastR-data` carries')
    A('`betting/csv/cfb_line_odds.csv.gz` — 1.18M rows, 2006-2025, spread, total and')
    A('moneyline, **opening and closing**, across multiple books including Pinnacle.')
    A('Coverage of completed FBS-vs-FBS games is 94-100% from 2012 on.')
    A('')
    A('So this model can be, and is, held to the market. The result above is what')
    A('being held to it looks like.')
    A('')

    A('## Where the model does earn its keep')
    A('')
    A('Being worse than the market is not the same as being uninformative. Measured')
    A('out of sample:')
    A('')
    rows = []
    v = rep.get('venue', {})
    if v.get('kept_per_venue_table'):
        rows.append(['venue home-field advantage', '%s venues rated individually, league mean %s pts, '
                     'SD across venues %s pts' % (v.get('n_venues'), v.get('league_hfa'),
                                                  v.get('sd_across_venues'))])
    else:
        rows.append(['home-field advantage', 'a single league constant of %s pts — the per-venue '
                     'table was tested and rejected (see below)' % v.get('league_hfa')])
    w = rep.get('winprob', {})
    rows.append(['win-probability calibration', 'Brier %s over %s games (a market-free baseline of 0.25 is a coin flip)'
                 % (w.get('brier'), w.get('n'))])
    q = repl.get('qb', {})
    if q.get('points_per_epa_db'):
        rows.append(['quarterback layer', '%.1f points of spread per 1.0 EPA/dropback of QB edge; '
                     'tune r2 %s, TEST r2 %s, permutation p %s'
                     % (q['points_per_epa_db'], q.get('r2_tune'), q.get('r2_test'), q.get('permutation_p'))])
    inj = repl.get('injury', {})
    if inj.get('qb_absence_points'):
        rows.append(['quarterback absence', '%.2f points, measured over %s games where the primary QB took no dropbacks'
                     % (inj['qb_absence_points'], inj.get('n_games_with_a_backup'))])
    sc = repl.get('schedule', {})
    if sc.get('mean_abs_points'):
        rows.append(['schedule stress', 'moves the number by %.2f points on average; tune r2 %s, test r2 %s'
                     % (sc['mean_abs_points'], sc.get('r2_tune'), sc.get('r2_test'))])
    cf = repl.get('conference', {})
    if cf.get('shipped'):
        rows.append(['conference strength', '%.2f points per point of PRIOR-season '
                     'cross-conference differential; tune r2 %s, TEST r2 %s, permutation p %s. '
                     'Applied to cross-conference games only and decayed to zero by six games — '
                     'the largest validated effect here after the ratings themselves'
                     % (cf['points_per_strength'], cf.get('r2_tune'), cf.get('r2_test'),
                        cf.get('permutation_p'))])
    mm = rep.get('matchup', {})
    if mm.get('r2_on_residual'):
        rows.append(['stylistic matchup', 'explains %.2f%% of what the ratings leave behind'
                     % (100 * mm['r2_on_residual'])])
    A(table(rows, ['layer', 'measured']))
    A('')

    A('## What was offered to the model and REJECTED by it')
    A('')
    A('These are the received wisdoms this data does not support. Each was fitted')
    A('honestly and came back at or near zero:')
    A('')
    A('- **Per-venue home-field advantage.** The obvious estimator — each stadium\'s')
    A('  own shrunk mean residual — correlates **%s** with the home team\'s own rating.'
      % v.get('artifact_corr_with_home_team_rating'))
    A('  Because a team plays every home game at one stadium, whatever the ratings have')
    A('  not yet absorbed about that team lands on its venue: the "top venues" list comes')
    A('  out reading like a top-25 poll. On held-out seasons it moved MAE from %s to %s —'
      % (v.get('holdout_mae_league_constant'), v.get('holdout_mae_venue_table')))
    A('  %.3f of a point, bought by absorbing team quality into stadium names. The table'
      % (float(v.get('improvement') or 0)))
    A('  does not ship; the single league constant does.')
    dv = repl.get('development', {})
    if dv and not dv.get('shipped'):
        A('- **Player development (Section VII).** A program\'s efficiency above what its')
        A('  experience, continuity and returning production predict does **not repeat**:')
        A('  year-over-year correlation of the development delta is **%s** over %s program'
          % (dv.get('delta_persistence_year_over_year'), dv.get('n_pairs')))
        A('  pairs. "This staff develops players" is not visible in this data, so no')
        A('  per-program development value ships. (Recruiting pedigree is absent from the')
        A('  baseline, so this measures development on top of continuity, not on top of talent.)')
    tv = rep.get('travel', {})
    A('- **Travel.** r2 = %s on %s road games (mean trip %s miles). Distance, time'
      % (tv.get('r2'), tv.get('n'), tv.get('mean_miles')))
    A('  zones and altitude barely move the mean once team strength is accounted for.')
    rv = rep.get('rivalry', {})
    A('- **Rivalry volatility.** %s detected pairs; only **%.0f%%** of them are actually'
      % (rv.get('pairs'), 100 * (rv.get('share_more_volatile') or 0)))
    A('  more volatile than a typical game. Rivalry games are not reliably wilder.')
    vf = rep.get('volatility_fit', {})
    A('- **Roster turnover, youth, rivalry, travel, scoring environment and mismatch as')
    A('  volatility drivers.** All seven were offered to a maximum-likelihood sigma fit;')
    A('  it kept exactly one: %s. Everything else was driven to zero.'
      % ', '.join(vf.get('nonzero_drivers') or ['none']))
    A('')
    vv = rep.get('volatility_validation', {})
    A('The surviving volatility model is **%s** out of sample: rank correlation between'
      % vv.get('verdict'))
    A('predicted sigma and realised absolute error is %s over %s games. The engine still'
      % (vv.get('rank_corr_sigma_vs_absresid'), vv.get('n')))
    A('publishes a volatility index, and it is labelled a research signal rather than a')
    A('validated one.')
    A('')

    A('## Regression constants (Section XXI), measured rather than assumed')
    A('')
    A('Game-to-game persistence of each statistic within a season. A statistic with')
    A('near-zero persistence is almost entirely regressed to the mean; one that repeats')
    A('is barely touched. Nothing here was chosen by hand.')
    A('')
    pers = rep.get('persistence', {})
    A(table([[k, v['n'], v['lag1_r']] for k, v in sorted(pers.items(), key=lambda x: -x[1]['lag1_r'])],
            ['statistic', 'n', 'lag-1 correlation']))
    A('')
    A('Turnovers repeat at r = %s. Anyone reading a turnover margin as a skill signal is'
      % (pers.get('turnovers', {}).get('lag1_r')))
    A('reading noise.')
    A('')

    A('## Preseason to in-season (Section XXIV)')
    A('')
    A('With the learned step size, the share of a team\'s rating still attributable to')
    A('its August value, by games played:')
    A('')
    share = rep.get('preseason_share_curve', {})
    if share:
        ks = [str(i) for i in range(0, 16) if str(i) in share]
        A(table([[k, share[k]] for k in ks], ['games played', 'share still from last season']))
        A('')
        A('The preseason belief is half gone by four or five games and under 15% by twelve.')
        A('')

    A('## Calibration')
    A('')
    cal = rep.get('calibration', [])
    if cal:
        A(table([[c['bin'], c['n'], c['p_pred'], c['p_obs']] for c in cal],
                ['predicted bin', 'n', 'mean predicted', 'observed']))
        A('')

    A('## Firewall')
    A('')
    A('- layer A (ratings, venue, travel, rivalry, conference): tuned 2001-2013')
    A('- layer B (efficiency, matchup, blend, QB, schedule, total): tuned 2014-2019')
    A('- layer C (roster continuity, volatility, confidence): tuned 2018-2021')
    A('- headline test window: **%s**, untouched by every layer' % mh.get('window'))
    A('')
    if ms:
        A('Secondary window %s (layers A only were frozen by then): model spread MAE %s'
          % (ms.get('window'), ms.get('spread_mae_model')))
        A('vs market %s.' % ms.get('spread_mae_market'))
        A('')

    A('## Reproducing this')
    A('')
    A('```')
    A('./fetch_data.sh data')
    A('python3 ep_surface.py fit out')
    A('python3 build_market.py out')
    A('python3 build_team_game.py out')
    A('python3 features_roster.py out')
    A('python3 train_p4.py out')
    A('python3 train_layers.py out')
    A('python3 make_params.py out       # -> ../params.js')
    A('python3 gen_goldens.py out       # -> ../goldens.json')
    A('python3 gen_report.py out        # -> this file')
    A('node ../tests.js                 # must exit 0')
    A('```')
    A('')

    os.makedirs(os.path.dirname(DEST), exist_ok=True)
    with open(DEST, 'w') as f:
        f.write('\n'.join(L) + '\n')
    print('[write] %s' % os.path.abspath(DEST))


if __name__ == '__main__':
    main()
