// collective_public - SELF-CONTAINED BUNDLE for the Supabase dashboard editor.
// Generated from supabase/functions/ by tools/collective/bundle_functions.py.
// Do not edit this file: edit the sources and regenerate.
// Paste this whole file as index.ts for a function named exactly: collective_public
// IMPORTANT: turn OFF "Enforce JWT verification" for this function.
//
// ---------------------------------------------------------------------------
// TRANSCRIBED, NOT EXPORTED. Pasted in from the deployed function, the same way
// close/index.ts and learn/index.ts were: DIFF IT AGAINST THE DEPLOYED FUNCTION
// before treating it as authoritative. The _shared/ sources the header names,
// and bundle_functions.py itself, are not in this repository -- so until they
// are, this bundle IS the source and editing it is how the function changes.
//
// The four defects the deployed version already documents are preserved
// verbatim below (the missing sport/week, the collapse rule, the empty-season
// param, and the OPEN_BOARD_UNTIL_BILLING switch, still defaulted to what this
// function does today). WHAT THIS COMMIT ADDS on top of them:
//
//   5. /v1/dashboard/submit PICKED THE MODEL WITHOUT LOOKING AT THE SPORT.
//      It read models[0] when the envelope named none, refused outright when
//      the account had no model at all, and then OVERWROTE the envelope's
//      sport with whatever that model happened to be. This is the exact bug
//      that was fixed in collective_ingest and left standing here -- and this
//      is the route the dashboard's own uploader posts to, so it is the one a
//      contributor actually hits. A creator with a college model posting an
//      NFL slate had every NFL game looked up in the COLLEGE schedule and
//      every row came back unmatched, with nothing saying why.
//
//      resolveModel() below is the same rule collective_ingest now applies:
//      the sport is normalised first, the model is chosen from the models IN
//      THAT SPORT, a sport with no model gets one, and a model named in a
//      different sport does not win silently. The browser already resolves
//      this before it posts; the server enforcing it too is the point --
//      trusting the client to pick the right record is what made the original
//      bug possible.
//
//   6. /v1/dashboard/prompt REFUSED AN ACCOUNT WITH NO MODEL. The Universal
//      Prompt is how a creator wires their model up in the first place, so
//      "this account has no model yet" is the state it most needs to serve.
//      It renders against the account now, naming the sports it covers.
//
//   7. RULES SAID A RANKING MINIMUM THE PRODUCT REMOVED. This function serves
//      /v1/rules, and the site's Rules page renders it verbatim -- so while it
//      said "at least 60 percent of the season slate and at least 20 graded
//      games", the published rules contradicted the boards, which rank every
//      model from its first graded game. collective_admin already carried the
//      corrected version 2 and a comment saying, exactly right, that changing
//      it there alone "changes nothing anybody can see". This is that change,
//      in the function readers actually reach.
// ---------------------------------------------------------------------------

// ---------- inlined _shared/env.ts ----------
// Shared environment access for Collective edge functions.
// SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, and SUPABASE_ANON_KEY are injected
// by the Supabase runtime. COLLECTIVE_BASE_URL is an optional secret that
// points at the public site root and defaults to production.

const SB_URL: string = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_KEY: string = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const ANON_KEY: string = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
const BASE_URL: string = Deno.env.get("COLLECTIVE_BASE_URL") ?? "https://edgedesksports.com";

/* ---------------------------------------------------------------------------
   THE ONE SWITCH IN THIS FILE.

   true  = what this function does today: while billing.enabled is not true,
           ANY signed-in account sees every pre-kickoff number. A free account
           created a minute ago is entitled.
   false = what collective_embed already enforces: paid access only. The ways
           in are an EdgeDesk subscription, a Collective subscription, or
           being a creator (they built the board, so they see it).

   These two functions disagreeing about the same reader is the actual defect
   -- the embed shows them a locked board while the site shows them
   everything. Set this to false to close it. It is left true so that pasting
   this file is a pure bug fix and changes nothing about who can see what.
   --------------------------------------------------------------------------- */
const OPEN_BOARD_UNTIL_BILLING = true;
// ---------- inlined _shared/http.ts ----------
// Shared HTTP helpers: JSON responses, the contract error shape, CORS, and
// subpath routing. Every Collective edge function builds its responses here so
// the error taxonomy and CORS behavior stay identical across functions.

function corsHeaders(origin = "*"): Record<string, string> {
  const headers: Record<string, string> = {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers":
      "authorization, apikey, content-type, x-collective-key, x-client-info",
    "Access-Control-Max-Age": "86400",
  };
  if (origin !== "*") {
    headers["Vary"] = "Origin";
  }
  return headers;
}

function json(
  body: unknown,
  status = 200,
  headers: Record<string, string> = {},
): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      ...corsHeaders(),
      ...headers,
    },
  });
}

// Error response in the contract shape { error: { code, message, details } }.
// details is always present, null when there is nothing row-level to report.
function err(
  code: string,
  message: string,
  status: number,
  details?: unknown,
): Response {
  return json({ error: { code, message, details: details ?? null } }, status);
}

// Returns a 204 Response for OPTIONS requests, else null.
function preflight(req: Request, origin = "*"): Response | null {
  if (req.method !== "OPTIONS") return null;
  return new Response(null, { status: 204, headers: corsHeaders(origin) });
}

// Path after /functions/v1/<fnName>, normalized. Works both behind the
// production gateway (/functions/v1/<fnName>/...) and when served locally
// (/<fnName>/...). "" becomes "/", duplicate slashes collapse, and a
// trailing slash is stripped except on the root.
function subpath(req: Request, fnName: string): string {
  const pathname = new URL(req.url).pathname;
  const marker = `/${fnName}`;
  const idx = pathname.indexOf(marker);
  let rest = idx >= 0 ? pathname.slice(idx + marker.length) : pathname;
  if (!rest.startsWith("/")) rest = `/${rest}`;
  rest = rest.replace(/\/{2,}/g, "/");
  if (rest.length > 1 && rest.endsWith("/")) rest = rest.slice(0, -1);
  return rest;
}

// ---------- inlined _shared/db.ts ----------
// Shared database access. Edge functions never talk SQL: they call the
// SECURITY DEFINER RPCs in the collective schema through PostgREST with the
// service role key. RPCs return jsonb outcome objects like { ok: true, ... }
// or { ok: false, code: "token_expired", message: "..." }; callers translate
// ok:false codes to the HTTP error taxonomy. RpcError means an unexpected
// database failure and maps to 500 server_error (log it, never leak the body).

class RpcError extends Error {
  status: number;
  body: string;

  constructor(fn: string, status: number, body: string) {
    super(`rpc ${fn} failed with status ${status}`);
    this.name = "RpcError";
    this.status = status;
    this.body = body;
  }
}

async function rpc<T = unknown>(
  fn: string,
  args: Record<string, unknown>,
): Promise<T> {
  const res = await fetch(`${SB_URL}/rest/v1/rpc/${fn}`, {
    method: "POST",
    headers: {
      "apikey": SERVICE_KEY,
      "Authorization": `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
      "Content-Profile": "collective",
    },
    body: JSON.stringify(args),
  });
  const text = await res.text();
  if (!res.ok) {
    throw new RpcError(fn, res.status, text);
  }
  if (text === "") {
    return null as T;
  }
  return JSON.parse(text) as T;
}

// ---------- inlined _shared/keys.ts ----------
// Shared key and token primitives. Submission keys are
// mck_live_{8 base62}{32 base62} or mck_test_{8 base62}{32 base62}.
// Invite tokens are mci_{24 base62}. Only the sha256 hex of the full raw
// string is ever stored; the prefix is stored for lookup and display.

const BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

// Unbiased base62 string via rejection sampling over crypto.getRandomValues.
// 248 is the largest multiple of 62 that fits in a byte, so bytes at or above
// it are discarded instead of skewing the distribution.
function randBase62(n: number): string {
  const out: string[] = [];
  const buf = new Uint8Array(n * 2);
  while (out.length < n) {
    crypto.getRandomValues(buf);
    for (let i = 0; i < buf.length && out.length < n; i++) {
      const b = buf[i];
      if (b < 248) {
        out.push(BASE62[b % 62]);
      }
    }
  }
  return out.join("");
}

async function sha256hex(s: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const KEY_RE = /^mck_(live|test)_([0-9A-Za-z]{8})[0-9A-Za-z]{32}$/;

// Validates shape mck_live_<8+32 base62> or mck_test_<8+32 base62>.
// prefix is the 8 chars after mck_live_ or mck_test_.
function parseCollectiveKey(
  raw: string,
): { prefix: string; kind: "live" | "test" } | null {
  const m = KEY_RE.exec(raw);
  if (!m) return null;
  return { prefix: m[2], kind: m[1] as "live" | "test" };
}

// New submission key. The raw string is shown once; hash is sha256hex of the
// FULL raw key string.
async function newApiKey(
  kind: "live" | "test",
): Promise<{ raw: string; prefix: string; hash: string }> {
  const prefix = randBase62(8);
  const secret = randBase62(32);
  const raw = `mck_${kind}_${prefix}${secret}`;
  const hash = await sha256hex(raw);
  return { raw, prefix, hash };
}

// New invite token mci_<24 base62>; prefix is the first 8 of the 24; hash is
// sha256hex of the full raw token.
async function newInviteToken(): Promise<{
  raw: string;
  prefix: string;
  hash: string;
}> {
  const body = randBase62(24);
  const raw = `mci_${body}`;
  const hash = await sha256hex(raw);
  return { raw, prefix: body.slice(0, 8), hash };
}


/* A config key nobody has set must never be able to take a surface down.
   get_config is not guaranteed to answer null for an unknown key -- a
   deployment is free to raise on one -- and rpc() turns any non-2xx into a
   throw, which the handler turns into a 500 for every reader. This is the
   lesson collective_embed learned the hard way when two new keys took the
   whole embed off the air; a missing knob is a default. */
async function cfg(key: string): Promise<unknown> {
  try {
    return await rpc<unknown>("get_config", { p_key: key });
  } catch (e) {
    console.error("collective_public: config key", key, "unreadable:",
      e instanceof RpcError ? `${e.status} ${e.body}` : e);
    return null;
  }
}

// Length-independent, value-independent comparison for secret digests.
function timingSafeEqual(a: string, b: string): boolean {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

// ---------- inlined _shared/auth.ts ----------
// Shared JWT auth. Bearer tokens are validated against Supabase Auth by
// calling /auth/v1/user; the JWT is never decoded locally, so revoked or
// expired sessions fail closed.

async function getUser(
  req: Request,
): Promise<{ id: string; email: string | null } | null> {
  const authz = req.headers.get("authorization") ?? "";
  if (!/^Bearer\s+\S+/i.test(authz)) return null;
  let res: Response;
  try {
    res = await fetch(`${SB_URL}/auth/v1/user`, {
      headers: {
        "apikey": ANON_KEY,
        "Authorization": authz,
      },
    });
  } catch (e) {
    console.error("auth.getUser: auth service unreachable:", e);
    return null;
  }
  if (!res.ok) return null;
  const user = await res.json().catch(() => null) as
    | { id?: string; email?: string | null }
    | null;
  if (!user || typeof user.id !== "string" || user.id.length === 0) return null;
  return { id: user.id, email: typeof user.email === "string" ? user.email : null };
}

// getUser plus membership of admin.user_ids. Returns the user, or an err()
// Response (401 invalid_key or 403 forbidden) ready to return to the caller.
async function requireAdmin(
  req: Request,
): Promise<{ id: string; email: string | null } | Response> {
  const user = await getUser(req);
  if (!user) {
    return err("invalid_key", "A valid signed-in session is required.", 401);
  }
  const conf = await cfg("admin.user_ids");
  const ids = Array.isArray(conf) ? conf.filter((v) => typeof v === "string") : [];
  if (!ids.includes(user.id)) {
    return err("forbidden", "This account is not an administrator.", 403);
  }
  return user;
}

// ---------- inlined _shared/reads.ts ----------
// Shared read paths over the collective views via PostgREST, plus the
// response builders used by both the public API and the embed API. The
// embed and the site MUST render from identical data (Section 4 of the
// build prompt), so the builders live here once.

async function viewGet<T = unknown>(view: string, query: string): Promise<T[]> {
  const res = await fetch(`${SB_URL}/rest/v1/${view}?${query}`, {
    headers: {
      "apikey": SERVICE_KEY,
      "Authorization": `Bearer ${SERVICE_KEY}`,
      "Accept-Profile": "collective",
    },
  });
  if (!res.ok) {
    throw new Error(`view ${view} read failed: ${res.status} ${await res.text()}`);
  }
  return await res.json() as T[];
}

async function viewCount(view: string, query: string, column = "id"): Promise<number> {
  const res = await fetch(`${SB_URL}/rest/v1/${view}?select=${column}&${query}`, {
    method: "HEAD",
    headers: {
      "apikey": SERVICE_KEY,
      "Authorization": `Bearer ${SERVICE_KEY}`,
      "Accept-Profile": "collective",
      "Prefer": "count=exact",
    },
  });
  const range = res.headers.get("content-range") ?? "";
  const total = Number(range.split("/")[1]);
  return Number.isFinite(total) ? total : 0;
}

async function tableWrite(
  table: string,
  method: "POST" | "PATCH" | "DELETE",
  query: string,
  body?: unknown,
): Promise<unknown> {
  const res = await fetch(`${SB_URL}/rest/v1/${table}${query ? "?" + query : ""}`, {
    method,
    headers: {
      "apikey": SERVICE_KEY,
      "Authorization": `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
      "Content-Profile": "collective",
      "Prefer": "return=representation",
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`${method} ${table} failed: ${res.status} ${text}`);
  return text ? JSON.parse(text) : null;
}

// ------------------------------------------------------------ shapes

interface WallRow {
  creator_slug: string; creator_name: string; logo_url: string | null; monogram: string;
  founding: boolean; membership: string; model_slug: string; model_name: string; sport: string;
  record: {
    graded: number; wins: number; losses: number; pushes: number;
    win_pct: number | null; margin_mae: number | null; brier: number | null;
  } | null;
  coverage_pct: number | null; last_submission_at: string | null;
  website_url: string | null; x_handle: string | null;
}

interface WallViewRow {
  creator_slug: string; creator_name: string; logo_url: string | null; monogram: string;
  founding: boolean; website_url: string | null; x_handle: string | null; membership: string;
  model_slug: string; model_name: string; sport: string;
  graded: number | null; wins: number | null; losses: number | null; pushes: number | null;
  win_pct: number | null; margin_mae: number | null; brier: number | null;
  coverage_pct: number | null; last_submission_at: string | null;
}

const MEMBER_RANK: Record<string, number> = { "ACTIVE CONTRIBUTOR": 0, "MEMBER": 1, "INACTIVE": 2 };

function toWallRow(v: WallViewRow): WallRow {
  return {
    creator_slug: v.creator_slug, creator_name: v.creator_name, logo_url: v.logo_url,
    monogram: v.monogram, founding: v.founding, membership: v.membership,
    model_slug: v.model_slug, model_name: v.model_name, sport: v.sport,
    record: v.graded && v.graded > 0
      ? { graded: v.graded, wins: v.wins ?? 0, losses: v.losses ?? 0, pushes: v.pushes ?? 0,
          win_pct: v.win_pct, margin_mae: v.margin_mae, brier: v.brier }
      : null,
    coverage_pct: v.coverage_pct, last_submission_at: v.last_submission_at,
    website_url: v.website_url, x_handle: v.x_handle,
  };
}

// Canonical order everywhere: membership rank, then graded desc, then name.
// One ordering for every host and every surface (Section 4 hard rule).
async function buildWall(): Promise<WallRow[]> {
  const rows = await viewGet<WallViewRow>("model_wall", "select=*");
  return rows.map(toWallRow).sort((a, b) =>
    (MEMBER_RANK[a.membership] ?? 9) - (MEMBER_RANK[b.membership] ?? 9) ||
    ((b.record?.graded ?? 0) - (a.record?.graded ?? 0)) ||
    a.creator_name.localeCompare(b.creator_name));
}

interface MetaShape {
  name: string;
  pricing: { monthly_cents: number; annual_cents: number; currency: string };
  billing_live: boolean;
  sports: { code: string; name: string; season: number; in_season: boolean }[];
  counts: { creators: number; models: number; graded_games: number; live_projections: number };
  urls: { site: string; join_info: string; rules: string };
}

async function buildMeta(): Promise<MetaShape> {
  const [monthly, annual, billing, sports, seasons] = await Promise.all([
    cfg("pricing.monthly_cents"),
    cfg("pricing.annual_cents"),
    cfg("billing.enabled"),
    viewGet<{ code: string; name: string; active: boolean }>("sports", "select=code,name,active&active=is.true"),
    viewGet<{ sport_code: string; season: number; starts_on: string; ends_on: string }>(
      "sport_seasons", "select=*&order=season.desc"),
  ]);
  const [creators, models, settled, liveRows] = await Promise.all([
    viewCount("creators", "is_listed=is.true&status=eq.active"),
    viewCount("models", "is_listed=is.true"),
    viewCount("games", "status=eq.final"),
    viewCount("projections", "data_origin=eq.live&resolution_status=eq.resolved"),
  ]);
  const today = new Date().toISOString().slice(0, 10);
  const site = `${BASE_URL}/collective/`;
  return {
    name: "Model Collective",
    pricing: { monthly_cents: Number(monthly ?? 2499), annual_cents: Number(annual ?? 0), currency: "usd" },
    billing_live: billing === true,
    sports: sports.map((s) => {
      const season = seasons.find((x) => x.sport_code === s.code);
      return {
        code: s.code, name: s.name, season: season?.season ?? new Date().getFullYear(),
        in_season: !!season && season.starts_on <= today && today <= season.ends_on,
      };
    }),
    counts: { creators, models, graded_games: settled, live_projections: liveRows },
    urls: { site, join_info: site + "#about", rules: site + "#rules" },
  };
}

// ------------------------------------------------------------ the board

interface GameDetailRow {
  game_id: string; sport: string; season: number; week: number | null; kickoff_at: string;
  status: string; home: string; away: string; label: string;
  home_score: number | null; away_score: number | null;
  closing_spread: number | null; closing_total: number | null;
}
interface BoardModelRow {
  game_id: string; model_id: string; creator_slug: string; model_slug: string;
  pick_side: string | null; projected_spread: number | null; projected_total: number | null;
  home_win_prob: number | null; line_at_submission: number | null; cover_prob: number | null;
  received_at: string; is_late: boolean;
  pick_result: string | null; margin_error: number | null; brier: number | null;
  // Both optional: whether the view exposes them is exactly what this file
  // must stop depending on. See collapseModels.
  movement_n?: number | null;
  superseded_at?: string | null;
}
interface ConsensusRow {
  game_id: string; n: number; spread_mean: number | null; spread_median: number | null;
  spread_stdev: number | null; spread_min: number | null; spread_max: number | null;
  total_mean: number | null; total_median: number | null; home_win_prob_mean: number | null;
  n_picks: number; pct_picks_home: number | null; agreement: number | null;
}

interface GamesPayload {
  sport: string; season: number; week: number | null; entitled: boolean;
  games: unknown[];
}

/* ONE ROW PER MODEL PER GAME, and how many submissions are behind it.

   This function used to map every row board_models returned, which meant the
   central rule of the whole Collective -- each model is graded and shown on
   its FIRST pre-kickoff live submission -- was asserted nowhere in the code
   that serves the board. Two things followed from that.

   If the view ever stops collapsing, the wall renders the same model twice on
   one game with nothing saying which one is graded. And movement_n, which the
   site prints as the +n beside a pick to tell a creator their re-upload WAS
   received, was passed through only where the view happened to carry it --
   so on a deployment where it does not, a creator who re-uploads is told
   nothing at all, which is the complaint that started this.

   board_models is read ordered by received_at.asc, so the first row seen for
   a model is its earliest. A late row does not hold the graded slot, so a
   non-late row always takes it.

   The fallback order matters more than the count. Counting alone, against a
   view that already collapses, would report 1 for every row -- a confident,
   wrong "no revision ever arrived", which is worse than the silence it
   replaced. So the count is used only where this collapse actually SEES more
   than one row, and the view's own number is trusted otherwise.

   superseded_at is filtered for the day 01_supersede.sql is applied. Until
   that column exists it is undefined, so nothing is filtered and this is a
   no-op: the readers and the migration can be deployed in either order. */
function collapseModels(rows: BoardModelRow[]): (BoardModelRow & { movement_n: number })[] {
  const by = new Map<string, BoardModelRow[]>();
  for (const m of rows) {
    if (m.superseded_at) continue;
    const k = `${m.creator_slug}/${m.model_slug}`;
    const list = by.get(k);
    if (list) list.push(m);
    else by.set(k, [m]);
  }
  const out: (BoardModelRow & { movement_n: number })[] = [];
  for (const list of by.values()) {
    const graded = list.find((m) => !m.is_late) ?? list[0];
    const fromView = Number(graded.movement_n);
    out.push({
      ...graded,
      movement_n: list.length > 1
        ? list.length
        : (Number.isFinite(fromView) && fromView > 0 ? fromView : 1),
    });
  }
  return out;
}

// The paid gate lives here, in the response body: a locked row carries no
// projection numbers at all (Section 5: the gate is in the API, not the DOM).
async function buildGames(
  sport: string, season: number, week: number | null, entitled: boolean,
): Promise<GamesPayload> {
  const wq = week === null ? "" : `&week=eq.${week}`;
  const games = await viewGet<GameDetailRow>(
    "game_detail", `select=*&sport=eq.${sport}&season=eq.${season}${wq}&order=kickoff_at.asc`);
  if (games.length === 0) return { sport, season, week, entitled, games: [] };
  const ids = games.map((g) => `"${g.game_id}"`).join(",");
  const [models, consensus] = await Promise.all([
    viewGet<BoardModelRow>("board_models", `select=*&game_id=in.(${ids})&order=received_at.asc`),
    viewGet<ConsensusRow>("consensus", `select=*&game_id=in.(${ids})`),
  ]);
  const now = Date.now();
  return {
    sport, season, week, entitled,
    games: games.map((g) => {
      const settled = g.status === "final" || (g.home_score !== null);
      // Postponed and canceled games keep a stale kickoff_at in the past;
      // they must stay locked or their pre-game numbers would leak free.
      const open = !settled &&
        (g.status === "postponed" || g.status === "canceled" ||
          new Date(g.kickoff_at).getTime() > now);
      const unlocked = entitled || settled || !open;
      const c = consensus.find((x) => x.game_id === g.game_id) ?? null;
      return {
        // sport and week ride along so a board carrying more than one sport
        // can say which is which, and so the model page's game log stops
        // printing "Wundefined". The collective_embed copy of this builder
        // has carried them since the multi-sport fix; this one had not, and
        // two copies of a "shared" builder that disagree IS the bug.
        game_id: g.game_id, sport: g.sport, week: g.week,
        label: g.label, home: g.home, away: g.away,
        kickoff_at: g.kickoff_at, status: g.status,
        result: settled && g.home_score !== null
          ? { home_score: g.home_score, away_score: g.away_score,
              closing_spread: g.closing_spread, closing_total: g.closing_total }
          : null,
        consensus: !c || c.n === 0
          ? (unlocked ? null : { locked: true, n: c?.n ?? 0 })
          : (unlocked
            ? { locked: false, n: c.n, spread_mean: c.spread_mean, spread_median: c.spread_median,
                spread_stdev: c.spread_stdev, spread_min: c.spread_min, spread_max: c.spread_max,
                total_mean: c.total_mean, total_median: c.total_median,
                home_win_prob_mean: c.home_win_prob_mean,
                pct_picks_home: c.pct_picks_home, agreement: c.agreement }
            : { locked: true, n: c.n }),
        // movement_n is on BOTH branches on purpose. It is a count of
        // submissions, not a projection, so it is not a paid number -- and a
        // locked reader learning that a model revised a game learns nothing
        // they could bet on. Withholding it would put a creator's own "did my
        // re-upload land?" answer behind the paywall.
        models: collapseModels(models.filter((m) => m.game_id === g.game_id)).map((m) =>
          unlocked
            ? { creator_slug: m.creator_slug, model_slug: m.model_slug, locked: false,
                late: m.is_late, pick_side: m.pick_side, projected_spread: m.projected_spread,
                projected_total: m.projected_total, home_win_probability: m.home_win_prob,
                line_at_submission: m.line_at_submission, cover_probability: m.cover_prob,
                received_at: m.received_at, movement_n: m.movement_n,
                grade: m.pick_result !== null || m.margin_error !== null || m.brier !== null
                  ? { pick_result: m.pick_result, margin_error: m.margin_error, brier: m.brier }
                  : null }
            : { creator_slug: m.creator_slug, model_slug: m.model_slug, locked: true,
                movement_n: m.movement_n }),
      };
    }),
  };
}

/* EdgeDesk's own PAYING accounts, read from the PUBLIC schema (no
   Accept-Profile) rather than the collective one. One subscription to the
   platform is one subscription to the Collective's numbers.

   PAID, not merely present: a free EdgeDesk account is a signed-in reader and
   nothing more. Best effort ON PURPOSE -- this is the one table read here
   that lives outside the Collective's own schema, so a rename there must cost
   this check and nothing else, never the whole board. Copied from
   collective_embed so the two functions answer the same question the same
   way. Only reached when OPEN_BOARD_UNTIL_BILLING is false. */
async function edgedeskPaid(userId: string): Promise<boolean> {
  try {
    const res = await fetch(
      `${SB_URL}/rest/v1/subscriptions?select=user_id&user_id=eq.${userId}` +
        `&status=in.(active,trialing,past_due)`,
      {
        method: "HEAD",
        headers: {
          "apikey": SERVICE_KEY,
          "Authorization": `Bearer ${SERVICE_KEY}`,
          "Prefer": "count=exact",
        },
      },
    );
    if (!res.ok) {
      console.error("collective_public: edgedesk paid check failed:", res.status);
      return false;
    }
    const total = Number((res.headers.get("content-range") ?? "").split("/")[1]);
    return Number.isFinite(total) && total > 0;
  } catch (e) {
    console.error("collective_public: edgedesk paid check threw:", e);
    return false;
  }
}

/* Entitlement: an active subscriber, or any creator (they contributed to the
   board), checked by the Collective and never by a host site. */
async function isEntitled(userId: string | null): Promise<boolean> {
  if (!userId) return false;
  if (OPEN_BOARD_UNTIL_BILLING) {
    const billing = await cfg("billing.enabled");
    if (billing !== true) return true;
    const [subs, creators] = await Promise.all([
      viewCount("subscribers", `user_id=eq.${userId}&status=in.(active,past_due)`),
      viewCount("creators", `user_id=eq.${userId}&status=eq.active`),
    ]);
    return subs > 0 || creators > 0;
  }
  const [subs, creators, edgedesk] = await Promise.all([
    viewCount("subscribers", `user_id=eq.${userId}&status=in.(active,trialing,past_due)`),
    viewCount("creators", `user_id=eq.${userId}&status=eq.active`),
    edgedeskPaid(userId),
  ]);
  return creators > 0 || subs > 0 || edgedesk;
}

/* The season a request means. "" IS NOT ABSENT: ?season= (which the site
   sends whenever its own season is falsy) survives ??, Number("") is 0, and 0
   is finite. So the season became 0, the game_detail filter matched nothing,
   and the board came back valid and empty with nothing anywhere saying why.
   Blank now means absent; a non-numeric season is still a 422. */
function seasonParam(raw: string | null, fallback: number | undefined): number {
  const s = (raw ?? "").trim();
  return s === "" ? Number(fallback) : Number(s);
}

/* ==== CURRENT-WEEK RESOLVER — mirror of collective/week.js ================
   WHAT THIS REPLACED, AND WHY. Current used to be "the week of the earliest
   game kicking off at or after now minus 36 hours". The grace existed so a
   week stayed current through its Monday night game, but it was applied to
   the EARLIEST game found rather than to the week's LAST one — so any game
   played inside the last 36 hours pinned Current to its week. A Monday night
   college game (SMU @ Florida State, Sep 7) kept /v1/games, and therefore the
   Collective's whole front page, on the finished Week 1 slate all through
   Sep 8, with Week 2 loaded and invisible.

   It was also the wrong question. A week is not current because of a clock
   offset. It is current because it still has football left in it.

   THE RULE: Current is the earliest week that still has a game to be played;
   when no week does, the last week that has games. Nothing here derives a
   week from a date — it reads the week the schedule provider stated, which is
   the only thing that survives Week 0, Thursday games, Tuesday games,
   conference championships, bowls and four playoff rounds.

   The block between the markers is a LINE-FOR-LINE mirror of the same
   functions in collective/week.js, which this bundle cannot import because
   the dashboard bundles one folder. tools/collective/week_resolution.test.js
   extracts it and runs both against the same table of cases, so the two
   cannot drift into being two competing answers.

   ---8<--- MIRROR OF collective/week.js — KEEP IN STEP ---8<--- */
const IN_PLAY_MS = 8 * 3600 * 1000;

interface WeekGame {
  week: number | null;
  kickoff_at?: string | null;
  status?: string | null;
  home_score?: number | null;
  away_score?: number | null;
  result?: { home_score?: number | null; away_score?: number | null } | null;
}

function weekMs(v: string | null | undefined): number {
  if (v == null || v === "") return NaN;
  const t = new Date(v).getTime();
  return isFinite(t) ? t : NaN;
}

function hasFinal(g: WeekGame): boolean {
  if (!g) return false;
  const r = g.result;
  if (r && r.home_score != null && r.away_score != null) return true;
  if (g.home_score != null && g.away_score != null) return true;
  return String(g.status ?? "").toLowerCase() === "final";
}

function gameState(g: WeekGame, now: number): string {
  if (!g) return "void";
  const st = String(g.status ?? "").toLowerCase();
  if (st === "canceled" || st === "cancelled") return "void";
  if (hasFinal(g)) return "final";
  const k = weekMs(g.kickoff_at);
  if (st === "postponed") return (isFinite(k) && k > now) ? "upcoming" : "void";
  if (!isFinite(k)) return "upcoming";
  if (k > now) return "upcoming";
  if (now - k < IN_PLAY_MS) return "live";
  return "stale";
}

function isPending(g: WeekGame, now: number): boolean {
  const s = gameState(g, now);
  return s === "upcoming" || s === "live";
}

function weekOf(g: WeekGame): number | null {
  if (!g || g.week == null) return null;
  const w = Number(g.week);
  return (isFinite(w) && Math.floor(w) === w && w >= 0) ? w : null;
}

function weekNumbers(games: WeekGame[]): number[] {
  const seen: Record<number, boolean> = {};
  const out: number[] = [];
  (games || []).forEach((g) => {
    const w = weekOf(g);
    if (w == null || seen[w]) return;
    seen[w] = true; out.push(w);
  });
  return out.sort((a, b) => a - b);
}

function weekIsActive(games: WeekGame[], week: number, now: number): boolean {
  const w = Number(week);
  return (games || []).some((g) => weekOf(g) === w && isPending(g, now));
}

function firstActiveWeek(games: WeekGame[], now: number): number | null {
  const weeks = weekNumbers(games);
  for (const w of weeks) if (weekIsActive(games, w, now)) return w;
  return null;
}
/* ---8<--- END MIRROR ---8<--- */

/* How many weeks past the first candidate to read before trusting the answer.
   The SQL below narrows to the earliest week that CAN still have football in
   it, and the rule above then decides on the real rows — reading a few weeks
   rather than one so a filter that is merely close cannot decide by itself. */
const WEEK_LOOKAHEAD = 3;

/* The current slate week, by the rule above, in at most three small reads. */
async function currentWeek(sport: string, season: number): Promise<number | null> {
  const now = Date.now();
  const floor = new Date(now - IN_PLAY_MS).toISOString();
  /* The earliest week that can still have a game to be played. Every filter
     here is implied by isPending(), so this can only be at or before the
     answer — never past it, which is what makes reading forward from it safe.
     A game already scored, already marked final, or canceled is not pending;
     nor is one whose kickoff is further back than the in-play window. */
  const cand = await viewGet<{ week: number | null }>("game_detail",
    `select=week&sport=eq.${sport}&season=eq.${season}&week=not.is.null` +
    `&home_score=is.null&status=not.in.(final,canceled,cancelled)` +
    `&kickoff_at=gte.${encodeURIComponent(floor)}&order=week.asc&limit=1`);
  const from = cand[0]?.week;
  if (from != null) {
    const rows = await viewGet<WeekGame>("game_detail",
      `select=week,kickoff_at,status,home_score,away_score` +
      `&sport=eq.${sport}&season=eq.${season}` +
      `&week=gte.${from}&week=lte.${from + WEEK_LOOKAHEAD}&order=week.asc`);
    const w = firstActiveWeek(rows, now);
    if (w != null) return w;
  }
  /* Nothing left to play anywhere: the season is over, or the schedule has
     not been loaded past it. The last week that HAS games is the answer, by
     week number rather than by kickoff — a bowl moved into January is still
     that week's game. */
  const last = await viewGet<{ week: number | null }>("game_detail",
    `select=week&sport=eq.${sport}&season=eq.${season}&week=not.is.null&order=week.desc&limit=1`);
  return last[0]?.week ?? null;
}

/* THE PUBLISHED RULES. Version 2.

   The site's Rules page renders this array VERBATIM from /v1/rules, and while
   it carried the version 1 text it told readers a model needed "at least 60
   percent of the season slate to date and at least 20 graded games" to be
   ranked. The product removed that floor: the boards rank every model from
   its first graded game and publish the sample beside the record.

   So the published rules contradicted the boards, in the one place a reader
   goes to find out what the rules ARE. collective_admin already carried this
   corrected copy and a comment saying, exactly right, that fixing it there
   alone "changes nothing anybody can see" -- because this is the function
   that serves it. Now they agree. */
const RULES = {
  version: 2,
  rules: [
    "Pick result: decided by the final score. The actual margin is measured against the Collective's own captured closing spread (home convention) on the pick side; the captured close is the yardstick so every model faces the same number, never the line a creator reports. Push on the exact number, excluded from win percentage. Never graded against a creator-supplied result column.",
    "Margin error: absolute difference between projected home margin and actual home margin. Projected home margin comes from projected scores when given, otherwise from the projected spread.",
    "Brier: squared error on the moneyline home win probability. 0.25 is a coin flip. Lower is better.",
    "First submission: each model is graded on its first pre-kickoff live submission per game, timestamped on server receipt. Later revisions are stored and shown as movement, never regraded. Post-kickoff receipts are stored, marked late, and excluded. Backfill and test data are stored, shown separately, and excluded from records, rankings, and consensus.",
    "Rankings: every model is ranked from its first graded game. There is no coverage floor and no minimum sample. Win percentage, margin error, and Brier are ranked separately and never blended, and a model's sample size is published beside its record so a short one can be read for what it is.",
    "Active participation: at least 3 eligible model projections per week within your declared sport or scope. Members who repeatedly submit fewer than that, or who miss weeks without communication, may be moved to inactive or removed. Personal betting activity does not matter: submit the model's output, not only the games you choose to bet.",
  ],
};

// ---------- inlined _shared/prompt_template.ts ----------
// The Universal Creator Prompt. This constant is the single source; the
// human-readable copy lives at collective/claude-prompt-template.md and must
// stay identical. It ships in the same repo and same deploy as the API, so
// an endpoint change and its prompt change land in one commit.

const PROMPT_TEMPLATE = `You are helping {{CREATOR_NAME}} connect their sports model to the Model Collective. The Collective is shared infrastructure for independent creators: they send finished projections to one endpoint, and the Collective grades them, shows them on a shared wall, and sends traffic back. You are working inside the creator's own project. Their model, code, and site belong to them and stay exactly as they are.

Follow these steps in order. Do not skip the confirmations.

1. Inspect first. Look through this project and report what you find before changing anything: what it is built with (plain HTML, React, Next.js, Vue, Node, Python, Flask, Django, Supabase, Firebase, a GitHub Action, or a script run by hand), and where it runs. Do not assume any particular framework. Everything below works for all of them.

2. Find the finished numbers. Locate where this project produces its final projections (a CSV file, a database table, a function's output, a spreadsheet export). Show {{CREATOR_NAME}} what you found and confirm it is the right place before going further.

3. Map the fields. The Collective accepts one JSON envelope per slate. Map the creator's fields to it and SHOW THE MAPPING for approval before sending anything. Required per game: game_ref (their own id for the game, any format), home_team, away_team, kickoff (ISO time). Optional, only if the model already produces them: pick_side (home or away), projected_spread (home team's number, negative means home favored), projected_total, proj_home_score, proj_away_score, home_win_probability (moneyline chance the home team wins, 0 to 1), cover_probability (chance the pick covers, 0 to 1, requires line_at_submission), line_at_submission, confidence. Do not invent numbers the model does not produce, and do not build any new modeling work. If a field means something different in their data (for example a result column that means "the pick covered"), leave it out and say so.

4. Never send proprietary logic. Only finished outputs leave this project: the numbers above, nothing else. No source code, no weights, no formulas, no intermediate data. Say this plainly to {{CREATOR_NAME}} and confirm they agree with what will be sent.

5. Add, do not rebuild. Put the submission code in one new file plus a small "Send to Model Collective" trigger that fits how this project already runs (a button, a script command, a step at the end of their pipeline). Do not restructure the project, do not touch the model logic, do not change any existing output.

6. Keep the key private. The API key below must never appear in a public page or a public repo. For a server or a script, read it from an environment variable named COLLECTIVE_KEY. For a purely static site, do not put the key in the browser: use a GitHub Action with a repository secret instead, like this:

   name: Send to Model Collective
   on: [workflow_dispatch, schedule]
   jobs:
     submit:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - run: |
             curl -s -X POST "{{API_BASE}}/collective_ingest/v1/projections" \\
               -H "x-collective-key: $COLLECTIVE_KEY" \\
               -H "content-type: application/json" \\
               --data @projections.json
           env:
             COLLECTIVE_KEY: \${{ secrets.COLLECTIVE_KEY }}

   Or a local Python script with only the standard library: read the JSON, urllib.request.urlopen a POST to the same URL with the x-collective-key header from os.environ.

7. Add the Collective tab. Put this snippet on one page or route of the creator's site, and nowhere else. It renders the whole Collective inside their site and touches nothing else on the page:

   {{EMBED_SNIPPET}}

8. Dry run first. Before anything goes live, send the mapped slate to the test endpoint and show {{CREATOR_NAME}} the exact JSON you sent and the exact response:

   POST {{API_BASE}}/collective_ingest/v1/projections/dry-run
   header x-collective-key: the key below

   The response lists every row as resolved, quarantined, late, or rejected, with reasons. Nothing is stored. Fix any rejected rows, rerun, and only then switch the URL to /v1/projections for the real submission.

9. Report back. When done, tell {{CREATOR_NAME}}: which files you added or changed, how to submit going forward and how often (before kickoff matters: only the first submission per game before kickoff counts toward their record), what to do if a submission fails (the response says exactly which row and why; quarantined rows are fine, a human resolves them), and that the key can be rotated any time at {{DASHBOARD_URL}}.

Credentials and identity for this creator:
  Creator: {{CREATOR_NAME}}
  Model: {{MODEL_NAME}} ({{SPORT}})
  API base: {{API_BASE}}
  API key (treat like a password): {{API_KEY}}
  Docs and grading rules: {{DOCS_URL}}

One honest rule to close on: the Collective grades every model the same way, against its own closing lines, on first submissions only. Backfilled history is stored and shown separately but never graded. Send the whole slate, not just the confident games, because slate coverage is published next to the record.`;

function renderPrompt(vars: Record<string, string>): string {
  let out = PROMPT_TEMPLATE;
  for (const [k, v] of Object.entries(vars)) {
    out = out.split(`{{${k}}}`).join(v);
  }
  return out;
}

// ---------- inlined _shared/sports.ts ----------
// One sport, one family. The same map as collective.sport_aliases, the SPORTS
// registry in collective/index.html, collective_ingest and collective_join --
// changed together or not at all. The database is the authority (the unique
// index is built on it); this copy exists so a function that bundles no
// imports can MATCH a sport without a round trip. It never decides what gets
// stored: creation goes through the database function, which canonicalises.
const SPORT_ALIASES: Record<string, string> = {
  NFL: "NFL",
  NATIONALFOOTBALLLEAGUE: "NFL",
  PROFOOTBALL: "NFL",
  NFLFOOTBALL: "NFL",
  AMERICANFOOTBALLNFL: "NFL",
  CFB: "CFB",
  NCAAF: "CFB",
  CFBP4: "CFB",
  COLLEGE: "CFB",
  NCAAFOOTBALL: "CFB",
  COLLEGEFOOTBALL: "CFB",
  NCAAFB: "CFB",
  CFP: "CFB",
  AMERICANFOOTBALLNCAAF: "CFB",
};

function sportFamily(code: unknown): string | null {
  const k = String(code ?? "").toUpperCase().replace(/[^A-Z0-9]+/g, "");
  if (!k) return null;
  return SPORT_ALIASES[k] ?? k;
}

interface ModelRow { id: string; slug: string; name: string; sport_code: string }
interface CreatedModel {
  model_id: string; model_slug: string; model_name: string; sport: string; created: boolean;
}

/* GET-OR-CREATE, and the only way this function ever makes a model.
   collective.get_or_create_model (supabase/collective_model_autocreate.sql)
   does the work: it normalises the sport, serialises on (creator, sport) with
   an advisory lock, inserts on conflict do nothing and reads the row back, so
   two submissions arriving at the same instant get the same model. Where the
   migration has not been run the row is written directly and a duplicate is
   re-read, so a contributor is never blocked on it. */
async function getOrCreateModel(
  creator: { id: string; slug: string; display_name: string },
  sport: string,
): Promise<CreatedModel> {
  try {
    const rows = await rpc<CreatedModel[] | CreatedModel | null>("get_or_create_model", {
      p_creator_id: creator.id, p_sport: sport, p_model_name: null,
    });
    const row = Array.isArray(rows) ? rows[0] : rows;
    if (row && row.model_slug) return row;
    throw new Error("get_or_create_model returned no row");
  } catch (e) {
    const missing = e instanceof RpcError &&
      (e.status === 404 || /PGRST202|PGRST203|could not find the function/i.test(e.body));
    if (!missing) throw e;
    console.error(
      "collective_public: collective.get_or_create_model is not installed " +
        "(run supabase/collective_model_autocreate.sql); creating the model directly.",
    );
  }
  const code = String(sport).toUpperCase().trim();
  const slug = `${creator.slug}-${code.toLowerCase().replace(/[^a-z0-9]+/g, "")}`;
  const name = `${creator.display_name || creator.slug} ${code}`.slice(0, 60);
  try {
    const made = await tableWrite("models", "POST", "", [{
      creator_id: creator.id, slug, name, sport_code: code, is_listed: true,
    }]) as { id?: string; slug?: string; name?: string; sport_code?: string }[] | null;
    const row = Array.isArray(made) ? made[0] : null;
    if (row?.slug) {
      return {
        model_id: String(row.id ?? ""), model_slug: row.slug,
        model_name: row.name ?? name, sport: row.sport_code ?? code, created: true,
      };
    }
  } catch (e) {
    const msg = String((e as Error)?.message ?? e);
    if (!/duplicate key|23505|already exists|conflict/i.test(msg)) throw e;
  }
  const back = await viewGet<ModelRow>(
    "models",
    `select=id,slug,name,sport_code&creator_id=eq.${encodeURIComponent(creator.id)}` +
      `&slug=eq.${encodeURIComponent(slug)}&limit=1`,
  );
  if (!back[0]) throw new Error(`the ${code} model could not be created`);
  return {
    model_id: back[0].id, model_slug: back[0].slug, model_name: back[0].name,
    sport: back[0].sport_code, created: false,
  };
}

interface ResolvedModel { model: ModelRow; created: boolean; note?: string }

/* WHICH MODEL THIS SLATE IS FOR -- and the sport decides.
   The same rule collective_ingest applies, on the route the dashboard's own
   uploader posts to. Before this, an account with one model got that one
   whatever sport the envelope said, so an NFL slate from a college creator was
   matched against the college schedule and every row came back unmatched. */
async function resolveModel(
  creator: { id: string; slug: string; display_name: string },
  models: ModelRow[],
  wanted: unknown,
  wantedSport: unknown,
): Promise<ResolvedModel | { error: Response }> {
  const named = typeof wanted === "string" && wanted
    ? models.find((m) => m.slug === wanted) ?? null
    : null;
  if (typeof wanted === "string" && wanted && !named) {
    return { error: err("invalid_payload",
      `No model named "${wanted}" on this account. Available: ${
        models.map((m) => m.slug).join(", ") || "none yet"}.`, 422) };
  }

  const fam = sportFamily(wantedSport);
  if (!fam) {
    if (named) return { model: named, created: false };
    if (models.length === 1) return { model: models[0], created: false };
    if (models.length === 0) {
      return { error: err("invalid_payload",
        'This envelope does not say which sport it is for, and this account has no model yet. ' +
        'Add "sport" (for example "sport": "NFL") and the model for it is created with this submission.',
        422) };
    }
    return { error: err("invalid_payload",
      `This account has several models; set "sport", or set "model" to one of: ${
        models.map((m) => m.slug).join(", ")}.`, 422) };
  }

  if (named && sportFamily(named.sport_code) === fam) return { model: named, created: false };

  const inSport = models.filter((m) => sportFamily(m.sport_code) === fam);
  const switched = named
    ? `This slate says sport "${String(wantedSport)}" and "${named.slug}" is a ${named.sport_code} ` +
      `model, so it was filed under this account's ${fam} model instead. A ${fam} slate under a ` +
      `${named.sport_code} model is looked up in the wrong schedule and every game comes back unmatched.`
    : undefined;

  if (inSport.length === 1) return { model: inSport[0], created: false, note: switched };
  if (inSport.length > 1) {
    return { error: err("invalid_payload",
      `This account has several ${fam} models; set "model" to one of: ${
        inSport.map((m) => m.slug).join(", ")}.`, 422) };
  }

  // Nothing for this sport yet. That is not a refusal any more.
  let made: CreatedModel;
  try {
    made = await getOrCreateModel(creator, String(wantedSport));
  } catch (e) {
    if (e instanceof RpcError) {
      console.error("collective_public: get_or_create_model failed:", e.message, e.body);
    } else {
      console.error("collective_public: get_or_create_model failed:", e);
    }
    return { error: err("server_error",
      `This account has no ${fam} model and one could not be created. Nothing was saved.`, 500) };
  }
  const model: ModelRow = {
    id: made.model_id, slug: made.model_slug, name: made.model_name, sport_code: made.sport,
  };
  if (!models.some((m) => m.slug === model.slug)) models.push(model);
  return {
    model,
    created: made.created,
    note: switched ?? (made.created
      ? `This account had no ${fam} model, so "${model.name}" was created for it. ` +
        "Nothing about your file needs to change."
      : undefined),
  };
}

// ---------- collective_public/index.ts ----------
// Model Collective public read API. Free surfaces are genuinely free (they
// are the marketing surface); paid surfaces gate IN THE RESPONSE BODY, so
// no unentitled caller ever receives a pre-kickoff number (Section 5).
// Dashboard routes serve the signed-in creator only.

const FREE_CACHE = { "cache-control": "public, max-age=60" };
const NO_STORE = { "cache-control": "no-store" };

interface CreatorRow {
  id: string; user_id: string | null; slug: string; display_name: string;
  description: string | null; website_url: string | null; x_handle: string | null;
  logo_url: string | null; founding_member: boolean; billing_mode: string;
  referral_share_bps: number; pinned_model_id: string | null; created_at: string;
}

function pub(c: CreatorRow, membership: string, monogram: string, pinned: string | null) {
  return {
    slug: c.slug, display_name: c.display_name, description: c.description,
    website_url: c.website_url, x_handle: c.x_handle, logo_url: c.logo_url,
    monogram, founding: c.founding_member, membership,
    joined_at: c.created_at, pinned_model_slug: pinned,
  };
}

async function creatorPayload(slug: string) {
  const wall = await buildWall();
  const mine = wall.filter((w) => w.creator_slug === slug);
  if (mine.length === 0) return null;
  const creators = await viewGet<CreatorRow>("creators", `select=*&slug=eq.${slug}&limit=1`);
  if (creators.length === 0) return null;
  const c = creators[0];
  const backfill = await viewGet<{ model_id: string; rows: number }>("model_backfill", `select=*`);
  const models = await viewGet<{ id: string; slug: string }>(
    "models", `select=id,slug&creator_id=eq.${c.id}`);
  const pinned = models.find((m) => m.id === c.pinned_model_id)?.slug ?? null;
  const anyLive = mine.some((w) => w.last_submission_at !== null);
  return {
    creator: pub(c, mine[0].membership, mine[0].monogram, pinned),
    models: mine.map((w) => {
      const modelId = models.find((m) => m.slug === w.model_slug)?.id;
      const bf = backfill.find((b) => b.model_id === modelId);
      return {
        model_slug: w.model_slug, model_name: w.model_name, sport: w.sport,
        record: w.record, coverage_pct: w.coverage_pct, last_submission_at: w.last_submission_at,
        backfill: bf ? { rows: bf.rows, note: "Backfilled history, shown separately, never ranked" } : null,
      };
    }),
    empty_state: !anyLive,
  };
}

async function requireCreator(req: Request): Promise<{ user: { id: string }; creator: CreatorRow } | Response> {
  const user = await getUser(req);
  if (!user) return err("invalid_key", "Sign in to use the dashboard.", 401);
  const rows = await viewGet<CreatorRow>("creators", `select=*&user_id=eq.${user.id}&limit=1`);
  if (rows.length === 0) return err("not_found", "This account has no creator profile.", 404);
  return { user, creator: rows[0] };
}

Deno.serve(async (req) => {
  const pre = preflight(req);
  if (pre) return pre;
  const path = subpath(req, "collective_public");

  try {
    // ------------------------------------------------------------ free
    if (req.method === "GET" && path === "/v1/meta") {
      return json(await buildMeta(), 200, FREE_CACHE);
    }
    if (req.method === "GET" && path === "/v1/wall") {
      return json({ generated_at: new Date().toISOString(), rows: await buildWall() }, 200, FREE_CACHE);
    }
    if (req.method === "GET" && path === "/v1/rules") {
      return json(RULES, 200, FREE_CACHE);
    }
    if (req.method === "GET" && path === "/v1/rankings") {
      interface RankRow {
        creator_slug: string; creator_name: string; model_slug: string; model_name: string;
        sport: string; graded: number | null; coverage_pct: number | null;
        win_pct: number | null; margin_mae: number | null; brier: number | null;
        is_ranked: boolean; unranked_reason: string | null;
        rank_win_pct: number | null; rank_margin_mae: number | null; rank_brier: number | null;
      }
      const rows = await viewGet<RankRow>("model_rankings", "select=*");
      const [minCov, minGraded] = await Promise.all([
        cfg("ranking.min_coverage_pct"),
        cfg("ranking.min_graded_games"),
      ]);
      const board = (rankKey: "rank_win_pct" | "rank_margin_mae" | "rank_brier",
        valKey: "win_pct" | "margin_mae" | "brier") =>
        rows.filter((r) => r.is_ranked && r[rankKey] !== null)
          .sort((a, b) => (a[rankKey] ?? 0) - (b[rankKey] ?? 0))
          .map((r) => ({
            rank: r[rankKey], creator_slug: r.creator_slug, creator_name: r.creator_name,
            model_slug: r.model_slug, model_name: r.model_name, sport: r.sport,
            value: r[valKey], graded: r.graded, coverage_pct: r.coverage_pct,
          }));
      return json({
        rules_version: RULES.version,
        thresholds: { min_coverage_pct: Number(minCov ?? 60), min_graded_games: Number(minGraded ?? 20) },
        boards: {
          win_pct: board("rank_win_pct", "win_pct"),
          margin_mae: board("rank_margin_mae", "margin_mae"),
          brier: board("rank_brier", "brier"),
        },
        unranked: rows.filter((r) => !r.is_ranked).map((r) => ({
          creator_slug: r.creator_slug, model_slug: r.model_slug,
          model_name: r.model_name, reason: r.unranked_reason,
        })),
      }, 200, FREE_CACHE);
    }
    if (req.method === "GET" && path === "/v1/activity") {
      interface ActRow {
        at: string; creator_slug: string; creator_name: string; model_name: string;
        sport: string; n_rows: number; n_first: number; week: number | null;
      }
      const rows = await viewGet<ActRow>("activity_feed", "select=*&limit=40");
      return json({
        rows: rows.map((r) => ({
          at: r.at, creator_slug: r.creator_slug, creator_name: r.creator_name,
          model_name: r.model_name, sport: r.sport, kind: "submission",
          n_rows: r.n_rows, n_first: r.n_first, week: r.week,
        })),
      }, 200, FREE_CACHE);
    }

    // Who am I: the one route the site uses to decide which dashboard to
    // render. Role resolution happens here, server side, from the actual rows.
    if (req.method === "GET" && path === "/v1/me") {
      const user = await getUser(req);
      if (!user) return json({ signed_in: false, role: "guest" }, 200, NO_STORE);
      interface SubscriberRow { status: string; plan: string; current_period_end: string | null; started_at: string }
      const [creators, subs, adminCfg] = await Promise.all([
        viewGet<CreatorRow>("creators", `select=*&user_id=eq.${user.id}&limit=1`),
        viewGet<SubscriberRow>("subscribers",
          `select=status,plan,current_period_end,started_at&user_id=eq.${user.id}&limit=1`),
        cfg("admin.user_ids"),
      ]);
      const admin = Array.isArray(adminCfg) && adminCfg.includes(user.id);
      const entitled = await isEntitled(user.id);
      const c = creators[0] ?? null;
      let creator = null;
      if (c) {
        const wall = await buildWall();
        const mine = wall.filter((w) => w.creator_slug === c.slug);
        creator = {
          slug: c.slug, display_name: c.display_name, founding: c.founding_member,
          membership: mine[0]?.membership ?? "MEMBER", monogram: mine[0]?.monogram ?? "",
          logo_url: c.logo_url,
          models: mine.map((w) => ({ model_slug: w.model_slug, model_name: w.model_name, sport: w.sport })),
        };
      }
      const sub = subs[0] ?? null;
      const role = c
        ? "creator"
        : (sub && ["active", "past_due"].includes(sub.status) ? "subscriber" : "member");
      return json({
        signed_in: true, email: user.email, role, admin, entitled,
        founding: c?.founding_member ?? false,
        creator,
        subscription: sub
          ? { status: sub.status, plan: sub.plan, current_period_end: sub.current_period_end, started_at: sub.started_at }
          : null,
      }, 200, NO_STORE);
    }

    let m = path.match(/^\/v1\/creators\/([a-z0-9-]+)$/);
    if (req.method === "GET" && m) {
      const payload = await creatorPayload(m[1]);
      if (!payload) return err("not_found", "No creator at this address.", 404);
      return json(payload, 200, FREE_CACHE);
    }

    m = path.match(/^\/v1\/models\/([a-z0-9-]+)\/([a-z0-9-]+)$/);
    if (req.method === "GET" && m) {
      const payload = await creatorPayload(m[1]);
      const model = payload?.models.find((x) => x.model_slug === m![2]);
      if (!payload || !model) return err("not_found", "No such model.", 404);
      const models = await viewGet<{ id: string; description: string | null }>(
        "models", `select=id,description,slug,creators!inner(slug)&slug=eq.${m[2]}&creators.slug=eq.${m[1]}&limit=1`);
      const modelId = models[0]?.id;
      interface CovRow { season: number; week: number; games_available: number; games_submitted: number }
      interface LogRow {
        game_id: string; label: string; kickoff_at: string; week: number | null;
        pick_side: string | null; closing_spread: number | null; final: string | null;
        pick_result: string | null; margin_error: number | null; brier: number | null; movement_n: number;
      }
      const [coverage, log] = await Promise.all([
        modelId
          ? viewGet<CovRow>("model_coverage", `select=season,week,games_available,games_submitted&model_id=eq.${modelId}&order=season.desc,week.asc`)
          : Promise.resolve([] as CovRow[]),
        modelId
          ? viewGet<LogRow>("model_game_log", `select=*&model_id=eq.${modelId}&order=graded_at.desc&limit=25`)
          : Promise.resolve([] as LogRow[]),
      ]);
      return json({
        creator: {
          slug: payload.creator.slug, display_name: payload.creator.display_name,
          founding: payload.creator.founding,
        },
        model: { model_slug: model.model_slug, model_name: model.model_name, sport: model.sport,
          description: models[0]?.description ?? null },
        record: model.record,
        coverage,
        coverage_pct: model.coverage_pct,
        recent_graded: log.map((g) => ({
          game_id: g.game_id, label: g.label, kickoff_at: g.kickoff_at, week: g.week,
          pick_side: g.pick_side, closing_spread: g.closing_spread, final: g.final,
          pick_result: g.pick_result, margin_error: g.margin_error, brier: g.brier,
          movement_n: g.movement_n,
        })),
      }, 200, FREE_CACHE);
    }

    // ------------------------------------------- free list, paid numbers
    if (req.method === "GET" && path === "/v1/games") {
      const u = new URL(req.url);
      const meta = await buildMeta();
      const rawSport = u.searchParams.get("sport") ?? "";
      const sport = /^[A-Z0-9]{2,10}$/.test(rawSport) ? rawSport : (meta.sports[0]?.code ?? "NFL");
      const season = seasonParam(u.searchParams.get("season"),
        meta.sports.find((s) => s.code === sport)?.season);
      if (!Number.isFinite(season) || season <= 0) {
        return err("invalid_payload", "season must be a number", 422);
      }
      const rawWeek = u.searchParams.get("week");
      let week: number | null = null;
      if (rawWeek !== null && rawWeek.trim() !== "") {
        week = Number(rawWeek);
        if (!Number.isInteger(week)) return err("invalid_payload", "week must be an integer", 422);
      } else {
        week = await currentWeek(sport, season);
      }
      const user = await getUser(req);
      const entitled = await isEntitled(user?.id ?? null);
      const payload = await buildGames(sport, season, week, entitled);
      return json(payload, 200, entitled ? NO_STORE : FREE_CACHE);
    }

    if (req.method === "GET" && path === "/v1/consensus") {
      const u = new URL(req.url);
      const meta = await buildMeta();
      const rawSport = u.searchParams.get("sport") ?? "";
      const sport = /^[A-Z0-9]{2,10}$/.test(rawSport) ? rawSport : (meta.sports[0]?.code ?? "NFL");
      const season = seasonParam(u.searchParams.get("season"),
        meta.sports.find((s) => s.code === sport)?.season);
      if (!Number.isFinite(season) || season <= 0) {
        return err("invalid_payload", "season must be a number", 422);
      }
      const rawWeek = u.searchParams.get("week");
      let week: number | null = null;
      if (rawWeek !== null && rawWeek.trim() !== "") {
        week = Number(rawWeek);
        if (!Number.isInteger(week)) return err("invalid_payload", "week must be an integer", 422);
      } else {
        week = await currentWeek(sport, season);
      }
      const user = await getUser(req);
      const entitled = await isEntitled(user?.id ?? null);
      const board = await buildGames(sport, season, week, entitled);
      type BoardGame = {
        game_id: string; label: string; kickoff_at: string; status: string;
        consensus: Record<string, unknown> | null;
      };
      const rows = (board.games as BoardGame[])
        .filter((g) => g.consensus !== null)
        .map((g) => {
          const c = g.consensus as Record<string, unknown>;
          if (c.locked) {
            return { game_id: g.game_id, label: g.label, kickoff_at: g.kickoff_at, status: g.status, n: c.n ?? null };
          }
          return { game_id: g.game_id, label: g.label, kickoff_at: g.kickoff_at, status: g.status, ...c };
        });
      if (entitled) return json({ entitled: true, rows }, 200, NO_STORE);
      return json({
        entitled: false,
        reason: meta.billing_live ? "subscription_required" : "billing_not_live",
        rows,
      }, 200, FREE_CACHE);
    }

    // ------------------------------------------------------- dashboard
    if (path === "/v1/dashboard" && req.method === "GET") {
      const ctx = await requireCreator(req);
      if (ctx instanceof Response) return ctx;
      const { creator } = ctx;
      const wall = await buildWall();
      const mine = wall.filter((w) => w.creator_slug === creator.slug);
      interface KeyRow { key_prefix: string; kind: string; status: string; created_at: string; last_used_at: string | null }
      interface OriginRow { id: string; origin: string; status: string }
      interface EarnRow {
        period_month: string; earned_cents: number | null; balance_cents: number | null; available_cents: number | null;
      }
      const [keys, origins, earnings, referredTotal, referredActive] = await Promise.all([
        viewGet<KeyRow>("api_keys", `select=key_prefix,kind,status,created_at,last_used_at&creator_id=eq.${creator.id}&order=created_at.desc`),
        viewGet<OriginRow>("embed_installs", `select=id,origin,status&creator_id=eq.${creator.id}&order=created_at.asc`),
        viewGet<EarnRow>("creator_earnings_monthly", `select=period_month,earned_cents,balance_cents,available_cents&creator_id=eq.${creator.id}&order=period_month.desc`),
        (await viewGet<{ id: string }>("attributions", `select=id&creator_id=eq.${creator.id}`)).length,
        (await viewGet<{ id: string }>("subscribers", `select=id,attributions!inner(creator_id)&attributions.creator_id=eq.${creator.id}&status=in.(active,past_due)`)).length,
      ]);
      const thisMonth = new Date().toISOString().slice(0, 7);
      const meta = await buildMeta();
      const [poolBps, fCount, refBps] = await Promise.all([
        cfg("econ.founder_pool_bps"),
        cfg("econ.founder_count"),
        cfg("econ.referral_bps"),
      ]);
      const balance = earnings.reduce((s, e) => s + (e.balance_cents ?? 0), 0);
      const available = earnings.reduce((s, e) => s + (e.available_cents ?? 0), 0);
      const models = await viewGet<ModelRow>(
        "models", `select=id,slug,name,sport_code&creator_id=eq.${creator.id}`);
      const pinned = models.find((x) => x.id === creator.pinned_model_id)?.slug ?? null;
      return json({
        creator: {
          ...pub(creator, mine[0]?.membership ?? "MEMBER", mine[0]?.monogram ?? "", pinned),
          billing_mode: creator.billing_mode, referral_share_bps: creator.referral_share_bps,
        },
        models: models.map((x) => ({ model_slug: x.slug, model_name: x.name, sport: x.sport_code })),
        keys: keys.map((k) => ({
          prefix: `mck_${k.kind}_${k.key_prefix}`, status: k.status,
          created_at: k.created_at, last_used_at: k.last_used_at,
        })),
        origins,
        earnings: {
          this_month_cents: earnings.find((e) => e.period_month?.startsWith(thisMonth))?.earned_cents ?? 0,
          balance_cents: balance, available_cents: available,
          referred_active: referredActive, referred_total: referredTotal,
          note: meta.billing_live
            ? null
            : "Billing is not live yet. Attribution is being recorded now and pays out when billing turns on.",
        },
        embed_snippet: `<script src="${BASE_URL}/collective/embed.js" data-collective-host="${creator.slug}" async></script>`,
        prompt_available: true,
        // A sport with no model is not a wall: posting a slate for it creates
        // the model with the submission. The dashboard reads this to know it
        // can offer every sport rather than only the ones already covered.
        creates_models: true,
        economics: {
          founding: creator.founding_member,
          founder_pool_bps: Number(poolBps ?? 6000),
          founder_count: Math.max(Number(fCount ?? 6), 1),
          referral_bps: Number(refBps ?? 0),
        },
      }, 200, NO_STORE);
    }

    if (path === "/v1/dashboard/profile" && req.method === "POST") {
      const ctx = await requireCreator(req);
      if (ctx instanceof Response) return ctx;
      const body = await req.json().catch(() => null) as Record<string, unknown> | null;
      if (!body) return err("invalid_payload", "Body must be JSON.", 422);
      const patch: Record<string, unknown> = {};
      // Creators edit identity fields only; records, rates, and flags are
      // never editable from here. Values must be strings; URLs must parse
      // as http(s) so a profile can never publish a javascript: link.
      for (const k of ["display_name", "description", "website_url", "x_handle", "logo_url"]) {
        if (!(k in body)) continue;
        const v = body[k];
        if (v !== null && typeof v !== "string") {
          return err("invalid_payload", `${k} must be a string.`, 422);
        }
        patch[k] = v === "" ? null : v;
      }
      for (const k of ["website_url", "logo_url"]) {
        const v = patch[k];
        if (typeof v !== "string") continue;
        try {
          const uu = new URL(v.startsWith("http") ? v : `https://${v}`);
          if (uu.protocol !== "https:" && uu.protocol !== "http:") throw new Error("scheme");
          patch[k] = uu.toString();
        } catch {
          return err("invalid_payload", `${k} is not a usable URL.`, 422);
        }
      }
      if (typeof patch.x_handle === "string") patch.x_handle = patch.x_handle.replace(/^@/, "");
      if (typeof body.pinned_model_slug === "string" && /^[a-z0-9-]{1,40}$/.test(body.pinned_model_slug)) {
        const mrows = await viewGet<{ id: string }>(
          "models", `select=id&creator_id=eq.${ctx.creator.id}&slug=eq.${body.pinned_model_slug}&limit=1`);
        if (mrows[0]) patch.pinned_model_id = mrows[0].id;
      }
      if (typeof patch.display_name === "string" &&
        ((patch.display_name as string).length < 2 || (patch.display_name as string).length > 60)) {
        return err("invalid_payload", "Display name must be 2 to 60 characters.", 422);
      }
      const updated = await tableWrite("creators", "PATCH", `id=eq.${ctx.creator.id}`, patch) as CreatorRow[];
      const c = updated[0];
      return json({ ok: true, creator: pub(c, "", "", null) }, 200, NO_STORE);
    }

    // Browser slate submission: the signed-in creator posts an envelope from
    // the dashboard (CSV or Excel upload, or manual entry) without ever
    // handling their API key. Same validation pipeline as the key path: the
    // envelope goes verbatim into the ingest RPC under the creator's own
    // active key identity, so rate limits and attribution behave identically.
    if (path === "/v1/dashboard/submit" && req.method === "POST") {
      const ctx = await requireCreator(req);
      if (ctx instanceof Response) return ctx;
      const body = await req.json().catch(() => null) as Record<string, unknown> | null;
      if (!body || typeof body !== "object" || Array.isArray(body)) {
        return err("invalid_payload", "Body must be a JSON envelope.", 422);
      }
      const rows = body.rows;
      if (!Array.isArray(rows) || rows.length === 0) {
        return err("invalid_payload", "Envelope must include a non-empty rows array.", 422);
      }
      if (rows.length > 500) {
        return err("invalid_payload", `${rows.length} rows exceeds the 500 row maximum.`, 422);
      }
      const models = await viewGet<ModelRow>(
        "models", `select=id,slug,name,sport_code&creator_id=eq.${ctx.creator.id}`);

      // THE SPORT DECIDES WHICH MODEL, and a sport with no model gets one.
      //
      // This used to read models[0] when the envelope named none, and refuse
      // outright when the account had none at all -- so an NFL slate from a
      // creator with only a college model was filed under the COLLEGE model
      // and every game was looked up in the wrong schedule. The browser
      // resolves this before it posts now, and the server enforcing it too is
      // the point: trusting the client to pick the right record is what made
      // the original bug possible.
      const picked = await resolveModel(ctx.creator, models, body.model, body.sport);
      if ("error" in picked) return picked.error;
      const model = picked.model;

      const keys = await viewGet<{ id: string }>(
        "api_keys", `select=id&creator_id=eq.${ctx.creator.id}&status=eq.active&order=created_at.desc&limit=1`);
      if (!keys[0]) return err("conflict", "No active API key on this account. Rotate a key from the dashboard first.", 409);
      const allowed = await rpc<boolean>("rate_check", { p_key_id: keys[0].id, p_endpoint: "/v1/dashboard/submit" });
      if (allowed === false) return err("rate_limited", "Hourly submission limit reached. Try again later.", 429);
      const pKey = {
        key_id: keys[0].id, kind: "live",
        creator_id: ctx.creator.id, creator_slug: ctx.creator.slug, creator_name: ctx.creator.display_name,
        model_id: model.id, model_slug: model.slug, model_name: model.name, sport: model.sport_code,
      };
      const envelope = { ...body, model: model.slug, sport: model.sport_code };
      delete (envelope as Record<string, unknown>).dry_run;
      const dry = body.dry_run === true;
      const result = await rpc<Record<string, unknown> | null>("ingest_submission", {
        p_key: pKey, p_envelope: envelope, p_dry: dry,
      });
      if (!result || result.ok === false) {
        const code = typeof result?.code === "string" ? result.code : "server_error";
        if (code === "server_error") {
          console.error("collective_public dashboard submit failed:", result);
          return err("server_error", "Something went wrong on our side.", 500);
        }
        return err(code, String(result?.message ?? "The submission was rejected."), 422);
      }
      const out = { ...result } as Record<string, unknown>;
      delete out.ok;
      out.model = model.slug;
      out.sport = model.sport_code;
      // A model that appeared because of this submission, or a model the sport
      // overrode, is stated on the receipt rather than left to be noticed on
      // the board.
      out.model_created = picked.created;
      if (picked.note) out.model_note = picked.note;
      if (dry) { out.dry_run = true; out.submission_id = null; }
      return json(out, 200, NO_STORE);
    }

    // The submission center: every slate this creator has ever posted, newest
    // first, with the stored per-slate counts.
    if (path === "/v1/dashboard/submissions" && req.method === "GET") {
      const ctx = await requireCreator(req);
      if (ctx instanceof Response) return ctx;
      interface SubListRow {
        id: string; received_at: string; data_origin: string;
        n_rows: number; n_resolved: number; n_quarantined: number; n_late: number;
        models: { slug: string; name: string; sport_code: string };
      }
      const rows = await viewGet<SubListRow>("submissions",
        `select=id,received_at,data_origin,n_rows,n_resolved,n_quarantined,n_late,` +
        `models!inner(slug,name,sport_code,creator_id)` +
        `&models.creator_id=eq.${ctx.creator.id}&order=received_at.desc&limit=40`);
      return json({
        rows: rows.map((s) => ({
          id: s.id, received_at: s.received_at, data_origin: s.data_origin,
          model_slug: s.models.slug, model_name: s.models.name, sport: s.models.sport_code,
          rows: s.n_rows, resolved: s.n_resolved, quarantined: s.n_quarantined, late: s.n_late,
        })),
      }, 200, NO_STORE);
    }

    // The Universal Prompt, on demand from the dashboard. The stored key is
    // hashed and can never be echoed back, so the prompt carries a marked
    // placeholder the creator swaps for their real key.
    //
    // IT NO LONGER REFUSES AN ACCOUNT WITH NO MODEL. This is the document that
    // tells a creator how to wire their model up in the first place, so
    // "this account has no model yet" is the state it most needs to serve --
    // and a slate posted for any sport now creates its model with the
    // submission, so there is nothing left for a model to gate.
    if (path === "/v1/dashboard/prompt" && req.method === "GET") {
      const ctx = await requireCreator(req);
      if (ctx instanceof Response) return ctx;
      const models = await viewGet<{ slug: string; name: string; sport_code: string }>(
        "models", `select=slug,name,sport_code&creator_id=eq.${ctx.creator.id}&order=created_at.asc`);
      const wanted = new URL(req.url).searchParams.get("model");
      const chosen = (wanted && models.find((x) => x.slug === wanted)) || models[0] || null;
      const meta = await buildMeta();
      const prompt = renderPrompt({
        CREATOR_NAME: ctx.creator.display_name,
        MODEL_NAME: chosen?.name ?? `${ctx.creator.display_name}'s model`,
        SPORT: chosen?.sport_code ??
          (meta.sports.map((s) => s.code).join(" or ") || "the sport you post"),
        API_BASE: `${SB_URL}/functions/v1`,
        API_KEY: "YOUR_API_KEY (paste your mck_live_ key here; rotate one from the dashboard if you no longer have it)",
        EMBED_SNIPPET: `<script src="${BASE_URL}/collective/embed.js" data-collective-host="${ctx.creator.slug}" async></script>`,
        DASHBOARD_URL: `${BASE_URL}/collective/#dashboard`,
        DOCS_URL: `${BASE_URL}/collective/#rules`,
      });
      return json({
        prompt,
        model: chosen ? { model_slug: chosen.slug, model_name: chosen.name, sport: chosen.sport_code } : null,
        note: chosen
          ? null
          : "This account has no model yet, and does not need one to start: post a slate with its " +
            "sport on the envelope and the model is created with the submission.",
      }, 200, NO_STORE);
    }

    if (path === "/v1/dashboard/keys/rotate" && req.method === "POST") {
      const ctx = await requireCreator(req);
      if (ctx instanceof Response) return ctx;
      const fresh = await newApiKey("live");
      const out = await rpc<{ ok: boolean }>("rotate_key", {
        p_creator_id: ctx.creator.id, p_new_prefix: fresh.prefix, p_new_hash: fresh.hash, p_kind: "live",
      });
      if (!out?.ok) return err("server_error", "Rotation failed.", 500);
      return json({ key: fresh.raw, prefix: `mck_live_${fresh.prefix}`, shown_once: true }, 200, NO_STORE);
    }

    if (path === "/v1/dashboard/origins" && req.method === "POST") {
      const ctx = await requireCreator(req);
      if (ctx instanceof Response) return ctx;
      const body = await req.json().catch(() => null) as { add?: string; remove?: string } | null;
      if (!body) return err("invalid_payload", "Body must be JSON.", 422);
      if (typeof body.add === "string") {
        let origin: string;
        try {
          const u = new URL(body.add);
          if (u.protocol !== "https:" && u.hostname !== "localhost") throw new Error("https required");
          origin = `${u.protocol}//${u.host}`;
        } catch {
          return err("invalid_payload", "Origins must be full https:// URLs.", 422);
        }
        await tableWrite("embed_installs", "POST", "", { creator_id: ctx.creator.id, origin })
          .catch(() => { /* already listed: adding again is a no-op */ });
      } else if (typeof body.remove === "string" && /^[0-9a-f-]{36}$/.test(body.remove)) {
        await tableWrite("embed_installs", "DELETE", `id=eq.${body.remove}&creator_id=eq.${ctx.creator.id}`);
      } else {
        return err("invalid_payload", "Pass add or remove.", 422);
      }
      const origins = await viewGet("embed_installs",
        `select=id,origin,status&creator_id=eq.${ctx.creator.id}&order=created_at.asc`);
      return json({ ok: true, origins }, 200, NO_STORE);
    }

    if (["/v1/dashboard/profile", "/v1/dashboard/keys/rotate", "/v1/dashboard/origins", "/v1/dashboard/submit"].includes(path) ||
      ["/v1/meta", "/v1/wall", "/v1/rules", "/v1/rankings", "/v1/activity", "/v1/games", "/v1/consensus",
        "/v1/dashboard", "/v1/dashboard/submissions", "/v1/dashboard/prompt", "/v1/me"].includes(path)) {
      return err("method_not_allowed", "Wrong method for this route.", 405);
    }
    return err("not_found", `No such route: ${req.method} ${path}`, 404);
  } catch (e) {
    /* The stack is the only thing that names the failing line, and this is
       the one place it exists. Logging the message alone cost a round trip
       in collective_embed working out which read threw. */
    if (e instanceof RpcError) {
      console.error("collective_public rpc failure:", e.message, e.status, e.body);
    } else {
      console.error("collective_public failure:", e,
        e instanceof Error ? e.stack : "(no stack)");
    }
    return err("server_error", "Something went wrong on our side.", 500);
  }
});
