"""The reference implementation of the frozen decision calibration artifact.

Everything here reads ONLY the artifact (plain JSON: knots, coefficients,
tables) and one row of inputs. It is the Python twin of
football/cfb_decision/decision.js: the parity fixture
(artifacts/decision/fixtures/decision_parity.json) is generated by `evaluate`
and the JavaScript engine must reproduce it.

    apply_map(spec, p)                          one probability map
    calibrate(cal, p, feats)                    the (conditional) cover calibration
    market_shrink(p_cal, p_mkt, spec, feats)    shrinkage toward the market
    decision_probability(row, artifact)         pure -> calibrated -> decision
    eval_model(spec, feats)                     linear / logistic model
    evaluate(row, artifact)                     every decision number for one quote

Probability maps (p clamped to [1e-4, 1-1e-4] before any logit):
  identity                  p
  platt    {a, b}           sigmoid(a + b*logit(p))
  beta     {a, b, c}        sigmoid(c + a*ln p - b*ln(1-p))
  isotonic {x, y}           linear interpolation in p, clamped at the end knots, then clamped to [1e-4, 1-1e-4]
  logit_pwl {x, y}          sigmoid(interp(x, y, logit(p))): piecewise linear in logit space, clamped at the end knots
Models: z = intercept + sum_k coef_k * (x_k - mu_k) / sd_k (x_k missing -> fill_k, still missing -> None);
logistic returns sigmoid(z).
"""
import math

from . import core

P_LO, P_HI = 1e-4, 1 - 1e-4


def isnum(x):
    return isinstance(x, (int, float)) and not isinstance(x, bool) and math.isfinite(x)


def clamp(x, lo, hi):
    return lo if x < lo else (hi if x > hi else x)


def logit(p):
    p = clamp(float(p), P_LO, P_HI)
    return math.log(p / (1 - p))


def sigm(z):
    return 1.0 / (1.0 + math.exp(-z))


def interp(xs, ys, v):
    """decision.js interp(): clamped at both ends, linear inside."""
    if not xs:
        return v
    if v <= xs[0]:
        return ys[0]
    if v >= xs[-1]:
        return ys[-1]
    for i in range(1, len(xs)):
        if v <= xs[i]:
            d = xs[i] - xs[i - 1]
            t = (v - xs[i - 1]) / (d if d else 1)
            return ys[i - 1] + t * (ys[i] - ys[i - 1])
    return ys[-1]


def apply_map(spec, p):
    if not spec or spec.get('method') == 'identity':
        return p
    m = spec['method']
    if m == 'platt':
        return sigm(spec['a'] + spec['b'] * logit(p))
    if m == 'beta':
        q = clamp(p, P_LO, P_HI)
        return sigm(spec['c'] + spec['a'] * math.log(q) - spec['b'] * math.log(1 - q))
    if m == 'isotonic':
        return clamp(interp(spec['x'], spec['y'], p), P_LO, P_HI)
    if m == 'logit_pwl':
        return sigm(interp(spec['x'], spec['y'], logit(p)))
    raise ValueError('unknown probability map %s' % m)


def bin_of(edges, v):
    """decision.js binOf(): index of the first edge v is below; len(edges) past the last."""
    for i, e in enumerate(edges):
        if v < e:
            return i
    return len(edges)


def calibrate(cal, p, feats):
    if cal and cal.get('conditional') and cal['conditional'].get('maps'):
        cd = cal['conditional']
        v = feats.get(cd['by'])
        if isnum(v):
            return apply_map(cd['maps'][bin_of(cd['bins'], v)], p)
    return apply_map((cal or {}).get('map', cal), p)


def market_shrink(p_cal, p_mkt, spec, feats):
    if not spec or not isnum(p_mkt):
        return p_cal, 1.0
    w = spec['w_model'] if isnum(spec.get('w_model')) else 1.0
    if spec.get('by') and spec.get('w_by') and isnum(feats.get(spec['by'])):
        w = interp(spec['w_by']['x'], spec['w_by']['y'], feats[spec['by']])
    w = clamp(w, 0.0, 1.0)
    if spec.get('space') == 'prob':
        return w * p_cal + (1 - w) * p_mkt, w
    return sigm(w * logit(p_cal) + (1 - w) * logit(p_mkt)), w


def eval_model(spec, feats):
    if not spec:
        return None
    z = spec['intercept'] if isnum(spec.get('intercept')) else 0.0
    for k, c in spec['coef'].items():
        x = feats.get(k)
        if not isnum(x):
            f = (spec.get('fill') or {}).get(k)
            x = f if isnum(f) else None
        if x is None:
            return None
        mu = (spec.get('mu') or {}).get(k)
        sd = (spec.get('sd') or {}).get(k)
        mu = mu if isnum(mu) else 0.0
        sd = sd if isnum(sd) and sd != 0 else 1.0
        z += c * (x - mu) / sd
    return sigm(z) if spec.get('type') == 'logistic' else z


def push_probability(home_line, table):
    """decision.js pushProb(): table keyed 'lo-hi' by |line|; integer lines only."""
    if not isnum(home_line) or abs(home_line - round(home_line)) > 1e-9:
        return 0.0
    a = abs(home_line)
    for k, v in (table or {}).items():
        lo, hi = (float(s) for s in k.split('-'))
        if lo <= a <= hi:
            return v
    return 0.02


def pure_cover(pure_margin, sigma, t_df, home_line, side):
    """P(side covers | no push) from the frozen model's standardized t at a BOOK home line."""
    if not (isnum(pure_margin) and isnum(sigma) and sigma > 0 and isnum(home_line)):
        return None
    df = t_df if isnum(t_df) and t_df <= 1e6 else 1e6
    p_home = 1.0 - core.t_cdf_std((-home_line - pure_margin) / sigma, df)
    return p_home if side == 'HOME' else 1.0 - p_home


def _scale(spec, v):
    return interp(spec['x'], spec['y'], v) if spec and isnum(v) else None


def side_numbers(row, side, A):
    price = row.get('price_home') if side == 'HOME' else row.get('price_away')
    other = row.get('price_away') if side == 'HOME' else row.get('price_home')
    hl = row['home_line']
    p_pure = pure_cover(row['pure_margin'], row['sigma'], row.get('t_df'), hl, side)
    gap = row['pure_margin'] - (-hl)
    gap_side = gap if side == 'HOME' else -gap
    p_mkt, basis = core.market_implied_side(price, other)
    feats = {k: row.get(k) for k in ('sigma', 'ens_sd', 'reliability', 'week', 'early_season', 'qb_unsettled',
                                     'qb_missing', 'dispersion', 'books', 'quote_age_min', 'total_line')}
    feats.update(pure_cover_prob=p_pure, gap_pts=gap_side, abs_gap_pts=abs(gap_side),
                 is_home_side=1 if side == 'HOME' else 0, abs_line=abs(hl))
    p_cal = calibrate(A['cover_calibration'], p_pure, feats)
    p_dec, w = market_shrink(p_cal, p_mkt, A.get('market_shrinkage'), feats)
    feats['decision_cover_prob'] = p_dec
    pp = push_probability(hl, A.get('push_table'))
    be = core.break_even(price) if isnum(price) else None
    be = be if isnum(be) else None
    ev = core.ev_with_push(p_dec, pp, price) if be is not None else None
    ev_t = core.ev_with_push(p_pure, pp, price) if be is not None else None
    ev_emp = _scale(A.get('ev_curve'), ev_t)
    ev_emp_d = _scale(A.get('ev_curve_decision'), ev)
    return {'side': side, 'price': price if isnum(price) else None, 'pure_cover_prob': p_pure,
            'calibrated_cover_prob': p_cal, 'market_implied_prob': p_mkt, 'market_implied_basis': basis,
            'w_model': w, 'decision_cover_prob': p_dec, 'push_prob': pp, 'break_even_prob': be,
            'probability_edge': (p_dec - be) if be is not None else None,
            'theoretical_ev': ev_t, 'decision_ev': ev, 'empirical_ev': ev_emp, 'empirical_ev_decision': ev_emp_d,
            'gap_pts': gap_side, 'features': feats}


def decision_probability(row, artifact, side=None):
    """pure -> calibrated -> decision cover probability for one quote."""
    s = side or ('HOME' if row['pure_margin'] - (-row['home_line']) > 0 else 'AWAY')
    n = side_numbers(row, s, artifact)
    return {k: n[k] for k in ('side', 'pure_cover_prob', 'calibrated_cover_prob', 'market_implied_prob',
                              'w_model', 'decision_cover_prob')}


def evaluate(row, A):
    """Every decision number for one quote, on the side decision.js would choose:
    the larger probability edge when both sides are priced, else the larger
    decision probability. `row` keys: pure_margin, sigma, t_df, home_line (BOOK
    convention), price_home, price_away (None when not captured), and the
    feature names of DATASET.md."""
    h = side_numbers(row, 'HOME', A)
    a = side_numbers(row, 'AWAY', A)
    if isnum(h['probability_edge']) and isnum(a['probability_edge']):
        s = h if h['probability_edge'] >= a['probability_edge'] else a
    else:
        s = h if h['decision_cover_prob'] >= a['decision_cover_prob'] else a
    f = s['features']
    out = {k: v for k, v in s.items() if k != 'features'}
    out['p_positive_clv'] = eval_model(A.get('p_positive_clv'), f)
    out['expected_clv_pts'] = eval_model(A.get('clv_magnitude'), f)
    bc = eval_model(A.get('bet_confidence'), f)
    out['bet_confidence'] = bc
    out['bet_confidence_score'] = round(100 * bc) if isnum(bc) else None
    fe = eval_model(A.get('football_confidence'), f)
    out['football_expected_abs_error'] = fe
    fcs = A.get('football_confidence_scale') or {}
    out['football_confidence_score'] = _scale(fcs.get('score_from_expected_abs_error'), fe)
    rs = (A.get('reliability_scale') or {}).get('expected_abs_error')
    out['reliability_expected_abs_error'] = _scale(rs, f.get('reliability'))
    me = eval_model(A.get('market_confidence'), f)
    out['market_expected_abs_move'] = me
    mcs = A.get('market_confidence_scale') or {}
    out['market_confidence_score'] = _scale(mcs.get('score_from_expected_abs_move'), me)
    out['features'] = f
    return out
