"""docs/cfb-market/BACKTEST.md from the market-intelligence outputs.

    python3 -m v2.market_intel.report

Every table is generated from $CFB_V2_OUT/market_intel/*.json (DEV) and
holdout.json (the 2024-2025 holdout, scored once). Nothing is typed by hand:
estimates carry n and a 95% game-level bootstrap interval, written est [lo, hi].
"""
import json
import os

from . import data as D

DOC = os.path.join(D.REPO, 'docs', 'cfb-market', 'BACKTEST.md')


def load(name):
    p = os.path.join(D.OUTDIR, name)
    return json.load(open(p)) if os.path.exists(p) else None


def c(x, pct=False, k=3):
    """est [lo, hi] (n)."""
    if not x or x.get('est') is None:
        return 'n/a'
    f = (lambda v: '%.1f%%' % (100 * v)) if pct else (lambda v: ('%.' + str(k) + 'f') % v)
    lo, hi = x['ci']
    ci = ' [%s, %s]' % (f(lo), f(hi)) if lo is not None else ''
    return f(x['est']) + ci


def n(x):
    return str(x.get('n', '')) if x else ''


def esc(v):
    return str(v).replace('|', '\\|')


def table(head, rows):
    out = ['| ' + ' | '.join(esc(h) for h in head) + ' |', '|' + '---|' * len(head)]
    out += ['| ' + ' | '.join(esc(v) for v in r) + ' |' for r in rows]
    return '\n'.join(out)


def ladder_rows(rows):
    out = []
    for x in rows:
        if not x.get('bets'):
            out.append([x.get('arm'), 0, '', '', '', '', '', ''])
            continue
        out.append([x['arm'], x['bets'], c(x.get('clv_pts'), k=2), c(x.get('positive_clv_rate'), pct=True),
                    c(x.get('ev_at_entry_market_close_view'), pct=True), c(x.get('ats'), pct=True), c(x.get('roi'), pct=True),
                    x.get('max_drawdown_u')])
    return out


def build():
    K, B, M, CH, BI, R, H = (load('keynumbers.json'), load('books.json'), load('movement.json'), load('challenger.json'),
                              load('bias.json'), load('replay.json'), load('holdout.json'))
    L = ['# CFB market intelligence — backtest', '',
         'Generated by `python3 -m v2.market_intel.report` from the research outputs; do not edit by hand. Methods:',
         '[`METHODS.md`](METHODS.md). The deliverable map: [`DELIVERABLE.md`](DELIVERABLE.md).', '',
         '**Windows.** Every fit and every choice read DEV 2016-2023 only. The 2024-2025 holdout was scored **once**, at %s, with every artifact frozen (last section). '
         'FBS vs FBS completed games. Every estimate: `est [95%% bootstrap CI]`, resampling games (2,000 draws, seeded).' % (H['scored_at'] if H else 'NOT YET'), '',
         '**Prices.** 2016-2019 carry real prices (the 5Dimes opener of the very opener bet; every book\'s close). 2020-2025 carry none: those rows are graded at an ASSUMED -110, labelled. A live output never assumes a price.', '']
    # ----------------------------------------------------------- key numbers
    L += ['## 1. Key numbers (DEV 2016-2023, n = %d games)' % K['landing_dev']['n'], '',
          'Share of games whose final |margin| is exactly k. College football has no ties (%s).' % ('verified: 0 tied finals' if K['landing_dev']['no_ties'] else 'NOT verified'), '']
    pre = {x['k']: x for x in K['landing_2009_2015']['abs_margin']}
    L.append(table(['abs margin', 'DEV share', '2009-2015 share'], [[x['k'], c(x, pct=True), c(pre.get(x['k']), pct=True)] for x in K['landing_dev']['abs_margin']]))
    L += ['', 'Most common |margin| (DEV): ' + ', '.join('%d (%.1f%%)' % (x['k'], 100 * x['share']) for x in K['landing_dev']['top20'][:10]) + '.', '',
          '**Does it vary?** Landing on 3 / 7 / 10 / 14 by group (chi-square test of homogeneity over the four keys and the rest):', '']
    rows = []
    for g, v in K['heterogeneity'].items():
        for x in v['rows']:
            rows.append([g, x['group'], x['n'], c(x['p3'], pct=True), c(x['p7'], pct=True), c(x['p10'], pct=True), c(x['p14'], pct=True), v['chi2_homogeneity_p']])
    L.append(table(['grouping', 'group', 'n', 'P(3)', 'P(7)', 'P(10)', 'P(14)', 'homogeneity p'], rows))
    L += ['', '**Push at the closing line** (integer closes; the in-sample check of the frozen distribution against the pure t alone):', '']
    L.append(table(['closing line', 'n', 'empirical push', 'pure t (continuity)', 'key-number distribution'],
                   [[x['line'], x['empirical']['n'], c(x['empirical'], pct=True), '%.1f%%' % (100 * x['pure_t_mass']), '%.1f%%' % (100 * x['key_distribution'])] for x in K['push_by_line_dev']['rows']]))
    L += ['', '**Local landing mass** q_k = P(favourite wins by exactly k | closing line within 1 point of k), the empirical ingredient of a half point:', '']
    L.append(table(['k', 'n', 'q_k'], [[x['k'], x['q']['n'], c(x['q'], pct=True)] for x in K['local_landing_dev']['rows']]))
    mk = {x['k']: x for x in K['market_half_point_prices']['rows']}
    L += ['', '**What books charge for a half point** (2016-2019 closes, real prices): for games where books hang the favourite at L and L+0.5, '
          '2 x the difference in no-vig cover probability estimates the landing mass the books price on the integer inside the step (%s quotes). '
          'Cross-book pairs mix pricing with differing opinions, so these are lower bounds on what the books believe.' % K['market_half_point_prices']['n_quotes'], '']
    L.append(table(['k', 'pairs', 'market-implied mass', 'empirical q_k (above)'],
                   [[k, mk[k]['n_pairs'], c(mk[k]['market_implied_q'], pct=True), c(next(x['q'] for x in K['local_landing_dev']['rows'] if x['k'] == k), pct=True)]
                    for k in sorted(mk) if any(x['k'] == k for x in K['local_landing_dev']['rows'])]))
    L += ['', '## 2. The key-number distribution and the value of each half point', '',
          'Method choice (DEV walk-forward: fit on 2017..S-1, score S = 2019..2023; %d games, %d integer closing lines, %d alternate-line outcomes). '
          'Chosen: **%s** (rule in METHODS.md).' % (K['dev_walkforward_methods']['pooled']['n'], K['dev_walkforward_methods']['pooled']['n_integer_lines'],
                                                   K['dev_walkforward_methods']['ladder']['n_line_outcomes'], K['chosen_method']), '']
    p, lad = K['dev_walkforward_methods']['pooled'], K['dev_walkforward_methods']['ladder']
    L.append(table(['method', 'push log loss change vs t', 'cover log loss change vs t', 'alternate-ladder log loss change vs t', 'mean abs shift of cover prob vs t'],
                   [[m, c(p[m + '_minus_t']['push_logloss_change'], k=5), c(p[m + '_minus_t']['cover_logloss_change'], k=5), c(lad[m + '_minus_t'], k=5),
                     p['cover_prob_shift_vs_t'].get(m, '')] for m in ('local', 'global', 't_untied')]))
    L += ['', 'Alternate-line calibration (market-centred, DEV walk-forward): observed P(home covers at close + d | no push) against each method:', '']
    L.append(table(['d', 'n', 'observed', 'plain t', 'local', 'global'], [[x['d'], x['n'], x['observed'], x['t'], x['local'], x['global']] for x in lad['by_offset']]))
    L += ['', '**The value of each half point** at a market-centred distribution (mean = the line, the typical frozen sigma of games near it), exact EV math at -110. '
          '`cents` = how much better a price the WORSE number needs to match the EV of -110 at the better number.', '']
    L.append(table(['favourite lays', 'step', 'integer', 'mass changed', 'EV change', 'equivalent price', 'cents', 'underdog step', 'mass', 'cents'],
                   [[x['line'], x['fav_step'], x['fav_integer'], '%.1f%%' % (100 * x['fav_mass_changed']), '%.3f' % x['fav_ev_change_at_-110'],
                     x['fav_equivalent_price'], x['fav_cents'], x['dog_step'], '%.1f%%' % (100 * (x['dog_mass_changed'] or 0)), x['dog_cents']]
                    for x in K['half_point_values'] if x['line'] <= 21]))
    ex = K['alt_ladder_example']
    L += ['', '**Alternate-line fair prices from one distribution** (worked example: pure margin %.1f, sigma %.1f):' % (ex['pure_margin'], ex['sigma']), '']
    L.append(table(['home line', 'P(win)', 'P(push)', 'P(cover, no push)', 'plain t P(cover, no push)', 'fair price', 'EV at -110'],
                   [[x['home_line'], x['p_win'], x['p_push'], x['p_cover_no_push'], x['plain_t_cover_no_push'], x['fair_price'], x['ev_at_-110']] for x in ex['rows']]))
    T = K['totals_dev']
    L += ['', '**Totals.** Most common final totals: ' + ', '.join('%d (%s)' % (x['total'], c(x, pct=True)) for x in T['most_common_totals'][:8])
          + '. Push rate at integer closing totals: %s (n %d). %s' % (c(T['push_rate_at_integer_total_lines'], pct=True), T['push_rate_at_integer_total_lines']['n'], T['reading']), '']
    # ------------------------------------------------------------------ books
    bb = B['books_2016_2019']
    L += ['## 3. Book quality: information vs price (2016-2019 closes, real prices; %d games with >= 5 books)' % bb['n_games'], '',
          'Information slope = the outcome residual (margin - leave-one-out median) per point of the book\'s price-adjusted deviation from that median. '
          'Empirical-Bayes shrinkage: pooled mean slope %.3f, between-book variance tau^2 = %.4f (Q = %.1f on %d books). Pooled over all books: %s.'
          % (bb['eb']['pooled_mean_slope'], bb['eb']['tau2_between_books'], bb['eb']['Q'], bb['eb']['k_books'], c(bb['pooled_slope_all_books'])), '']
    L.append(table(['book', 'games', 'mean abs dev pts', 'off consensus >= 1 pt', 'information slope', 'shrunk', 'close MAE - consensus MAE', 'hold', 'best number share', 'best price-adjusted share'],
                   [[x['book'], x['games'], x['mean_abs_deviation_pts'], '%.1f%%' % (100 * x['share_off_consensus_ge_1']), c(x['information_slope']), x['information_slope_shrunk'],
                     c(x['close_mae_minus_loo_consensus_mae']), '%.1f%%' % (100 * x['hold']) if x['hold'] is not None else 'n/a', x['best_number_share'], x['best_price_adjusted_share']]
                    for x in bb['books']]))
    wf = B['consensus_walkforward']
    L += ['', '**Consensus rules** (walk-forward: weights from earlier price seasons; scored 2017-2019, %d games with a Pinnacle close):' % wf['n_games'], '']
    L.append(table(['rule', 'MAE', 'RMSE', 'MAE - median line'], [[x['rule'], x['mae'], x['rmse'], c(x['mae_minus_median_line'], k=4)] for x in wf['rows']]))
    P = B['pinnacle_vs_consensus']
    L += ['', '**Pinnacle vs the other books** (%d games): MAE(Pinnacle) - MAE(rest) = %s. When Pinnacle differs from the rest by >= 0.25 / 0.5 / 1 point, the result sides with Pinnacle %s / %s / %s.'
          % (P['n_games'], c(P['mae_pinnacle_minus_rest'], k=4), c(P['diff_ge_0.25']['result_sides_with_pinnacle_vs_loo_median'], pct=True),
             c(P['diff_ge_0.5']['result_sides_with_pinnacle_vs_loo_median'], pct=True), c(P['diff_ge_1']['result_sides_with_pinnacle_vs_loo_median'], pct=True)), '']
    L += ['**Opener vs close vs EdgeDesk** (the same games):', '']
    L.append(table(['era', 'n', 'MAE opener', 'MAE close', 'close - opener', 'pure - opener', 'pure - close', 'share moved', 'result residual per point of move'],
                   [[k, v['n'], v['mae_open'], v['mae_close'], c(v['mae_close_minus_open']), c(v.get('mae_pure_minus_open')), c(v.get('mae_pure_minus_close')), v['share_moved'],
                     c(v['result_residual_per_point_of_move (1 = the move is fully information)'])] for k, v in B['opener_vs_close'].items()]))
    L += ['', '**US books 2021-2023** (lines only):', '']
    L.append(table(['book', 'games', 'mean abs dev pts', 'off >= 1 pt', 'information slope'],
                   [[x['book'], x['games'], x['mean_abs_deviation_pts'], '%.1f%%' % (100 * x['share_off_ge_1']), c(x['information_slope'])] for x in B['us_books_2021_2023']['books']]))
    L += ['', '**Closing dispersion vs the market\'s error** (quartiles of the SD of price-adjusted book margins, edges %s pts):' % B['dispersion_vs_market_error']['quartile_edges_pts'], '']
    L.append(table(['quartile', 'n', 'abs(margin - consensus close)'], [[x['dispersion_quartile'], x['ae_close']['n'], c(x['ae_close'])] for x in B['dispersion_vs_market_error']['rows']]))
    # --------------------------------------------------------------- movement
    L += ['', '## 4. Line movement (opener -> close; the archive has no path between them)', '']
    L.append(table(['series', 'n', 'mean abs move', 'median', 'p90', 'no move', '0.5', '1', '1.5', '2', '2.5-3', '3.5-5', '>5'],
                   [[k.replace('moves_', ''), v['n'], c(v['mean_abs_move']), v['median_abs_move'], v['p90_abs_move']] + [c(s, pct=True) for s in v['shares']]
                    for k, v in M.items() if k.startswith('moves_') and 'shares' in v]))
    L += ['', 'By week (DEV consensus):', '']
    L.append(table(['week', 'n', 'mean abs move', 'share moved'], [[x['wk'], x['n'], c(x['mean_abs_move']), c(x['share_moved'], pct=True)] for x in M['moves_by_week_dev']]))
    for key, lab in (('stickiness_5dimes_2016_2019', '5Dimes 2016-2019'), ('stickiness_bovada_2021_2023', 'Bovada 2021-2023')):
        st = M[key]
        L += ['', '**Resistance at key numbers, %s** (one book\'s opener -> its close, %d games): stay rate by kind of opener; key minus other integers = %s.'
              % (lab, st['n'], c(st['stay_key_minus_other_integers'], pct=True)), '']
        L.append(table(['opener kind', 'stay rate'], [[k, c(v, pct=True)] for k, v in st['pooled_stay_rate'].items()]))
    st = M['stickiness_5dimes_2016_2019']
    L += ['', 'Openers half a point off a number (5Dimes 2016-2019): where the close ends up.', '']
    L.append(table(['number', 'key?', 'opener', 'n', 'close ON it', 'close THROUGH it', 'unchanged'],
                   [[x['key'], x['is_key'], x['opener'], x['n'], c(x['close_on_key'], pct=True), c(x['close_through_key'], pct=True), c(x['close_unchanged'], pct=True)] for x in st['around_keys']]))
    g = M['gap_and_toward_dev']
    L += ['', '## 5. EdgeDesk vs the market: the gap and movement toward EdgeDesk (DEV, opener -> close)', '',
          'Gap = pure - opener (home margin). Mean |gap| %s; quantiles %s. The model sides with the underdog in %s of games. '
          'The close moved toward EdgeDesk in %s of moved lines; mean move toward %s pts; %s points per point of gap.'
          % (c(g['distribution']['mean_abs_gap']), g['distribution']['quantiles_abs_gap'], c(g['distribution']['model_favours_underdog_share'], pct=True),
             c(g['overall_toward_given_moved'], pct=True), c(g['overall_mean_move_toward']), c(g['move_per_point_of_gap'])), '']
    L.append(table(['abs gap', 'n', 'share moved', 'toward, given moved', 'mean move toward', 'share of gap closed'],
                   [[x['abs_gap'], x['n'], c(x['share_moved'], pct=True), c(x['toward_given_moved'], pct=True), c(x['mean_move_toward_pts']), c(x['share_of_gap_closed'], pct=True)] for x in g['by_gap']]))
    L += ['', '**Which EdgeDesk disagreements the market absorbs** (points of move per point of gap, by segment; submodels jointly):', '']
    rows = []
    for seg, v in M['decay_by_segment_dev'].items():
        if seg == 'submodels_joint':
            rows.append(['submodels (joint)', 'C ridge gap', v['n'], c(v['C_ridge_gap'])])
            rows.append(['submodels (joint)', 'D GBM gap', v['n'], c(v['D_gbm_gap'])])
            continue
        for x in v:
            rows.append([seg, x[seg], x['n'], c(x['move_per_point_of_gap'])])
    L.append(table(['segment', 'value', 'n', 'move per point of gap'], rows))
    e = M['expected_close_dev']
    L += ['', '**Expected close** (walk-forward, seasons %s, n %d): MAE %.3f vs %.3f for "close = opener" (difference %s); direction right in %s of moved lines. Calibration of the predicted move:'
          % (e['seasons_scored'], e['n'], e['mae_model'], e['mae_naive_open'], c(e['mae_model_minus_naive'], k=4), c(e['direction_accuracy_when_moved'], pct=True)), '']
    L.append(table(['bin', 'n', 'predicted move', 'actual move'], [[x['bin'], x['n'], x['pred_move'], c(x['actual_move'])] for x in e['calibration_by_predicted_move']]))
    d = M['opener_dispersion_2023']
    L += ['', '**Does opener disagreement predict movement?** 2023 (the only DEV season with two or more openers; %d games):' % d['n'], '']
    L.append(table(['books at the open', 'n', 'mean abs move to close'], [[x['opener_range'], x['n'], c(x['mean_abs_move_to_close'])] for x in d['rows']]))
    # ------------------------------------------------------------- challenger
    L += ['', '## 6. The market-informed challenger and the market residual (DEV walk-forward, 2017-2023)', '',
          'market_adjusted_projection = opener + w (pure - opener); w fit on earlier seasons: ' + ', '.join('%s: %.3f (close %.3f)' % (s, v['w_open'], v['w_close']) for s, v in CH['walkforward_weights'].items()) + '.', '']
    L.append(table(['model', 'n', 'MAE', 'RMSE', 'bias', 'MAE - opener'], [[x['model'], CH['scores_vs_open']['n'], x['mae'], x['rmse'], x['bias'], c(x['mae_minus_ref'])] for x in CH['scores_vs_open']['rows']]))
    L += ['', 'Conditional weight (early season, reliability, QB, ensemble SD) minus the single weight: %s.' % c(CH['hybrid_cond_minus_hybrid']['rows'][0]['mae_minus_ref']), '',
          '**Market weight toward kickoff**: w(pure) at the opener %.3f, at the close %.3f; difference %s (negative = the market weighs more at the close).'
          % (CH['open_vs_close_weight']['w_open'], CH['open_vs_close_weight']['w_close'], c(CH['open_vs_close_weight']['w_close_minus_w_open'])), '']
    L.append(table(['segment', 'value', 'n', 'w(pure) vs opener', 'w(pure) vs close'], [[x['segment'], x['value'], x['n'], c(x['w_pure_vs_open']), c(x['w_pure_vs_close'])] for x in CH['weight_by_segment']]))
    mr = CH['market_residual']
    L += ['', '**Market residual** (margin - market) on EdgeDesk\'s gap: at the opener slope %s, walk-forward out-of-sample R^2 %.4f; at the close slope %s, R^2 %.4f.'
          % (c(mr['opener']['slope']), mr['opener']['oos_r2_pooled'], c(mr['close']['slope']), mr['close']['oos_r2_pooled']), '']
    # -------------------------------------------------------------------- bias
    L += ['## 7. Bias audit (DEV, %d games)' % BI['n'], '', 'From the GROUP\'s side. Market cover rate excludes pushes. EdgeDesk error > 0 = EdgeDesk underrates the group. %s.' % BI['multiplicity'], '']
    L.append(table(['group', 'n', 'market cover (close)', 'market residual pts', 'EdgeDesk error pts', 'EdgeDesk picks group', 'ATS picking group', 'ATS picking other'],
                   [[x['group'], x['n'], c(x['market_cover_rate_close'], pct=True), c(x['market_residual_close_pts']), c(x['edgedesk_error_pts (+ = underrates the group)']),
                     c(x['edgedesk_picks_group_share'], pct=True), c(x['edgedesk_ats_open_when_picking_group'], pct=True), c(x['edgedesk_ats_open_when_picking_other'], pct=True)]
                    for x in BI['groups'] + BI['conferences'] if 'market_cover_rate_close' in x]))
    t = BI['totals']
    L += ['', '**Totals**: over rate at the close %s; EdgeDesk total error %s; EdgeDesk leans over in %s of games; its over picks hit %s, its under picks %s.'
          % (c(t['over_rate_close'], pct=True), c(t['edgedesk_total_error_pts (+ = EdgeDesk too low)']), c(t['edgedesk_leans_over_share'], pct=True),
             c(t['edgedesk_total_side_hit_rate_open_when_over'], pct=True), c(t['edgedesk_total_side_hit_rate_open_when_under'], pct=True)), '']
    # ------------------------------------------------------------------ replay
    L += ['## 8. Replay, execution, timing and the market-layer backtest (DEV 2017-2023, %d games)' % R['n_games'], '',
          'Decision at the Tuesday freeze on the opener only; executed at the opener (price: %s) or at the close (%s). '
          '`EV (market view)` = the entry\'s EV under the market\'s own closing distribution: CLV in EV units, free of outcome noise.'
          % (R['price_sources_open'], R['price_sources_close']), '',
          'Thresholds, fixed before each registration was run: %s.' % R['thresholds'], '']
    hdr = ['arm', 'bets', 'CLV pts', '+CLV', 'EV (market view)', 'ATS', 'ROI', 'max DD (u)']
    L += ['**Registration 2 (standalone arms), DEV:**', '', table(hdr, ladder_rows(R['ladder_dev'])), '',
          '**Registration 2, 2017-2019 only (real prices):**', '', table(hdr, ladder_rows(R['ladder_dev_real_prices_2017_2019'])), '',
          '**Registration 1 (cumulative; degenerate: A1 = A2 = A3), DEV:**', '', table(hdr, ladder_rows(R['ladder_dev_registration_1'])), '',
          'The OLD rule was SELECTED on these DEV seasons (in-sample); its reality-check p = 0.136 (docs/cfb-v2/BACKTEST.md).', '',
          '**Timing: the same EdgeDesk side at the opener vs at the close (final pre-kick):**', '']
    trs = []
    for x in R['timing_scorecard_dev']:
        if 'roi_diff' in x:
            trs.append([x['arm'], 'opener minus close', '', '', c(x['ev_market_view_diff'], pct=True), '', c(x['roi_diff'], pct=True), ''])
        else:
            trs.append([x['arm'], x['execution'], c(x['clv_pts'], k=2), '', c(x['ev_at_entry_market_close_view'], pct=True), c(x['ats'], pct=True), c(x['roi'], pct=True), c(x['ev_at_entry_pure_view'], pct=True)])
    L.append(table(['games', 'execution', 'CLV', '', 'EV (market view)', 'ATS', 'ROI', 'EV (pure view)'], trs))
    S = R['line_shopping_2016_2019']
    L += ['', '**Line shopping** (2016-2019 closes, real prices; EdgeDesk\'s side vs the close):', '']
    L.append(table(['subset', 'strategy', 'games', 'points vs consensus', 'EV (market view)', 'EV - consensus', 'ATS', 'ROI', 'ROI - consensus', 'push->win', 'loss->push', 'loss->win'],
                   [[x['subset'], x['strategy'], x['games'], c(x['points_vs_consensus']), c(x['ev_market_view'], pct=True), c(x['ev_market_view_minus_consensus'], pct=True),
                     c(x['ats'], pct=True), c(x['roi'], pct=True), c(x['roi_minus_consensus'], pct=True), x['conversions_vs_consensus']['push_to_win'],
                     x['conversions_vs_consensus']['loss_to_push'], x['conversions_vs_consensus']['loss_to_win']] for x in S['rows']]))
    pp = R['pinnacle_vs_consensus_close_2013_2019']
    L += ['', 'Pinnacle close vs the consensus close (2013-2019, %d games): mean |difference| %s pts; >= 0.5 pts in %s of games; >= 1 pt in %s.'
          % (pp['n'], c(pp['mean_abs_diff_pts']), c(pp['share_diff_ge_0_5'], pct=True), c(pp['share_diff_ge_1'], pct=True)), '',
          '**Live Model Lab ledger (2026, as of the replay run)**: %s.' % json.dumps(R['live_ledger_2026']), '']
    # ------------------------------------------------------------------ holdout
    if H:
        L += ['## 9. Holdout 2024-2025 (scored once, %s; no prices exist: ASSUMED -110)' % H['scored_at'], '',
              'Frozen: %s.' % H['frozen'], '']
        kp = H['key_numbers']['paired']
        L.append(table(['key-number method vs t', 'push log loss change', 'cover log loss change', 'margin log-likelihood gain'],
                       [[m, c(kp[m + '_minus_t']['push_logloss_change'], k=5), c(kp[m + '_minus_t']['cover_logloss_change'], k=5), c(kp[m + '_minus_t']['loglik_margin_gain'], k=4)]
                        for m in ('local', 'global', 't_untied')]))
        kl = H['key_numbers_ladder']
        L += ['', 'Alternate-line ladder log loss change vs t: local %s, global %s (n %d games, %d outcomes). Observed push rate at integer closes %.1f%% (n %d).'
              % (c(kl['local_minus_t'], k=5), c(kl['global_minus_t'], k=5), kl['n_games'], kl['n_line_outcomes'], 100 * H['key_numbers']['observed']['push_rate_integer_lines'],
                 H['key_numbers']['observed']['n_integer_lines']), '']
        ch = H['challenger']
        L += ['Challenger (w %.4f frozen): MAE pure %.3f, opener %.3f, hybrid %.3f, close %.3f (n %d); hybrid - opener %s; pure - opener %s; w refit on the holdout (reference only) %.3f.'
              % (ch['w_pure'], ch['mae']['ens_pred'], ch['mae']['open_margin'], ch['mae']['hybrid'], ch['mae']['close_margin'], ch['n'], c(ch['hybrid_minus_open']),
                 c(ch['pure_minus_open']), ch['w_refit_on_holdout_for_reference']), '']
        mt = H['movement_toward']
        L += ['Movement toward EdgeDesk: %s per point of gap; toward in %s of moved lines; mean %s pts.'
              % (c(mt['move_per_point_of_gap']), c(mt['overall_toward_given_moved'], pct=True), c(mt['overall_mean_move_toward'])), '']
        L.append(table(['books at the open', 'n', 'mean abs move to close'], [[x['opener_range'], x['n'], c(x['mean_abs_move_to_close'])] for x in H['opener_dispersion']['rows']]))
        L += ['', '**Ladder, holdout (registration 2):**', '', table(hdr, ladder_rows(H['ladder'])), '', '**Timing, holdout:**', '']
        trs = []
        for x in H['timing_scorecard']:
            if 'roi_diff' in x:
                trs.append([x['arm'], 'opener minus close', '', c(x['ev_market_view_diff'], pct=True), '', c(x['roi_diff'], pct=True)])
            else:
                trs.append([x['arm'], x['execution'], c(x['clv_pts'], k=2), c(x['ev_at_entry_market_close_view'], pct=True), c(x['ats'], pct=True), c(x['roi'], pct=True)])
        L.append(table(['games', 'execution', 'CLV', 'EV (market view)', 'ATS', 'ROI'], trs))
        L += ['', '**Bias, holdout:**', '']
        L.append(table(['group', 'n', 'market cover (close)', 'EdgeDesk error pts', 'EdgeDesk picks group', 'ATS picking group', 'ATS picking other'],
                       [[x['group'], x['n'], c(x['market_cover_rate_close'], pct=True), c(x['edgedesk_error_pts (+ = underrates the group)']),
                         c(x['edgedesk_picks_group_share'], pct=True), c(x['edgedesk_ats_open_when_picking_group'], pct=True), c(x['edgedesk_ats_open_when_picking_other'], pct=True)]
                        for x in H['bias']]))
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    with open(DOC, 'w') as f:
        f.write('\n'.join(L) + '\n')
    return DOC


if __name__ == '__main__':
    print(build())
