-- portfolio -- part 1 of 9.
-- Run the parts IN ORDER in the Supabase SQL editor. Each part holds a whole
-- number of statements; nothing is cut in the middle. Re-running a part is safe.

-- =============================================================================
-- portfolio.sql — EdgeDesk Portfolio: one ledger for every sportsbook wager
-- and every prediction-market position a reader holds, on any platform.
--
-- WHAT THIS IS
--   platform_accounts         the platforms a reader tracks, and how: MANUAL
--                             entry, CSV import, or (Phase B onward) a real
--                             API / OAuth / aggregator connection.
--   portfolio_positions       one normalized row per wager or contract
--                             position. Sportsbook and prediction-market
--                             positions share the table but NOT the math.
--   portfolio_transactions    the fills, sells, settlements and cash moves
--                             behind a position. A prediction-market
--                             position's contracts, cost and fees are always
--                             rebuilt from these rows, never typed in.
--   portfolio_imports         one CSV upload, staged → classified → committed.
--   portfolio_import_rows     every row of that upload, its server-side
--                             classification (NEW / DUPLICATE / NEEDS_REVIEW /
--                             INVALID) and what happened to it.
--   portfolio_sync_logs       what every import (and, later, every sync) did.
--   portfolio_private.platform_credentials
--                             ciphertext only, in a schema the API never
--                             serves, readable by the service role alone.
--
-- THE RULES, ENFORCED BY THE SERVER
--   1. Money is NUMERIC. Every derived figure is computed HERE, by trigger,
--      from the inputs: a client cannot store a P&L its own inputs do not
--      produce. lib/edgedesk_portfolio.js mirrors this arithmetic exactly and
--      tools/portfolio/portfolio_sql.test.js holds the two in parity.
--   2. Row level security on every table: auth.uid() = user_id. Composite
--      foreign keys (id, user_id) make it impossible to attach a fill, a
--      position or an import row to another reader's record, whatever id the
--      payload names.
--   3. The owner is the caller, whatever the payload says, and ownership
--      fields are frozen after insert.
--   4. A record is stored once: by its platform id where it has one, else by
--      a SHA-256 fingerprint of its normalized fields (docs/portfolio-
--      architecture.md § Deduplication states the exact algorithm).
--   5. "Connected" is a claim about a live integration. A MANUAL or CSV
--      account cannot hold that status, and readers cannot create any other
--      kind of account — only the service role, after a real connect.
--   6. Synced rows are read-only to readers except notes and attribution.
--   7. EdgeDesk attribution is explicit: a position links only to an EdgeDesk
--      record that the same reader owns.
--
-- CONVENTION (supabase/README.md): idempotent, additive, pasted into the SQL
-- editor, no psql meta-commands, ends in a report. Safe to run again. Too big
-- for one paste: supabase/parts/portfolio.part*-of-*.sql are the same file in
-- order, generated by `npm run portfolio:parts`.
-- Needs PostgreSQL 15+ (ON DELETE SET NULL (column)), as every Supabase
-- project is.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. PURE HELPERS — exact decimal rounding and the fingerprint material
-- ─────────────────────────────────────────────────────────────────────────────
-- n / d rounded half away from zero at p_scale decimals, computed with integer
-- division so no intermediate rounding can ever leak in. Every division in
-- this file goes through it; lib/edgedesk_portfolio.js divRound() is the same
-- algorithm on BigInt.
create or replace function public.portfolio_div_round(p_n numeric, p_d numeric, p_scale int)
returns numeric language plpgsql immutable strict as $$
declare
  f numeric := power(10::numeric, p_scale);
  n numeric := p_n * f;
  q numeric;
  r numeric;
begin
  if p_d = 0 then return null; end if;
  q := div(n, p_d);
  r := n - q * p_d;
  if 2 * abs(r) >= abs(p_d) then q := q + sign(n) * sign(p_d); end if;
  return trim_scale(round(q / f, p_scale));
end $$;

create or replace function public.portfolio_num_text(p numeric)
returns text language sql immutable as $$
  select case when p is null then '' else trim_scale(p)::text end
$$;

-- Text normalized for fingerprinting: NFKD, ASCII-only lower case, accents
-- and apostrophes removed, punctuation to spaces, "at" / "vs" / "v." / "@"
-- unified to " @ ", whitespace collapsed. Lower-casing is done by translate,
-- not lower(), so the result does not depend on the database's locale.
create or replace function public.portfolio_norm_text(p text)
returns text language sql immutable as $$
  select btrim(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(regexp_replace(
           translate(normalize(coalesce(p, ''), NFKD),
                     'ABCDEFGHIJKLMNOPQRSTUVWXYZ' || chr(9) || chr(10) || chr(11) || chr(12) || chr(13),
                     'abcdefghijklmnopqrstuvwxyz     '),
           '[''`]', '', 'g'),
           '[^ -~]', '', 'g'),
           '[^a-z0-9+.@ -]', ' ', 'g'),
           '\s+(at|vs|v)\.?\s+', ' @ ', 'g'),
           '\s*@\s*', ' @ ', 'g'),
           '\s+', ' ', 'g'))
$$;

create or replace function public.portfolio_minute_utc(p timestamptz)
returns text language sql stable as $$
  select case when p is null then '' else to_char(p at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI') end
$$;

create or replace function public.portfolio_sha256(p text)
returns text language sql immutable strict as $$
  select encode(sha256(convert_to(p, 'UTF8')), 'hex')
$$;

-- A selection and its line, as one token: "Chiefs" + line -2.5, "Chiefs -2.5"
-- with no line, and "Chiefs -2.5" + line -2.5 are the same pick, whichever
-- way a book's export or a reader's form happened to split them. Plus signs
-- are dropped so "Over" + 47.5 and "Over +47.5" agree too.
create or replace function public.portfolio_selection_token(p_selection text, p_line numeric)
returns text language sql immutable as $$
  select case when l <> '' and right(sel, length(l)) <> l then btrim(sel || ' ' || l) else sel end
    from (select replace(public.portfolio_norm_text(p_selection), '+', '') as sel, public.portfolio_num_text(p_line) as l) x
$$;

-- The fingerprint MATERIAL (exposed so the JS mirror can be checked against
-- it byte for byte) and its SHA-256.
create or replace function public.portfolio_fp_wager_material(p_platform text, p_event text, p_market text, p_selection text,
  p_line numeric, p_american int, p_decimal numeric, p_stake numeric, p_placed timestamptz)
returns text language sql stable as $$
  select concat_ws('|', 'pf1', 'wager', lower(btrim(coalesce(p_platform, ''))),
    public.portfolio_norm_text(p_event), public.portfolio_norm_text(p_market), public.portfolio_selection_token(p_selection, p_line),
    case when p_american is not null then 'a' || p_american::text
         when p_decimal is not null then 'd' || public.portfolio_num_text(p_decimal) else '' end,
    public.portfolio_num_text(p_stake), public.portfolio_minute_utc(p_placed))
$$;

create or replace function public.portfolio_fp_contract_material(p_platform text, p_event text, p_market text, p_side text, p_placed timestamptz)
returns text language sql stable as $$
  select concat_ws('|', 'pf1', 'contract', lower(btrim(coalesce(p_platform, ''))),
    public.portfolio_norm_text(p_event), public.portfolio_norm_text(p_market), public.portfolio_norm_text(p_side),
    public.portfolio_minute_utc(p_placed))
$$;

create or replace function public.portfolio_fp_fill_material(p_platform text, p_event text, p_market text, p_side text,
  p_action text, p_quantity numeric, p_price numeric, p_executed timestamptz)
returns text language sql stable as $$
  select concat_ws('|', 'pf1', 'fill', lower(btrim(coalesce(p_platform, ''))),
    public.portfolio_norm_text(p_event), public.portfolio_norm_text(p_market), public.portfolio_norm_text(p_side),
    upper(btrim(coalesce(p_action, ''))), public.portfolio_num_text(p_quantity), public.portfolio_num_text(p_price),
    public.portfolio_minute_utc(p_executed))
$$;

-- the group a prediction-market fill belongs to: one market, one side
create or replace function public.portfolio_contract_key(p_platform text, p_event text, p_market text, p_side text)
returns text language sql immutable as $$
  select concat_ws('|', lower(btrim(coalesce(p_platform, ''))), public.portfolio_norm_text(p_event),
    public.portfolio_norm_text(p_market), public.portfolio_norm_text(p_side))
$$;

-- Tolerant casts for staged import rows: a bad cell is an INVALID row, never
-- a failed import. They decide by pattern first, so the common case is a cast
-- that cannot fail and opens no subtransaction (an EXCEPTION block costs one
-- per call — 60,000 of them for one 5,000-row file); only an odd-looking date
-- falls through to the slow, exception-guarded path.
create or replace function public.portfolio_try_numeric(p text)
returns numeric language sql immutable as $$
  select case when btrim(p) ~ '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)([eE][+-]?[0-9]{1,3})?$' then btrim(p)::numeric end
$$;

create or replace function public.portfolio_try_timestamptz_slow(p text)
returns timestamptz language plpgsql stable as $$
begin
  return btrim(p)::timestamptz;
exception when others then return null;
end $$;

create or replace function public.portfolio_try_timestamptz(p text)
returns timestamptz language sql stable as $$
  select case
    when p is null or btrim(p) = '' then null
    /* every field in range (days 29-31 go the slow way): this cast cannot fail */
    when btrim(p) ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|1[0-9]|2[0-8])[T ]([01][0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9]([.][0-9]{1,6})?)?(Z|[+-][0-9]{2}(:?[0-9]{2})?)?$'
      then btrim(p)::timestamptz
    else public.portfolio_try_timestamptz_slow(p) end
$$;

-- Re-running this file on a live site: a reader saving a position holds
-- portfolio_positions and then reads platform_accounts, while this file
-- re-creates triggers table by table. Take every existing portfolio table at
-- once, without waiting while holding any of them, so the two can never
-- deadlock: either all are free and this file proceeds, or it lets go and
-- tries again a moment later. (On a first run there is nothing to take.)
do $lock$
declare tries int := 0; tables text;
begin
  select string_agg(format('%I.%I', schemaname, tablename), ', ') into tables from pg_tables
   where schemaname = 'public' and tablename in ('portfolio_positions', 'portfolio_transactions', 'platform_accounts',
         'portfolio_imports', 'portfolio_import_rows', 'portfolio_sync_logs');
  if tables is null then return; end if;
  loop
    begin
      execute 'lock table ' || tables || ' in access exclusive mode nowait';
      return;
    exception when lock_not_available then
      tries := tries + 1;
      if tries > 300 then
        raise exception 'portfolio: the tables stayed busy for a minute; run this file again when traffic is quieter';
      end if;
      perform pg_sleep(0.2);
    end;
  end loop;
end $lock$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. PLATFORM ACCOUNTS
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.platform_accounts (
  id                  uuid        primary key default gen_random_uuid(),
  user_id             uuid        not null default auth.uid() references auth.users(id) on delete cascade,
  platform            text        not null,
  platform_label      text        not null,
  platform_type       text        not null,
  connection_type     text        not null default 'MANUAL',
  external_account_id text        null,
  display_name        text        null,
  status              text        not null default 'MANUAL',
  last_sync_at        timestamptz null,
  last_success_at     timestamptz null,
  last_error          text        null,
  sync_cursor         text        null,
  metadata            jsonb       not null default '{}'::jsonb,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint platform_accounts_id_owner unique (id, user_id),
  constraint platform_accounts_platform_key check (platform ~ '^[a-z0-9][a-z0-9_]{1,47}$'),
  constraint platform_accounts_label check (length(btrim(platform_label)) between 1 and 60),
  constraint platform_accounts_type check (platform_type in ('SPORTSBOOK', 'PREDICTION_MARKET')),
  constraint platform_accounts_connection check (connection_type in ('MANUAL', 'CSV', 'API', 'OAUTH', 'AGGREGATOR')),
  constraint platform_accounts_status check (status in ('CONNECTED', 'IMPORT_ONLY', 'MANUAL', 'SYNCING', 'ACTION_REQUIRED', 'DISCONNECTED', 'ERROR')),
  -- a manual or CSV account can never read "connected": nothing is connected
  constraint platform_accounts_status_honest check (
    (connection_type = 'MANUAL' and status in ('MANUAL', 'DISCONNECTED'))
    or (connection_type = 'CSV' and status in ('IMPORT_ONLY', 'DISCONNECTED'))
    or connection_type in ('API', 'OAUTH', 'AGGREGATOR')),
  constraint platform_accounts_display_name check (display_name is null or length(display_name) <= 60),
  constraint platform_accounts_external_id check (external_account_id is null or length(external_account_id) <= 200),
  constraint platform_accounts_metadata check (jsonb_typeof(metadata) = 'object' and pg_column_size(metadata) <= 8192),
  constraint platform_accounts_error check (last_error is null or length(last_error) <= 500),
  constraint platform_accounts_cursor check (sync_cursor is null or length(sync_cursor) <= 2000)
);
-- How an account's data arrives, apart from what kind of platform it is
-- (platform_type is the SOURCE TYPE: SPORTSBOOK or PREDICTION_MARKET):
--   ingestion_method  MANUAL · FILE_IMPORT · API_KEY · PUBLIC_WALLET · OAUTH · AUTHORIZED_API
--   connection_tier   1 automatic authorization (OAUTH, AUTHORIZED_API) ·
--                     2 assisted automatic (API_KEY, PUBLIC_WALLET) ·
--                     3 easy import (FILE_IMPORT) · 4 manual (MANUAL)
-- An account can be upgraded in place (QUICK IMPORT → AUTOMATIC) by the
-- service role when a real integration exists: its history stays where it is.
alter table public.platform_accounts add column if not exists ingestion_method text null;
alter table public.platform_accounts add column if not exists connection_tier int null;
alter table public.platform_accounts add column if not exists history_start_at timestamptz null;
update public.platform_accounts set ingestion_method = case connection_type when 'MANUAL' then 'MANUAL' when 'CSV' then 'FILE_IMPORT'
    when 'API' then 'API_KEY' when 'OAUTH' then 'OAUTH' else 'AUTHORIZED_API' end
 where ingestion_method is null;
update public.platform_accounts set connection_tier = case ingestion_method when 'OAUTH' then 1 when 'AUTHORIZED_API' then 1
    when 'API_KEY' then 2 when 'PUBLIC_WALLET' then 2 when 'FILE_IMPORT' then 3 else 4 end
 where connection_tier is null;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'platform_accounts_ingestion') then
    alter table public.platform_accounts add constraint platform_accounts_ingestion check (
      (connection_type = 'MANUAL' and ingestion_method = 'MANUAL' and connection_tier = 4)
      or (connection_type = 'CSV' and ingestion_method = 'FILE_IMPORT' and connection_tier = 3)
      or (connection_type = 'API' and ingestion_method in ('API_KEY', 'PUBLIC_WALLET') and connection_tier = 2)
      or (connection_type = 'API' and ingestion_method = 'AUTHORIZED_API' and connection_tier = 1)
      or (connection_type = 'OAUTH' and ingestion_method = 'OAUTH' and connection_tier = 1)
      or (connection_type = 'AGGREGATOR' and ingestion_method = 'AUTHORIZED_API' and connection_tier = 1));
  end if;
end $$;

comment on table public.platform_accounts is
  'The platforms a reader tracks and how. MANUAL and CSV accounts are created by readers; API, OAUTH and AGGREGATOR accounts only by the service role after a real connection. No credential is ever stored here.';
create unique index if not exists platform_accounts_one_per_method
  on public.platform_accounts (user_id, platform, connection_type, coalesce(external_account_id, ''));
